DECLARE @finance BIGINT;
DECLARE @functional BIGINT;
DECLARE @restricted BIGINT;
DECLARE @readOnly BIGINT;
DECLARE @systemAdministrator BIGINT;
SELECT @finance = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Finance';
SELECT @functional = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Functional';
SELECT @restricted = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Functional (Restricted)';
SELECT @readOnly = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Read Only';
SELECT @systemAdministrator = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'System Administrator';

DECLARE @noteView BIGINT;
DECLARE @noteAdd BIGINT;
DECLARE @noteEdit BIGINT;
DECLARE @noteDelete BIGINT;
SELECT @noteView = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-view';
SELECT @noteAdd = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-add';
SELECT @noteEdit = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-edit';
SELECT @noteDelete = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-delete';

/* Functional */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @noteView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @noteEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @noteAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* Functional Restricted */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @noteView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @noteEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @noteAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* Read Only */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@readOnly, @noteView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* System Administrator */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @noteView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @noteEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @noteAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @noteDelete, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')
GO
