-- Add more fields to seed data for read view of contact organization
UPDATE [PIMS_ORGANIZATION]
    SET [ORGANIZATION_ALIAS] = 'MOTI', [COMMENT] = 'This is a test comment', [INCORPORATION_NUMBER] = 1234, [CONCURRENCY_CONTROL_NUMBER] = [CONCURRENCY_CONTROL_NUMBER] + 1
    WHERE [ORGANIZATION_ID] = 1

INSERT INTO [PIMS_ORGANIZATION_ADDRESS] ([ORGANIZATION_ID], [ADDRESS_ID], [ADDRESS_USAGE_TYPE_CODE], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES (1, 1, 'BILLING', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data'), (1, 1, 'MAILING', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')

INSERT INTO [PIMS_PERSON_ORGANIZATION] ([PERSON_ID], [ORGANIZATION_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES (2, 1, 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data'), (1, 1, 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')

INSERT INTO [PIMS_CONTACT_METHOD] ([CONTACT_METHOD_TYPE_CODE], [ORGANIZATION_ID], [CONTACT_METHOD_VALUE], [IS_PREFERRED_METHOD], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES ('WORKEMAIL', 1, 'tester@test.com', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data'), ('WORKPHONE', 1, '2501234567', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')

-- Add data for individual contact view
INSERT INTO [PIMS_CONTACT_METHOD] ([CONTACT_METHOD_TYPE_CODE], [PERSON_ID], [CONTACT_METHOD_VALUE], [IS_PREFERRED_METHOD], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES ('WORKEMAIL', 1, 'tester@test.com', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data'), ('WORKPHONE', 1, '2501234567', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')

INSERT INTO [PIMS_PERSON_ADDRESS] ([PERSON_ID], [ADDRESS_ID], [ADDRESS_USAGE_TYPE_CODE], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES (1, 1, 'BILLING', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data'), (1, 2, 'MAILING', 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')

UPDATE [PIMS_PERSON]
    SET [PREFERRED_NAME] = 'Tester McTest', [COMMENT] = 'This is a test comment.', [CONCURRENCY_CONTROL_NUMBER] = [CONCURRENCY_CONTROL_NUMBER] + 1
    WHERE [PERSON_ID] = 1

INSERT INTO [PIMS_PERSON_ORGANIZATION] ([PERSON_ID], [ORGANIZATION_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_DIRECTORY])
    VALUES (1, 2, 0, 1, 'Test Data', 'Test Data', 'Test Data', 'Test Data')
