x-mayan-container: &mayan-container
  env_file: .mayan-env
  environment:
    MAYAN_CELERY_BROKER_URL: amqp://${MAYAN_RABBITMQ_USER:-mayan}:${MAYAN_RABBITMQ_PASSWORD:-mayanrabbitpass}@rabbitmq:5672/${MAYAN_RABBITMQ_VHOST:-mayan}
    MAYAN_CELERY_RESULT_BACKEND: redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@redis:6379/1
    MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'${MAYAN_DATABASE_NAME:-mayan}','PASSWORD':'${MAYAN_DATABASE_PASSWORD:-mayandbpass}','USER':'${MAYAN_DATABASE_USER:-mayan}','HOST':'${MAYAN_DATABASE_HOST:-postgresql}'}}"
    MAYAN_LOCK_MANAGER_BACKEND: mayan.apps.lock_manager.backends.redis_lock.RedisLock
    MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS: "{'redis_url':'redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@redis:6379/2'}"

  image: ${MAYAN_DOCKER_IMAGE:-image-registry.apps.silver.devops.gov.bc.ca/3cd915-tools/mayan-bcgov}:${MAYAN_DOCKER_TAG:-4.7.1}
  networks:
    - psp
  restart: unless-stopped
  volumes:
    - ${MAYAN_APP_VOLUME:-app}:/var/lib/mayan
    # Optional volumes to access external data like staging or watch folders
    # - /opt/staging_folder:/staging_folder
    # - /opt/watch_folder:/watch_folder

services:
  mayan-app:
    <<: *mayan-container
    container_name: mayan-frontend
    profiles:
      - all_in_one
      - all
      - mayan
    ports:
      - "7080:8000"
    command:
      - run_frontend
    environment:
      - MAYAN_GUNICORN_WORKERS=3
      - MAYAN_GUNICORN_MAX_REQUESTS=500
      - MAYAN_GUNICORN_TIMEOUT=120
      - MAYAN_GUNICORN_WORKER_CLASS=gevent
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully
    # CPU/Memory resource constraints
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1500M
        reservations:
          memory: 400M

  elasticsearch:
    container_name: mayan-elasticsearch
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - http.max_content_length=400mb
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${MAYAN_ELASTICSEARCH_PASSWORD:-mayanespassword}
    image: ${MAYAN_DOCKER_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch}:${MAYAN_DOCKER_ELASTICSEARCH_TAG:-7.17.26}
    networks:
      - psp
    # Enable to allow external access to the database.
    # ports:
    #  - "9200:9200"
    profiles:
      - elasticsearch
      - all
      - mayan
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${MAYAN_ELASTICSEARCH_VOLUME:-elasticsearch}:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M

  postgresql:
    container_name: mayan-postgres
    command:
      - "postgres"
      - "-c"
      - "checkpoint_completion_target=0.6"
      - "-c"
      - "default_statistics_target=200"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=8MB"
    environment:
      POSTGRES_DB: ${MAYAN_DATABASE_NAME:-mayan}
      POSTGRES_PASSWORD: ${MAYAN_DATABASE_PASSWORD:-mayandbpass}
      POSTGRES_USER: ${MAYAN_DATABASE_USER:-mayan}
    image: postgres:${MAYAN_DOCKER_POSTGRES_TAG:-12.9-alpine}
    networks:
      - psp
    # Enable to allow external access to the database.
    # ports:
    #  - "5432:5432"
    profiles:
      - postgresql
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_POSTGRES_VOLUME:-postgres}:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
  redis:
    container_name: mayan-redis
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "3"
      - --maxmemory
      - "100mb"
      - --maxclients
      - "500"
      - --maxmemory-policy
      - "allkeys-lru"
      - --save
      - ""
      - --tcp-backlog
      - "256"
      - --requirepass
      - "${MAYAN_REDIS_PASSWORD:-mayanredispassword}"
    image: redis:${MAYAN_DOCKER_REDIS_TAG:-6.2-alpine}
    networks:
      - psp
    profiles:
      - redis
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_REDIS_VOLUME:-redis}:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  rabbitmq:
    container_name: mayan-rabbitmq
    image: rabbitmq:${MAYAN_DOCKER_RABBITMQ_TAG:-3.9-management-alpine}
    environment:
      RABBITMQ_DEFAULT_USER: ${MAYAN_RABBITMQ_USER:-mayan}
      RABBITMQ_DEFAULT_PASS: ${MAYAN_RABBITMQ_PASSWORD:-mayanrabbitpass}
      RABBITMQ_DEFAULT_VHOST: ${MAYAN_RABBITMQ_VHOST:-mayan}
    networks:
      - psp
    # Enable to allow access to the administration interface.
    # ports:
    #   - "15672:15672"
    profiles:
      - rabbitmq
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_RABBITMQ_VOLUME:-rabbitmq}:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M

  command_initialsetup_or_performupgrade:
    <<: *mayan-container
    container_name: mayan-db-migration
    command:
      - run_initial_setup_or_perform_upgrade
    profiles:
      - extra_command_initialsetup_or_performupgrade
      - all
      - mayan
    restart: "no"

  # Worker A handles fast UI responses, low latency tasks, AND periodic tasks (--beat)
  worker_a:
    <<: *mayan-container
    container_name: mayan-worker-a
    command:
      - run_worker
      - worker_a
      - --autoscale=10,1 --max-tasks-per-child=1 --beat --pidfile=/tmp/celerybeat.pid -l INFO
    profiles:
      - extra_worker_a
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully

  # Worker B processes document uploads & metadata changes
  worker_b:
    <<: *mayan-container
    container_name: mayan-worker-b
    command:
      - run_worker
      - worker_b
      - --autoscale=3,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_b
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully

  # Worker C handles complex processing tasks (OCR, layout parsing)
  worker_c:
    <<: *mayan-container
    container_name: mayan-worker-c
    command:
      - run_worker
      - worker_c
      - --autoscale=10,5 --max-tasks-per-child=1
    profiles:
      - extra_worker_c
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "2.0" # Higher allocation for heavy file conversions
          memory: 2000M
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully

  # Worker D processes long background maintenance scripts
  worker_d:
    <<: *mayan-container
    container_name: mayan-worker-d
    command:
      - run_worker
      - worker_d
      - --autoscale=5,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_d
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully

  # Worker E handles low-priority events or scheduled workflows
  worker_e:
    <<: *mayan-container
    container_name: mayan-worker-e
    command:
      - run_worker
      - worker_e
      - --autoscale=5,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_e
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
    depends_on:
      command_initialsetup_or_performupgrade:
        condition: service_completed_successfully

  # worker_custom_queue:
  #   <<: *mayan-container
  #   command:
  #     - /bin/sh
  #     - -c
  #     - "MAYAN_QUEUE_LIST=${MAYAN_WORKER_CUSTOM_QUEUE_LIST:-} /usr/local/bin/run_worker.sh --prefetch-multiplier=1"
  #   profiles:
  #     - extra_worker_custom
  #     - all
  #     - mayan

  # Run a separate Celery beat container
  # celery_beat:
  #   <<: *mayan-container
  #   command:
  #     - run_celery
  #     - beat -l INFO --pidfile=/tmp/celerybeat.pid
  #   profiles:
  #     - extra_celery_beat
  #     - all
  #     - mayan

  # Enable to run standalone workers
  mountindex:
    <<: *mayan-container
    container_name: mayan-mountindex
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    entrypoint:
      - /bin/sh
      - -c
      - 'mkdir --parents /mnt/index && chown mayan:mayan /mnt/index && /usr/local/bin/entrypoint.sh run_command "mountindex --allow-other creation_date /mnt/index"' # Replace "creation_date" with the index of your choice.
    profiles:
      - mountindex
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: /mnt/mayan_indexes/creation_date # Host location where the index will show up.
        target: /mnt/index # Location inside the container where the index will be mounted. Must the same is in the "entrypoint" section.
        bind:
          propagation: shared

volumes:
  app:
  elasticsearch:
  pgadmin:
  postgres:
  mountindex:
  rabbitmq:
  redis:
