####################### Common variables for all mayan containers #######################
x-mayan-environment: &mayan-environment
  MAYAN_CELERY_BROKER_URL: amqp://${MAYAN_RABBITMQ_USER:-mayan}:${MAYAN_RABBITMQ_PASSWORD:-mayanrabbitpass}@mayan-rabbitmq:5672/${MAYAN_RABBITMQ_VHOST:-mayan}
  MAYAN_CELERY_RESULT_BACKEND: redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@mayan-redis:6379/1
  MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'${MAYAN_DATABASE_NAME:-mayan}','PASSWORD':'${MAYAN_DATABASE_PASSWORD:-mayandbpass}','USER':'${MAYAN_DATABASE_USER:-mayan}','HOST':'${MAYAN_DATABASE_HOST:-mayan-postgres}'}}"
  MAYAN_LOCK_MANAGER_BACKEND: mayan.apps.lock_manager.backends.redis_lock.RedisLock
  MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS: "{'redis_url':'redis://:${MAYAN_REDIS_PASSWORD:-mayanredispassword}@mayan-redis:6379/2'}"

x-mayan-container: &mayan-container
  env_file: .mayan-env
  environment:
    <<: [*mayan-environment]
  image: ${MAYAN_DOCKER_IMAGE:-image-registry.apps.silver.devops.gov.bc.ca/3cd915-tools/mayan-bcgov}:${MAYAN_DOCKER_TAG:-4.7.1}
  networks:
    - mayan
  restart: unless-stopped
  volumes:
    - ${MAYAN_APP_VOLUME:-mayan-app}:/var/lib/mayan
    # Optional volumes to access external data like staging or watch folders
    # - /opt/staging_folder:/staging_folder
    # - /opt/watch_folder:/watch_folder

x-mayan-depends_on: &mayan-depends_on
  depends_on:
    mayan-postgres:
      condition: service_healthy
    mayan-rabbitmq:
      condition: service_healthy
    mayan-redis:
      condition: service_healthy
    setup-or-upgrade:
      condition: service_completed_successfully # This ensures that the setup-or-upgrade service has completed successfully before starting the mayan containers.

services:
  ####################### Mayan Frontend (Web Server) #######################
  mayan-frontend:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-frontend
    profiles:
      - all_in_one
      - all
      - mayan
    ports:
      - "7080:8000"
    # Give mayan-frontend dual network membership. This allows it to communicate with the mayan backend and workers
    # on the mayan network, while also being accessible from the psp network for PIMS access (for document uploads).
    networks:
      - mayan
      - psp
    command:
      - run_frontend
    # CPU/Memory resource constraints
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1500M
        reservations:
          memory: 400M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mayan-edms/bin/python -c "import sys,urllib.request; r=urllib.request.urlopen(''http://127.0.0.1:8000/'', timeout=5); sys.exit(0 if r.status<400 else 1)"',
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s # Gives Gunicorn processes time to worker-fork on slow boots

  ####################### Mayan Elasticsearch #######################
  mayan-elasticsearch:
    container_name: mayan-elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.max_content_length=400mb
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${MAYAN_ELASTICSEARCH_PASSWORD:-mayanespassword}
    image: ${MAYAN_DOCKER_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch}:${MAYAN_DOCKER_ELASTICSEARCH_TAG:-7.17.26}
    networks:
      - mayan
    # Enable to allow external access to the database.
    # ports:
    #  - "9200:9200"
    profiles:
      - elasticsearch
      - all
      - mayan
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${MAYAN_ELASTICSEARCH_VOLUME:-mayan-elasticsearch}:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --silent --user elastic:${MAYAN_ELASTICSEARCH_PASSWORD:-mayanespassword} "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" >/dev/null',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  ####################### Mayan PostgreSQL (holds configuration and data for mayan) #######################
  mayan-postgres:
    container_name: mayan-postgres
    command:
      - "postgres"
      - "-c"
      - "checkpoint_completion_target=0.6"
      - "-c"
      - "default_statistics_target=200"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=8MB"
    environment:
      POSTGRES_DB: ${MAYAN_DATABASE_NAME:-mayan}
      POSTGRES_PASSWORD: ${MAYAN_DATABASE_PASSWORD:-mayandbpass}
      POSTGRES_USER: ${MAYAN_DATABASE_USER:-mayan}
    image: postgres:${MAYAN_DOCKER_POSTGRES_TAG:-14.12-alpine}
    networks:
      - mayan
    # Enable to allow external access to the database.
    # ports:
    #  - "5432:5432"
    profiles:
      - postgresql
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_POSTGRES_VOLUME:-mayan-postgres}:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${MAYAN_DATABASE_USER:-mayan} -d ${MAYAN_DATABASE_NAME:-mayan}",
        ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

  ####################### Mayan Redis (holds caching data for mayan) #######################
  mayan-redis:
    container_name: mayan-redis
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "3"
      - --maxmemory
      - "100mb"
      - --maxclients
      - "500"
      - --maxmemory-policy
      - "allkeys-lru"
      - --save
      - ""
      - --tcp-backlog
      - "256"
      - --requirepass
      - "${MAYAN_REDIS_PASSWORD:-mayanredispassword}"
    image: redis:${MAYAN_DOCKER_REDIS_TAG:-6.2-alpine}
    networks:
      - mayan
    profiles:
      - redis
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_REDIS_VOLUME:-mayan-redis}:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${MAYAN_REDIS_PASSWORD:-mayanredispassword}",
          "ping",
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  ####################### Mayan RabbitMQ (handles message queuing for mayan) #######################
  mayan-rabbitmq:
    container_name: mayan-rabbitmq
    image: rabbitmq:${MAYAN_DOCKER_RABBITMQ_TAG:-3.12.1-management-alpine}
    environment:
      RABBITMQ_DEFAULT_USER: ${MAYAN_RABBITMQ_USER:-mayan}
      RABBITMQ_DEFAULT_PASS: ${MAYAN_RABBITMQ_PASSWORD:-mayanrabbitpass}
      RABBITMQ_DEFAULT_VHOST: ${MAYAN_RABBITMQ_VHOST:-mayan}
    networks:
      - mayan
    # Enable to allow access to the administration interface.
    # ports:
    #   - "15672:15672"
    profiles:
      - rabbitmq
      - all
      - mayan
    restart: unless-stopped
    volumes:
      - ${MAYAN_RABBITMQ_VOLUME:-mayan-rabbitmq}:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 10s

  ####################### Setup or Upgrade (Initializes or upgrades the mayan database. Runs before mayan containers) #######################
  setup-or-upgrade:
    <<: *mayan-container
    container_name: mayan-db-migration
    command:
      - run_initial_setup_or_perform_upgrade
    profiles:
      - setup_or_upgrade
      - all
      - mayan
    restart: "no"
    depends_on:
      mayan-postgres:
        condition: service_healthy
      mayan-rabbitmq:
        condition: service_healthy
      mayan-redis:
        condition: service_healthy

  ####################### Worker A handles fast UI responses, low latency tasks, AND periodic tasks (--beat) #######################
  mayan-worker-a:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-worker-a
    command:
      - run_worker
      - worker_a
      - --autoscale=10,1 --max-tasks-per-child=1 --beat --pidfile=/tmp/celerybeat.pid -l INFO
    profiles:
      - extra_worker_a
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M

  ####################### Worker B processes document uploads & metadata changes #######################
  mayan-worker-b:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-worker-b
    command:
      - run_worker
      - worker_b
      - --autoscale=3,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_b
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M

  ####################### Worker C handles complex processing tasks (OCR, layout parsing) #######################
  mayan-worker-c:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-worker-c
    command:
      - run_worker
      - worker_c
      - --autoscale=10,5 --max-tasks-per-child=1
    profiles:
      - extra_worker_c
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "2.0" # Higher allocation for heavy file conversions
          memory: 2000M

  ####################### Worker D processes long background maintenance scripts #######################
  mayan-worker-d:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-worker-d
    command:
      - run_worker
      - worker_d
      - --autoscale=5,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_d
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M

  ####################### Worker E handles low-priority events or scheduled workflows #######################
  mayan-worker-e:
    <<: [*mayan-container, *mayan-depends_on]
    container_name: mayan-worker-e
    command:
      - run_worker
      - worker_e
      - --autoscale=5,1 --max-tasks-per-child=1 --prefetch-multiplier=1
    profiles:
      - extra_worker_e
      - all
      - mayan
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M

  # worker_custom_queue:
  #   <<: *mayan-container
  #   command:
  #     - /bin/sh
  #     - -c
  #     - "MAYAN_QUEUE_LIST=${MAYAN_WORKER_CUSTOM_QUEUE_LIST:-} /usr/local/bin/run_worker.sh --prefetch-multiplier=1"
  #   profiles:
  #     - extra_worker_custom
  #     - all
  #     - mayan

  # Run a separate Celery beat container
  # celery_beat:
  #   <<: *mayan-container
  #   command:
  #     - run_celery
  #     - beat -l INFO --pidfile=/tmp/celerybeat.pid
  #   profiles:
  #     - extra_celery_beat
  #     - all
  #     - mayan

  # Enable to run standalone workers
  mayan-mountindex:
    <<: *mayan-container
    container_name: mayan-mountindex
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    entrypoint:
      - /bin/sh
      - -c
      - 'mkdir --parents /mnt/index && chown mayan:mayan /mnt/index && /usr/local/bin/entrypoint.sh run_command "mountindex --allow-other creation_date /mnt/index"' # Replace "creation_date" with the index of your choice.
    profiles:
      - mountindex
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: /mnt/mayan_indexes/creation_date # Host location where the index will show up.
        target: /mnt/index # Location inside the container where the index will be mounted. Must the same is in the "entrypoint" section.
        bind:
          propagation: shared

volumes:
  mayan-app:
  mayan-elasticsearch:
  mayan-postgres:
  mayan-rabbitmq:
  mayan-redis:
  mayan-mountindex:
