/* -----------------------------------------------------------------------------
Populate PIMS_PROP_ACT_MIN_CONTACT_HIST from the TMP_PROP_ACT_MIN_CONTACT_HIST 
table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-24  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROP_ACT_MIN_CONTACT_HIST data to the PIMS_PROP_ACT_MIN_CONTACT_HIST table
PRINT N'Migrate the TMP_PROP_ACT_MIN_CONTACT_HIST data to the PIMS_PROP_ACT_MIN_CONTACT_HIST table'
GO
INSERT INTO dbo.PIMS_PROP_ACT_MIN_CONTACT_HIST (_PROP_ACT_MIN_CONTACT_HIST_ID, EFFECTIVE_DATE_HIST, END_DATE_HIST, PROP_ACT_MIN_CONTACT_ID, PIMS_MANAGEMENT_ACTIVITY_ID, PERSON_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT _PROP_ACT_MIN_CONTACT_HIST_ID
       , EFFECTIVE_DATE_HIST
       , END_DATE_HIST
       , PROP_ACT_MIN_CONTACT_ID
       , PIMS_MANAGEMENT_ACTIVITY_ID
       , PERSON_ID
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROP_ACT_MIN_CONTACT_HIST
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
