/* -----------------------------------------------------------------------------
Populate PIMS_PROP_ACT_MIN_CONTACT from the TMP_PROP_ACT_MIN_CONTACT table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-24  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT DISABLE TRIGGER PIMS_PRACMC_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT DISABLE TRIGGER PIMS_PRACMC_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT DISABLE TRIGGER PIMS_PRACMC_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROP_ACT_MIN_CONTACT data to the PIMS_PROP_ACT_MIN_CONTACT table
PRINT N'Migrate the TMP_PROP_ACT_MIN_CONTACT data to the PIMS_PROP_ACT_MIN_CONTACT table'
GO
INSERT INTO dbo.PIMS_PROP_ACT_MIN_CONTACT (PROP_ACT_MIN_CONTACT_ID, PIMS_MANAGEMENT_ACTIVITY_ID, PERSON_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT PROP_ACT_MIN_CONTACT_ID
       , PIMS_MANAGEMENT_ACTIVITY_ID
       , PERSON_ID
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROP_ACT_MIN_CONTACT
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Enable the triggers on the table
PRINT N'Enable the triggers on the table'
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT ENABLE TRIGGER PIMS_PRACMC_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT ENABLE TRIGGER PIMS_PRACMC_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROP_ACT_MIN_CONTACT ENABLE TRIGGER PIMS_PRACMC_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
