/* -----------------------------------------------------------------------------
Populate PIMS_PROPERTY_ACTIVITY_INVOICE from the 
TMP_PROPERTY_ACTIVITY_INVOICE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-24  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE DISABLE TRIGGER PIMS_PRACIN_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE DISABLE TRIGGER PIMS_PRACIN_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE DISABLE TRIGGER PIMS_PRACIN_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROPERTY_ACTIVITY_INVOICE data to the PIMS_PROPERTY_ACTIVITY_INVOICE table
PRINT N'Migrate the TMP_PROPERTY_ACTIVITY_INVOICE data to the PIMS_PROPERTY_ACTIVITY_INVOICE table'
GO
INSERT INTO dbo.PIMS_PROPERTY_ACTIVITY_INVOICE (PROPERTY_ACTIVITY_INVOICE_ID, PIMS_MANAGEMENT_ACTIVITY_ID, INVOICE_DT, INVOICE_NUM, DESCRIPTION, PRETAX_AMT, GST_AMT, PST_AMT, TOTAL_AMT, IS_PST_REQUIRED, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT PROPERTY_ACTIVITY_INVOICE_ID
       , PIMS_MANAGEMENT_ACTIVITY_ID
       , INVOICE_DT
       , INVOICE_NUM
       , DESCRIPTION
       , PRETAX_AMT
       , GST_AMT
       , PST_AMT
       , TOTAL_AMT
       , IS_PST_REQUIRED
       , IS_DISABLED
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROPERTY_ACTIVITY_INVOICE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE ENABLE TRIGGER PIMS_PRACIN_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE ENABLE TRIGGER PIMS_PRACIN_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY_INVOICE ENABLE TRIGGER PIMS_PRACIN_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
