#!groovy
def MS_TEAMS_SECRET
def MS_TEAMS_WEBHOOK_KEY
def RELEASE_VERSION
def TAG
pipeline {

    agent any
    environment {
            // MS Teams Configuration
        MS_TEAMS_SECRET = 'ms-teams-secrets'
        MS_TEAMS_WEBHOOK_KEY = 'notification-webhook'
    }

    options {
        office365ConnectorWebhooks([[
                    startNotification: true,
                        url: 'https://bcgov.webhook.office.com/webhookb2/2efef2eb-e8ad-40ac-826c-87ae0751445e@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/4487f15457684a3cbb78de177fdf6e20/09519648-29f1-4055-ba6b-ba6a2cab509a'
            ]]
        )
    }

    stages {
        stage('Init') {
            steps {
                echo 'Starting!'
            }
        }
        stage('Upload') {
    steps {
        script {
        MS_TEAMS_SECRET = 'ms-teams-secrets'
        MS_TEAMS_WEBHOOK_KEY = 'notification-webhook'
         env.NOTIFICATION_WEBHOOK_URL = sh(script: "oc extract --to=- --keys=${MS_TEAMS_WEBHOOK_KEY} secret/ms-teams-secrets 2>&1 | sed -n 2p", returnStdout: true).trim()
        //RELEASE_VERSION = 'v2.0.7.0.3'
		    RELEASE_VERSION = sh (
      returnStdout: true,
      script: 'git describe --abbrev=0 --tags'
    ).trim()
	    TAG = sh (
      returnStdout: true,
      script: 'git describe --tags `git rev-list --tags --max-count=1`'
    ).trim()

    BUILD_TRIGGER_BY = "${currentBuild.getBuildCauses()[0].shortDescription}"
    echo "BUILD_TRIGGER_BY: ${BUILD_TRIGGER_BY}"
        // some instructions here
          // Print all environment variables
          echo "${RELEASE_VERSION}"
		  echo "${TAG}"
          echo "${env.NOTIFICATION_WEBHOOK_UR}"
          echo sh(returnStdout: true, script: 'env')
        }
                  
    }
        }
    }
        post {
        failure {
            office365ConnectorSend webhookUrl: "https://bcgov.webhook.office.com/webhookb2/2efef2eb-e8ad-40ac-826c-87ae0751445e@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/4487f15457684a3cbb78de177fdf6e20/09519648-29f1-4055-ba6b-ba6a2cab509a",
                factDefinitions: [[name: "fact1", template: "content of fact1"],
                                  [name: "fact2", template: "content of fact2"]]
        }
        success{
            script {
            office365ConnectorSend webhookUrl: "https://bcgov.webhook.office.com/webhookb2/2efef2eb-e8ad-40ac-826c-87ae0751445e@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/4487f15457684a3cbb78de177fdf6e20/09519648-29f1-4055-ba6b-ba6a2cab509a",
            message: 'Application has been [deployed](https://uat.green.biz)',
            status: 'Success',
            color: '#00FF00',
            factDefinitions: [[name: "Release version", template: "${RELEASE_VERSION}" ],
                              [name: "Remarks", template: "${BUILD_TRIGGER_BY}" ]]
            }
        }
        }
}