/* -----------------------------------------------------------------------------
Alter the data in the PIMS_ACQ_CHKLST_ITEM_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2023-Jan-30  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set all hints to NULL
UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
SET    HINT = NULL
     , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "LANDTTL" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LANDTTL'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DESCRIPTION                = N'Land Title documents or plans'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "SGNPAPLAN" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SGNPAPLAN'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DESCRIPTION                = N'Property Acquisition (PA) Plan'
       , HINT                       = N'A signed copy of the PA Plan is required'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "OTHERRPTS" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'OTHERRPTS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    HINT                       = N'Final copies of professional reports (e.g. Environmental reports)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "SAASIGNED" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SAASIGNED'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    HINT                       = N'The signed SAA is required'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "FINALAGRM" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FINALAGRM'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Final agreements with owner(s)'
       , HINT                       = N'H179 P/T/A, TLCA, LTC, etc.'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "LEGALDOCS" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LEGALDOCS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Instructions or documents sent to lawyer'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "ENTRYCOND" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ENTRYCOND'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Conditions of Entry (H0443)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "REGSTRDPLAN" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'REGSTRDPLAN'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Registered Plan'
       , HINT                       = N'Letter size (8.5" x 11")'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "NEWTTLACOMP" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NEWTTLACOMP'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    HINT                       = N'Copy of new title after completion'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "BCTFANOTIF" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'BCTFANOTIF'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'If this a total take with a surplus, then BCTFA notified'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "AVNCDPMTNTY" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'AVNCDPMTNTY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Notice of Advanced Payment (Form 8)'
       , HINT                       = N'The signed Form 8 is required'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "CLAIMRELSS3" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CLAIMRELSS3'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Release of Claims'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "ALCORDER" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ALCORDER'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    HINT                       = N'If applicable'
       , DISPLAY_ORDER              = 28
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "EXPROPAPPRV" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPAPPRV'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    HINT                       = N'Executive and case summaries'
       , DISPLAY_ORDER              = 28
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "EXPROPFORM1" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPFORM1'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Notice of Expropriation (Form 1)'
       , HINT                       = N'The signed Form 1 is required'
       , DISPLAY_ORDER              = 29
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "EXPROPFORM5" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPFORM5'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Approval of Expropriation (Form 5)'
       , HINT                       = N'The signed Form 5 is required'
       , DISPLAY_ORDER              = 30
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "VESTNOTICE" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'VESTNOTICE'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Vesting Notice (Form 9)'
       , HINT                       = N'The signed Form 5 is required'
       , DISPLAY_ORDER              = 31
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "SVCAFFADAV" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SVCAFFADAV'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Copies of Affidavits of Service'
       , DISPLAY_ORDER              = 32
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "CLAIMRELSS6" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CLAIMRELSS6'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    DESCRIPTION                = N'Release of Claims'
       , DISPLAY_ORDER              = 33
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter the "PIMSUPDTFIL" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PIMSUPDTFIL'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE
  SET    HINT                       = N'Data is complete in this system'
       , DISPLAY_ORDER              = 34
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
