-- File generated on 01/08/2026 12:25:28 PM.
-- Autogenerated file. Do not manually modify.

:On Error Exit
SET XACT_ABORT ON
GO

PRINT '     == DB SCRIPT START ========'
GO

BEGIN TRANSACTION
PRINT '     == DB TRANSACTION START ========'
   GO

   --Script section

   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/010_PSP_PIMS_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/010_PSP_PIMS_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/123_DML_PIMS_FORM_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/123_DML_PIMS_FORM_TYPE_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/147_DML_PIMS_DSP_CHKLST_SECTION_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/147_DML_PIMS_DSP_CHKLST_SECTION_TYPE_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/148_DML_PIMS_DSP_CHKLST_ITEM_TYPE_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S115_00/Alter Down/153_DML_PIMS_LEASE_CHKLST_ITEM_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S115_00/Alter Down/153_DML_PIMS_LEASE_CHKLST_ITEM_TYPE_Alter_Down.sql"
   :r $(filepath)

   --End script section

PRINT '     == DB TRANSACTION FINISH ========'
GO

If XACT_STATE()=1
  BEGIN
  PRINT '- Success: Committing Transaction...'
  COMMIT TRANSACTION;
  END
ELSE IF XACT_STATE()=-1
  BEGIN
  PRINT '- Error: Rolling Back Transaction...'
  ROLLBACK TRANSACTION;
  END;
ELSE IF XACT_STATE()=0
  BEGIN
  PRINT '- Error: No pending transactions...'
  ROLLBACK TRANSACTION;
  END;
GO
