import { MAP_MAX_NATIVE_ZOOM, MAP_MAX_ZOOM } from 'constants/strings';

import { ILayerItem } from './types';

export const layersTree: ILayerItem[] = [
  {
    key: 'Administrative Boundaries',
    label: 'Administrative Boundaries',
    on: false,
    nodes: [
      {
        key: 'currentEconomicRegions',
        label: 'Current Census Economic Regions',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW/ows?',
        layers: 'pub:WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW',
        transparent: true,
        format: 'image/png',
        zIndex: 0,
        id: 'currentEconomicRegions',
        color: '#bbdefb',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'moti',
        label: 'MOTI Regions',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.TADM_MOT_REGIONAL_BNDRY_POLY/ows?',
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.TADM_MOT_REGIONAL_BNDRY_POLY',
        transparent: true,
        format: 'image/png',
        zIndex: 21,
        id: 'moti',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'motiHighwayDistricts',
        label: 'MOTI Highway Districts',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.TADM_MOT_DISTRICT_BNDRY_POLY/ows?',
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.TADM_MOT_DISTRICT_BNDRY_POLY',
        transparent: true,
        format: 'image/png',
        zIndex: 21,
        id: 'motiHighwayDistricts',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'municipalities',
        label: 'Municipalities',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP',
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 20,
        id: 'municipalityLayer',
        opacity: 0.5,
        color: '#b39ddb',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'regionalDistricts ',
        label: 'Regional Districts ',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP',
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 19,
        id: 'regionalDistricts',
        opacity: 0.5,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'firstNations',
    label: 'First Nations',
    on: false,
    nodes: [
      {
        key: 'firstNationsReserves',
        label: 'First Nations reserves',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP/ows?',
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationsReserves',
        color: '#ebe0d7',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyAreas',
        label: 'First Nation Treaty Areas',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyAreas',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyLands',
        label: 'First Nations Treaty Lands',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyLands',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyRelatedLands',
        label: 'First Nations Treaty Related Lands',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyRelatedLands',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatySideAgreement',
        label: 'First Nation Treaty Side Agreements',
        on: false,
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatySideAgreement',
        color: '#ffc5ae',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'landOwnership',
    label: 'Land Ownership',
    on: false,
    nodes: [
      {
        key: 'crownLeases',
        label: 'Crown Leases',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_LEASES_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LEASES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 7,
        id: 'crownLeases',
        opacity: 0.5,
        color: '#8dc2d5',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownInventory',
        label: 'Crown Inventory',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 6,
        id: 'crownInventory',
        opacity: 0.5,
        color: '#fcc1eb',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownInclusions',
        label: 'Crown Inclusions',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownInclusions',
        opacity: 0.5,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownLandLicenses',
        label: 'Crown Land Licenses',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_LICENSES_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LICENSES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownLandLicenses',
        opacity: 0.5,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownTenures',
        label: 'Crown Tenures',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_TENURES_SVW/',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_TENURES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownTenures',
        opacity: 0.5,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'parcelBoundaries',
        label: 'Parcel Boundaries',
        on: true,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
        layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
        transparent: true,
        format: 'image/png',
        zIndex: 18,
        id: 'parcelLayer',
        color: '#ff9800',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'zoning',
    label: 'Zoning',
    on: false,
    nodes: [
      {
        key: 'agriculturalLandReserveLines',
        label: 'Agricultural Land Reserve Lines',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_BOUNDARY_LINES_SVW',
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_BOUNDARY_LINES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'agriculturalLandReserveLines',
        opacity: 0.5,
        color: '#00b300',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'electoral',
    label: 'Electoral',
    on: false,
    nodes: [
      {
        key: 'currentElectoralDistricts',
        label: 'Current Provincial Electoral Districts of British Columbia',
        on: false,
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW',
        url:
          'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'currentElectoralDistricts',
        opacity: 0.5,
        color: '#da2223',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
];
