<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveButton</name>
   <tag></tag>
   <elementGuidId>6c2cdfe1-db3c-45ee-aefc-6275d29f4131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[2]/div[2]/div[1]/div[3]/form[1]/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button.btn.btn-primary > div.Button__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-lbhJmS LGkYn authenticated&quot;]/div[@class=&quot;sc-eicnZh bSQUzR content&quot;]/div[@class=&quot;sc-jivCuG hcnbXe&quot;]/div[@class=&quot;sc-hYQoDq fTqTJk&quot;]/form[@class=&quot;sc-gslxyl yrhAb&quot;]/div[@class=&quot;sc-lkgURy bppiDU&quot;]/button[@class=&quot;Button btn btn-primary&quot;]/div[@class=&quot;Button__value&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[3]/form[1]/div[2]/button[2]</value>
   </webElementXpaths>
</WebElementEntity>
