DELETE 
FROM   PIMS_ACTIVITY_TEMPLATE;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_TEMPLATE] ([ACTIVITY_TEMPLATE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER])
VALUES
  (N'GENERAL', 1),
  (N'SITEVIS', 1),
  (N'SURVEY',  1),
  (N'FILEDOC', 1);
GO
