PRINT N'Adding DB Audit Columns'

ALTER TABLE dbo.[PIMS_LEASE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_LEASE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_EXPECTED_AMOUNT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_ACTIVITY_PERIOD]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_ACTIVITY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_SUBTYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_PURPOSE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_PURPOSE_SUBTYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_STATUS_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_PMT_FREQ_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_PROGRAM_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
