DELETE FROM PIMS_MANAGEMENT_ACTIVITY_PROPERTY;
GO

INSERT INTO PIMS_MANAGEMENT_ACTIVITY_PROPERTY (MANAGEMENT_ACTIVITY_ID, PROPERTY_ID)
VALUES
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()));
GO
