INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 20, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 3, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'RESEARCH', 22, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'RESEARCH', 19, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 4, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 15, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 11, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 17, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 13, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 9, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 4, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'LEASLIC', 18, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'DISPOSE', 9, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'LEASLIC', 8, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 6, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 20, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'DISPOSE', 25, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'DISPOSE', 5, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 5, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 16, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 2, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'RESEARCH', 9, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 18, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'RESEARCH', 1, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 7, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 22, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'LEASLIC', 3, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'LEASLIC', 1, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'PROJECT', 12, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 6, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 14, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 25, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 10, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'MANAGEMENT', 3, 1)
GO
INSERT INTO [dbo].[PIMS_DOCUMENT_CATEGORY_SUBTYPE]([DOCUMENT_CATEGORY_TYPE_CODE], [DOCUMENT_TYPE_ID], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(N'ACQUIRE', 19, 1)
GO
