kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs-20
  namespace: 3cd915-tools
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2024-03-06T01:22:09Z'
    description: ImageStream definitions for NodeJS 20
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 1-34
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi9/nodejs-20:1-34'
      generation: 1
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source