PRINT N'Adding DB Audit Columns'

ALTER TABLE dbo.[PIMS_ACTIVITY_MODEL]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_WORKFLOW_MODEL_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_REGION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_COUNTRY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ADDRESS_USAGE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_CLAIM]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_TASK_TEMPLATE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ORGANIZATION_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ACCESS_REQUEST_STATUS_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_STATUS_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_SERVICE_FILE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_RISK_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_TIER_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ROLE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_CLASSIFICATION_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_CONTACT_METHOD_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_TENURE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_AREA_UNIT_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_DATA_SOURCE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_STATUS_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ORG_IDENTIFIER_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_SERVICE_FILE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_TASK_TEMPLATE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_WORKFLOW_MODEL]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_DISTRICT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROVINCE_STATE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ROLE_CLAIM]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_NOTE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_WORKFLOW_MODEL]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ADDRESS]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ORGANIZATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PERSON]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PERSON_ORGANIZATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_CONTACT_METHOD]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ACTIVITY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_USER]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROJECT_PROPERTY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_ACTIVITY]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_USER_ORGANIZATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ACCESS_REQUEST]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_ACCESS_REQUEST_ORGANIZATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_USER_ROLE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_PROPERTY_SERVICE_FILE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_ORGANIZATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_EVALUATION]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_TASK]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_TENANT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
