PRINT 'Adding AdministrativeAreas'

MERGE INTO dbo.[AdministrativeAreas] Target
USING ( VALUES
('100 Mile House','2','Cariboo Regional District'),
('150 Mile House','3',NULL),
('Abbotsford','4','Fraser Valley Regional District'),
('Agassiz','5',NULL),
('Ahousaht','6',NULL),
('Albert Canyon','7',NULL),
('Aldergrove','8',NULL),
('Alert Bay','9','Regional District of Mount Waddington'),
('Alexis Creek','10',NULL),
('Aleza Lake','11',NULL),
('Allison Pass','12',NULL),
('Anahim Lake','13',NULL),
('Anmore','Anmore','Metro Vancouver Regional District'),
('Armstrong','14','Regional District of North Okanagan'),
('Ashcroft','15','Thompson-Nicola Regional District'),
('Athalmere','16',NULL),
('Atlin','17',NULL),
('Avola','18',NULL),
('Baldonnel','19',NULL),
('Balfour','20',NULL),
('Bamfield','21',NULL),
('Barnston Island','22',NULL),
('Barriere','23','Thompson-Nicola Regional District'),
('Bear Lake','24',NULL),
('Beaverdell','25',NULL),
('Belcarra','Belcarra','Metro Vancouver Regional District'),
('Bella Bella','26',NULL),
('Bella Coola','27',NULL),
('Big Bar Creek','28',NULL),
('Birch Island','29',NULL),
('Blue River','30',NULL),
('Bob Quinn Lake','31',NULL),
('Boston Bar','32',NULL),
('Boswell','33',NULL),
('Bowen Island','34','Metro Vancouver Regional District'),
('Bradner','35',NULL),
('Bridge Lake','36',NULL),
('Buick Creek','37',NULL),
('Burnaby','38','Metro Vancouver Regional District'),
('Burns Lake','39','Regional District of Bulkley-Nechako'),
('Cache Creek','41','Thompson-Nicola Regional District'),
('Cache','40',NULL),
('Campbell River','42','Strathcona Regional District'),
('Canal Flats','Canal Flats','Regional District of East Kootenay'),
('Cassiar','43',NULL),
('Cassidy','44',NULL),
('Castlegar','45','Regional District of Central Kootenay'),
('Cecil Lake','46',NULL),
('Central Saanich','47','Capital Regional District'),
('Charlie Lake','48',NULL),
('Chase','49','Thompson-Nicola Regional District'),
('Chemainus','50',NULL),
('Cherryville','51',NULL),
('Chetwynd','52','Peace River Regional District'),
('Chief Lake','53',NULL),
('Chilliwack','54','Fraser Valley Regional District'),
('Clayhurst','55',NULL),
('Clearbrook','56',NULL),
('Clearwater','57','Thompson-Nicola Regional District'),
('Clinton','58','Thompson-Nicola Regional District'),
('Cloverdale','59',NULL),
('Coalmont','60',NULL),
('Cobble Hill','61',NULL),
('Coldstream','Coldstream','Regional District of North Okanagan'),
('Coldwater Lakes','62',NULL),
('Colwood','63','Capital Regional District'),
('Comox','64','Comox Valley Regional District'),
('Coquitlam','65','Metro Vancouver Regional District'),
('Cortes Island','66',NULL),
('Courtenay','67','Comox Valley Regional District'),
('Cowichan Bay','68',NULL),
('Cowichan Lake','69',NULL),
('Cranbrook','70','Regional District of East Kootenay'),
('Crawford Bay','71',NULL),
('Creston','72','Regional District of Central Kootenay'),
('Cultus Lake','73',NULL),
('Cumberland','74','Comox Valley Regional District'),
('Dawson Creek','75','Peace River Regional District'),
('Dease Lake','76',NULL),
('Decker Lake','77',NULL),
('Delta','78','Metro Vancouver Regional District'),
('Denman Island','79',NULL),
('Duncan','81','Cowichan Valley Regional District'),
('Edgewood','82',NULL),
('Elkford','83','Regional District of East Kootenay'),
('Elko','84',NULL),
('Enderby','85','Regional District of North Okanagan'),
('Errington','86',NULL),
('Esquimalt','87','Capital Regional District'),
('Fairharbour','88',NULL),
('Falkland','89',NULL),
('Fauquier','90',NULL),
('Fernie','91','Regional District of East Kootenay'),
('Field','92',NULL),
('Fort Fraser','93',NULL),
('Fort Nelson','94',NULL),
('Fort St. James','95','Regional District of Bulkley-Nechako'),
('Fort St. John','96','Peace River Regional District'),
('Fort Ware','97',NULL),
('Francois Lake','98',NULL),
('Fraser Lake','99','Regional District of Bulkley-Nechako'),
('Fruitvale','100','Regional District of Kootenay Boundary'),
('Gabriola Island','101',NULL),
('Galiano Island','102',NULL),
('Ganges','103',NULL),
('Garibaldi Highlands','104',NULL),
('Gibsons','105','Sunshine Coast Regional District'),
('Gillies Bay','106',NULL),
('Gold River','107','Strathcona Regional District'),
('Goldbridge','108',NULL),
('Golden','109','Columbia-Shuswap Regional District'),
('Good Hope','110',NULL),
('Grand Forks','111','Regional District of Kootenay Boundary'),
('Granisle','112','Regional District of Bulkley-Nechako'),
('Grassy Plains','113',NULL),
('Greenwood','114','Regional District of Kootenay Boundary'),
('Hagensborg','115',NULL),
('Hansard Creek','116',NULL),
('Harrison Hot Springs','117','Fraser Valley Regional District'),
('Hartley Bay','118',NULL),
('Hazelton','119','Regional District of Kitimat-Stikine'),
('Highlands','Highlands','Capital Regional District'),
('Hixon','120',NULL),
('Holberg','121',NULL),
('Honeymoon Creek','122',NULL),
('Hope','123','Fraser Valley Regional District'),
('Hornby Island','124',NULL),
('Horsefly','125',NULL),
('Houston','126','Regional District of Bulkley-Nechako'),
('Hudson''s Hope','127','Peace River Regional District'),
('Hutda Lake','128',NULL),
('Invermere','129','Regional District of East Kootenay'),
('Jade City','130',NULL),
('Jaffray','131',NULL),
('Jordan River','132',NULL),
('Juliet Pit','133',NULL),
('Jumbo Glacier Mountain Resort Municipality','Jumbo Glacier','Regional District of East Kootenay'),
('Kaleden','134',NULL),
('Kamloops','135','Thompson-Nicola Regional District'),
('Kaslo','136','Regional District of Central Kootenay'),
('Kelowna','137','Regional District of Central Okanagan'),
('Kent','Kent','Fraser Valley Regional District'),
('Keremeos','138','Regional District of Okanagan-Similkameen'),
('Kimberley','139','Regional District of East Kootenay'),
('Kincolith','140',NULL),
('Kiskatinaw','141',NULL),
('Kitimat','142','Regional District of Kitimat-Stikine'),
('Kitkatla','143',NULL),
('Kitwanga','144',NULL),
('Klemtu','145',NULL),
('Kyuquot','146',NULL),
('Ladner','147',NULL),
('Ladysmith','148','Cowichan Valley Regional District'),
('Lake Country','Lake Country','Regional District of Central Okanagan'),
('Lake Cowichan','Lake Cowichan','Cowichan Valley Regional District'),
('Langford','149','Capital Regional District'),
('Langley','150','Metro Vancouver Regional District'),
('Lantzville','151','Regional District of Nanaimo'),
('Lardeau','152',NULL),
('Lasqueti Island','153',NULL),
('Likely','154',NULL),
('Lillooet','155','Squamish-Lillooet Regional District'),
('Lions Bay','156','Metro Vancouver Regional District'),
('Little Fort','157',NULL),
('Logan Lake','158','Thompson-Nicola Regional District'),
('Loon Creek','159',NULL),
('Lower Nicola','Nicola','Lower County'),
('Lumby','161','Regional District of North Okanagan'),
('Lytton','162','Thompson-Nicola Regional District'),
('Mackenzie','163','Regional District of Fraser-Fort George'),
('Madeira Park','164',NULL),
('Mansons Landing','165',NULL),
('Maple Ridge','166','Metro Vancouver Regional District'),
('Marysville','167',NULL),
('Masset','168','North Coast Regional District'),
('Matsqui','169',NULL),
('Mayne Island','170',NULL),
('Mcbride','171','Regional District of Fraser-Fort George'),
('Mcleese Lake','172',NULL),
('Mclure','173',NULL),
('Meadow Creek','174',NULL),
('Merritt','175','Thompson-Nicola Regional District'),
('Metchosin','176','Capital Regional District'),
('Meziadin Lake','177',NULL),
('Midway','178','Regional District of Kootenay Boundary'),
('Mill Bay','179',NULL),
('Mission','180','Fraser Valley Regional District'),
('Montney','181',NULL),
('Montrose','182','Regional District of Kootenay Boundary'),
('Mount Lemoray','183',NULL),
('Nakusp','184','Regional District of Central Kootenay'),
('Nanaimo','185','Regional District of Nanaimo'),
('Nanoose Bay','186',NULL),
('Nazko','187',NULL),
('Nelson','188','Regional District of Central Kootenay'),
('New Aiyansh','189',NULL),
('New Denver','190','Regional District of Central Kootenay'),
('New Hazelton','191','Regional District of Kitimat-Stikine'),
('New Westminster','192','Metro Vancouver Regional District'),
('No City Yet','1',NULL),
('North Cowichan','North Cowichan','Cowichan Valley Regional District'),
('North Delta','193',NULL),
('North Pender Island','194',NULL),
('North Saanich','195','Capital Regional District'),
('North Vancouver','196','Metro Vancouver Regional District'),
('Northern Rockies Regional Municipality','NRRM','Province of British Columbia'),
('Oak Bay','197','Capital Regional District'),
('Okanagan Falls','198',NULL),
('Oliver','199','Regional District of Okanagan-Similkameen'),
('Osoyoos','200','Regional District of Okanagan-Similkameen'),
('Oyama','201',NULL),
('Parksville','202','Regional District of Nanaimo'),
('Peachland','203','Regional District of Central Okanagan'),
('Pemberton','204','Squamish-Lillooet Regional District'),
('Pender Island','205',NULL),
('Penticton','206','Regional District of Okanagan-Similkameen'),
('Pink Mountain','207',NULL),
('Pitt Meadows','208','Metro Vancouver Regional District'),
('Port Alberni','210','Regional District of Alberni-Clayoquot'),
('Port Alice','211','Regional District of Mount Waddington'),
('Port Clements','212','North Coast Regional District'),
('Port Coquitlam','213','Metro Vancouver Regional District'),
('Port Edward','Port Edward','North Coast Regional District'),
('Port Hardy','214','Regional District of Mount Waddington'),
('Port Mcneill','215','Regional District of Mount Waddington'),
('Port Moody','216','Metro Vancouver Regional District'),
('Port Renfrew','217',NULL),
('Port Simpson','209',NULL),
('Pouce Coupe','218','Peace River Regional District'),
('Powell River','219','qathet Regional District'),
('Prince George','220','Regional District of Fraser-Fort George'),
('Prince Rupert','221','North Coast Regional District'),
('Princeton','222','Regional District of Okanagan-Similkameen'),
('Progress','223',NULL),
('Purden Lake','224',NULL),
('Quadra Island','225',NULL),
('Qualicum Bay','226',NULL),
('Qualicum Beach','227','Regional District of Nanaimo'),
('Queen Charlotte','228','North Coast Regional District'),
('Quesnel','229','Cariboo Regional District'),
('Radium Hot Springs','Radium Hot Springs','Regional District of East Kootenay'),
('Rayleigh Corr Inst','230',NULL),
('Revelstoke','231','Columbia-Shuswap Regional District'),
('Richmond','232','Metro Vancouver Regional District'),
('Riondel','233',NULL),
('Riske Creek','234',NULL),
('Roberts Creek','235',NULL),
('Rock Creek','236',NULL),
('Rolla','237',NULL),
('Rose Prairie','238',NULL),
('Rosedale','239',NULL),
('Rossland','240','Regional District of Kootenay Boundary'),
('Rutland','241',NULL),
('Saanich','242','Capital Regional District'),
('Saanichton','243',NULL),
('Salmo','244','Regional District of Central Kootenay'),
('Salmon Arm Tsey Key','246',NULL),
('Salmon Arm Tsey Key','248',NULL),
('Salmon Arm','245','Columbia-Shuswap Regional District'),
('Saltspring Island','249',NULL),
('Salvus','250',NULL),
('Sandspit','251',NULL),
('Sardis','252',NULL),
('Saturna Island','253',NULL),
('Savona','254',NULL),
('Sayward','255','Strathcona Regional District'),
('Scotch Creek','256',NULL),
('Sechelt','257','Sunshine Coast Regional District'),
('Seton Portage','258',NULL),
('Shawnigan Lake','259',NULL),
('Shelter Bay','260',NULL),
('Sicamous','261','Columbia-Shuswap Regional District'),
('Sidney','262','Capital Regional District'),
('Silverton','263','Regional District of Central Kootenay'),
('Skidegate','264',NULL),
('Slim Creek','265',NULL),
('Slocan','Slocan','Regional District of Central Kootenay'),
('Smithers','266','Regional District of Bulkley-Nechako'),
('Soda Creek','267',NULL),
('Sointula','268',NULL),
('Sooke','269','Capital Regional District'),
('Southbank','270',NULL),
('Spallumcheen','Spallumcheen','Regional District of North Okanagan'),
('Sparwood','271','Regional District of East Kootenay'),
('Squamish','272','Squamish-Lillooet Regional District'),
('Stewart','273','Regional District of Kitimat-Stikine'),
('Summerland','274','Regional District of Okanagan-Similkameen'),
('Sun Peaks Mountain Resort Municipality','Sun Peaks','Thompson-Nicola Regional District'),
('Surrey','275','Metro Vancouver Regional District'),
('Tachie','276',NULL),
('Tahsis','277','Strathcona Regional District'),
('Takla','278',NULL),
('Tatla Lake','279',NULL),
('Tatogga Lake','280',NULL),
('Taylor','281','Peace River Regional District'),
('Telegraph Creek','282',NULL),
('Telkwa','283','Regional District of Bulkley-Nechako'),
('Terrace','284','Regional District of Kitimat-Stikine'),
('Tete Jaune','285',NULL),
('Texada Island','286',NULL),
('Thetis Island','287',NULL),
('Toad River','288',NULL),
('Tofino','289','Regional District of Alberni-Clayoquot'),
('Trail','290','Regional District of Kootenay Boundary'),
('Trout Lake','291',NULL),
('Tsawwassen','Tsawwassen','City of Delta'),
('Tsay Keh Dene Old Goldstream Creek','292',NULL),
('Tumbler Ridge','293','Peace River Regional District'),
('Ucluelet','294','Regional District of Alberni-Clayoquot'),
('Usk','295',NULL),
('Valemount','296','Regional District of Fraser-Fort George'),
('Vancouver','297','Metro Vancouver Regional District'),
('Vanderhoof','298','Regional District of Bulkley-Nechako'),
('Vernon','299','Regional District of North Okanagan'),
('Victoria','300','Capital Regional District'),
('View Royal','301','Capital Regional District'),
('Waglisla','302',NULL),
('Wardner','303',NULL),
('Warfield','Warfield','Regional District of Kootenay Boundary'),
('Wells','304','Cariboo Regional District'),
('West Kelowna','305','Regional District of Central Okanagan'),
('West Vancouver','306','Metro Vancouver Regional District'),
('Whistler','307','Squamish-Lillooet Regional District'),
('White Rock','308','Metro Vancouver Regional District'),
('Williams Lake','309','Cariboo Regional District'),
('Winlaw','310',NULL),
('Woss','311',NULL),
('Yahk','312',NULL),
('Zeballos','313','Strathcona Regional District')) AS MSrc (Name, Abbreviation, GroupName)
ON Target.Name = MSrc.NAME
WHEN MATCHED THEN
UPDATE
SET Target.Abbreviation = MSrc.Abbreviation, Target.GroupName = MSrc.GroupName
WHEN NOT MATCHED THEN
INSERT (Name, Abbreviation, GroupName) VALUES (MSrc.Name, MSrc.Abbreviation, MSrc.GroupName);
