PRINT N'Adding [PIMS_PROPERTY_DATA_SOURCE_TYPE]'

INSERT INTO PIMS_PROPERTY_DATA_SOURCE_TYPE (PROPERTY_DATA_SOURCE_TYPE_CODE, DESCRIPTION)
VALUES
  (N'PAIMS', N'Property Acquisition and Inventory Management System (PAIMS)'),
  (N'GAZ', N'BC Gazette');
