PRINT N'Create Property Spatial Indexes'

CREATE SPATIAL INDEX [PARCEL_LOCATION_IDX] ON dbo.[PIMS_PARCEL](Location) USING GEOGRAPHY_AUTO_GRID
CREATE SPATIAL INDEX [BUILDG_LOCATION_IDX] ON dbo.[PIMS_BUILDING](Location) USING GEOGRAPHY_AUTO_GRID
