SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

CREATE SPATIAL INDEX [PRPRTY_BOUNDARY_IDX] ON [dbo].[PIMS_PROPERTY] (BOUNDARY) 
  USING GEOMETRY_AUTO_GRID
    WITH (BOUNDING_BOX =( XMIN =200000, YMIN =300000, XMAX =1900000, YMAX =1800000 ))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
    
CREATE SPATIAL INDEX [PRPRTY_LOCATION_IDX] ON [dbo].[PIMS_PROPERTY] (LOCATION)
  USING GEOMETRY_AUTO_GRID
    WITH (BOUNDING_BOX =( XMIN =200000, YMIN =300000, XMAX =1900000, YMAX =1800000 ))        
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
