-- Script generated by Aqua Data Studio Schema Synchronization for MS SQL Server 2016 on Wed Feb 04 12:09:55 PST 2026
-- Execute this script on:
-- 		PSP_PIMS_S116_00/dbo - This database/schema will be modified
-- to synchronize it with MS SQL Server 2016:
-- 		PSP_PIMS_S117_00/dbo

-- We recommend backing up the database prior to executing the script.

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_PIMPRV_I_S_I_TR
PRINT N'Drop trigger dbo.PIMS_PIMPRV_I_S_I_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_PIMPRV_I_S_I_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_PIMPRV_I_S_U_TR
PRINT N'Drop trigger dbo.PIMS_PIMPRV_I_S_U_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_PIMPRV_I_S_U_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_PIMPRV_A_S_IUD_TR
PRINT N'Drop trigger dbo.PIMS_PIMPRV_A_S_IUD_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_PIMPRV_A_S_IUD_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop view dbo.PIMS_PROPERTY_LITE_VW
PRINT N'Drop view dbo.PIMS_PROPERTY_LITE_VW'
GO
DROP VIEW IF EXISTS [dbo].[PIMS_PROPERTY_LITE_VW]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop procedure dbo.PIM_DELETION_HISTORY
PRINT N'Drop procedure dbo.PIM_DELETION_HISTORY'
GO
DROP PROCEDURE IF EXISTS [dbo].[PIM_DELETION_HISTORY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop function dbo.PIM_GET_PK_COLUMN
PRINT N'Drop function dbo.PIM_GET_PK_COLUMN'
GO
DROP FUNCTION IF EXISTS [dbo].[PIM_GET_PK_COLUMN]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop function dbo.PIM_GET_COLUMN_LIST
PRINT N'Drop function dbo.PIM_GET_COLUMN_LIST'
GO
DROP FUNCTION IF EXISTS [dbo].[PIM_GET_COLUMN_LIST]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_FORM_TYPE
PRINT N'Create table dbo.PIMS_DISPOSITION_FORM_TYPE'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_FORM_TYPE]  ( 
	[DISPOSITION_FORM_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DOCUMENT_ID]               	bigint NULL,
	[DESCRIPTION]               	nvarchar(200) NOT NULL,
	[IS_DISABLED]               	bit NOT NULL CONSTRAINT [DSPFMT_IS_DISABLED_DEF]  DEFAULT (CONVERT([bit],(0))),
	[DISPLAY_ORDER]             	int NULL,
	[CONCURRENCY_CONTROL_NUMBER]	bigint NOT NULL CONSTRAINT [DSPFMT_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[DB_CREATE_TIMESTAMP]       	datetime NOT NULL CONSTRAINT [DSPFMT_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]          	nvarchar(30) NOT NULL CONSTRAINT [DSPFMT_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]  	datetime NOT NULL CONSTRAINT [DSPFMT_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]     	nvarchar(30) NOT NULL CONSTRAINT [DSPFMT_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [DSPFMT_PK] PRIMARY KEY CLUSTERED([DISPOSITION_FORM_TYPE_CODE])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Code value of the disposition form type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DISPOSITION_FORM_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DOCUMENT table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DOCUMENT_ID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Description of the form type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DESCRIPTION'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Indicates if the record is disabled and therefore not selectable or displayed.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'IS_DISABLED'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Designates a preferred presentation order of the code descriptions.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DISPLAY_ORDER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Codified values for the form types.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FORM_TYPE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_FILE_FORM
PRINT N'Create table dbo.PIMS_DISPOSITION_FILE_FORM'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_FILE_FORM]  ( 
	[DISPOSITION_FILE_FORM_ID]      	bigint NOT NULL CONSTRAINT [DSPFRM_DISPOSITION_FILE_FORM_ID_DEF]  DEFAULT (NEXT VALUE FOR [PIMS_ACQUISITION_FILE_FORM_ID_SEQ]),
	[DISPOSITION_FILE_ID]           	bigint NOT NULL,
	[DISPOSITION_FORM_TYPE_CODE]    	nvarchar(20) NULL,
	[FORM_JSON]                     	nvarchar(4000) NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL CONSTRAINT [DSPFRM_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[APP_CREATE_TIMESTAMP]          	datetime NOT NULL CONSTRAINT [DSPFRM_APP_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[APP_CREATE_USERID]             	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_APP_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[APP_CREATE_USER_GUID]          	uniqueidentifier NULL,
	[APP_CREATE_USER_DIRECTORY]     	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_APP_CREATE_USER_DIRECTORY_DEF]  DEFAULT (user_name()),
	[APP_LAST_UPDATE_TIMESTAMP]     	datetime NOT NULL CONSTRAINT [DSPFRM_APP_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[APP_LAST_UPDATE_USERID]        	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_APP_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	[APP_LAST_UPDATE_USER_GUID]     	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY]	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_APP_LAST_UPDATE_USER_DIRECTORY_DEF]  DEFAULT (user_name()),
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL CONSTRAINT [DSPFRM_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL CONSTRAINT [DSPFRM_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL CONSTRAINT [DSPFRM_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [DSPFRM_PK] PRIMARY KEY CLUSTERED([DISPOSITION_FILE_FORM_ID])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'System-generated unique surrogate primary key.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DISPOSITION_FILE_FORM_ID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DISPOSITION_FILE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DISPOSITION_FILE_ID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DISPOSITION_FORM_TYPE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DISPOSITION_FORM_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'JSON associated with the form.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'FORM_JSON'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the user created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'GUID of the user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USER_GUID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'User directory of the user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USER_DIRECTORY'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was updated by the user.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'GUID of the user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USER_GUID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'User directory of the user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USER_DIRECTORY'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Entity associating a form to an acquisition file.  The acquisition file can have multiple forms.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_FILE_FORM'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create sequence dbo.PIMS_DISPOSITION_AGREEMENT_ID_SEQ
PRINT N'Create sequence dbo.PIMS_DISPOSITION_AGREEMENT_ID_SEQ'
GO
CREATE SEQUENCE [dbo].[PIMS_DISPOSITION_AGREEMENT_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_AGREEMENT_TYPE
PRINT N'Create table dbo.PIMS_DISPOSITION_AGREEMENT_TYPE'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT_TYPE]  ( 
	[DISPOSITION_AGREEMENT_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DESCRIPTION]                    	nvarchar(200) NOT NULL,
	[DISPLAY_ORDER]                  	int NULL,
	[IS_DISABLED]                    	bit NULL,
	[CONCURRENCY_CONTROL_NUMBER]     	bigint NOT NULL CONSTRAINT [DSPAGT_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[DB_CREATE_TIMESTAMP]            	datetime NOT NULL CONSTRAINT [DSPAGT_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]               	nvarchar(30) NOT NULL CONSTRAINT [DSPAGT_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]       	datetime NOT NULL CONSTRAINT [DSPAGT_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]          	nvarchar(30) NOT NULL CONSTRAINT [DSPAGT_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [DSPAGT_PK] PRIMARY KEY CLUSTERED([DISPOSITION_AGREEMENT_TYPE_CODE])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Code value of the disposition agreement type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DISPOSITION_AGREEMENT_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Description of the disposition agreement type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DESCRIPTION'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Designates a preferred presentation order of the code descriptions.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DISPLAY_ORDER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Indicates if the record is disabled and therefore not selectable or displayed.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'IS_DISABLED'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Table that contains the codes and associated descriptions of the agreement types.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT_TYPE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DSP_AGREEMENT_STATUS_TYPE
PRINT N'Create table dbo.PIMS_DSP_AGREEMENT_STATUS_TYPE'
GO
CREATE TABLE [dbo].[PIMS_DSP_AGREEMENT_STATUS_TYPE]  ( 
	[DSP_AGREEMENT_STATUS_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DESCRIPTION]                   	nvarchar(200) NOT NULL,
	[DISPLAY_ORDER]                 	int NULL,
	[IS_DISABLED]                   	bit NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL CONSTRAINT [DSPAST_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL CONSTRAINT [DSPAST_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL CONSTRAINT [DSPAST_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL CONSTRAINT [DSPAST_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL CONSTRAINT [DSPAST_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [DSPAST_PK] PRIMARY KEY CLUSTERED([DSP_AGREEMENT_STATUS_TYPE_CODE])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Code value of the disposition agreement status type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DSP_AGREEMENT_STATUS_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Description of the disposition agreement status type.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DESCRIPTION'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Designates a preferred presentation order of the code descriptions.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DISPLAY_ORDER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Indicates if the record is disabled and therefore not selectable or displayed.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'IS_DISABLED'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Table that contains the codes and associated descriptions of the agreement types.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_AGREEMENT_STATUS_TYPE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_AGREEMENT
PRINT N'Create table dbo.PIMS_DISPOSITION_AGREEMENT'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT]  ( 
	[DISPOSITION_AGREEMENT_ID]       	bigint NOT NULL CONSTRAINT [DSPAGR_DISPOSITION_AGREEMENT_ID_DEF]  DEFAULT (NEXT VALUE FOR [PIMS_DISPOSITION_AGREEMENT_ID_SEQ]),
	[DISPOSITION_FILE_ID]            	bigint NOT NULL,
	[DISPOSITION_AGREEMENT_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DSP_AGREEMENT_STATUS_TYPE_CODE] 	nvarchar(20) NOT NULL CONSTRAINT [DSPAGR_DSP_AGREEMENT_STATUS_TYPE_CODE_DEF]  DEFAULT ('N''DRAFT'''),
	[AGREEMENT_DATE]                 	date NULL,
	[COMPLETION_DATE]                	date NULL,
	[TERMINATION_DATE]               	date NULL,
	[COMMENCEMENT_DATE]              	date NULL,
	[DEPOSIT_AMOUNT]                 	money NULL,
	[NO_LATER_THAN_DAYS]             	int NULL,
	[PURCHASE_PRICE]                 	money NULL,
	[LEGAL_SURVEY_PLAN_NUM]          	nvarchar(250) NULL,
	[OFFER_DATE]                     	date NULL,
	[EXPIRY_TS]                      	datetime NULL,
	[SIGNED_DATE]                    	date NULL,
	[INSPECTION_DATE]                	date NULL,
	[EXPROPRIATION_DATE]             	date NULL,
	[POSSESSION_DATE]                	date NULL,
	[CANCELLATION_NOTE]              	nvarchar(2000) NULL,
	[CONCURRENCY_CONTROL_NUMBER]     	bigint NOT NULL CONSTRAINT [DSPAGR_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[APP_CREATE_TIMESTAMP]           	datetime NOT NULL CONSTRAINT [DSPAGR_APP_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[APP_CREATE_USERID]              	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_APP_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[APP_CREATE_USER_GUID]           	uniqueidentifier NULL,
	[APP_CREATE_USER_DIRECTORY]      	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_APP_CREATE_USER_DIRECTORY_DEF]  DEFAULT (user_name()),
	[APP_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL CONSTRAINT [DSPAGR_APP_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[APP_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_APP_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	[APP_LAST_UPDATE_USER_GUID]      	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY] 	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_APP_LAST_UPDATE_USER_DIRECTORY_DEF]  DEFAULT (user_name()),
	[DB_CREATE_TIMESTAMP]            	datetime NOT NULL CONSTRAINT [DSPAGR_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]               	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]       	datetime NOT NULL CONSTRAINT [DSPAGR_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]          	nvarchar(30) NOT NULL CONSTRAINT [DSPAGR_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [DSPAGR_PK] PRIMARY KEY CLUSTERED([DISPOSITION_AGREEMENT_ID])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'System-generated unique surrogate primary key.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DISPOSITION_AGREEMENT_ID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DISPOSITION_FILE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DISPOSITION_FILE_ID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DISPOSITION_AGREEMENT_TYPE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DISPOSITION_AGREEMENT_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_DSP_AGREEMENT_STATUS_TYPE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DSP_AGREEMENT_STATUS_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'AGREEMENT_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of completion of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'COMPLETION_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of termination of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'TERMINATION_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of commencement of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'COMMENCEMENT_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Amount of the deposit on the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DEPOSIT_AMOUNT'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Deposit due date' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'NO_LATER_THAN_DAYS'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Amount of the purchase price of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'PURCHASE_PRICE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Legal survey plan number,' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'LEGAL_SURVEY_PLAN_NUM'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of acquisition offer.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'OFFER_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Expiry date and time of acquisition offer.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'EXPIRY_TS'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Signed date of acquisition offer.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'SIGNED_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of inspection.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'INSPECTION_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of expropriation of the property.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'EXPROPRIATION_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of possession of the property.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'POSSESSION_DATE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Note pertaining to the cancellation of the agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'CANCELLATION_NOTE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the user created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'GUID of the user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USER_GUID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'User directory of the user that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_CREATE_USER_DIRECTORY'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was updated by the user.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'GUID of the user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USER_GUID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'User directory of the user that updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'APP_LAST_UPDATE_USER_DIRECTORY'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Table containing the details of the acquisition agreement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DISPOSITION_AGREEMENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_PROP_IMPRVMNT_STATUS_TYPE
PRINT N'Create table dbo.PIMS_PROP_IMPRVMNT_STATUS_TYPE'
GO
CREATE TABLE [dbo].[PIMS_PROP_IMPRVMNT_STATUS_TYPE]  ( 
	[PROP_IMPRVMNT_STATUS_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DESCRIPTION]                   	nvarchar(200) NOT NULL,
	[IS_DISABLED]                   	bit NOT NULL CONSTRAINT [PIMPRS_IS_DISABLED_DEF]  DEFAULT (CONVERT([bit],(0))),
	[DISPLAY_ORDER]                 	int NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL CONSTRAINT [PIMPRS_CONCURRENCY_CONTROL_NUMBER_DEF]  DEFAULT ((1)),
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL CONSTRAINT [PIMPRS_DB_CREATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL CONSTRAINT [PIMPRS_DB_CREATE_USERID_DEF]  DEFAULT (user_name()),
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL CONSTRAINT [PIMPRS_DB_LAST_UPDATE_TIMESTAMP_DEF]  DEFAULT (getutcdate()),
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL CONSTRAINT [PIMPRS_DB_LAST_UPDATE_USERID_DEF]  DEFAULT (user_name()),
	CONSTRAINT [PIMPRS_PK] PRIMARY KEY CLUSTERED([PROP_IMPRVMNT_STATUS_TYPE_CODE])
 ON [PRIMARY])
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Code value of the status of improvements made to a property during the lease.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'PROP_IMPRVMNT_STATUS_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Code description of the status of improvements made to a property during the lease.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DESCRIPTION'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Indicates if the record is disabled and therefore not selectable or displayed.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'IS_DISABLED'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Designates a preferred presentation order of the code descriptions.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DISPLAY_ORDER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any o' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_CREATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The date and time the record was created or last updated.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'The user or proxy account that created or last updated the record.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE', 
	@level2type = N'Column', @level2name = N'DB_LAST_UPDATE_USERID'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Description of the types of improvements made to a property during the lease.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROP_IMPRVMNT_STATUS_TYPE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter table dbo.PIMS_PROPERTY_IMPROVEMENT
PRINT N'Alter table dbo.PIMS_PROPERTY_IMPROVEMENT'
GO
EXEC sp_updateextendedproperty 
	@name = N'MS_Description', @value = N'Description of the improvement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROPERTY_IMPROVEMENT', 
	@level2type = N'Column', @level2name = N'IMPROVEMENT_DESCRIPTION'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT]
	ADD [PROP_IMPRVMNT_STATUS_TYPE_CODE] nvarchar(20) NOT NULL CONSTRAINT [PIMPRV_PROP_IMPRVMNT_STATUS_TYPE_CODE_DEF] DEFAULT ('ACTIVE'), 
	[IMPROVEMENT_NAME] nvarchar(500) NOT NULL DEFAULT 'NAME',
	[IMPROVEMENT_DATE] datetime NULL
GO
-- Drop dynamically-named default constraint
PRINT N'Drop dynamically-named default constraint'
GO
DECLARE @sqlQry  VARCHAR(1000)
DECLARE @defName VARCHAR(100)
SET @defName = (SELECT obj.NAME
                FROM   SYSOBJECTS obj                          INNER JOIN
                       SYSCOLUMNS col on obj.ID = col.CDEFAULT INNER JOIN
                       SYSOBJECTS tbl on col.ID = tbl.ID
                WHERE  obj.XTYPE = 'D'
                   AND tbl.NAME = 'PIMS_PROPERTY_IMPROVEMENT' 
                   AND col.NAME = 'IMPROVEMENT_NAME')
SET @sqlQry = 'ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT] DROP CONSTRAINT IF EXISTS [' + @defName + ']'
EXEC (@sqlQry)
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Foreign key to the PIMS_PROP_IMPRVMNT_STATUS_TYPE table.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROPERTY_IMPROVEMENT', 
	@level2type = N'Column', @level2name = N'PROP_IMPRVMNT_STATUS_TYPE_CODE'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Name assigned to the property improvement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROPERTY_IMPROVEMENT', 
	@level2type = N'Column', @level2name = N'IMPROVEMENT_NAME'
GO
EXEC sp_addextendedproperty 
	@name = N'MS_Description', @value = N'Date of the property improvement.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_PROPERTY_IMPROVEMENT', 
	@level2type = N'Column', @level2name = N'IMPROVEMENT_DATE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO


-- Alter table dbo.PIMS_PROPERTY_IMPROVEMENT_HIST
PRINT N'Alter table dbo.PIMS_PROPERTY_IMPROVEMENT_HIST'
GO
ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT_HIST]
	ADD [PROP_IMPRVMNT_STATUS_TYPE_CODE] nvarchar(20) NOT NULL DEFAULT 'ACTIVE',
	[IMPROVEMENT_NAME] nvarchar(500) NOT NULL DEFAULT 'NAME',
	[IMPROVEMENT_DATE] datetime NULL
GO
-- Drop dynamically-named default constraint
PRINT N'Drop dynamically-named default constraint'
GO
DECLARE @sqlQry  VARCHAR(1000)
DECLARE @defName VARCHAR(100)
SET @defName = (SELECT obj.NAME
                FROM   SYSOBJECTS obj                          INNER JOIN
                       SYSCOLUMNS col on obj.ID = col.CDEFAULT INNER JOIN
                       SYSOBJECTS tbl on col.ID = tbl.ID
                WHERE  obj.XTYPE = 'D'
                   AND tbl.NAME = 'PIMS_PROPERTY_IMPROVEMENT_HIST' 
                   AND col.NAME = 'PROP_IMPRVMNT_STATUS_TYPE_CODE')
SET @sqlQry = 'ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT_HIST] DROP CONSTRAINT IF EXISTS [' + @defName + ']'
EXEC (@sqlQry)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
-- Drop dynamically-named default constraint
PRINT N'Drop dynamically-named default constraint'
GO
DECLARE @sqlQry  VARCHAR(1000)
DECLARE @defName VARCHAR(100)
SET @defName = (SELECT obj.NAME
                FROM   SYSOBJECTS obj                          INNER JOIN
                       SYSCOLUMNS col on obj.ID = col.CDEFAULT INNER JOIN
                       SYSOBJECTS tbl on col.ID = tbl.ID
                WHERE  obj.XTYPE = 'D'
                   AND tbl.NAME = 'PIMS_PROPERTY_IMPROVEMENT_HIST' 
                   AND col.NAME = 'IMPROVEMENT_NAME')
SET @sqlQry = 'ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT_HIST] DROP CONSTRAINT IF EXISTS [' + @defName + ']'
EXEC (@sqlQry)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create sequence dbo.PIMS_DISPOSITION_FILE_FORM_H_ID_SEQ
PRINT N'Create sequence dbo.PIMS_DISPOSITION_FILE_FORM_H_ID_SEQ'
GO
CREATE SEQUENCE [dbo].[PIMS_DISPOSITION_FILE_FORM_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_FILE_FORM_HIST
PRINT N'Create table dbo.PIMS_DISPOSITION_FILE_FORM_HIST'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_FILE_FORM_HIST]  ( 
	[_DISPOSITION_FILE_FORM_HIST_ID]	bigint NOT NULL DEFAULT (NEXT VALUE FOR [PIMS_DISPOSITION_FILE_FORM_H_ID_SEQ]),
	[EFFECTIVE_DATE_HIST]           	datetime NOT NULL DEFAULT (getutcdate()),
	[END_DATE_HIST]                 	datetime NULL,
	[DISPOSITION_FILE_FORM_ID]      	bigint NOT NULL,
	[DISPOSITION_FILE_ID]           	bigint NOT NULL,
	[DISPOSITION_FORM_TYPE_CODE]    	nvarchar(20) NULL,
	[FORM_JSON]                     	nvarchar(4000) NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL,
	[APP_CREATE_TIMESTAMP]          	datetime NOT NULL,
	[APP_CREATE_USERID]             	nvarchar(30) NOT NULL,
	[APP_CREATE_USER_GUID]          	uniqueidentifier NULL,
	[APP_CREATE_USER_DIRECTORY]     	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_TIMESTAMP]     	datetime NOT NULL,
	[APP_LAST_UPDATE_USERID]        	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_USER_GUID]     	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY]	nvarchar(30) NOT NULL,
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL,
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL,
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL,
	CONSTRAINT [PIMS_DSPFRM_H_PK] PRIMARY KEY CLUSTERED([_DISPOSITION_FILE_FORM_HIST_ID])
 ON [PRIMARY])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create unique constraint dbo.PIMS_DSPFRM_H_UK
PRINT N'Create unique constraint dbo.PIMS_DSPFRM_H_UK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_FILE_FORM_HIST]
	ADD CONSTRAINT [PIMS_DSPFRM_H_UK]
	UNIQUE ([_DISPOSITION_FILE_FORM_HIST_ID], [END_DATE_HIST]) 
	WITH (
		DATA_COMPRESSION = NONE
	) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create sequence dbo.PIMS_DISPOSITION_AGREEMENT_H_ID_SEQ
PRINT N'Create sequence dbo.PIMS_DISPOSITION_AGREEMENT_H_ID_SEQ'
GO
CREATE SEQUENCE [dbo].[PIMS_DISPOSITION_AGREEMENT_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create table dbo.PIMS_DISPOSITION_AGREEMENT_HIST
PRINT N'Create table dbo.PIMS_DISPOSITION_AGREEMENT_HIST'
GO
CREATE TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT_HIST]  ( 
	[_DISPOSITION_AGREEMENT_HIST_ID] 	bigint NOT NULL DEFAULT (NEXT VALUE FOR [PIMS_DISPOSITION_AGREEMENT_H_ID_SEQ]),
	[EFFECTIVE_DATE_HIST]            	datetime NOT NULL DEFAULT (getutcdate()),
	[END_DATE_HIST]                  	datetime NULL,
	[DISPOSITION_AGREEMENT_ID]       	bigint NOT NULL,
	[DISPOSITION_FILE_ID]            	bigint NOT NULL,
	[DISPOSITION_AGREEMENT_TYPE_CODE]	nvarchar(20) NOT NULL,
	[DSP_AGREEMENT_STATUS_TYPE_CODE] 	nvarchar(20) NOT NULL,
	[AGREEMENT_DATE]                 	date NULL,
	[COMPLETION_DATE]                	date NULL,
	[TERMINATION_DATE]               	date NULL,
	[COMMENCEMENT_DATE]              	date NULL,
	[DEPOSIT_AMOUNT]                 	money NULL,
	[NO_LATER_THAN_DAYS]             	int NULL,
	[PURCHASE_PRICE]                 	money NULL,
	[LEGAL_SURVEY_PLAN_NUM]          	nvarchar(250) NULL,
	[OFFER_DATE]                     	date NULL,
	[EXPIRY_TS]                      	datetime NULL,
	[SIGNED_DATE]                    	date NULL,
	[INSPECTION_DATE]                	date NULL,
	[EXPROPRIATION_DATE]             	date NULL,
	[POSSESSION_DATE]                	date NULL,
	[CANCELLATION_NOTE]              	nvarchar(2000) NULL,
	[CONCURRENCY_CONTROL_NUMBER]     	bigint NOT NULL,
	[APP_CREATE_TIMESTAMP]           	datetime NOT NULL,
	[APP_CREATE_USERID]              	nvarchar(30) NOT NULL,
	[APP_CREATE_USER_GUID]           	uniqueidentifier NULL,
	[APP_CREATE_USER_DIRECTORY]      	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL,
	[APP_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_USER_GUID]      	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY] 	nvarchar(30) NOT NULL,
	[DB_CREATE_TIMESTAMP]            	datetime NOT NULL,
	[DB_CREATE_USERID]               	nvarchar(30) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP]       	datetime NOT NULL,
	[DB_LAST_UPDATE_USERID]          	nvarchar(30) NOT NULL,
	CONSTRAINT [PIMS_DSPAGR_H_PK] PRIMARY KEY CLUSTERED([_DISPOSITION_AGREEMENT_HIST_ID])
 ON [PRIMARY])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create unique constraint dbo.PIMS_DSPAGR_H_UK
PRINT N'Create unique constraint dbo.PIMS_DSPAGR_H_UK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT_HIST]
	ADD CONSTRAINT [PIMS_DSPAGR_H_UK]
	UNIQUE ([_DISPOSITION_AGREEMENT_HIST_ID], [END_DATE_HIST]) 
	WITH (
		DATA_COMPRESSION = NONE
	) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create function dbo.PIM_GET_COLUMN_LIST
PRINT N'Create function dbo.PIM_GET_COLUMN_LIST'
GO
-- --------------------------------------------------------------------------------
-- SQL Server function to return the list of non-PK columns in the specified table.
-- 
-- Input Parameters
-- ----------------
-- SchemaName: Database schema of the history table of interest.
-- TableName:  Name of the history table of interest.
-- 
-- Output Parameters
-- -----------------
-- ColumnLst: The comma-separated list of non-PK columns for the specified table.
-- 
-- Author        Date         Comment
-- ------------  -----------  -----------------------------------------------------
-- Doug Filteau  2025-Apr-04  Initial version.
-- --------------------------------------------------------------------------------

CREATE FUNCTION [dbo].[PIM_GET_COLUMN_LIST] (@prmSchemaName nvarchar(128) = 'dbo', @prmTableName nvarchar(128), @prmPKColName NVARCHAR(128))
RETURNS nvarchar(max)
AS
  BEGIN
  DECLARE @ColumnLst nvarchar(max);
  
  SELECT   @ColumnLst = COALESCE(@ColumnLst + ', ', '') + COLUMN_NAME
  FROM     information_schema.columns
  WHERE    TABLE_SCHEMA = @prmSchemaName
       AND TABLE_NAME   = @prmTableName
       AND COLUMN_NAME <> @prmPKColName
  ORDER BY ORDINAL_POSITION
  
  RETURN @ColumnLst
  END

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create function dbo.PIM_GET_PK_COLUMN
PRINT N'Create function dbo.PIM_GET_PK_COLUMN'
GO
-- --------------------------------------------------------------------------------
-- SQL Server function to return the primary key column of the specified table
-- 
-- Input Parameters
-- ----------------
-- SchemaName: Database schema of the history table of interest.
-- TableName:  Name of the history table of interest.
-- 
-- Output Parameters
-- -----------------
-- PKColNm: The name of the primary key column for the table.
-- 
-- Author        Date         Comment
-- ------------  -----------  -----------------------------------------------------
-- Doug Filteau  2025-Feb-27  Initial version.
-- --------------------------------------------------------------------------------

CREATE FUNCTION [dbo].[PIM_GET_PK_COLUMN] (@SchemaName nvarchar(128), @TableName nvarchar(128))
RETURNS nvarchar(128)
AS
  BEGIN
  DECLARE @Result   nvarchar(128)

  -- Retrieve the name of the primary key column from the specified table.
  SET @Result = (SELECT COLUMN_NAME
                 FROM   information_schema.key_column_usage
                 WHERE  OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1
                    AND TABLE_SCHEMA = @SchemaName
                    AND TABLE_NAME   = @TableName)

  RETURN @Result 
  END

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create procedure dbo.PIM_DELETION_HISTORY
PRINT N'Create procedure dbo.PIM_DELETION_HISTORY'
GO
-- ********************************************************************************
-- Stored procedure to preserve the user that deleted the record in the history 
-- table.
-- 
-- Parameter     Description
-- ------------  ------------------------------------------------------------------
-- prmUserID     The user ID of the user that deleted the record.
-- prmHstSchema  The name of the database schema of the history table.
-- prmBizSchema  The name of the database schema of the business table.
-- prmBizTblNm   The name of the business table that is being operated upon.  This 
--               table must have a corresponding history table.
-- prmPKValue    The value of the primary key of the record in the business table 
--               that is being deleted. 
-- 
-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
-- Author        Date         Comment
-- ------------  -----------  -----------------------------------------------------
-- Doug Filteau  2024-Sep-26  Original version.
-- Doug Filteau  2025-Mar-25  Further enhancement and debugging capability.
-- Doug Filteau  2025-Mar-28  Add row cloning to preserve original UserID.
-- Doug Filteau  2025-Aug-26  Added DROP statement.
-- ********************************************************************************

CREATE PROCEDURE [dbo].[PIM_DELETION_HISTORY] @prmUserID    nvarchar(30),
                                              @prmHstSchema nvarchar(128) = 'dbo', 
                                              @prmBizSchema nvarchar(128) = 'dbo', 
                                              @prmBizTblNm  nvarchar(128), 
                                              @prmPKValue   bigint,
                                              @modeDebug    bit = 0
AS
BEGIN
  SET XACT_ABORT ON;
  SET NOCOUNT ON;
  
  DECLARE @HstPKCol  nvarchar(128); -- Column name of the primary key of the history table.
  DECLARE @BizPKCol  nvarchar(128); -- Column name of the primary key of the business table.
  DECLARE @HstTblNm  nvarchar(128); -- Derived name of the history table.
  DECLARE @ColList   nvarchar(max); -- Non-PK column list of the history table.
  DECLARE @InsList   nvarchar(max); -- Non-PK column list of the values to be 
                                    -- instered into the history table.
  DECLARE @HstPKValu bigint;        -- Value of the newly cloned history row.
  DECLARE @RowCount  integer;       -- Count of rows with specified PK value.
  DECLARE @Msg       nvarchar(50);  -- Generic error message.
  DECLARE @qry       nvarchar(max); -- Dynamic query string.
  
  DECLARE @trancount int;
  SET @trancount = @@trancount;
  
  BEGIN TRY
  	IF @trancount = 0 
      BEGIN TRANSACTION PIM_DELETION_HISTORY
    ELSE
      SAVE TRANSACTION PIM_DELETION_HISTORY;
    	
    -- Initialize the name of the history table.
    IF @prmHstSchema = N'dbo'
      SET @HstTblNm = @prmBizTblNm + '_HIST'
    ELSE
      SET @HstTblNm = @prmBizTblNm;
      
    -- Determine the name of the primary key column in the history table.
    SET @HstPKCol = dbo.PIM_GET_PK_COLUMN (@prmHstSchema, @HstTblNm);
    
    -- Determine the name of the primary key column in the business table.
    SET @BizPKCol = dbo.PIM_GET_PK_COLUMN (@prmBizSchema, @prmBizTblNm);
        
    -- Delete the specified record.
    SET @qry = 'DELETE FROM [' + @prmBizSchema + '].[' + @prmBizTblNm + '] WHERE ' + @BizPKCol + ' = ' + CONVERT(nvarchar, @prmPKValue);
    
    -- If not in debug mode, execute the query.  Otherwise display the values of 
    -- the internal variables. 
    IF @modeDebug = 1
      BEGIN
      PRINT '@qry = ' + @qry;
      END
    ELSE
      BEGIN
      EXEC sp_executesql @qry;
      SELECT @RowCount = @@ROWCOUNT;
      -- If RowCount = 0, the record was not deleted.  Stop execution of the 
      -- stored procedure and return to the caller.
      IF @RowCount = 0
        BEGIN
        SET @Msg = 'Record for ' + @prmPKValue + 'in table ' + @prmBizSchema + '.' + @prmBizTblNm + + ' not deleted.';
        RAISERROR (@Msg, 16, 1) WITH NOWAIT;
        RETURN;
        END;
      END;
    
    -- Obtain the list of columns for the history record  
    SET @ColList = [dbo].[PIM_GET_COLUMN_LIST] (@prmHstSchema, @HstTblNm, @HstPKCol);
    
    -- Modify the column list to alter the columns specific to deletion.
    SET @InsList = STUFF(@ColList, CHARINDEX('EFFECTIVE_DATE_HIST, END_DATE_HIST, ', @ColList), LEN('EFFECTIVE_DATE_HIST, END_DATE_HIST, '), 'getutcdate(), getutcdate(), ');  -- Current dates for Effective/End dates
    SET @InsList = STUFF(@InsList, CHARINDEX('APP_LAST_UPDATE_USERID',               @InsList), LEN('APP_LAST_UPDATE_USERID'),               QUOTENAME(@prmUserID, ''''));     -- Userid requestiong the deletion.
    SET @InsList = STUFF(@InsList, CHARINDEX('APP_LAST_UPDATE_USER_DIRECTORY',       @InsList), LEN('APP_LAST_UPDATE_USER_DIRECTORY'),       QUOTENAME('DELETED',  ''''));     -- Indicates this is a deleted row.

    -- If in debug mode, display the values of the internal variables. 
    IF @modeDebug = 1
      BEGIN
      PRINT '@ColList = ' + @ColList;
      PRINT '@InsList = ' + @InsList;  
      END;
    
    -- Clone most recent history row for the specified business PK and populate 
    -- the END_DATE_HIST, APP_LAST_UPDATE_USERID, and APP_LAST_UPDATE_USER_DIRECTORY 
    -- columns of the newly created history row.
    SET @qry =        'WITH cte_Latest_Hist_Row (HIST_ID, BIZ_ID, RANK) AS ';
    SET @qry = @qry + '(SELECT ' + @HstPKCol + ', ' + @BizPKCol + ', RANK() OVER (PARTITION BY ' + @BizPKCol + ' ORDER BY END_DATE_HIST DESC) AS RANK FROM ' + @prmHstSchema + '.' + @HstTblNm + ') ';
    SET @qry = @qry + 'INSERT INTO ' + @prmHstSchema + '.' + @HstTblNm + ' (' + @ColList + ') ';
    SET @qry = @qry + 'SELECT ' + @InsList + ' ';
    SET @qry = @qry + 'FROM ' + @prmHstSchema + '.' + @HstTblNm + ' hst JOIN cte_Latest_Hist_Row cte ON ';
    SET @qry = @qry + 'cte.HIST_ID = hst.' + @HstPKCol + ' ';
    SET @qry = @qry + 'WHERE cte.RANK = 1 AND cte.BIZ_ID ' + ' = ' + CONVERT(nvarchar, @prmPKValue);
    
    -- If not in debug mode, execute the query.  Otherwise display the values of 
    -- the internal variables. 
    IF @modeDebug = 0
      BEGIN
      EXEC sp_executesql @qry;
      END
    ELSE
      BEGIN
      PRINT '@qry = ' + @qry;
      END;

    IF @trancount = 0
      COMMIT TRANSACTION
  END TRY
  
  BEGIN CATCH
    DECLARE @error INT, @message VARCHAR(4000), @xstate INT;
    SELECT @error = ERROR_NUMBER(), @message = ERROR_MESSAGE(), @xstate = XACT_STATE();
    IF (XACT_STATE()) = -1
      ROLLBACK;
    IF (XACT_STATE()) = 1 AND @trancount = 0
      ROLLBACK;
    IF (XACT_STATE()) = 1 AND @trancount > 0
      ROLLBACK TRANSACTION PIM_DELETION_HISTORY;
    
    RAISERROR ('PIM_DELETION_HISTORY: %d: %s', 16, 1, @error, @message) ;
  END CATCH
END;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create view dbo.PIMS_PROPERTY_LITE_VW
PRINT N'Create view dbo.PIMS_PROPERTY_LITE_VW'
GO
CREATE VIEW [dbo].[PIMS_PROPERTY_LITE_VW] AS
SELECT PROP.PROPERTY_ID
     , PROP.BOUNDARY
     , PROP.LOCATION  
     , PROP.IS_OWNED
     , PROP.IS_RETIRED
     , CASE
         WHEN EXISTS (SELECT 1
                      FROM   PIMS_TAKE                      TAKE JOIN
                             PIMS_PROPERTY_ACQUISITION_FILE PRAF   ON PRAF.PROPERTY_ACQUISITION_FILE_ID = TAKE.PROPERTY_ACQUISITION_FILE_ID
                                                                  AND PRAF.PROPERTY_ID                  = PROP.PROPERTY_ID
                      WHERE  TAKE.IS_NEW_LAND_ACT       = 1
                         AND TAKE.TAKE_STATUS_TYPE_CODE = 'COMPLETE'
                         AND TAKE.LAND_ACT_TYPE_CODE   IN (N'Section 15', N'Section 16', N'Section 17', N'Section 66', N'NOI')) THEN CONVERT([bit],(1))
         WHEN EXISTS (SELECT 1
                      FROM   PIMS_TAKE                      TAKE JOIN
                             PIMS_PROPERTY_ACQUISITION_FILE PRAF   ON PRAF.PROPERTY_ACQUISITION_FILE_ID = TAKE.PROPERTY_ACQUISITION_FILE_ID
                                                                  AND PRAF.PROPERTY_ID                  = PROP.PROPERTY_ID
                      WHERE  TAKE.IS_NEW_INTEREST_IN_SRW = 1
                         AND TAKE.TAKE_STATUS_TYPE_CODE  = N'COMPLETE') THEN CONVERT([bit],(1))
         WHEN EXISTS (SELECT 1
                      FROM   PIMS_TAKE                      TAKE JOIN
                             PIMS_PROPERTY_ACQUISITION_FILE PRAF   ON PRAF.PROPERTY_ACQUISITION_FILE_ID = TAKE.PROPERTY_ACQUISITION_FILE_ID
                                                                  AND PRAF.PROPERTY_ID                  = PROP.PROPERTY_ID
                      WHERE  TAKE.IS_NEW_LICENSE_TO_CONSTRUCT = 1
                         AND TAKE.TAKE_STATUS_TYPE_CODE       = N'COMPLETE') THEN CONVERT([bit],(1))
         WHEN EXISTS (SELECT 1
                      FROM   PIMS_TAKE                      TAKE JOIN
                             PIMS_PROPERTY_ACQUISITION_FILE PRAF   ON PRAF.PROPERTY_ACQUISITION_FILE_ID = TAKE.PROPERTY_ACQUISITION_FILE_ID
                                                                  AND PRAF.PROPERTY_ID                  = PROP.PROPERTY_ID
                      WHERE  IS_ACTIVE_LEASE       = 1
                         AND TAKE_STATUS_TYPE_CODE = N'COMPLETE') THEN CONVERT([bit],(1))
         ELSE CONVERT([bit],(0))
         END AS IS_OTHER_INTEREST
     , IIF(EXISTS (SELECT 1
                   FROM   PIMS_DISPOSITION_FILE_PROPERTY DFPR JOIN
                          PIMS_DISPOSITION_FILE          DISP   ON DISP.DISPOSITION_FILE_ID = DFPR.DISPOSITION_FILE_ID
                                                               AND DFPR.PROPERTY_ID         = PROP.PROPERTY_ID
                   WHERE  DISP.DISPOSITION_FILE_STATUS_TYPE_CODE = N'COMPLETE'), CONVERT([bit],(1)), CONVERT([bit],(0))) AS IS_DISPOSED
     , IIF(EXISTS (SELECT 1
                   FROM   PIMS_PROPERTY_ACQUISITION_FILE PRAF JOIN
                          PIMS_ACQUISITION_FILE          ACQF   ON ACQF.ACQUISITION_FILE_ID = PRAF.ACQUISITION_FILE_ID
                                                               AND PRAF.PROPERTY_ID         = PROP.PROPERTY_ID
                   WHERE  ACQF.ACQUISITION_FILE_STATUS_TYPE_CODE IN (N'DRAFT', N'ACTIVE')), CONVERT([bit],(1)), CONVERT([bit],(0))) AS HAS_ACTIVE_ACQUISITION_FILE
     , IIF(EXISTS (SELECT 1
                   FROM   PIMS_PROPERTY_RESEARCH_FILE PRSF JOIN
                          PIMS_RESEARCH_FILE          RSHF   ON RSHF.RESEARCH_FILE_ID = PRSF.RESEARCH_FILE_ID
                                                            AND PRSF.PROPERTY_ID      = PROP.PROPERTY_ID
                   WHERE  RSHF.RESEARCH_FILE_STATUS_TYPE_CODE = N'ACTIVE'), CONVERT([bit],(1)), CONVERT([bit],(0)))  AS HAS_ACTIVE_RESEARCH_FILE
FROM   PIMS_PROPERTY PROP
WHERE  PROP.LOCATION IS NOT NULL

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter table dbo.PIMS_DSP_CHKLST_ITEM_TYPE
PRINT N'Alter table dbo.PIMS_DSP_CHKLST_ITEM_TYPE'
GO
EXEC sp_updateextendedproperty 
	@name = N'MS_Description', @value = N'Date the disposition checklist section is removed from the input form.' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_DSP_CHKLST_ITEM_TYPE', 
	@level2type = N'Column', @level2name = N'EXPIRY_DATE'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPFRM_DISPOSITION_FILE_ID_IDX
PRINT N'Create index dbo.DSPFRM_DISPOSITION_FILE_ID_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPFRM_DISPOSITION_FILE_ID_IDX]
	ON [dbo].[PIMS_DISPOSITION_FILE_FORM]([DISPOSITION_FILE_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPAGR_DISPOSITION_AGREEMENT_TYPE_CODE_IDX
PRINT N'Create index dbo.DSPAGR_DISPOSITION_AGREEMENT_TYPE_CODE_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPAGR_DISPOSITION_AGREEMENT_TYPE_CODE_IDX]
	ON [dbo].[PIMS_DISPOSITION_AGREEMENT]([DISPOSITION_AGREEMENT_TYPE_CODE])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPAGR_DSP_AGREEMENT_STATUS_TYPE_CODE_IDX
PRINT N'Create index dbo.DSPAGR_DSP_AGREEMENT_STATUS_TYPE_CODE_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPAGR_DSP_AGREEMENT_STATUS_TYPE_CODE_IDX]
	ON [dbo].[PIMS_DISPOSITION_AGREEMENT]([DSP_AGREEMENT_STATUS_TYPE_CODE])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.PIMPRV_PROP_IMPRVMNT_STATUS_TYPE_CODE_IDX
PRINT N'Create index dbo.PIMPRV_PROP_IMPRVMNT_STATUS_TYPE_CODE_IDX'
GO
CREATE NONCLUSTERED INDEX [PIMPRV_PROP_IMPRVMNT_STATUS_TYPE_CODE_IDX]
	ON [dbo].[PIMS_PROPERTY_IMPROVEMENT]([PROP_IMPRVMNT_STATUS_TYPE_CODE])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPFMT_DOCUMENT_ID_IDX
PRINT N'Create index dbo.DSPFMT_DOCUMENT_ID_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPFMT_DOCUMENT_ID_IDX]
	ON [dbo].[PIMS_DISPOSITION_FORM_TYPE]([DOCUMENT_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPAGR_DISPOSITION_FILE_ID_IDX
PRINT N'Create index dbo.DSPAGR_DISPOSITION_FILE_ID_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPAGR_DISPOSITION_FILE_ID_IDX]
	ON [dbo].[PIMS_DISPOSITION_AGREEMENT]([DISPOSITION_FILE_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create index dbo.DSPFRM_DISPOSITION_FORM_TYPE_CODE_IDX
PRINT N'Create index dbo.DSPFRM_DISPOSITION_FORM_TYPE_CODE_IDX'
GO
CREATE NONCLUSTERED INDEX [DSPFRM_DISPOSITION_FORM_TYPE_CODE_IDX]
	ON [dbo].[PIMS_DISPOSITION_FILE_FORM]([DISPOSITION_FORM_TYPE_CODE])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DOCMNT_PIM_DSPFMT_FK
PRINT N'Create foreign key constraint dbo.PIM_DOCMNT_PIM_DSPFMT_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_FORM_TYPE]
	ADD CONSTRAINT [PIM_DOCMNT_PIM_DSPFMT_FK]
	FOREIGN KEY([DOCUMENT_ID])
	REFERENCES [dbo].[PIMS_DOCUMENT]([DOCUMENT_ID])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DSPFMT_PIM_DSPFRM_FK
PRINT N'Create foreign key constraint dbo.PIM_DSPFMT_PIM_DSPFRM_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_FILE_FORM]
	ADD CONSTRAINT [PIM_DSPFMT_PIM_DSPFRM_FK]
	FOREIGN KEY([DISPOSITION_FORM_TYPE_CODE])
	REFERENCES [dbo].[PIMS_DISPOSITION_FORM_TYPE]([DISPOSITION_FORM_TYPE_CODE])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DISPFL_PIM_DSPFRM_FK
PRINT N'Create foreign key constraint dbo.PIM_DISPFL_PIM_DSPFRM_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_FILE_FORM]
	ADD CONSTRAINT [PIM_DISPFL_PIM_DSPFRM_FK]
	FOREIGN KEY([DISPOSITION_FILE_ID])
	REFERENCES [dbo].[PIMS_DISPOSITION_FILE]([DISPOSITION_FILE_ID])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DISPFL_PIM_DSPAGR_FK
PRINT N'Create foreign key constraint dbo.PIM_DISPFL_PIM_DSPAGR_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT]
	ADD CONSTRAINT [PIM_DISPFL_PIM_DSPAGR_FK]
	FOREIGN KEY([DISPOSITION_FILE_ID])
	REFERENCES [dbo].[PIMS_DISPOSITION_FILE]([DISPOSITION_FILE_ID])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DSPAGT_PIM_DSPAGR_FK
PRINT N'Create foreign key constraint dbo.PIM_DSPAGT_PIM_DSPAGR_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT]
	ADD CONSTRAINT [PIM_DSPAGT_PIM_DSPAGR_FK]
	FOREIGN KEY([DISPOSITION_AGREEMENT_TYPE_CODE])
	REFERENCES [dbo].[PIMS_DISPOSITION_AGREEMENT_TYPE]([DISPOSITION_AGREEMENT_TYPE_CODE])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create foreign key constraint dbo.PIM_DSPAST_PIM_DSPAGR_FK
PRINT N'Create foreign key constraint dbo.PIM_DSPAST_PIM_DSPAGR_FK'
GO
ALTER TABLE [dbo].[PIMS_DISPOSITION_AGREEMENT]
	ADD CONSTRAINT [PIM_DSPAST_PIM_DSPAGR_FK]
	FOREIGN KEY([DSP_AGREEMENT_STATUS_TYPE_CODE])
	REFERENCES [dbo].[PIMS_DSP_AGREEMENT_STATUS_TYPE]([DSP_AGREEMENT_STATUS_TYPE_CODE])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_PIMPRS_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_PIMPRS_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_PIMPRS_I_S_I_TR] ON PIMS_PROP_IMPRVMNT_STATUS_TYPE INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_PROP_IMPRVMNT_STATUS_TYPE ("PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "DESCRIPTION",
      "IS_DISABLED",
      "DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER")
    select "PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "DESCRIPTION",
      "IS_DISABLED",
      "DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPFMT_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_DSPFMT_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPFMT_I_S_I_TR] ON PIMS_DISPOSITION_FORM_TYPE INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_DISPOSITION_FORM_TYPE ("DISPOSITION_FORM_TYPE_CODE",
      "DOCUMENT_ID",
      "DESCRIPTION",
      "IS_DISABLED",
      "DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER")
    select "DISPOSITION_FORM_TYPE_CODE",
      "DOCUMENT_ID",
      "DESCRIPTION",
      "IS_DISABLED",
      "DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_PIMPRV_A_S_IUD_TR
PRINT N'Create trigger dbo.PIMS_PIMPRV_A_S_IUD_TR'
GO
CREATE TRIGGER [dbo].[PIMS_PIMPRV_A_S_IUD_TR] ON PIMS_PROPERTY_IMPROVEMENT FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update PIMS_PROPERTY_IMPROVEMENT_HIST set END_DATE_HIST = @curr_date where PROPERTY_IMPROVEMENT_ID in (select PROPERTY_IMPROVEMENT_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into PIMS_PROPERTY_IMPROVEMENT_HIST ([PROPERTY_IMPROVEMENT_ID], [PROPERTY_ID], [PROPERTY_IMPROVEMENT_TYPE_CODE], [PROP_IMPRVMNT_STATUS_TYPE_CODE], [IMPROVEMENT_NAME], [IMPROVEMENT_DESCRIPTION], [IMPROVEMENT_DATE], [STRUCTURE_SIZE], [ADDRESS], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], _PROPERTY_IMPROVEMENT_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [PROPERTY_IMPROVEMENT_ID], [PROPERTY_ID], [PROPERTY_IMPROVEMENT_TYPE_CODE], [PROP_IMPRVMNT_STATUS_TYPE_CODE], [IMPROVEMENT_NAME], [IMPROVEMENT_DESCRIPTION], [IMPROVEMENT_DATE], [STRUCTURE_SIZE], [ADDRESS], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], (next value for [dbo].[PIMS_PROPERTY_IMPROVEMENT_H_ID_SEQ]) as [_PROPERTY_IMPROVEMENT_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPFRM_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_DSPFRM_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPFRM_I_S_U_TR] ON PIMS_DISPOSITION_FILE_FORM INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.DISPOSITION_FILE_FORM_ID = deleted.DISPOSITION_FILE_FORM_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_DISPOSITION_FILE_FORM
    set "DISPOSITION_FILE_FORM_ID" = inserted."DISPOSITION_FILE_FORM_ID",
      "DISPOSITION_FILE_ID" = inserted."DISPOSITION_FILE_ID",
      "DISPOSITION_FORM_TYPE_CODE" = inserted."DISPOSITION_FORM_TYPE_CODE",
      "FORM_JSON" = inserted."FORM_JSON",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY" = inserted."APP_LAST_UPDATE_USER_DIRECTORY"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_DISPOSITION_FILE_FORM
    inner join inserted
    on (PIMS_DISPOSITION_FILE_FORM.DISPOSITION_FILE_FORM_ID = inserted.DISPOSITION_FILE_FORM_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAGR_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_DSPAGR_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAGR_I_S_U_TR] ON PIMS_DISPOSITION_AGREEMENT INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.DISPOSITION_AGREEMENT_ID = deleted.DISPOSITION_AGREEMENT_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_DISPOSITION_AGREEMENT
    set "DISPOSITION_AGREEMENT_ID" = inserted."DISPOSITION_AGREEMENT_ID",
      "DISPOSITION_FILE_ID" = inserted."DISPOSITION_FILE_ID",
      "DISPOSITION_AGREEMENT_TYPE_CODE" = inserted."DISPOSITION_AGREEMENT_TYPE_CODE",
      "DSP_AGREEMENT_STATUS_TYPE_CODE" = inserted."DSP_AGREEMENT_STATUS_TYPE_CODE",
      "AGREEMENT_DATE" = inserted."AGREEMENT_DATE",
      "COMPLETION_DATE" = inserted."COMPLETION_DATE",
      "TERMINATION_DATE" = inserted."TERMINATION_DATE",
      "COMMENCEMENT_DATE" = inserted."COMMENCEMENT_DATE",
      "DEPOSIT_AMOUNT" = inserted."DEPOSIT_AMOUNT",
      "NO_LATER_THAN_DAYS" = inserted."NO_LATER_THAN_DAYS",
      "PURCHASE_PRICE" = inserted."PURCHASE_PRICE",
      "LEGAL_SURVEY_PLAN_NUM" = inserted."LEGAL_SURVEY_PLAN_NUM",
      "OFFER_DATE" = inserted."OFFER_DATE",
      "EXPIRY_TS" = inserted."EXPIRY_TS",
      "SIGNED_DATE" = inserted."SIGNED_DATE",
      "INSPECTION_DATE" = inserted."INSPECTION_DATE",
      "EXPROPRIATION_DATE" = inserted."EXPROPRIATION_DATE",
      "POSSESSION_DATE" = inserted."POSSESSION_DATE",
      "CANCELLATION_NOTE" = inserted."CANCELLATION_NOTE",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY" = inserted."APP_LAST_UPDATE_USER_DIRECTORY"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_DISPOSITION_AGREEMENT
    inner join inserted
    on (PIMS_DISPOSITION_AGREEMENT.DISPOSITION_AGREEMENT_ID = inserted.DISPOSITION_AGREEMENT_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAST_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_DSPAST_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAST_I_S_I_TR] ON PIMS_DSP_AGREEMENT_STATUS_TYPE INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_DSP_AGREEMENT_STATUS_TYPE ("DSP_AGREEMENT_STATUS_TYPE_CODE",
      "DESCRIPTION",
      "DISPLAY_ORDER",
      "IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER")
    select "DSP_AGREEMENT_STATUS_TYPE_CODE",
      "DESCRIPTION",
      "DISPLAY_ORDER",
      "IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPFMT_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_DSPFMT_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPFMT_I_S_U_TR] ON PIMS_DISPOSITION_FORM_TYPE INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.DISPOSITION_FORM_TYPE_CODE = deleted.DISPOSITION_FORM_TYPE_CODE)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_DISPOSITION_FORM_TYPE
    set "DISPOSITION_FORM_TYPE_CODE" = inserted."DISPOSITION_FORM_TYPE_CODE",
      "DOCUMENT_ID" = inserted."DOCUMENT_ID",
      "DESCRIPTION" = inserted."DESCRIPTION",
      "IS_DISABLED" = inserted."IS_DISABLED",
      "DISPLAY_ORDER" = inserted."DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_DISPOSITION_FORM_TYPE
    inner join inserted
    on (PIMS_DISPOSITION_FORM_TYPE.DISPOSITION_FORM_TYPE_CODE = inserted.DISPOSITION_FORM_TYPE_CODE);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAGT_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_DSPAGT_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAGT_I_S_U_TR] ON PIMS_DISPOSITION_AGREEMENT_TYPE INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.DISPOSITION_AGREEMENT_TYPE_CODE = deleted.DISPOSITION_AGREEMENT_TYPE_CODE)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_DISPOSITION_AGREEMENT_TYPE
    set "DISPOSITION_AGREEMENT_TYPE_CODE" = inserted."DISPOSITION_AGREEMENT_TYPE_CODE",
      "DESCRIPTION" = inserted."DESCRIPTION",
      "DISPLAY_ORDER" = inserted."DISPLAY_ORDER",
      "IS_DISABLED" = inserted."IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_DISPOSITION_AGREEMENT_TYPE
    inner join inserted
    on (PIMS_DISPOSITION_AGREEMENT_TYPE.DISPOSITION_AGREEMENT_TYPE_CODE = inserted.DISPOSITION_AGREEMENT_TYPE_CODE);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAGR_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_DSPAGR_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAGR_I_S_I_TR] ON PIMS_DISPOSITION_AGREEMENT INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_DISPOSITION_AGREEMENT ("DISPOSITION_AGREEMENT_ID",
      "DISPOSITION_FILE_ID",
      "DISPOSITION_AGREEMENT_TYPE_CODE",
      "DSP_AGREEMENT_STATUS_TYPE_CODE",
      "AGREEMENT_DATE",
      "COMPLETION_DATE",
      "TERMINATION_DATE",
      "COMMENCEMENT_DATE",
      "DEPOSIT_AMOUNT",
      "NO_LATER_THAN_DAYS",
      "PURCHASE_PRICE",
      "LEGAL_SURVEY_PLAN_NUM",
      "OFFER_DATE",
      "EXPIRY_TS",
      "SIGNED_DATE",
      "INSPECTION_DATE",
      "EXPROPRIATION_DATE",
      "POSSESSION_DATE",
      "CANCELLATION_NOTE",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "DISPOSITION_AGREEMENT_ID",
      "DISPOSITION_FILE_ID",
      "DISPOSITION_AGREEMENT_TYPE_CODE",
      "DSP_AGREEMENT_STATUS_TYPE_CODE",
      "AGREEMENT_DATE",
      "COMPLETION_DATE",
      "TERMINATION_DATE",
      "COMMENCEMENT_DATE",
      "DEPOSIT_AMOUNT",
      "NO_LATER_THAN_DAYS",
      "PURCHASE_PRICE",
      "LEGAL_SURVEY_PLAN_NUM",
      "OFFER_DATE",
      "EXPIRY_TS",
      "SIGNED_DATE",
      "INSPECTION_DATE",
      "EXPROPRIATION_DATE",
      "POSSESSION_DATE",
      "CANCELLATION_NOTE",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_PIMPRV_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_PIMPRV_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_PIMPRV_I_S_U_TR] ON PIMS_PROPERTY_IMPROVEMENT INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.PROPERTY_IMPROVEMENT_ID = deleted.PROPERTY_IMPROVEMENT_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_PROPERTY_IMPROVEMENT
    set "PROPERTY_IMPROVEMENT_ID" = inserted."PROPERTY_IMPROVEMENT_ID",
      "PROPERTY_ID" = inserted."PROPERTY_ID",
      "PROPERTY_IMPROVEMENT_TYPE_CODE" = inserted."PROPERTY_IMPROVEMENT_TYPE_CODE",
      "PROP_IMPRVMNT_STATUS_TYPE_CODE" = inserted."PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "IMPROVEMENT_NAME" = inserted."IMPROVEMENT_NAME",
      "IMPROVEMENT_DESCRIPTION" = inserted."IMPROVEMENT_DESCRIPTION",
      "IMPROVEMENT_DATE" = inserted."IMPROVEMENT_DATE",
      "STRUCTURE_SIZE" = inserted."STRUCTURE_SIZE",
      "ADDRESS" = inserted."ADDRESS",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY" = inserted."APP_LAST_UPDATE_USER_DIRECTORY"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_PROPERTY_IMPROVEMENT
    inner join inserted
    on (PIMS_PROPERTY_IMPROVEMENT.PROPERTY_IMPROVEMENT_ID = inserted.PROPERTY_IMPROVEMENT_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPFRM_A_S_IUD_TR
PRINT N'Create trigger dbo.PIMS_DSPFRM_A_S_IUD_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPFRM_A_S_IUD_TR] ON PIMS_DISPOSITION_FILE_FORM FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update PIMS_DISPOSITION_FILE_FORM_HIST set END_DATE_HIST = @curr_date where DISPOSITION_FILE_FORM_ID in (select DISPOSITION_FILE_FORM_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into PIMS_DISPOSITION_FILE_FORM_HIST ([DISPOSITION_FILE_FORM_ID], [DISPOSITION_FILE_ID], [DISPOSITION_FORM_TYPE_CODE], [FORM_JSON], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], _DISPOSITION_FILE_FORM_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [DISPOSITION_FILE_FORM_ID], [DISPOSITION_FILE_ID], [DISPOSITION_FORM_TYPE_CODE], [FORM_JSON], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], (next value for [dbo].[PIMS_DISPOSITION_FILE_FORM_H_ID_SEQ]) as [_DISPOSITION_FILE_FORM_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAGR_A_S_IUD_TR
PRINT N'Create trigger dbo.PIMS_DSPAGR_A_S_IUD_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAGR_A_S_IUD_TR] ON PIMS_DISPOSITION_AGREEMENT FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update PIMS_DISPOSITION_AGREEMENT_HIST set END_DATE_HIST = @curr_date where DISPOSITION_AGREEMENT_ID in (select DISPOSITION_AGREEMENT_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into PIMS_DISPOSITION_AGREEMENT_HIST ([DISPOSITION_AGREEMENT_ID], [DISPOSITION_FILE_ID], [DISPOSITION_AGREEMENT_TYPE_CODE], [DSP_AGREEMENT_STATUS_TYPE_CODE], [AGREEMENT_DATE], [COMPLETION_DATE], [TERMINATION_DATE], [COMMENCEMENT_DATE], [DEPOSIT_AMOUNT], [NO_LATER_THAN_DAYS], [PURCHASE_PRICE], [LEGAL_SURVEY_PLAN_NUM], [OFFER_DATE], [EXPIRY_TS], [SIGNED_DATE], [INSPECTION_DATE], [EXPROPRIATION_DATE], [POSSESSION_DATE], [CANCELLATION_NOTE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], _DISPOSITION_AGREEMENT_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [DISPOSITION_AGREEMENT_ID], [DISPOSITION_FILE_ID], [DISPOSITION_AGREEMENT_TYPE_CODE], [DSP_AGREEMENT_STATUS_TYPE_CODE], [AGREEMENT_DATE], [COMPLETION_DATE], [TERMINATION_DATE], [COMMENCEMENT_DATE], [DEPOSIT_AMOUNT], [NO_LATER_THAN_DAYS], [PURCHASE_PRICE], [LEGAL_SURVEY_PLAN_NUM], [OFFER_DATE], [EXPIRY_TS], [SIGNED_DATE], [INSPECTION_DATE], [EXPROPRIATION_DATE], [POSSESSION_DATE], [CANCELLATION_NOTE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], (next value for [dbo].[PIMS_DISPOSITION_AGREEMENT_H_ID_SEQ]) as [_DISPOSITION_AGREEMENT_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_PIMPRS_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_PIMPRS_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_PIMPRS_I_S_U_TR] ON PIMS_PROP_IMPRVMNT_STATUS_TYPE INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.PROP_IMPRVMNT_STATUS_TYPE_CODE = deleted.PROP_IMPRVMNT_STATUS_TYPE_CODE)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_PROP_IMPRVMNT_STATUS_TYPE
    set "PROP_IMPRVMNT_STATUS_TYPE_CODE" = inserted."PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "DESCRIPTION" = inserted."DESCRIPTION",
      "IS_DISABLED" = inserted."IS_DISABLED",
      "DISPLAY_ORDER" = inserted."DISPLAY_ORDER",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_PROP_IMPRVMNT_STATUS_TYPE
    inner join inserted
    on (PIMS_PROP_IMPRVMNT_STATUS_TYPE.PROP_IMPRVMNT_STATUS_TYPE_CODE = inserted.PROP_IMPRVMNT_STATUS_TYPE_CODE);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAGT_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_DSPAGT_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAGT_I_S_I_TR] ON PIMS_DISPOSITION_AGREEMENT_TYPE INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_DISPOSITION_AGREEMENT_TYPE ("DISPOSITION_AGREEMENT_TYPE_CODE",
      "DESCRIPTION",
      "DISPLAY_ORDER",
      "IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER")
    select "DISPOSITION_AGREEMENT_TYPE_CODE",
      "DESCRIPTION",
      "DISPLAY_ORDER",
      "IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_PIMPRV_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_PIMPRV_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_PIMPRV_I_S_I_TR] ON PIMS_PROPERTY_IMPROVEMENT INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_PROPERTY_IMPROVEMENT ("PROPERTY_IMPROVEMENT_ID",
      "PROPERTY_ID",
      "PROPERTY_IMPROVEMENT_TYPE_CODE",
      "PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "IMPROVEMENT_NAME",
      "IMPROVEMENT_DESCRIPTION",
      "IMPROVEMENT_DATE",
      "STRUCTURE_SIZE",
      "ADDRESS",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "PROPERTY_IMPROVEMENT_ID",
      "PROPERTY_ID",
      "PROPERTY_IMPROVEMENT_TYPE_CODE",
      "PROP_IMPRVMNT_STATUS_TYPE_CODE",
      "IMPROVEMENT_NAME",
      "IMPROVEMENT_DESCRIPTION",
      "IMPROVEMENT_DATE",
      "STRUCTURE_SIZE",
      "ADDRESS",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPAST_I_S_U_TR
PRINT N'Create trigger dbo.PIMS_DSPAST_I_S_U_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPAST_I_S_U_TR] ON PIMS_DSP_AGREEMENT_STATUS_TYPE INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.DSP_AGREEMENT_STATUS_TYPE_CODE = deleted.DSP_AGREEMENT_STATUS_TYPE_CODE)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update PIMS_DSP_AGREEMENT_STATUS_TYPE
    set "DSP_AGREEMENT_STATUS_TYPE_CODE" = inserted."DSP_AGREEMENT_STATUS_TYPE_CODE",
      "DESCRIPTION" = inserted."DESCRIPTION",
      "DISPLAY_ORDER" = inserted."DISPLAY_ORDER",
      "IS_DISABLED" = inserted."IS_DISABLED",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER"
    , DB_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_LAST_UPDATE_USERID = user_name()
    from PIMS_DSP_AGREEMENT_STATUS_TYPE
    inner join inserted
    on (PIMS_DSP_AGREEMENT_STATUS_TYPE.DSP_AGREEMENT_STATUS_TYPE_CODE = inserted.DSP_AGREEMENT_STATUS_TYPE_CODE);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create trigger dbo.PIMS_DSPFRM_I_S_I_TR
PRINT N'Create trigger dbo.PIMS_DSPFRM_I_S_I_TR'
GO
CREATE TRIGGER [dbo].[PIMS_DSPFRM_I_S_I_TR] ON PIMS_DISPOSITION_FILE_FORM INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into PIMS_DISPOSITION_FILE_FORM ("DISPOSITION_FILE_FORM_ID",
      "DISPOSITION_FILE_ID",
      "DISPOSITION_FORM_TYPE_CODE",
      "FORM_JSON",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "DISPOSITION_FILE_FORM_ID",
      "DISPOSITION_FILE_ID",
      "DISPOSITION_FORM_TYPE_CODE",
      "FORM_JSON",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USERID",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC pims_error_handling
END CATCH;

GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
