/* -----------------------------------------------------------------------------
Alter the data in the PIMS_PROPERTY_TENURE_TYPE table and repopulate.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2021-Jul-20  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable "ADJLAND" type
UPDATE PIMS_PROPERTY_TENURE_TYPE
SET    IS_DISABLED                = CONVERT([bit],(1))
     , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE  PROPERTY_TENURE_TYPE_CODE = N'ADJLAND';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "FSMOTI" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FSMOTI'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'FSMOTI', N'Fee Simple - MoTI');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "FSBCTFA" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FSBCTFA'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'FSBCTFA', N'Fee Simple - BCTFA');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "FSPRIVAT" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FSPRIVAT'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'FSPRIVAT', N'Fee Simple - Private');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "FSCROWN" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FSCROWN'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'FSCROWN', N'Fee Simple - Crown (Non-MoTI)');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "NSRWMOTI" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NSRWMOTI'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'NSRWMOTI', N'Non-SRW Interests - MoTI');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "NSRWBCTFA" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NSRWBCTFA'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'NSRWBCTFA', N'Non-SRW Interests - BCTFA');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "SRWMOTI" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SRWMOTI'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'SRWMOTI', N'Statutory Right of Way (SRW) � MoTI');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "SRWBCTFA" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SRWBCTFA'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'SRWBCTFA', N'Statutory Right of Way (SRW) � BCTFA');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "SRWOTHER" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SRWOTHER'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'SRWOTHER', N'Statutory Right of Way (SRW) � Other');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "LNDACTR" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LNDACTR'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'LNDACTR', N'Land Act Reserve (Section 16/17/12/14');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "SPECUPMT" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SPECUPMT'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'SPECUPMT', N'Special Use Permit (SUP)');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "IRESERVE" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'IRESERVE'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'IRESERVE', N'Indian Reserve (IR)');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "UNCRWNLMD" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'UNCRWNLMD'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'UNCRWNLMD', N'Unsurveyed Crown Land');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the "LEASELIC" type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LEASELIC'

SELECT PROPERTY_TENURE_TYPE_CODE
FROM   PIMS_PROPERTY_TENURE_TYPE
WHERE  PROPERTY_TENURE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_PROPERTY_TENURE_TYPE (PROPERTY_TENURE_TYPE_CODE, DESCRIPTION)
    VALUES
      (N'LEASELIC', N'Leased/Licensed');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
