/* -----------------------------------------------------------------------------
Update data in the PIMS_DOCUMENT_STATUS_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2021-Aug-24  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable "Sent" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SENT'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    IS_DISABLED                = CONVERT([bit],(1))
       , DISPLAY_ORDER              = 999
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable "Registered" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'RGSTRD'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    IS_DISABLED                = CONVERT([bit],(1))
       , DISPLAY_ORDER              = 999
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable "Unregistered" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'UNREGD'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    IS_DISABLED                = CONVERT([bit],(1))
       , DISPLAY_ORDER              = 999
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "None" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NONE'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Draft" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'DRAFT'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 2
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Approved" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'APPROVD'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 3
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Signed" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SIGND'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 4
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Final" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FINAL'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 5
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Amended" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'AMENDD'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 6
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set display order for "Cancelled" document status type
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CNCLD'

SELECT DOCUMENT_STATUS_TYPE_CODE
FROM   PIMS_DOCUMENT_STATUS_TYPE
WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_DOCUMENT_STATUS_TYPE
  SET    DISPLAY_ORDER              = 7
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DOCUMENT_STATUS_TYPE_CODE = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
