/* -----------------------------------------------------------------------------
Alter the code values in the PIMS_ACQ_CHKLST_ITEM_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2023-Jan-30  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the LGLSURVEY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LGLSURVEY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_ACQ_CHKLST_ITEM_TYPE (ACQ_CHKLST_SECTION_TYPE_CODE, ACQ_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
  VALUES
    (N'FILEMGMT', N'LGLSURVEY', N'Legal survey(s)', 8);
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the CRWNLNDRSCH code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CRWNLNDRSCH'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_ACQ_CHKLST_ITEM_TYPE (ACQ_CHKLST_SECTION_TYPE_CODE, ACQ_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
  VALUES
    (N'CROWNLND', N'CRWNLNDRSCH', N'Crown Land research', 23, N'Existing / overlapping / conflicting tenures');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the SUBCLTENAPP code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SUBCLTENAPP'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_ACQ_CHKLST_ITEM_TYPE (ACQ_CHKLST_SECTION_TYPE_CODE, ACQ_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
  VALUES
    (N'CROWNLND', N'SUBCLTENAPP', N'Submit Crown Land tenure application', 24, N'Section 16 / Section 17 applications');
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the CRWNGRNTPKG code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CRWNGRNTPKG'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_ACQ_CHKLST_ITEM_TYPE (ACQ_CHKLST_SECTION_TYPE_CODE, ACQ_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
  VALUES
    (N'CROWNLND', N'CRWNGRNTPKG', N'Crown grant package', 25);
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert the EXPROPCOPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPCOPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_ACQ_CHKLST_ITEM_TYPE (ACQ_CHKLST_SECTION_TYPE_CODE, ACQ_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
  VALUES
    (N'SCTN6XPRP', N'EXPROPCOPY', N'Copy of offer(s) extended to owner(s)', 35);
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- =============================================================================          
-- Update the OTHERRPTS code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'OTHERRPTS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 9
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the RECNEGOT code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'RECNEGOT'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 10
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CORRESCPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CORRESCPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 11
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the SAASIGNED code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SAASIGNED'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 12
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the FINALAGRM code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'FINALAGRM'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 13
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the H120COMPREQ code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'H120COMPREQ'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 14
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the LEGALDOCS code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LEGALDOCS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 15
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the OWNERCOMP code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'OWNERCOMP'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 16
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the ENTRYCOND code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ENTRYCOND'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 17
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CONVEYCLOS code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CONVEYCLOS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 18
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the REGSTRDPLAN code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'REGSTRDPLAN'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 19
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the ALCORDER code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ALCORDER'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 20
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the NEWTTLACOMP code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NEWTTLACOMP'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 21
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the BCTFANOTIF code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'BCTFANOTIF'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 22
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the AVNCDPMTNTY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'AVNCDPMTNTY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 26
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CLAIMRELSS3 code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CLAIMRELSS3'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 27
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CONVEYLTR code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CONVEYLTR'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 28
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the EXPROPACT code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPACT'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 29
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the SGNDAGRMNT code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SGNDAGRMNT'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 30
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the TTLCHRGS code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'TTLCHRGS'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 31
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CURRYRASSMN code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CURRYRASSMN'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 32
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the S3CHEQCOPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'S3CHEQCOPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 33
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the S3APPRCOPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'S3APPRCOPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 34
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the EXPROPAPPRV code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPAPPRV'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 36
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the EXPROPFORM1 code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPFORM1'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 37
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the EXPROPFORM5 code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPFORM5'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 38
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the ADVPAYMENT8 code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ADVPAYMENT8'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 39
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the VESTNOTICE code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'VESTNOTICE'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 40
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the SVCAFFADAV code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'SVCAFFADAV'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 41
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the S6CHEQCOPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'S6CHEQCOPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 42
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the S6APPRCOPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'S6APPRCOPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 43
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the CLAIMRELSS6 code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'CLAIMRELSS6'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 44
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the EASEMENTCPY code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EASEMENTCPY'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 45
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
                
-- Update the PIMSUPDTFIL code.
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PIMSUPDTFIL'

SELECT ACQ_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_ACQ_CHKLST_ITEM_TYPE
WHERE  ACQ_CHKLST_ITEM_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  BEGIN
  UPDATE PIMS_ACQ_CHKLST_ITEM_TYPE 
  SET    DISPLAY_ORDER              = 46
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_CHKLST_ITEM_TYPE_CODE  = @CurrCd;
  END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
