/* -----------------------------------------------------------------------------
Alter the PIMS_DSP_CHKLST_ITEM_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Dec-09  Added 'UTILCOAPP', 'ADJLOREF', and 'ADCOMPLT' 
                           checklist items.
Doug Filteau  2025-Dec-09  Disabled 'STRNTHCLM' checklist item.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable UTILCOAPP code.
PRINT N'Add/enable UTILCOAPP code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'UTILCOAPP';

IF @@ROWCOUNT = 0
 INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
   VALUES (N'DIRCTSAL',  N'UTILCOAPP',  N'Utility company referral', 25, NULL);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable ADJLOREF code.
PRINT N'Add/enable ADJLOREF code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADJLOREF';

IF @@ROWCOUNT = 0
  INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
	  VALUES (N'DIRCTSAL',  N'ADJLOREF',  N'Adjacent landowner referral', 26, NULL);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable ADCOMPLT code.
PRINT N'Add/enable ADCOMPLT code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADCOMPLT';

IF @@ROWCOUNT = 0
  INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
	  VALUES (N'DIRCTSAL',  N'ADCOMPLT',  N'Advertising completed', 27, NULL);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "LITIGATN" type.
PRINT N'Disable the "LITIGATN" type.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'REFRCONS'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'LITIGATN';

IF @@ROWCOUNT = 1
  UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
  SET    IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'REFRCONS'
     AND DSP_CHKLST_ITEM_TYPE_CODE    = N'LITIGATN';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the display order for the Sale Information checklist item.
PRINT N'Update the display order for the Sale Information checklist item.'
GO
UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
SET    DISPLAY_ORDER = DISPLAY_ORDER + 3
     , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'SALEINFO';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) 
  PRINT 'The database update succeeded'
ELSE 
  BEGIN
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'The database update failed'
  END
GO
