/* -----------------------------------------------------------------------------
Alter the  PIMS_LL_TEAM_PROFILE_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Mar-20  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "MOTTCONTACT" type
PRINT N'Insert/Enable the "MOTTCONTACT" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'MOTTCONTACT'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LL_TEAM_PROFILE_TYPE (LL_TEAM_PROFILE_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
    VALUES (N'MOTTCONTACT',  N'MoTT contact', 1);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "MOTTLAWYER" type
PRINT N'Insert/Enable the "MOTTLAWYER" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'MOTTLAWYER'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LL_TEAM_PROFILE_TYPE (LL_TEAM_PROFILE_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
    VALUES (N'MOTTLAWYER',  N'MoTT Solicitor', 2);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set the display order of the "PROPANALYST" type
PRINT N'Set the display order of the "PROPANALYST" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PROPANALYST'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    DISPLAY_ORDER              = 3
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Set the display order of the "PROPCOORD" type
PRINT N'Set the display order of the "PROPCOORD" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PROPCOORD'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    DISPLAY_ORDER              = 4
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "PROPADMIN" type
PRINT N'Insert/Enable the "PROPADMIN" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PROPADMIN'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LL_TEAM_PROFILE_TYPE (LL_TEAM_PROFILE_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
    VALUES (N'PROPADMIN',  N'Property administrator', 5);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "LANDPRJMGR" type
PRINT N'Insert/Enable the "LANDPRJMGR" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LANDPRJMGR'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LL_TEAM_PROFILE_TYPE (LL_TEAM_PROFILE_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
    VALUES (N'LANDPRJMGR',  N'Land project manager', 6);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "LANDOPSMGR" type
PRINT N'Insert/Enable the "LANDOPSMGR" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LANDOPSMGR'

SELECT LL_TEAM_PROFILE_TYPE_CODE
FROM   PIMS_LL_TEAM_PROFILE_TYPE
WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LL_TEAM_PROFILE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LL_TEAM_PROFILE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LL_TEAM_PROFILE_TYPE (LL_TEAM_PROFILE_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER)
    VALUES (N'LANDOPSMGR',  N'Land operations manager', 7);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "EXPROPAGENT" type
PRINT N'Disable the "EXPROPAGENT" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'EXPROPAGENT'

SELECT ACQ_PHYS_FILE_STATUS_TYPE_CODE
FROM   PIMS_ACQ_PHYS_FILE_STATUS_TYPE
WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_ACQ_PHYS_FILE_STATUS_TYPE
  SET    IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "MOTILAWYER" type
PRINT N'Disable the "MOTILAWYER" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'MOTILAWYER'

SELECT ACQ_PHYS_FILE_STATUS_TYPE_CODE
FROM   PIMS_ACQ_PHYS_FILE_STATUS_TYPE
WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_ACQ_PHYS_FILE_STATUS_TYPE
  SET    IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "NEGOTAGENT" type
PRINT N'Disable the "NEGOTAGENT" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'NEGOTAGENT'

SELECT ACQ_PHYS_FILE_STATUS_TYPE_CODE
FROM   PIMS_ACQ_PHYS_FILE_STATUS_TYPE
WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_ACQ_PHYS_FILE_STATUS_TYPE
  SET    IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "PROPAGENT" type
PRINT N'Disable the "PROPAGENT" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'PROPAGENT'

SELECT ACQ_PHYS_FILE_STATUS_TYPE_CODE
FROM   PIMS_ACQ_PHYS_FILE_STATUS_TYPE
WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_ACQ_PHYS_FILE_STATUS_TYPE
  SET    IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  ACQ_PHYS_FILE_STATUS_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
