/* -----------------------------------------------------------------------------
Migrate the data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY from the temporary 
TMP_PROP_PROP_ACTIVITY table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-07  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY DISABLE TRIGGER PIMS_MAACPR_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY DISABLE TRIGGER PIMS_MAACPR_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY DISABLE TRIGGER PIMS_MAACPR_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROP_PROP_ACTIVITY data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY table
PRINT N'Migrate the TMP_PROP_PROP_ACTIVITY data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY table'
GO
INSERT INTO dbo.PIMS_MANAGEMENT_ACTIVITY_PROPERTY (MANAGEMENT_ACTIVITY_PROPERTY_ID, PROPERTY_ID, PIMS_MANAGEMENT_ACTIVITY_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT PROP_PROP_ACTIVITY_ID
       , PROPERTY_ID
       , PIMS_PROPERTY_ACTIVITY_ID
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROP_PROP_ACTIVITY
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Re-enable the triggers on the table
PRINT N'Re-enable the triggers on the table'
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY ENABLE TRIGGER PIMS_MAACPR_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY ENABLE TRIGGER PIMS_MAACPR_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_MANAGEMENT_ACTIVITY_PROPERTY ENABLE TRIGGER PIMS_MAACPR_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop the temporary table
PRINT N'Drop the temporary table'
GO
DROP TABLE IF EXISTS dbo.TMP_PROP_PROP_ACTIVITY
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
