-- ----------------------------------------------------------------------------------
-- Migrate the contact data from the PIMS_PROPERTY table to the PIMS_PROPERTY_CONTACT
-- table.  Following a successful data migration, remove the PROPERTY_MANAGER_ID and 
-- PROP_MGMT_ORG_ID columns from PIMS_PROPERTY.
-- ----------------------------------------------------------------------------------

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PROPERTY_MANAGER_ID data
PRINT N'Migrate the PROPERTY_MANAGER_ID data'
GO
INSERT INTO PIMS_PROPERTY_CONTACT (PROPERTY_ID, PERSON_ID, PURPOSE)
  SELECT PROPERTY_ID
       , PROPERTY_MANAGER_ID
       , 'LIS LEGACY PROPERTY MANAGER'
  FROM    PIMS_PROPERTY
  WHERE   PROPERTY_MANAGER_ID IS NOT NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PROP_MGMT_ORG_ID data
PRINT N'Migrate the PROP_MGMT_ORG_ID data'
GO
INSERT INTO PIMS_PROPERTY_CONTACT (PROPERTY_ID, ORGANIZATION_ID, PURPOSE)
  SELECT PROPERTY_ID
       , PROP_MGMT_ORG_ID
       , 'LIS LEGACY PROPERTY MANAGEMENT ORGANIZATION'
  FROM   PIMS_PROPERTY
  WHERE  PROP_MGMT_ORG_ID IS NOT NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.PRPRTY_PROPERTY_MANAGER_ID_IDX
PRINT N'Drop index dbo.PRPRTY_PROPERTY_MANAGER_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_PROPERTY].[PRPRTY_PROPERTY_MANAGER_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_ORG_PIM_PRPRTY_FK
PRINT N'Drop foreign key constraint dbo.PIM_ORG_PIM_PRPRTY_FK'
GO
ALTER TABLE [dbo].[PIMS_PROPERTY]
	DROP CONSTRAINT IF EXISTS [PIM_ORG_PIM_PRPRTY_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_PERSON_PIM_PRPRTY_FK
PRINT N'Drop foreign key constraint dbo.PIM_PERSON_PIM_PRPRTY_FK'
GO
ALTER TABLE [dbo].[PIMS_PROPERTY]
	DROP CONSTRAINT IF EXISTS [PIM_PERSON_PIM_PRPRTY_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.PRPRTY_PROP_MGMT_ORG_ID_IDX
PRINT N'Drop index dbo.PRPRTY_PROP_MGMT_ORG_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_PROPERTY].[PRPRTY_PROP_MGMT_ORG_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter table dbo.PIMS_PROPERTY
PRINT N'Alter table dbo.PIMS_PROPERTY'
GO
ALTER TABLE [dbo].[PIMS_PROPERTY]
	DROP COLUMN IF EXISTS [PROPERTY_MANAGER_ID], [PROP_MGMT_ORG_ID]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
