-- File generated on 04/07/2026 03:36:12 PM.
-- Autogenerated file. Do not manually modify.

:On Error Exit
SET XACT_ABORT ON
GO

PRINT '     == DB SCRIPT START ========'
GO

BEGIN TRANSACTION
PRINT '     == DB TRANSACTION START ========'
   GO

   --Script section

   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/010_PSP_PIMS_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/010_PSP_PIMS_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/054_DML_PIMS_LEASE_LICENSE_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/054_DML_PIMS_LEASE_LICENSE_TYPE_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/057_DML_PIMS_LEASE_PROGRAM_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/057_DML_PIMS_LEASE_PROGRAM_TYPE_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/093_DML_PIMS_ACQ_FL_TEAM_PROFILE_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/093_DML_PIMS_ACQ_FL_TEAM_PROFILE_TYPE_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/144_DML_PIMS_DSP_FL_TEAM_PROFILE_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/144_DML_PIMS_DSP_FL_TEAM_PROFILE_TYPE_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/164_DML_PIMS_LL_TEAM_PROFILE_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/164_DML_PIMS_LL_TEAM_PROFILE_TYPE_Alter_Up.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S120_00/Alter Up/167_DML_PIMS_MANAGEMENT_FILE_PROFILE_TYPE_Alter_Up.sql '
   :setvar filepath "PSP_PIMS_S120_00/Alter Up/167_DML_PIMS_MANAGEMENT_FILE_PROFILE_TYPE_Alter_Up.sql"
   :r $(filepath)

   --End script section

PRINT '     == DB TRANSACTION FINISH ========'
GO

If XACT_STATE()=1
  BEGIN
  PRINT '- Success: Committing Transaction...'
  COMMIT TRANSACTION;
  END
ELSE IF XACT_STATE()=-1
  BEGIN
  PRINT '- Error: Rolling Back Transaction...'
  ROLLBACK TRANSACTION;
  END;
ELSE IF XACT_STATE()=0
  BEGIN
  PRINT '- Error: No pending transactions...'
  ROLLBACK TRANSACTION;
  END;
GO
