-- File generated on 04/07/2026 03:36:12 PM.
-- Autogenerated file. Do not manually modify.
:On Error Exit

PRINT '- Creating procedure PSP_PIMS_S121_00/001_PIMS_DELETE_BY_USER_GUID.sql';
GO
:setvar filepath "PSP_PIMS_S121_00/Alter Up/001_PIMS_DELETE_BY_USER_GUID.sql"
:r $(filepath)
GO
PRINT '- Procedure PSP_PIMS_S121_00/001_PIMS_DELETE_BY_USER_GUID.sql created';

SET
  XACT_ABORT ON
GO
  PRINT '     == DB SCRIPT START ========'
GO
  BEGIN TRANSACTION PRINT '     == DB TRANSACTION START ========'
GO
GO
  If XACT_STATE() = 1 BEGIN PRINT '- Success: Committing Transaction...' COMMIT TRANSACTION;

END
ELSE IF XACT_STATE() = -1 BEGIN PRINT '- Error: Rolling Back Transaction...' ROLLBACK TRANSACTION;

END;

ELSE IF XACT_STATE() = 0 BEGIN PRINT '- Error: No pending transactions...' ROLLBACK TRANSACTION;

END;

GO