DELETE
FROM   PIMS_DISPOSITION_SALE
GO

DECLARE @i INT = 0
WHILE @i < 25
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DISPOSITION_SALE (DISPOSITION_FILE_ID, FINAL_CONDITION_REMOVAL_DT, SALE_COMPLETION_DT, IS_GST_REQUIRED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES
      ((SELECT TOP 1 DISPOSITION_FILE_ID                FROM PIMS_DISPOSITION_FILE              ORDER BY NEWID()), -- DISPOSITION_FILE_ID
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                 -- FINAL_CONDITION_REMOVAL_DT
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                 -- SALE_COMPLETION_DT
       CONVERT([bit],(0)),                                                                                         -- IS_GST_REQUIRED
       1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');       -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO
