codecov:
  require_ci_to_pass: yes
  branch: dev

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        informational: true
    project:
      default:
        target: 75%
        threshold: 1%
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "*.ignore.*"
  - "PimsContext.cs"
  - "PimsBaseContext.cs"
  - "source/backend/entities"
  - "source/backend/api/Helpers/Swagger"
  - "source/backend/api/Helpers/Healthchecks"
