DELETE FROM PIMS_PROPERTY_CONTACT;
GO

INSERT INTO PIMS_PROPERTY_CONTACT (PROPERTY_ID, PERSON_ID, PURPOSE)
VALUES
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Person');
GO

INSERT INTO PIMS_PROPERTY_CONTACT (PROPERTY_ID, ORGANIZATION_ID, PURPOSE)
VALUES
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), N'Test purpose - Organization');
GO

INSERT INTO PIMS_PROPERTY_CONTACT (PROPERTY_ID, PRIMARY_CONTACT_ID, PURPOSE)
VALUES
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact'),
  ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), N'Test purpose - Primary Contact');
GO 
