DELETE 
FROM   PIMS_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_INSTANCE] ([ACTIVITY_TEMPLATE_ID], ACTIVITY_INSTANCE_STATUS_TYPE_CODE, [CONCURRENCY_CONTROL_NUMBER])
VALUES
  (1, N'NOSTART', 1),
  (2, N'NOSTART', 1),
  (3, N'NOSTART', 1);
GO
