/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 12.3.1                     */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          PIMS V02.02 - Sprint 7.dez                      */
/* Project name:          MoTI Property Services Project                  */
/* Author:                Doug Filteau                                    */
/* Script type:           Database drop script                            */
/* Created on:            2021-08-03 16:50                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Drop foreign key constraints                                           */
/* ---------------------------------------------------------------------- */

ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PIM_PRJTYP_PIM_PROJCT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PIM_PRJSTY_PIM_PROJCT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PIM_PRJRSK_PIM_PROJCT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PIM_PROJTR_PIM_PROJCT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_PRPTYP_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_ADDRSS_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_REGION_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_DSTRCT_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_PRPCLT_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_PRPTNR_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_ARUNIT_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_PRPSTS_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PIM_PIDSRT_PIM_PRPRTY_FK]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [PIM_PROJCT_PIM_ACTVTY_FK]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [PIM_PRWKMD_PIM_ACTVTY_FK]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [PIM_ACTMDL_PIM_ACTVTY_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PIM_PRSVFT_PIM_PRPSVC_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [PIM_TSKTMP_PIM_TASK_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [PIM_ACTVTY_PIM_TASK_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [PIM_USER_PIM_TASK_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [PIM_TSKTMT_PIM_TSKTMP_FK]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [PIM_PERSON_PIM_USER_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PIM_WFLMDL_PIM_PRWKMD_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PIM_PROJCT_PIM_PRWKMD_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PIM_PRPRTY_PIM_PRJPRP_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PIM_PROJCT_PIM_PRJPRP_FK]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [PIM_WFLMDT_PIM_WFLMDL_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PIM_ACTVTY_PIM_PRPACT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PIM_PRPRTY_PIM_PRPACT_FK]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [PIM_DSTRCT_PIM_ADDRSS_FK]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [PIM_REGION_PIM_ADDRSS_FK]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [PIM_ADUSGT_PIM_ADDRSS_FK]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [PIM_PROVNC_PIM_ADDRSS_FK]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [PIM_CNTRY_PIM_ADDRSS_FK]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [PIM_REGION_PIM_DSTRCT_FK]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PIM_CNTRY_PIM_PROVNC_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_ADDRSS_PIM_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_ORGTYP_PIM_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_ORG_PIM_PRNT_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_DSTRCT_PIM_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_REGION_PIM_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [PIM_ORGIDT_PIM_ORG_FK]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [PIM_USER_PIM_USRORG_FK]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [PIM_ORG_PIM_USRORG_FK]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [PIM_ROLE_PIM_USRORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [PIM_CLMTYP_PIM_ROLCLM_FK]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [PIM_ROLE_PIM_ROLCLM_FK]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PIM_ADDRSS_PIM_PERSON_FK]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PIM_PERSON_PIM_PERORG_FK]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PIM_ORG_PIM_PERORG_FK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [PIM_USER_PIM_ACRQST_FK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [PIM_ARQSTT_PIM_ACRQST_FK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [PIM_ROLE_PIM_ACRQST_FK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [PIM_ORG_PIM_ACRQOR_FK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [PIM_ACRQST_PIM_ACRQOR_FK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PIM_PROJCT_PIM_PROJNT_FK]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [PIM_USER_PIM_USERRL_FK]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [PIM_ROLE_PIM_USERRL_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PIM_PRPRTY_PIM_PRPRSF_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PIM_PRPSVC_PIM_PRPRSF_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [PIM_TSKTMP_PIM_TSKTAM_FK]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [PIM_ACTMDL_PIM_TSKTAM_FK]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [PIM_CNTMTT_PIM_CNTMTH_FK]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [PIM_PERSON_PIM_CNTMTH_FK]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [PIM_ORG_PIM_CNTMTH_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PIM_PRPRTY_PIM_PRPORG_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PIM_ORG_PIM_PRPORG_FK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PIM_PRPRTY_PIM_PRPEVL_FK]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_TASK"                                             */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_TASK_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_PK]
GO


ALTER TABLE [dbo].[PIMS_TASK] DROP CONSTRAINT [TASK_TEMPLATE_ACTIVITY_USER_TUC]
GO


DROP TABLE [dbo].[PIMS_TASK]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_EVALUATION"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_PROPERTY_EVALUATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_EVALUATION] DROP CONSTRAINT [PRPEVL_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_EVALUATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_ORGANIZATION"                            */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_PROPERTY_ORGANIZATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_PK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION] DROP CONSTRAINT [PRPORG_PROPERTY_ORGANIZATION_TUC]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_PROPERTY_SERVICE_FILE"                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_PROPERTY_PROPERTY_SERVICE_FILE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_PK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPRSF_PROPERTY_SERVICE_FILE_TUC]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_USER_ROLE"                                        */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_USER_ROLE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_PK]
GO


ALTER TABLE [dbo].[PIMS_USER_ROLE] DROP CONSTRAINT [USERRL_USER_ROLE_TUC]
GO


DROP TABLE [dbo].[PIMS_USER_ROLE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ACCESS_REQUEST_ORGANIZATION"                      */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_ACCESS_REQUEST_ORGANIZATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_PK]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION] DROP CONSTRAINT [ACRQOR_ORGANIZATION_ACCESS_REQUEST_TUC]
GO


DROP TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ACCESS_REQUEST"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_ACCESS_REQUEST_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST] DROP CONSTRAINT [ACRQST_PK]
GO


DROP TABLE [dbo].[PIMS_ACCESS_REQUEST]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_USER_ORGANIZATION"                                */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_USER_ORGANIZATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_PK]
GO


ALTER TABLE [dbo].[PIMS_USER_ORGANIZATION] DROP CONSTRAINT [USRORG_USER_ROLE_ORGANIZATION_TUC]
GO


DROP TABLE [dbo].[PIMS_USER_ORGANIZATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_ACTIVITY"                                */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_PROPERTY_ACTIVITY_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_PK]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_ACTIVITY] DROP CONSTRAINT [PRPACT_PROPERTY_ACTIVITY_TUC]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_ACTIVITY]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_PROPERTY"                                 */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_PROJECT_PROPERTY_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_PK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_PROPERTY] DROP CONSTRAINT [PRJPRP_PROJECT_PROPERTY_TUC]
GO


DROP TABLE [dbo].[PIMS_PROJECT_PROPERTY]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_USER"                                             */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_USER_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_USER] DROP CONSTRAINT [USER_PK]
GO


DROP TABLE [dbo].[PIMS_USER]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ACTIVITY"                                         */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_ACTIVITY_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY] DROP CONSTRAINT [ACTVTY_PK]
GO


DROP TABLE [dbo].[PIMS_ACTIVITY]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY"                                         */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_PROPERTY_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_IS_OWNED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_IS_PROPERTY_OF_INTEREST_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_IS_VISIBLE_TO_OTHER_AGENCIES_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_IS_SENSITIVE_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY] DROP CONSTRAINT [PRPRTY_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_CONTACT_METHOD"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_CONTACT_METHOD_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_IS_PREFERRED_METHOD_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD] DROP CONSTRAINT [CNTMTH_PK]
GO


DROP TABLE [dbo].[PIMS_CONTACT_METHOD]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PERSON_ORGANIZATION"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_PERSON_ORGANIZATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_PK]
GO


ALTER TABLE [dbo].[PIMS_PERSON_ORGANIZATION] DROP CONSTRAINT [PERORG_PERSON_ORGANIZATION_TUC]
GO


DROP TABLE [dbo].[PIMS_PERSON_ORGANIZATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PERSON"                                           */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_PERSON_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PERSON] DROP CONSTRAINT [PERSON_PK]
GO


DROP TABLE [dbo].[PIMS_PERSON]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ORGANIZATION"                                     */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_ORGANIZATION_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION] DROP CONSTRAINT [ORG_PK]
GO


DROP TABLE [dbo].[PIMS_ORGANIZATION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ADDRESS"                                          */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_ADDRESS_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS] DROP CONSTRAINT [ADDRSS_PK]
GO


DROP TABLE [dbo].[PIMS_ADDRESS]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_WORKFLOW_MODEL"                           */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_PROJECT_WORKFLOW_MODEL_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_PK]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL] DROP CONSTRAINT [PRWKMD_PROJECT_WORKFLOW_MODEL_TUC]
GO


DROP TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_TASK_TEMPLATE_ACTIVITY_MODEL"                     */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_TASK_TEMPLATE_ACTIVITY_MODEL_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_IS_MANDATORY_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_IMPLEMENTATION_ORDER_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_PK]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT [TSKTAM_TASK_TEMPLATE_ACTIVITY_MODEL_TUC]
GO


DROP TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_NOTE"                                     */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_PROJECT_NOTE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_NOTE] DROP CONSTRAINT [PROJNT_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT_NOTE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ROLE_CLAIM"                                       */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_ROLE_CLAIM_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_PK]
GO


ALTER TABLE [dbo].[PIMS_ROLE_CLAIM] DROP CONSTRAINT [ROLCLM_ROLE_CLAIM_TUC]
GO


DROP TABLE [dbo].[PIMS_ROLE_CLAIM]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROVINCE_STATE"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROVINCE_STATE] DROP CONSTRAINT [PROVNC_PK]
GO


DROP TABLE [dbo].[PIMS_PROVINCE_STATE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_DISTRICT"                                         */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_DISTRICT] DROP CONSTRAINT [DSTRCT_PK]
GO


DROP TABLE [dbo].[PIMS_DISTRICT]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_WORKFLOW_MODEL"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_WORKFLOW_MODEL_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL] DROP CONSTRAINT [WFLMDL_PK]
GO


DROP TABLE [dbo].[PIMS_WORKFLOW_MODEL]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_TASK_TEMPLATE"                                    */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_TASK_TEMPLATE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE] DROP CONSTRAINT [TSKTMP_PK]
GO


DROP TABLE [dbo].[PIMS_TASK_TEMPLATE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_SERVICE_FILE"                            */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_PROPERTY_SERVICE_FILE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE] DROP CONSTRAINT [PRPSVC_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT"                                          */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_PROJECT_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT] DROP CONSTRAINT [PROJCT_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ORG_IDENTIFIER_TYPE"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE] DROP CONSTRAINT [ORGIDT_PK]
GO


DROP TABLE [dbo].[PIMS_ORG_IDENTIFIER_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_STATUS_TYPE"                             */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE] DROP CONSTRAINT [PRPSTS_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_STATUS_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_DATA_SOURCE_TYPE"                        */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE] DROP CONSTRAINT [PIDSRT_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_DATA_SOURCE_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.__EFMigrationsHistory"                                 */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[__EFMigrationsHistory] DROP CONSTRAINT [MIGHIS_PK]
GO


DROP TABLE [dbo].[__EFMigrationsHistory]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_AREA_UNIT_TYPE"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_AREA_UNIT_TYPE] DROP CONSTRAINT [ARUNIT_PK]
GO


DROP TABLE [dbo].[PIMS_AREA_UNIT_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_TENURE_TYPE"                             */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE] DROP CONSTRAINT [PRPTNR_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_TENURE_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_CONTACT_METHOD_TYPE"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE] DROP CONSTRAINT [CNTMTT_PK]
GO


DROP TABLE [dbo].[PIMS_CONTACT_METHOD_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_CLASSIFICATION_TYPE"                     */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE] DROP CONSTRAINT [PRPCLT_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_CLASSIFICATION_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ROLE"                                             */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_ROLE_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_IS_PUBLIC_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ROLE] DROP CONSTRAINT [ROLE_PK]
GO


DROP TABLE [dbo].[PIMS_ROLE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_TIER_TYPE"                                */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TIER_TYPE] DROP CONSTRAINT [PROJTR_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT_TIER_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_RISK_TYPE"                                */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_RISK_TYPE] DROP CONSTRAINT [PRJRSK_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT_RISK_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_SERVICE_FILE_TYPE"                       */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE] DROP CONSTRAINT [PRSVFT_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_STATUS_TYPE"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_IS_MILESTONE_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_IS_TERMINAL_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE] DROP CONSTRAINT [PRJSTY_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT_STATUS_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ACCESS_REQUEST_STATUS_TYPE"                       */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE] DROP CONSTRAINT [ARQSTT_PK]
GO


DROP TABLE [dbo].[PIMS_ACCESS_REQUEST_STATUS_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ORGANIZATION_TYPE"                                */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ORGANIZATION_TYPE] DROP CONSTRAINT [ORGTYP_PK]
GO


DROP TABLE [dbo].[PIMS_ORGANIZATION_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_TASK_TEMPLATE_TYPE"                               */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE] DROP CONSTRAINT [TSKTMT_PK]
GO


DROP TABLE [dbo].[PIMS_TASK_TEMPLATE_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROJECT_TYPE"                                     */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROJECT_TYPE] DROP CONSTRAINT [PRJTYP_PK]
GO


DROP TABLE [dbo].[PIMS_PROJECT_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_CLAIM"                                            */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_CLAIM_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_CLAIM] DROP CONSTRAINT [CLMTYP_PK]
GO


DROP TABLE [dbo].[PIMS_CLAIM]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ADDRESS_USAGE_TYPE"                               */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE] DROP CONSTRAINT [ADUSGT_PK]
GO


DROP TABLE [dbo].[PIMS_ADDRESS_USAGE_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_COUNTRY"                                          */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_COUNTRY] DROP CONSTRAINT [CNTRY_PK]
GO


DROP TABLE [dbo].[PIMS_COUNTRY]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_REGION"                                           */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_REGION] DROP CONSTRAINT [REGION_PK]
GO


DROP TABLE [dbo].[PIMS_REGION]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_PROPERTY_TYPE"                                    */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_PROPERTY_TYPE] DROP CONSTRAINT [PRPTYP_PK]
GO


DROP TABLE [dbo].[PIMS_PROPERTY_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_WORKFLOW_MODEL_TYPE"                              */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE] DROP CONSTRAINT [WFLMDT_PK]
GO


DROP TABLE [dbo].[PIMS_WORKFLOW_MODEL_TYPE]
GO


/* ---------------------------------------------------------------------- */
/* Drop table "dbo.PIMS_ACTIVITY_MODEL"                                   */
/* ---------------------------------------------------------------------- */

/* Drop constraints */

ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_ACTIVITY_MODEL_ID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_IS_DISABLED_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_CONCURRENCY_CONTROL_NUMBER_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_APP_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_APP_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_DB_CREATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_DB_CREATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_DB_LAST_UPDATE_TIMESTAMP_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_DB_LAST_UPDATE_USERID_DEF]
GO


ALTER TABLE [dbo].[PIMS_ACTIVITY_MODEL] DROP CONSTRAINT [ACTMDL_PK]
GO


DROP TABLE [dbo].[PIMS_ACTIVITY_MODEL]
GO


/* ---------------------------------------------------------------------- */
/* Drop sequences                                                         */
/* ---------------------------------------------------------------------- */

DROP SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACTIVITY_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACTIVITY_MODEL_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACTIVITY_MODEL_TASK_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACTIVITY_SERVICE_FILE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ACTIVITY_TASK_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ADDRESS_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ASSET_EVALUATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_CONSTRUCTION_TYPE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_EVALUATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_FISCAL_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_OCCUPANT_TYPE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_BUILDING_PREDOMINATE_USE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_CLAIM_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_CONTACT_METHOD_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PERSON_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PERSON_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_NOTE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_NUMBER_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_PROPERTY_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_ACTIVITY_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_EVALUATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_SERVICE_FILE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_PROPERTY_STRUCTURE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ROLE_CLAIM_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_ROLE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_STRUCTURE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_TASK_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_USER_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_USER_ORGANIZATION_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_USER_ROLE_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_USER_TASK_ID_SEQ]
GO


DROP SEQUENCE [dbo].[PIMS_WORKFLOW_MODEL_ID_SEQ]
GO

