DELETE 
FROM   PIMS_ACQUISITION_FILE_PERSON;
GO

INSERT INTO [dbo].[PIMS_ACQUISITION_FILE_PERSON] ([ACQUISITION_FILE_ID], [PERSON_ID], [ACQ_FL_PERSON_PROFILE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES(1, 1, N'EXPRAGENT', 1)
GO
