DELETE 
FROM   PIMS_ACQUISITION_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_ACQUISITION_ACTIVITY_INSTANCE] ([ACQUISITION_FILE_ID], [ACTIVITY_INSTANCE_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES(1, 1, 1)
GO
