/* 
 * Title Direct Search Services
 *
 * Title Direct Search Services
 *
 * OpenAPI spec version: 4.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.IO;
using System.Runtime.Serialization;


namespace Pims.Ltsa.Models
{
    /// <summary>
    /// Parameters required for ordering a Strata Plan Common Property
    /// </summary>
    [DataContract]
    public partial class StrataPlanCommonPropertyOrderParameters
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StrataPlanCommonPropertyOrderParameters" /> class.
        /// </summary>
        /// <param name="strataPlanNumber">Strata plan number for the common property Mandatory parameter # Note: All plan numbers must include the plan’s prefix and/or suffix  (required).</param>
        /// <param name="includeCancelledInfo">Indicate whether to include cancelled charges, legal notations and corrections on the strata plan common property.</param>
        public StrataPlanCommonPropertyOrderParameters(string strataPlanNumber = default, bool? includeCancelledInfo = default)
        {
            // to ensure "strataPlanNumber" is required (not null)
            if (strataPlanNumber == null)
            {
                throw new InvalidDataException("strataPlanNumber is a required property for StrataPlanCommonPropertyOrderParameters and cannot be null");
            }
            else
            {
                this.StrataPlanNumber = strataPlanNumber;
            }
            this.IncludeCancelledInfo = includeCancelledInfo;
        }

        /// <summary>
        /// Strata plan number for the common property Mandatory parameter # Note: All plan numbers must include the plan’s prefix and/or suffix 
        /// </summary>
        /// <value>Strata plan number for the common property Mandatory parameter # Note: All plan numbers must include the plan’s prefix and/or suffix </value>
        [DataMember(Name = "strataPlanNumber", EmitDefaultValue = false)]
        public string StrataPlanNumber { get; set; }

        /// <summary>
        /// Indicate whether to include cancelled charges, legal notations and corrections on the strata plan common property
        /// </summary>
        /// <value>Indicate whether to include cancelled charges, legal notations and corrections on the strata plan common property</value>
        [DataMember(Name = "includeCancelledInfo", EmitDefaultValue = false)]
        public bool? IncludeCancelledInfo { get; set; }
    }
}
