/* 
 * Title Direct Search Services
 *
 * Title Direct Search Services
 *
 * OpenAPI spec version: 4.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Pims.Ltsa.Models
{
    /// <summary>
    /// TitleSummary
    /// </summary>
    [DataContract]
    public partial class TitleSummary
    {
        /// <summary>
        /// Status of the title
        /// </summary>
        /// <value>Status of the title</value>
        [JsonStringEnumMemberConverterOptions(deserializationFailureFallbackValue: 0)]
        [JsonConverter(typeof(JsonStringEnumMemberConverter))]
        public enum StatusEnum
        {
            Unknown = 0,
            /// <summary>
            /// Enum REGISTERED for value: REGISTERED
            /// </summary>
            [EnumMember(Value = "REGISTERED")]
            REGISTERED = 1,
            /// <summary>
            /// Enum CANCELLED for value: CANCELLED
            /// </summary>
            [EnumMember(Value = "CANCELLED")]
            CANCELLED = 2
        }
        /// <summary>
        /// Status of the title
        /// </summary>
        /// <value>Status of the title</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TitleSummary" /> class.
        /// </summary>
        /// <param name="titleNumber">Title number of the title.</param>
        /// <param name="landTitleDistrict">Land title district (e.g. Victoria) where the title belongs.</param>
        /// <param name="landTitleDistrictCode">landTitleDistrictCode.</param>
        /// <param name="parcelIdentifier">Parcel identifier in Land Title Registry, format: 123-123-123.</param>
        /// <param name="status">Status of the title.</param>
        /// <param name="firstOwner">First registered owner name on title.</param>
        public TitleSummary(string titleNumber = default, string landTitleDistrict = default, LandTitleDistrictCode landTitleDistrictCode = default, string parcelIdentifier = default, StatusEnum? status = default, string firstOwner = default)
        {
            this.TitleNumber = titleNumber;
            this.LandTitleDistrict = landTitleDistrict;
            this.LandTitleDistrictCode = landTitleDistrictCode;
            this.ParcelIdentifier = parcelIdentifier;
            this.Status = status;
            this.FirstOwner = firstOwner;
        }

        /// <summary>
        /// Title number of the title
        /// </summary>
        /// <value>Title number of the title</value>
        [DataMember(Name = "titleNumber", EmitDefaultValue = false)]
        public string TitleNumber { get; set; }

        /// <summary>
        /// Land title district (e.g. Victoria) where the title belongs
        /// </summary>
        /// <value>Land title district (e.g. Victoria) where the title belongs</value>
        [DataMember(Name = "landTitleDistrict", EmitDefaultValue = false)]
        public string LandTitleDistrict { get; set; }

        /// <summary>
        /// Gets or Sets LandTitleDistrictCode
        /// </summary>
        [DataMember(Name = "landTitleDistrictCode", EmitDefaultValue = false)]
        public LandTitleDistrictCode LandTitleDistrictCode { get; set; }

        /// <summary>
        /// Parcel identifier in Land Title Registry, format: 123-123-123
        /// </summary>
        /// <value>Parcel identifier in Land Title Registry, format: 123-123-123</value>
        [DataMember(Name = "parcelIdentifier", EmitDefaultValue = false)]
        public string ParcelIdentifier { get; set; }


        /// <summary>
        /// First registered owner name on title
        /// </summary>
        /// <value>First registered owner name on title</value>
        [DataMember(Name = "firstOwner", EmitDefaultValue = false)]
        public string FirstOwner { get; set; }
    }
}
