/* 
 * Title Direct Search Services
 *
 * Title Direct Search Services
 *
 * OpenAPI spec version: 4.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.IO;
using System.Runtime.Serialization;


namespace Pims.Ltsa.Models
{
    /// <summary>
    /// UnsubdividedShortLegalDescription
    /// </summary>
    [DataContract]
    public partial class UnsubdividedShortLegalDescription
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsubdividedShortLegalDescription" /> class.
        /// </summary>
        /// <param name="landDistrict1">Land District (required).</param>
        /// <param name="meridian2">Meridian.</param>
        /// <param name="range3">Range.</param>
        /// <param name="townshipOrIsland4">Township/Island.</param>
        /// <param name="group5">Group.</param>
        /// <param name="block6">Block.</param>
        /// <param name="districtLotOrLotOrSection7">District Lot/Lot/Section.</param>
        /// <param name="section8">Section.</param>
        /// <param name="quadrant9">Quadrant.</param>
        /// <param name="blockOrSection10">Block.</param>
        /// <param name="subdivision11">Legal Subdivision.</param>
        /// <param name="lotOrSubLotOrParcel12">Lot/Sublot/Parcel.</param>
        /// <param name="lotOrParcel13">Lot/Parcel.</param>
        /// <param name="mineralClaimIOrIndianReserveName14">Mineral Claim / Indian Reserve Name.</param>
        /// <param name="mineralClaimOrIndianReserveNumber15">Mineral Claim Number / Indian Reserve Number.</param>
        /// <param name="concatShortLegal">Parcel Short Legal obtained by concatenating all previous Short Legal search fields (required).</param>
        /// <param name="marginalNotes">Marginal Notes.</param>
        public UnsubdividedShortLegalDescription(string landDistrict1 = default, string meridian2 = default, string range3 = default, string townshipOrIsland4 = default, string group5 = default, string block6 = default, string districtLotOrLotOrSection7 = default, string section8 = default, string quadrant9 = default, string blockOrSection10 = default, string subdivision11 = default, string lotOrSubLotOrParcel12 = default, string lotOrParcel13 = default, string mineralClaimIOrIndianReserveName14 = default, string mineralClaimOrIndianReserveNumber15 = default, string concatShortLegal = default, string marginalNotes = default)
        {
            // to ensure "landDistrict1" is required (not null)
            if (landDistrict1 == null)
            {
                throw new InvalidDataException("landDistrict1 is a required property for UnsubdividedShortLegalDescription and cannot be null");
            }
            else
            {
                this.LandDistrict1 = landDistrict1;
            }
            // to ensure "concatShortLegal" is required (not null)
            if (concatShortLegal == null)
            {
                throw new InvalidDataException("concatShortLegal is a required property for UnsubdividedShortLegalDescription and cannot be null");
            }
            else
            {
                this.ConcatShortLegal = concatShortLegal;
            }
            this.Meridian2 = meridian2;
            this.Range3 = range3;
            this.TownshipOrIsland4 = townshipOrIsland4;
            this.Group5 = group5;
            this.Block6 = block6;
            this.DistrictLotOrLotOrSection7 = districtLotOrLotOrSection7;
            this.Section8 = section8;
            this.Quadrant9 = quadrant9;
            this.BlockOrSection10 = blockOrSection10;
            this.Subdivision11 = subdivision11;
            this.LotOrSubLotOrParcel12 = lotOrSubLotOrParcel12;
            this.LotOrParcel13 = lotOrParcel13;
            this.MineralClaimIOrIndianReserveName14 = mineralClaimIOrIndianReserveName14;
            this.MineralClaimOrIndianReserveNumber15 = mineralClaimOrIndianReserveNumber15;
            this.MarginalNotes = marginalNotes;
        }

        /// <summary>
        /// Land District
        /// </summary>
        /// <value>Land District</value>
        [DataMember(Name = "landDistrict1", EmitDefaultValue = false)]
        public string LandDistrict1 { get; set; }

        /// <summary>
        /// Meridian
        /// </summary>
        /// <value>Meridian</value>
        [DataMember(Name = "meridian2", EmitDefaultValue = false)]
        public string Meridian2 { get; set; }

        /// <summary>
        /// Range
        /// </summary>
        /// <value>Range</value>
        [DataMember(Name = "range3", EmitDefaultValue = false)]
        public string Range3 { get; set; }

        /// <summary>
        /// Township/Island
        /// </summary>
        /// <value>Township/Island</value>
        [DataMember(Name = "townshipOrIsland4", EmitDefaultValue = false)]
        public string TownshipOrIsland4 { get; set; }

        /// <summary>
        /// Group
        /// </summary>
        /// <value>Group</value>
        [DataMember(Name = "group5", EmitDefaultValue = false)]
        public string Group5 { get; set; }

        /// <summary>
        /// Block
        /// </summary>
        /// <value>Block</value>
        [DataMember(Name = "block6", EmitDefaultValue = false)]
        public string Block6 { get; set; }

        /// <summary>
        /// District Lot/Lot/Section
        /// </summary>
        /// <value>District Lot/Lot/Section</value>
        [DataMember(Name = "districtLotOrLotOrSection7", EmitDefaultValue = false)]
        public string DistrictLotOrLotOrSection7 { get; set; }

        /// <summary>
        /// Section
        /// </summary>
        /// <value>Section</value>
        [DataMember(Name = "section8", EmitDefaultValue = false)]
        public string Section8 { get; set; }

        /// <summary>
        /// Quadrant
        /// </summary>
        /// <value>Quadrant</value>
        [DataMember(Name = "quadrant9", EmitDefaultValue = false)]
        public string Quadrant9 { get; set; }

        /// <summary>
        /// Block
        /// </summary>
        /// <value>Block</value>
        [DataMember(Name = "blockOrSection10", EmitDefaultValue = false)]
        public string BlockOrSection10 { get; set; }

        /// <summary>
        /// Legal Subdivision
        /// </summary>
        /// <value>Legal Subdivision</value>
        [DataMember(Name = "subdivision11", EmitDefaultValue = false)]
        public string Subdivision11 { get; set; }

        /// <summary>
        /// Lot/Sublot/Parcel
        /// </summary>
        /// <value>Lot/Sublot/Parcel</value>
        [DataMember(Name = "lotOrSubLotOrParcel12", EmitDefaultValue = false)]
        public string LotOrSubLotOrParcel12 { get; set; }

        /// <summary>
        /// Lot/Parcel
        /// </summary>
        /// <value>Lot/Parcel</value>
        [DataMember(Name = "lotOrParcel13", EmitDefaultValue = false)]
        public string LotOrParcel13 { get; set; }

        /// <summary>
        /// Mineral Claim / Indian Reserve Name
        /// </summary>
        /// <value>Mineral Claim / Indian Reserve Name</value>
        [DataMember(Name = "mineralClaimIOrIndianReserveName14", EmitDefaultValue = false)]
        public string MineralClaimIOrIndianReserveName14 { get; set; }

        /// <summary>
        /// Mineral Claim Number / Indian Reserve Number
        /// </summary>
        /// <value>Mineral Claim Number / Indian Reserve Number</value>
        [DataMember(Name = "mineralClaimOrIndianReserveNumber15", EmitDefaultValue = false)]
        public string MineralClaimOrIndianReserveNumber15 { get; set; }

        /// <summary>
        /// Parcel Short Legal obtained by concatenating all previous Short Legal search fields
        /// </summary>
        /// <value>Parcel Short Legal obtained by concatenating all previous Short Legal search fields</value>
        [DataMember(Name = "concatShortLegal", EmitDefaultValue = false)]
        public string ConcatShortLegal { get; set; }

        /// <summary>
        /// Marginal Notes
        /// </summary>
        /// <value>Marginal Notes</value>
        [DataMember(Name = "marginalNotes", EmitDefaultValue = false)]
        public string MarginalNotes { get; set; }
    }
}
