DELETE FROM PIMS_PROPERTY_ACTIVITY;
GO

INSERT INTO PIMS_PROPERTY_ACTIVITY (PROP_MGMT_ACTIVITY_STATUS_TYPE_CODE, SERVICE_PROVIDER_PERSON_ID, SERVICE_PROVIDER_ORG_ID, MANAGEMENT_FILE_ID, REQUEST_ADDED_DT, COMPLETION_DT, DESCRIPTION, REQUEST_SOURCE)
VALUES
  (N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'INPROGRESS', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'COMPLETED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source');
GO
