DELETE FROM PIMS_PROPERTY_ACTIVITY_INVOICE;
GO

INSERT INTO PIMS_PROPERTY_ACTIVITY_INVOICE (PIMS_PROPERTY_ACTIVITY_ID, INVOICE_DT, DESCRIPTION, PRETAX_AMT, GST_AMT, PST_AMT, TOTAL_AMT)
VALUES
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 100, 5, 7, 112),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 110, 2, 0, 112),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 101, 3, 5, 109),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 102, 6, 4, 112),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 103, 4, 4, 111),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 104, 8, 5, 117),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 105, 7, 7, 119),
  ((SELECT TOP 1 PIMS_PROPERTY_ACTIVITY_ID FROM PIMS_PROPERTY_ACTIVITY ORDER BY NEWID()), getutcdate(), N'This is a description', 106, 9, 8, 123);
GO
