INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(1, N'1STNTNCONSULT', N'CONSULTREC')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(1, N'PROPERTYMTC', N'ARBORIST')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(1, N'PROPERTYMTC', N'WINDOWCLEAN')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(1, N'UTILITYBILL', N'INTERNETBILL')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(2, N'INVESTRPT', N'ENGINEERiNG')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(3, N'PROPERTYMTC', N'PARKINGLOT')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(4, N'INCDNTISSUE', N'VANDALISM')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(5, N'CONSULTATION', N'PUBLIC')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(6, N'LANDLORDIMPRV', N'LL_PREMISES')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(7, N'TAXESLEVIES', N'OTHERTAX')
GO
INSERT INTO [dbo].[PIMS_PROP_ACTIVITY_MGMT_ACTIVITY]([PIMS_PROPERTY_ACTIVITY_ID], [PROP_MGMT_ACTIVITY_TYPE_CODE], [PROP_MGMT_ACTIVITY_SUBTYPE_CODE])
  VALUES(8, N'TRAILMTC', N'RIPARIAN')
GO
