INSERT INTO PIMS_PROPERTY_ACQUISITION_FILE(ACQUISITION_FILE_ID, PROPERTY_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
  VALUES
    ( 9, 292, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (41, 345, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (49,  83, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (13, 340, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (18,  43, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 4, 242, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (35,   7, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (40, 321, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 1, 149, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (14,  60, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (36, 273, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (42, 256, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (41, 150, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (41, 401, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (40, 394, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (18, 260, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (16, 265, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 2,  44, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 4, 267, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (49, 218, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 3, 307, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (10, 276, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (48, 190, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (21, 125, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (26,  37, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 9, 361, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (42, 376, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (42, 439, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (15,  55, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 6, 335, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 2, 109, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 2, 220, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 5,  90, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (23, 154, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (46,  70, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (15,  11, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (47, 379, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (50, 417, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (34, 265, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (39,  36, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 4, 290, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 2, 342, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (24, 350, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (17,  40, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (10, 331, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (41, 162, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (42, 312, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (39, 155, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    (30, 129, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo'),
    ( 5, 243, 1, getutcdate(), N'TestFoo', NULL, N'TestFoo', getutcdate(), N'TestFoo', NULL, N'TestFoo');
GO
