DELETE
FROM   PIMS_RESEARCH_FILE_PURPOSE;
GO

INSERT INTO [dbo].[PIMS_RESEARCH_FILE_PURPOSE] ([RESEARCH_FILE_ID], [RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES(1, N'ACQUIRE', 0)
GO
