DELETE
FROM   PIMS_ACQUISITION_FILE;
GO

INSERT INTO [dbo].[PIMS_ACQUISITION_FILE] ([ACQUISITION_FILE_ID], [ACQUISITION_FILE_STATUS_TYPE_CODE], [ACQUISITION_TYPE_CODE], [ACQUISITION_FUNDING_TYPE_CODE], [ACQ_PHYS_FILE_STATUS_TYPE_CODE], [REGION_CODE], [FILE_NAME], [FILE_NUMBER], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES(1, N'ACTIVE', N'CONSEN', N'DFAA', N'ACTIVE', 1, N'Brain Freeze', N'Uno', 1)
GO
