/* 
 * Title Direct Search Services
 *
 * Title Direct Search Services
 *
 * OpenAPI spec version: 4.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.IO;
using System.Runtime.Serialization;


namespace Pims.Ltsa.Models
{
    /// <summary>
    /// SubdividedShortLegalDescription
    /// </summary>
    [DataContract]
    public partial class SubdividedShortLegalDescription
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubdividedShortLegalDescription" /> class.
        /// </summary>
        /// <param name="planNumber1">Plan (required).</param>
        /// <param name="townshipOrTownSite2">Township/Townsite.</param>
        /// <param name="range3">Range.</param>
        /// <param name="block4">Block.</param>
        /// <param name="subdivision5">Subdivision.</param>
        /// <param name="lotOrDistrictLotOrSubLot6">District Lot/Lot/Sublot.</param>
        /// <param name="subdivision7">Subdivision.</param>
        /// <param name="lotOrParcel8">Lot/Parcel.</param>
        /// <param name="section9">Section.</param>
        /// <param name="quadrant10">Quadrant.</param>
        /// <param name="blockOrLot11">Block/Lot.</param>
        /// <param name="lotOrParcel12">Lot/Parcel.</param>
        /// <param name="parcelOrBlock13">Parcel/Block.</param>
        /// <param name="concatShortLegal">Parcel Short Legal obtained by concatenating all previous Short Legal search fields (required).</param>
        /// <param name="marginalNotes">Marginal Notes.</param>
        public SubdividedShortLegalDescription(string planNumber1 = default, string townshipOrTownSite2 = default, string range3 = default, string block4 = default, string subdivision5 = default, string lotOrDistrictLotOrSubLot6 = default, string subdivision7 = default, string lotOrParcel8 = default, string section9 = default, string quadrant10 = default, string blockOrLot11 = default, string lotOrParcel12 = default, string parcelOrBlock13 = default, string concatShortLegal = default, string marginalNotes = default)
        {
            // to ensure "planNumber1" is required (not null)
            if (planNumber1 == null)
            {
                throw new InvalidDataException("planNumber1 is a required property for SubdividedShortLegalDescription and cannot be null");
            }
            else
            {
                this.PlanNumber1 = planNumber1;
            }
            // to ensure "concatShortLegal" is required (not null)
            if (concatShortLegal == null)
            {
                throw new InvalidDataException("concatShortLegal is a required property for SubdividedShortLegalDescription and cannot be null");
            }
            else
            {
                this.ConcatShortLegal = concatShortLegal;
            }
            this.TownshipOrTownSite2 = townshipOrTownSite2;
            this.Range3 = range3;
            this.Block4 = block4;
            this.Subdivision5 = subdivision5;
            this.LotOrDistrictLotOrSubLot6 = lotOrDistrictLotOrSubLot6;
            this.Subdivision7 = subdivision7;
            this.LotOrParcel8 = lotOrParcel8;
            this.Section9 = section9;
            this.Quadrant10 = quadrant10;
            this.BlockOrLot11 = blockOrLot11;
            this.LotOrParcel12 = lotOrParcel12;
            this.ParcelOrBlock13 = parcelOrBlock13;
            this.MarginalNotes = marginalNotes;
        }

        /// <summary>
        /// Plan
        /// </summary>
        /// <value>Plan</value>
        [DataMember(Name = "planNumber1", EmitDefaultValue = false)]
        public string PlanNumber1 { get; set; }

        /// <summary>
        /// Township/Townsite
        /// </summary>
        /// <value>Township/Townsite</value>
        [DataMember(Name = "townshipOrTownSite2", EmitDefaultValue = false)]
        public string TownshipOrTownSite2 { get; set; }

        /// <summary>
        /// Range
        /// </summary>
        /// <value>Range</value>
        [DataMember(Name = "range3", EmitDefaultValue = false)]
        public string Range3 { get; set; }

        /// <summary>
        /// Block
        /// </summary>
        /// <value>Block</value>
        [DataMember(Name = "block4", EmitDefaultValue = false)]
        public string Block4 { get; set; }

        /// <summary>
        /// Subdivision
        /// </summary>
        /// <value>Subdivision</value>
        [DataMember(Name = "subdivision5", EmitDefaultValue = false)]
        public string Subdivision5 { get; set; }

        /// <summary>
        /// District Lot/Lot/Sublot
        /// </summary>
        /// <value>District Lot/Lot/Sublot</value>
        [DataMember(Name = "lotOrDistrictLotOrSubLot6", EmitDefaultValue = false)]
        public string LotOrDistrictLotOrSubLot6 { get; set; }

        /// <summary>
        /// Subdivision
        /// </summary>
        /// <value>Subdivision</value>
        [DataMember(Name = "subdivision7", EmitDefaultValue = false)]
        public string Subdivision7 { get; set; }

        /// <summary>
        /// Lot/Parcel
        /// </summary>
        /// <value>Lot/Parcel</value>
        [DataMember(Name = "lotOrParcel8", EmitDefaultValue = false)]
        public string LotOrParcel8 { get; set; }

        /// <summary>
        /// Section
        /// </summary>
        /// <value>Section</value>
        [DataMember(Name = "section9", EmitDefaultValue = false)]
        public string Section9 { get; set; }

        /// <summary>
        /// Quadrant
        /// </summary>
        /// <value>Quadrant</value>
        [DataMember(Name = "quadrant10", EmitDefaultValue = false)]
        public string Quadrant10 { get; set; }

        /// <summary>
        /// Block/Lot
        /// </summary>
        /// <value>Block/Lot</value>
        [DataMember(Name = "blockOrLot11", EmitDefaultValue = false)]
        public string BlockOrLot11 { get; set; }

        /// <summary>
        /// Lot/Parcel
        /// </summary>
        /// <value>Lot/Parcel</value>
        [DataMember(Name = "lotOrParcel12", EmitDefaultValue = false)]
        public string LotOrParcel12 { get; set; }

        /// <summary>
        /// Parcel/Block
        /// </summary>
        /// <value>Parcel/Block</value>
        [DataMember(Name = "parcelOrBlock13", EmitDefaultValue = false)]
        public string ParcelOrBlock13 { get; set; }

        /// <summary>
        /// Parcel Short Legal obtained by concatenating all previous Short Legal search fields
        /// </summary>
        /// <value>Parcel Short Legal obtained by concatenating all previous Short Legal search fields</value>
        [DataMember(Name = "concatShortLegal", EmitDefaultValue = false)]
        public string ConcatShortLegal { get; set; }

        /// <summary>
        /// Marginal Notes
        /// </summary>
        /// <value>Marginal Notes</value>
        [DataMember(Name = "marginalNotes", EmitDefaultValue = false)]
        public string MarginalNotes { get; set; }
    }
}
