DELETE FROM PIMS_MGMT_ACT_INVOLVED_PARTY;
GO

INSERT INTO PIMS_MGMT_ACT_INVOLVED_PARTY (MANAGEMENT_ACTIVITY_ID, PERSON_ID, ORGANIZATION_ID)
VALUES
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()));
GO
