DELETE
FROM   PIMS_PROP_TENURE_CLEANUP
GO

DECLARE @i   INT = 0
DECLARE @max INT = 50

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_PROP_TENURE_CLEANUP (PROPERTY_ID, TENURE_CLEANUP_TYPE_CODE)
    VALUES
      ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()), (SELECT TOP 1 TENURE_CLEANUP_TYPE_CODE FROM PIMS_TENURE_CLEANUP_TYPE ORDER BY NEWID()))
  END
GO
