DECLARE @i         INT = 0
DECLARE @max       INT = 1000
DECLARE @StartDate DATE = '2020-01-01'
DECLARE @EndDate   DATE = '2025-12-31'

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_NOTIFICATION_USER_OUTPUT (NOTIFICATION_USER_ID, NOTIFICATION_OUTPUT_TYPE_CODE, NOTIFICATION_SENT_DT, NOTIFICATION_READ_DT, NOTIFICATION_RETRY_CNT, NOTIFICATION_ERROR_REASON, NOTIFICATION_ERROR_DT, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
    VALUES
      ((SELECT TOP 1 NOTIFICATION_USER_ID          FROM PIMS_NOTIFICATION_USER        ORDER BY NEWID()),
       (SELECT TOP 1 NOTIFICATION_OUTPUT_TYPE_CODE FROM PIMS_NOTIFICATION_OUTPUT_TYPE ORDER BY NEWID()),
       (SELECT DATEADD(DAY, ABS(CHECKSUM(NEWID())) % (DATEDIFF(DAY, @StartDate, @EndDate) + 1), @StartDate)),
       (SELECT DATEADD(DAY, ABS(CHECKSUM(NEWID())) % (DATEDIFF(DAY, @StartDate, @EndDate) + 1), @StartDate)),
       (SELECT FLOOR(RAND()*(10)+1)),
       N'Notification_error_reason',
       (SELECT DATEADD(DAY, ABS(CHECKSUM(NEWID())) % (DATEDIFF(DAY, @StartDate, @EndDate) + 1), @StartDate)),       
       1, getutcdate(), N'PSP-11294', NEWID(), N'PSP-11294', getutcdate(), N'PSP-11294', NEWID(), N'PSP-11294')
  END
GO
