DELETE
FROM   PIMS_ACTIVITY_INSTANCE_DOCUMENT;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_INSTANCE_DOCUMENT] ([ACTIVITY_INSTANCE_ID], [DOCUMENT_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES((SELECT MAX(ACTIVITY_INSTANCE_ID) FROM PIMS_ACTIVITY_INSTANCE), (SELECT MAX(DOCUMENT_ID) FROM PIMS_DOCUMENT), 1)
GO
