DECLARE @noteView BIGINT;
DECLARE @noteAdd BIGINT;
DECLARE @noteEdit BIGINT;
DECLARE @noteDelete BIGINT;
SELECT @noteView = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-view';
SELECT @noteAdd = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-add';
SELECT @noteEdit = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-edit';
SELECT @noteDelete = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'note-delete';

DELETE FROM [dbo].[PIMS_CLAIM] WHERE CLAIM_ID = @noteView;
DELETE FROM [dbo].[PIMS_CLAIM] WHERE CLAIM_ID = @noteAdd;
DELETE FROM [dbo].[PIMS_CLAIM] WHERE CLAIM_ID = @noteEdit;
DELETE FROM [dbo].[PIMS_CLAIM] WHERE CLAIM_ID = @noteDelete;
GO
