# Enable the spanmetrics connector to bridge
# the traces pipeline into the metrics pipeline.
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: ${env:JAEGER_LISTEN_HOST:-0.0.0.0}
                port: 8888
    logs:
      level: debug

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: ${env:JAEGER_LISTEN_HOST:-0.0.0.0}:13133

  # pprof:
  #   endpoint: 0.0.0.0:1777
  # zpages:
  #   endpoint: 0.0.0.0:55679

  jaeger_query:
    storage:
      traces: some_storage
      metrics: some_metrics_storage
    ui:
      # config_file: ./cmd/jaeger/config-ui.json
    # The maximum duration that is considered for clock skew adjustments.
    # Defaults to 0 seconds, which means it's disabled.
    max_clock_skew_adjust: 0s

  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000
    metric_backends:
      some_metrics_storage:
        prometheus:
          endpoint: http://${env:PROMETHEUS_HOST:-prometheus}:${env:PROMETHEUS_PORT:-9090}
          normalize_calls: true
          normalize_duration: true

# Declare spanmetrics connector.
connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:JAEGER_LISTEN_HOST:-0.0.0.0}:4317
      http:
        endpoint: ${env:JAEGER_LISTEN_HOST:-0.0.0.0}:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
  # Declare an exporter for metrics produced by the connector.
  # For example, a Prometheus server may be configured to scrape
  # the metrics from this endpoint.
  prometheus:
    endpoint: ${env:JAEGER_LISTEN_HOST:-0.0.0.0}:8889
