apiVersion: v1
kind: Template
metadata:
  name: pims-app-deploy
  annotations:
    openshift.io/display-name: Nginx with Node build
    description: Deployment template for a React frontend application served through Nginx
    tags: pims,app,react,nginx
parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "pims"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role (e.g api, app, database)."
    required: true
    value: "app"
  - name: API_ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role for the API."
    required: true
    value: "api"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "3cd915"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: INSTANCE
    displayName: "Unique Identifier"
    description: "A unique identifier to allow for multiple instances (i.e. '-01')."
    value: ""
  - name: TIME_ZONE
    displayName: "Time Zone"
    description: "The time zone of the pod."
    value: "America/Los_Angeles"

  - name: IMAGE_TAG
    displayName: "Image Tag Name"
    description: "The image tag that will be used for this deployment.
      This provides a way to setup an environment for other branches."
    value: "dev"

  - name: APP_DOMAIN
    displayName: "Application Hostname"
    description:
      "The exposed hostname that will route to the the React frontend, if left blank a
      value will be defaulted."
    value: "pims-app-3cd915-dev.apps.silver.devops.gov.bc.ca"
  - name: APP_PORT
    displayName: "Application Port"
    description: "The port used to communicate with the Pod"
    value: "8080"

  - name: KEYCLOAK_REALM
    displayName: "Keycloak SSO realm"
    description: "Keycloak SSO realm, used by the frontend login."
    required: true
    value: 72x8v9rw
  - name: KEYCLOAK_CONFIG_FILE_NAME
    displayName: "keycloak.json Config File Name"
    description: "The name of the configuration file to be used for keycloak.json."
    required: true
    value: "keycloak.json"
  - name: TENANT_CONFIG_FILE_NAME
    displayName: "tenant.json Config File Name"
    description: "The name of the configuration file to be used for tenant.json."
    required: true
    value: "tenant.json"
  - name: CONFIG_MOUNT_PATH
    displayName: "keycloak.json Mount Path"
    description: "The path to use to mount the config file."
    required: true
    value: "/tmp/app/dist/"
  - name: KEYCLOAK_AUTHORITY_URL
    displayName: "Keycloak Authority URL"
    description: "The Keycloak authority URL."
    required: true
    value: "https://dev.oidc.gov.bc.ca/auth"

  - name: REAL_IP_FROM
    description:
      "OpenShift cluster private IP range in CIDR notation, used by Nginx
      ngx_http_realip_module."
    displayName: "OpenShift Cluster IP Range"
    required: true
    value: "172.51.0.0/16"

  - name: API_URL
    description:
      "The default URL to use when proxying requests to the application's
      API.  The value here will be overridden if a API_SERVICE_NAME is defined."
    displayName: "API URL"
    required: false
    value: ""
  - name: API_PATH
    description: "The root path for the API.  Used in conjunction with API_SERVICE_NAME."
    displayName: "API Path"
    required: true
    value: "/api"
  - name: API_SERVICE_NAME
    description: "The name of the api service in OpenShift"
    displayName: "API Path"
    required: true
    value: "pims-api"

  - name: GEOSERVER_URL
    description: "The URL to use when proxying requests to the application's
      Geoserver instance."
    displayName: "GEOSERVER URL"
    required: false
    value: ""
  - name: CSP
    description: "The string content of the desired CSP that should be applied to the frontend application."
    displayName: "CSP"
    required: false
    value: ""

  - name: REPLICAS
    displayName: "Pod Replicas"
    description: "Number of pod replicas to run"
    value: "2"

  - name: CPU_REQUEST
    displayName: "CPU Request"
    description: "Starting amount of CPU the container can use."
    value: "100m"
  - name: CPU_LIMIT
    displayName: "CPU Limit"
    description: "Maximum amount of CPU the container can use."
    value: "1"
  - name: MEMORY_REQUEST
    displayName: "Memory Request"
    description: "Starting amount of memory the container can use."
    value: "100Mi"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "2Gi"
objects:
  # Allow the app to communicate with the api.
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: pod-from-pod-permit-${APP_NAME}-${API_ROLE_NAME}-${ROLE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    spec:
      #description: Allow api pod(s) to receive communication from app pod(s).
      podSelector:
        matchLabels:
          app: ${APP_NAME}
          role: ${API_ROLE_NAME}
          env: ${ENV_NAME}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: ${APP_NAME}
                  role: ${ROLE_NAME}
                  env: ${ENV_NAME}

  # Open up ports to communicate with the app.
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Exposes and load balances the application pods.
      labels:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      ports:
        - name: ${APP_PORT}-tcp
          port: ${{APP_PORT}}
          protocol: TCP
          targetPort: ${{APP_PORT}}
      selector:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
      sessionAffinity: None
      type: ClusterIP

  # Keycloak configuration settings.
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-sso${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keycloak client JSON configuration
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-sso${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    type: Opaque
    data:
      keycloak.json: '{
        "realm": "${KEYCLOAK_REALM}",
        "auth-server-url": "${KEYCLOAK_AUTHORITY_URL}",
        "ssl-required": "external",
        "resource": "${APP_NAME}-${ROLE_NAME}",
        "public-client": true,
        "confidential-port": 0
        }'

  # Tenant configuration settings.
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-tenant${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Tenant configuration settings
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-tenant${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    type: Opaque
    data:
      tenant.json: |-
        {
            "id": "MOTI",
            "title": "Property Information Management System",
            "colour": "#003366",
            "logo": {
                "favicon": "/tenants/MOTI/favicon.ico",
                "image": "/tenants/MOTI/PIMS-logo.png",
                "imageWithText": "/tenants/MOTI/PIMS-logo-with-text.png"
            },
            "login": {
                "title": "TRAN Property Information Management System (PIMS)",
                "heading": "PIMS enables you to view highways and properties owned by the Ministry of Transportation and Infrastructure",
                "body": "WARNING: Not all data included within has been vetted for accuracy and completeness. Please use caution when proceeding and confirm data before relying on it.",
                "backgroundImage": "/tenants/MOTI/background-image.webp"
            },
            "layers": [
                {
                    "key": "Administrative Boundaries",
                    "label": "Administrative Boundaries",
                    "on": false,
                    "nodes": [
                        {
                            "id": "gazettedHighway",
                            "key": "gazettedHighway",
                            "label": "Gazetted Highway",
                            "on": false,
                            "color": "#FF0000",
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:ISS_PSP_GAZETTED_HIGHWAY",
                            "transparent": true,
                            "opacity": 0.9,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "closedHighway",
                            "key": "closedHighway",
                            "label": "Closed Highway",
                            "color": "#00FF04",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:ISS_PSP_CLOSED_HIGHWAY",
                            "transparent": true,
                            "opacity": 0.9,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "parentParcelAcquisition",
                            "key": "parentParcelAcquisition",
                            "label": "Parent Parcel Acquisition",
                            "color": "#FFB237",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:ISS_PSP_PARENT_PARCEL",
                            "transparent": true,
                            "opacity": 0.8,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "section107Plan",
                            "key": "section107Plan",
                            "label": "S. 107 Plan",
                            "color": "#1818FF",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:ISS_PSP_SECTION_107_PLAN",
                            "transparent": true,
                            "opacity": 0.8,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "motiPlan",
                            "key": "motiPlan",
                            "label": "MoTI Plan",
                            "color": "#101010",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:ISS_PSP_MOTI_PLAN",
                            "transparent": true,
                            "opacity": 0.8,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "motiPlanFootprint",
                            "key": "motiPlanFootprint",
                            "label": "MoTI Plan Footprint",
                            "color": "#FF88DF",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:plan_footprint",
                            "transparent": true,
                            "opacity": 0.8,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        },
                        {
                            "id": "plans",
                            "key": "plans",
                            "label": "Plans",
                            "on": false,
                            "url": "ogs-internal/ows?",
                            "layers": "psp_dev:plans",
                            "transparent": true,
                            "opacity": 0.8,
                            "format": "image/png",
                            "authenticated": true,
                            "maxNativeZoom": 17,
                            "maxZoom": 20
                        }
                    ]
                }
            ],
            "propertiesUrl": "ogs-internal/ows?service=wfs&request=GetFeature&typeName=PIMS_PROPERTY_LOCATION_VW&outputformat=json&srsName=EPSG:4326&version=2.0.0&",
            "parcelMapFullyAttributed": {
                "url": "https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_FA_SVW/ows",
                "name": "pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_FA_SVW"
            },
            "bcAssessment": {
                "url": "https://delivery.apps.gov.bc.ca/ext/sgw/geo.bca",
                "names": {
                    "LEGAL_DESCRIPTION": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_LEGAL_DESCRIPTS_SV",
                    "ADDRESS": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_ADDRESSES_SV",
                    "FOLIO_DESCRIPTION": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_DESCRIPTIONS_SV",
                    "CHARGE": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_LAND_CHARS_SV",
                    "VALUE": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_GNRL_PROP_VALUES_SV",
                    "SALE": "geo.bca:WHSE_HUMAN_CULTURAL_ECONOMIC.BCA_FOLIO_SALES_SV"
                }
            }
        }

  # How the app will be deployed to the pod.
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Defines how to deploy ${APP_NAME}-${ROLE_NAME}"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
          labels:
            name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            app: ${APP_NAME}
            role: ${ROLE_NAME}
            env: ${ENV_NAME}
        spec:
          volumes:
            - name: "${APP_NAME}-${ROLE_NAME}-keycloak${INSTANCE}"
              configMap:
                name: ${APP_NAME}-${ROLE_NAME}-sso${INSTANCE}
                items:
                  - key: "${KEYCLOAK_CONFIG_FILE_NAME}"
                    path: "${KEYCLOAK_CONFIG_FILE_NAME}"
            - name: "${APP_NAME}-${ROLE_NAME}-tenant${INSTANCE}"
              configMap:
                name: ${APP_NAME}-${ROLE_NAME}-tenant${INSTANCE}
                items:
                  - key: "${TENANT_CONFIG_FILE_NAME}"
                    path: "${TENANT_CONFIG_FILE_NAME}"
          containers:
            - name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
              image: ""
              imagePullPolicy: Always
              ports:
                - containerPort: ${{APP_PORT}}
                  protocol: TCP
              env:
                - name: API_URL
                  value: ${API_URL}
                - name: API_SERVICE_NAME
                  value: ${API_SERVICE_NAME}
                - name: API_PATH
                  value: ${API_PATH}
                - name: RealIpFrom
                  value: ${REAL_IP_FROM}
                - name: TZ
                  value: ${TIME_ZONE}
                - name: GEOSERVER_URL
                  value: ${GEOSERVER_URL}
                - name: CSP
                  value: ${CSP}
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: "${APP_NAME}-${ROLE_NAME}-keycloak${INSTANCE}"
                  mountPath: "${CONFIG_MOUNT_PATH}${KEYCLOAK_CONFIG_FILE_NAME}"
                  subPath: "${KEYCLOAK_CONFIG_FILE_NAME}"
                - name: "${APP_NAME}-${ROLE_NAME}-tenant${INSTANCE}"
                  mountPath: "${CONFIG_MOUNT_PATH}/tenants/${TENANT_CONFIG_FILE_NAME}"
                  subPath: "${TENANT_CONFIG_FILE_NAME}"
              livenessProbe:
                httpGet:
                  path: "/nginx_status"
                  port: ${{APP_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/nginx_status"
                  port: ${{APP_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            from:
              kind: ImageStreamTag
              namespace: "${PROJECT_NAMESPACE}-tools"
              name: "${APP_NAME}-${ROLE_NAME}:${IMAGE_TAG}"
