PRINT N'Adding DB Audit Columns'

ALTER TABLE dbo.[PIMS_LEASE_LICENSE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_TENANT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_PAY_RVBL_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_SURPLUS_DECLARATION_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_CATEGORY_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()