PRINT N'Create history tables'
GO

CREATE TABLE [dbo].[ADS_SSDATA_1632946420752]  ( 
	[_LEASE_HIST_ID]                	bigint NOT NULL DEFAULT (NEXT VALUE FOR [PIMS_LEASE_H_ID_SEQ]),
	[APP_CREATE_TIMESTAMP]          	datetime NOT NULL,
	[APP_CREATE_USER_DIRECTORY]     	nvarchar(30) NOT NULL,
	[APP_CREATE_USER_GUID]          	uniqueidentifier NULL,
	[APP_CREATE_USERID]             	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_TIMESTAMP]     	datetime NOT NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY]	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_USER_GUID]     	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USERID]        	nvarchar(30) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL,
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL,
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL,
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL,
	[EFFECTIVE_DATE_HIST]           	datetime NOT NULL DEFAULT (getutcdate()),
	[END_DATE_HIST]                 	datetime NULL,
	[HAS_DIGITAL_FILE]              	bit NOT NULL,
	[HAS_DIGITAL_LICENSE]           	bit NOT NULL,
	[HAS_PHYSICAL_FILE]             	bit NOT NULL,
	[HAS_PHYSICAL_LICENSE]         	  bit NOT NULL,
	[INCLUDED_RENEWALS]             	smallint NULL,
	[INSPECTION_DATE]               	datetime NULL,
	[INSPECTION_NOTES]              	nvarchar(4000) NULL,
	[IS_EXPIRED]                    	bit NOT NULL,
	[IS_ORIG_EXPIRY_REQUIRED]       	bit NOT NULL,
	[L_FILE_NO]                     	nvarchar(50) NULL,
	[LEASE_AMOUNT]                  	money NULL,
	[LEASE_CATEGORY_TYPE_CODE]      	nvarchar(20) NOT NULL,
	[LEASE_DESCRIPTION]             	nvarchar(4000) NULL,
	[LEASE_ID]                      	bigint NOT NULL,
	[LEASE_LICENSE_TYPE_CODE]       	nvarchar(20) NOT NULL,
	[LEASE_NOTES]                   	nvarchar(4000) NULL,
	[LEASE_PAY_RVBL_TYPE_CODE]      	nvarchar(20) NOT NULL,
	[LEASE_PMT_FREQ_TYPE_CODE]      	nvarchar(20) NOT NULL,
	[LEASE_PROGRAM_TYPE_CODE]       	nvarchar(20) NOT NULL,
	[LEASE_PURPOSE_OTHER_DESC]      	nvarchar(200) NULL,
	[LEASE_PURPOSE_TYPE_CODE]       	nvarchar(20) NOT NULL,
	[MOTI_NAME_ID]                  	bigint NOT NULL,
	[ORIG_EXPIRY_DATE]              	datetime NULL,
	[ORIG_START_DATE]               	datetime NOT NULL,
	[PS_FILE_NO]                    	nvarchar(50) NULL,
	[RENEWAL_COUNT]                 	smallint NOT NULL,
	[RENEWAL_TERM_MONTHS]           	smallint NOT NULL,
	[TERM_EXPIRY_DATE]              	datetime NULL,
	[TERM_RENEWAL_DATE]             	datetime NULL,
	[TERM_START_DATE]               	datetime NULL,
	[TFA_FILE_NO]                   	int NULL,
	PRIMARY KEY CLUSTERED([_LEASE_HIST_ID])
 ON [PRIMARY])
GO
INSERT INTO [dbo].[ADS_SSDATA_1632946420752]([_LEASE_HIST_ID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [EFFECTIVE_DATE_HIST], [END_DATE_HIST], [HAS_DIGITAL_FILE], [HAS_DIGITAL_LICENSE], [HAS_PHYSICAL_FILE], [HAS_PHYSICAL_LICENSE], [INCLUDED_RENEWALS], [INSPECTION_DATE], [INSPECTION_NOTES], [IS_EXPIRED], [IS_ORIG_EXPIRY_REQUIRED], [L_FILE_NO], [LEASE_AMOUNT], [LEASE_CATEGORY_TYPE_CODE], [LEASE_DESCRIPTION], [LEASE_ID], [LEASE_LICENSE_TYPE_CODE], [LEASE_NOTES], [LEASE_PAY_RVBL_TYPE_CODE], [LEASE_PMT_FREQ_TYPE_CODE], [LEASE_PROGRAM_TYPE_CODE], [LEASE_PURPOSE_TYPE_CODE], [MOTI_NAME_ID], [ORIG_EXPIRY_DATE], [ORIG_START_DATE], [PS_FILE_NO], [RENEWAL_COUNT], [TERM_EXPIRY_DATE], [TERM_RENEWAL_DATE], [TERM_START_DATE], [TFA_FILE_NO]) 
	SELECT [_LEASE_HIST_ID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [EFFECTIVE_DATE_HIST], [END_DATE_HIST], [HAS_DIGITAL_FILE], [HAS_DIGITAL_LICENSE], [HAS_PHYSICAL_FILE], [HAS_PHYSICAL_LICENSE], [PROP_MGMT_ORG_ID], [INSPECTION_DATE], [INSPECTION_NOTES], [EXPIRED], [PROPERTY_MANAGER_ID], [L_FILE_NO], [LEASE_AMOUNT], SUBSTRING(LEASE_STATUS_TYPE_CODE,1,20), [UNIT], [LEASE_ID], [SECURITY_START_DATE], [LEASE_NOTES], [START_DATE], SUBSTRING(LEASE_PMT_FREQ_TYPE_CODE,1,20), SUBSTRING(LEASE_PROGRAM_TYPE_CODE,1,20), [LEASE_PURPOSE_TYPE_CODE], [TENANT_ID], [EXPIRY_DATE], [SECURITY_END_DATE], [PS_FILE_NO], [LEASE_PURPOSE_SUBTYPE_CODE], [INSURANCE_END_DATE], [INSURANCE_START_DATE], [RENEWAL_DATE], [TFA_FILE_NO] 
	FROM [dbo].[PIMS_LEASE_HIST]
GO
DROP TABLE [dbo].[PIMS_LEASE_HIST]
GO
EXEC dbo.sp_rename N'[dbo].[ADS_SSDATA_1632946420752]', N'PIMS_LEASE_HIST', [OBJECT]
GO