/* -----------------------------------------------------------------------------
Alter the data in the PIMS_LEASE_LICENSE_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2024-Jul-11  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the "OTHER" type
PRINT N'Update the "OTHER" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'OTHER'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Other'
       , IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'OTHER',  N'Other');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the "LIOCCUTIL" type
PRINT N'Update the "LIOCCUTIL" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIOCCUTIL'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION, IS_DISABLED)
    VALUES (N'LIOCCUTIL',  N'Licence of Occupation (BCTFA fee simple)', 1);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the "LIOCCUSE" type
PRINT N'Update the "LIOCCUSE" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIOCCUSE'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION, IS_DISABLED)
    VALUES (N'LIOCCUSE',  N'Licence of Occupation (BCTFA fee simple)', 1);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LIMOTIPRJ" type
PRINT N'Update the description for the "LIMOTIPRJ" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIMOTIPRJ'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "LTRINTENT" type
PRINT N'Update the description for the "LTRINTENT" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LTRINTENT'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'LTRINTENT',  N'Letter of Intended Use');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "LTRINDMNY" type
PRINT N'Update the description for the "LTRINDMNY" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LTRINDMNY'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'LTRINDMNY',  N'Indemnity letter');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "AMNDAGREE" type
PRINT N'Update the description for the "AMNDAGREE" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'AMNDAGREE'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'AMNDAGREE',  N'Amending Agreement');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Insert/Enable the "BLDGLSRCV" type
PRINT N'Update the description for the "BLDGLSRCV" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'BLDGLSRCV'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    IS_DISABLED                = 0
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'BLDGLSRCV',  N'Building Lease (receivable)');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LIOCCACCS" type
PRINT N'Update the description for the "LIOCCACCS" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIOCCACCS'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION, IS_DISABLED)
    VALUES (N'LIOCCACCS',  N'Licence of Occupation (BCTFA fee simple)', 1);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LIOCCTTLD" type
PRINT N'Update the description for the "LIOCCTTLD" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIOCCTTLD'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , IS_DISABLED                = 1
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION, IS_DISABLED)
    VALUES (N'LIOCCTTLD',  N'Licence of Occupation (BCTFA fee simple)', 1);
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LIOCCHMK" type
PRINT N'Update the description for the "LIOCCHMK" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LIOCCHMK'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (HMK fee simple)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'LIOCCHMK',  N'Licence of Occupation (HMK fee simple)');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LOOBCTFA" type
PRINT N'Update the description for the "LOOBCTFA" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LOOBCTFA'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Licence of Occupation (BCTFA fee simple)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
ELSE
  INSERT INTO PIMS_LEASE_LICENSE_TYPE (LEASE_LICENSE_TYPE_CODE, DESCRIPTION)
    VALUES (N'LOOBCTFA',  N'Licence of Occupation (BCTFA fee simple)');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LSGRND" type
PRINT N'Update the description for the "LSGRND" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LSGRND'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Land Lease (receivable)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LSREG" type
PRINT N'Update the description for the "LSREG" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LSREG'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Lease - Registered (payable)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "LSUNREG" type
PRINT N'Update the description for the "LSUNREG" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'LSUNREG'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Lease - Unregistered (payable)'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "MANUFHOME" type
PRINT N'Update the description for the "MANUFHOME" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'MANUFHOME'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Manufactured Home Tenancy'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "RESLNDTEN" type
PRINT N'Update the description for the "RESLNDTEN" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'RESLNDTEN'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Residential Tenancy Agreement'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the description for the "ROADXING" type
PRINT N'Update the description for the "ROADXING" type'
GO
DECLARE @CurrCd NVARCHAR(20)
SET     @CurrCd = N'ROADXING'

SELECT LEASE_LICENSE_TYPE_CODE
FROM   PIMS_LEASE_LICENSE_TYPE
WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;

IF @@ROWCOUNT = 1
  UPDATE PIMS_LEASE_LICENSE_TYPE
  SET    DESCRIPTION                = N'Crossing Agreement'
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  LEASE_LICENSE_TYPE_CODE = @CurrCd;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- --------------------------------------------------------------
-- Update the display order.
-- --------------------------------------------------------------
UPDATE tbl
SET    tbl.DISPLAY_ORDER              = seq.ROW_NUM
     , tbl.CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
FROM   PIMS_LEASE_LICENSE_TYPE tbl JOIN
       (SELECT LEASE_LICENSE_TYPE_CODE
             , ROW_NUMBER() OVER (ORDER BY DESCRIPTION) AS ROW_NUM
        FROM   PIMS_LEASE_LICENSE_TYPE) seq  ON seq.LEASE_LICENSE_TYPE_CODE = tbl.LEASE_LICENSE_TYPE_CODE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
