INSERT INTO [dbo].[PIMS_COMPENSATION_REQUISITION] ([ACQUISITION_FILE_ID], [CHART_OF_ACCOUNTS_ID], [RESPONSIBILITY_ID], [YEARLY_FINANCIAL_ID], [IS_DRAFT], [FISCAL_YEAR], [AGREEMENT_DT], [EXPROP_NOTICE_SERVED_DT], [EXPROP_VESTING_DT], [GENERATION_DT], [SPECIAL_INSTRUCTION], [DETAILED_REMARKS])
VALUES
  ( 1, NULL, NULL, NULL, CONVERT([bit],(0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ( 2, NULL, NULL, NULL, CONVERT([bit],(0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ( 3, NULL, NULL, NULL, CONVERT([bit],(0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ( 5, NULL, NULL, NULL, CONVERT([bit],(0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ( 7, NULL, NULL, NULL, CONVERT([bit],(1)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ( 9, NULL, NULL, NULL, CONVERT([bit],(1)), NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (11, NULL, NULL, NULL, CONVERT([bit],(1)), NULL, NULL, NULL, NULL, NULL, NULL, NULL);
GO
