DELETE 
FROM   PIMS_PRF_PROP_RESEARCH_PURPOSE_TYP;
GO

INSERT INTO [dbo].[PIMS_PRF_PROP_RESEARCH_PURPOSE_TYP] ([PROPERTY_RESEARCH_FILE_ID], [PROP_RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER])
  VALUES(1, N'ACQUIRE', 1)
GO
