/* -----------------------------------------------------------------------------
Migrate the data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY_HIST table from the 
temporary TMP_PROP_PROP_ACTIVITY_HIST table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-07  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROP_PROP_ACTIVITY_HIST_HIST data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY_HIST table
PRINT N'Migrate the TMP_PROP_PROP_ACTIVITY_HIST_HIST data to the PIMS_MANAGEMENT_ACTIVITY_PROPERTY_HIST table'
GO
INSERT INTO dbo.PIMS_MANAGEMENT_ACTIVITY_PROPERTY_HIST (_MANAGEMENT_ACTIVITY_PROPERTY_HIST_ID, EFFECTIVE_DATE_HIST, END_DATE_HIST, MANAGEMENT_ACTIVITY_PROPERTY_ID, PROPERTY_ID, PIMS_MANAGEMENT_ACTIVITY_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT _PROP_PROP_ACTIVITY_HIST_ID
       , EFFECTIVE_DATE_HIST
       , END_DATE_HIST
       , PROP_PROP_ACTIVITY_ID
       , PROPERTY_ID
       , PIMS_PROPERTY_ACTIVITY_ID
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROP_PROP_ACTIVITY_HIST
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop the temporary table
PRINT N'Drop the temporary table'
GO
DROP TABLE IF EXISTS dbo.TMP_PROP_PROP_ACTIVITY_HIST
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
