DELETE
FROM  PIMS_RESEARCH_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_RESEARCH_ACTIVITY_INSTANCE] ([ACTIVITY_INSTANCE_ID], [RESEARCH_FILE_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES((SELECT MAX(ACTIVITY_INSTANCE_ID) FROM PIMS_ACTIVITY_INSTANCE), (SELECT MAX(RESEARCH_FILE_ID) FROM PIMS_RESEARCH_FILE), 1)
GO
