global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
# Rules and alerts are read from the specified file(s)
rule_files:
  - alert-rules.yml
alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v1
      static_configs:
        - targets: []
scrape_configs:
  - job_name: psp_api
    honor_timestamps: true
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:5000
