DELETE
FROM  PIMS_ACTIVITY_INSTANCE_NOTE;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_INSTANCE_NOTE]([ACTIVITY_INSTANCE_ID], [NOTE_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES((SELECT MAX(ACTIVITY_INSTANCE_ID) FROM PIMS_ACTIVITY_INSTANCE), (SELECT MAX(NOTE_ID) FROM PIMS_NOTE), 1)
GO
