/* -----------------------------------------------------------------------------
Migrate the date columns to be removed from PIMS_COMPENSATION_REQUISITION to the
PIMS_EXPROPRIATION_NOTICE and PIMS_EXPROPRIATION_VESTING tables.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2024-Jan-24  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the EXPROP_NOTICE_SERVED_DT and INTEREST_HOLDER_ID from PIMS_COMPENSATION_REQUISITION
PRINT N'Migrate the EXPROP_NOTICE_SERVED_DT and INTEREST_HOLDER_ID from PIMS_COMPENSATION_REQUISITION'
GO
WITH CTE_Comp_Req_Date (ACQUISITION_FILE_ID, COMPENSATION_REQUISITION_ID, EXPROP_NOTICE_SERVED_DT, INTEREST_HOLDER_ID)
AS
 (SELECT req.ACQUISITION_FILE_ID
       , req.COMPENSATION_REQUISITION_ID
       , req.EXPROP_NOTICE_SERVED_DT
       , pay.INTEREST_HOLDER_ID
  FROM   PIMS_COMPENSATION_REQUISITION req LEFT JOIN
         PIMS_COMP_REQ_PAYEE           pay ON pay.COMPENSATION_REQUISITION_ID = req.COMPENSATION_REQUISITION_ID
  WHERE  req.EXPROP_NOTICE_SERVED_DT IS NOT NULL)

INSERT INTO PIMS_EXPROPRIATION_NOTICE (ACQUISITION_FILE_ID, COMPENSATION_REQUISITION_ID, EXPROP_NOTICE_SERVED_DT, INTEREST_HOLDER_ID)
  SELECT ACQUISITION_FILE_ID
       , COMPENSATION_REQUISITION_ID
       , EXPROP_NOTICE_SERVED_DT
       , INTEREST_HOLDER_ID
  FROM   CTE_Comp_Req_Date
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the EXPROP_VESTING_DT from PIMS_COMPENSATION_REQUISITION
PRINT N'Migrate the EXPROP_VESTING_DT from PIMS_COMPENSATION_REQUISITION'
GO
WITH CTE_Comp_Req_Date (ACQUISITION_FILE_ID, COMPENSATION_REQUISITION_ID, EXPROP_VESTING_DT)
AS
 (SELECT ACQUISITION_FILE_ID
       , COMPENSATION_REQUISITION_ID
       , EXPROP_VESTING_DT
  FROM   PIMS_COMPENSATION_REQUISITION
   WHERE EXPROP_VESTING_DT IS NOT NULL)

INSERT INTO PIMS_EXPROPRIATION_VESTING (ACQUISITION_FILE_ID, COMPENSATION_REQUISITION_ID, EXPROP_VESTING_DT)
  SELECT ACQUISITION_FILE_ID
       , COMPENSATION_REQUISITION_ID
       , EXPROP_VESTING_DT
  FROM   CTE_Comp_Req_Date
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
