import { MAP_MAX_NATIVE_ZOOM, MAP_MAX_ZOOM } from '@/constants/strings';

import { ILayerItem } from './types';

export const PIMS_PROPERTY_BOUNDARY_KEY = 'PIMS_PROPERTY_BOUNDARY_KEY';

export const layersTree: ILayerItem[] = [
  {
    key: 'PimsLayers',
    label: 'PIMS',
    on: false,
    nodes: [
      {
        key: 'research',
        label: 'Research',
        on: false,
        layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
        url: '/ogs-internal/ows?',
        styles: 'research_style',
        transparent: true,
        format: 'image/png',
        zIndex: 1000,
        zIndexAbsolute: true,
        id: 'pims_research_files',
        color: '#3388ff',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
        authenticated: true,
        cql_filter: 'HAS_ACTIVE_RESEARCH_FILE = 1',
      },
      {
        key: 'acquisition',
        label: 'Acquisition',
        on: false,
        layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
        url: '/ogs-internal/ows?',
        styles: 'acquisition_style',
        transparent: true,
        format: 'image/png',
        zIndex: 2000,
        zIndexAbsolute: true,
        id: 'pims_acquisition_files',
        color: '#42814A',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
        authenticated: true,
        cql_filter: 'HAS_ACTIVE_ACQUISITION_FILE = 1',
      },
      {
        key: 'management',
        label: 'Management',
        on: false,
        layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
        url: '/ogs-internal/ows?',
        styles: 'management_style',
        transparent: true,
        format: 'image/png',
        zIndex: 4000,
        zIndexAbsolute: true,
        id: 'pims_lease_files',
        color: '#FC802D',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
        authenticated: true,
        cql_filter: 'HAS_ACTIVE_MANAGEMENT_FILE = 1',
      },
      {
        key: 'disposition',
        label: 'Disposition',
        on: false,
        layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
        url: '/ogs-internal/ows?',
        styles: 'disposition_style',
        transparent: true,
        format: 'image/png',
        zIndex: 5000,
        zIndexAbsolute: true,
        id: 'pims_disposed_files',
        color: '#555555',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
        authenticated: true,
        cql_filter: 'HAS_ACTIVE_DISPOSITION_FILE = 1',
      },
      {
        key: 'LeaseLayers',
        label: 'Lease',
        on: false,
        nodes: [
          {
            key: 'lease_receivable',
            label: 'Lease (Receivable)',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'lease_receivable_style',
            transparent: true,
            format: 'image/png',
            zIndex: 3000,
            zIndexAbsolute: true,
            id: 'pims_lease_receivable',
            color: '#fee391',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'IS_RECEIVABLE_LEASE = 1',
          },
          {
            key: 'lease_payable',
            label: 'Lease (Payable)',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'lease_payable_style',
            transparent: true,
            format: 'image/png',
            zIndex: 3500,
            zIndexAbsolute: true,
            id: 'pims_lease_payable',
            color: '#fe9929',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'IS_PAYABLE_LEASE = 1',
          },
        ],
      },
      {
        key: 'InterestLayers',
        label: 'Interests',
        on: false,
        nodes: [
          {
            key: 'license_to_construct_take',
            label: 'Licence to Construct Take',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'license_to_construct_style',
            transparent: true,
            format: 'image/png',
            zIndex: 5000,
            zIndexAbsolute: true,
            id: 'license_to_construct_take',
            color: '#fa9fb5',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'HAS_LICENSE_TO_CONSTRUCT_TAKE = 1',
          },
          {
            key: 'land_act_take',
            label: 'Land Act Take',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'land_act_take_style',
            transparent: true,
            format: 'image/png',
            zIndex: 5100,
            zIndexAbsolute: true,
            id: 'land_act_take',
            color: '#f768a1',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'HAS_LAND_ACT_TAKE = 1',
          },
          {
            key: 'srw_take',
            label: 'SRW Take',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'srw_take_style',
            transparent: true,
            format: 'image/png',
            zIndex: 5200,
            zIndexAbsolute: true,
            id: 'srw_take',
            color: '#dd3497',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'HAS_SRW_TAKE = 1',
          },
          {
            key: 'surplus_take',
            label: 'Surplus Take',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'surplus_take_style',
            transparent: true,
            format: 'image/png',
            zIndex: 5300,
            zIndexAbsolute: true,
            id: 'surplus_take',
            color: '#ae017e',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'IS_SURPLUS = 1',
          },
          {
            key: 'inventory_take',
            label: 'Inventory Take',
            on: false,
            layers: 'psp:PIMS_PROPERTY_BOUNDARY_VW',
            url: '/ogs-internal/ows?',
            styles: 'inventory_take_style',
            transparent: true,
            format: 'image/png',
            zIndex: 5400,
            zIndexAbsolute: true,
            id: 'inventory_take',
            color: '#7a0177',
            maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
            maxZoom: MAP_MAX_ZOOM,
            authenticated: true,
            cql_filter: 'IS_ACQUIRED_FOR_INVENTORY = 1',
          },
        ],
      },
    ],
  },
  {
    key: 'Administrative Boundaries',
    label: 'Administrative Boundaries',
    on: false,
    nodes: [
      {
        key: 'currentEconomicRegions',
        label: 'Current Census Economic Regions',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW/ows?',
        layers: 'pub:WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW',
        transparent: true,
        format: 'image/png',
        zIndex: 0,
        id: 'currentEconomicRegions',
        color: '#bbdefb',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        // only works on the vpn
        key: 'moti',
        label: 'MOTI Regions (multiple colors)',
        on: false,
        url: 'https://maps.th.gov.bc.ca/geoV05/wms?',
        layers: 'hwy:DSA_REGION_BOUNDARY',
        styles: 'PSP_DSA_REGION_BOUNDARY',
        transparent: true,
        opacity: 0.9,
        format: 'image/png',
        zIndex: 21,
        id: 'moti',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        // only works on the vpn
        key: 'motiHighwayDistricts',
        label: 'MOTI Highway Districts (multiple colors)',
        on: false,
        url: 'https://maps.th.gov.bc.ca/geoV05/wms?',
        layers: 'hwy:DSA_DISTRICT_BOUNDARY',
        styles: 'PSP_DSA_DISTRICT_BOUNDARY',
        transparent: true,
        opacity: 0.9,
        format: 'image/png',
        zIndex: 22,
        id: 'motiHighwayDistricts',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'municipalities',
        label: 'Municipalities',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 20,
        id: 'municipalityLayer',
        color: '#b39ddb',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'regionalDistricts ',
        label: 'Regional Districts (multiple colors)',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 19,
        id: 'regionalDistricts',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    // The actual layers are populated via tenant.json configuration for each live environment
    key: 'legalHighwayResearch',
    label: 'Legal Highway Research',
    on: false,
    nodes: [
      {
        id: 'plans',
        key: 'plans',
        label: 'Plans',
        on: false,
        url: 'ogs-internal/ows?',
        layers: 'psp_dev:plans',
        transparent: true,
        opacity: 0.8,
        format: 'image/png',
        authenticated: true,
        maxNativeZoom: 17,
        maxZoom: 20,
      },
    ],
  },
  {
    key: 'firstNations',
    label: 'First Nations',
    on: false,
    nodes: [
      {
        key: 'firstNationsReserves',
        label: 'First Nations Reserves',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP/ows?',
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationsReserves',
        color: '#DCBDAD',
        opacity: 0.9,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyAreas',
        label: 'First Nation Treaty Areas',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyAreas',
        color: '#367428',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyLands',
        label: 'First Nations Treaty Lands (multiple colors)',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyLands',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatyRelatedLands',
        label: 'First Nations Treaty Related Lands (multiple colors)',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatyRelatedLands',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'firstNationTreatySideAgreement',
        label: 'First Nation Treaty Side Agreements',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP/ows?',
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP',
        transparent: true,
        format: 'image/png',
        zIndex: 10,
        id: 'firstNationTreatySideAgreement',
        color: '#DEA39F',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'landOwnership',
    label: 'Land Ownership',
    on: false,
    nodes: [
      {
        key: 'crownLeases',
        label: 'Crown Leases',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_LEASES_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LEASES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 7,
        id: 'crownLeases',
        color: '#36708D',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownInventory',
        label: 'Crown Inventory',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 6,
        id: 'crownInventory',
        color: '#D2A9FE',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownInclusions',
        label: 'Crown Inclusions (multiple colors)',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownInclusions',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownLandLicenses',
        label: 'Crown Land Licenses',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_LICENSES_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LICENSES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownLandLicenses',
        color: '#2C519B',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'crownTenures',
        label: 'Crown Tenures',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_CROWN_TENURES_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_TENURES_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 5,
        id: 'crownTenures',
        color: '#FC802D',
        styles: 2216,
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'parcelBoundaries',
        label: 'Parcel Boundaries',
        on: true,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
        layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
        transparent: true,
        format: 'image/png',
        zIndex: 18,
        id: 'parcelLayer',
        color: '#E9AD34',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'srwInterestParcels',
        label: 'Interest Parcels - SRW',
        on: false,
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
        layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
        transparent: true,
        format: 'image/png',
        zIndex: 20,
        id: 'srwInterestParcels',
        color: '#E6270A',
        styles: 8984,
        cql_filter: "PARCEL_CLASS = 'Interest'",
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'PMBC_BCTFA_PARCEL_POLYGON_FABRIC_KEY',
        label: 'BCTFA Ownership',
        on: true,
        layers: 'psp:PMBC_BCTFA_PARCEL_POLYGON_FABRIC',
        url: '/ogs-internal/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4000,
        zIndexAbsolute: true,
        id: 'bctfa_property',
        color: '#42814A',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
        authenticated: true,
      },
    ],
  },
  {
    key: 'zoning',
    label: 'Zoning',
    on: false,
    nodes: [
      {
        key: 'agriculturalLandReserve',
        label: 'Agricultural Land Reserve',
        on: false,
        layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_POLYS',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_POLYS/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'agriculturalLandReserve',
        opacity: 1,
        color: '#BBD99E',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'electoral',
    label: 'Electoral',
    on: false,
    nodes: [
      {
        key: 'currentElectoralDistricts',
        label: 'Current Provincial Electoral Districts of British Columbia',
        on: false,
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'currentElectoralDistricts',
        color: '#da2223',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
  {
    key: 'federal_bc_parks',
    label: 'Federal/BC Parks',
    on: false,
    nodes: [
      {
        key: 'federalParks',
        label: 'Federal Parks',
        on: false,
        layers: 'pub:WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'federalParks',
        color: '#AEF51F',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
      {
        key: 'bcParks',
        label: 'BC Parks',
        on: false,
        layers: 'pub:WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW',
        url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW/ows?',
        transparent: true,
        format: 'image/png',
        zIndex: 4,
        id: 'bcParks',
        color: '#AAD589',
        maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
        maxZoom: MAP_MAX_ZOOM,
      },
    ],
  },
];
