import { MAP_MAX_NATIVE_ZOOM, MAP_MAX_ZOOM, PIMS_PROPERTY_BOUNDARY_KEY } from '@/constants/strings';

import { LayerDefinition } from './types';

export const layerDefinitions: LayerDefinition[] = [
  {
    layerIdentifier: 'pims_research_files',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_RESEARCH_VW',
    url: '/ogs-internal/ows?',
    styles: 'research_style',
    transparent: true,
    format: 'image/png',
    zIndex: 1000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
  },
  {
    layerIdentifier: 'pims_acquisition_files',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_ACQUISITION_VW',
    url: '/ogs-internal/ows?',
    styles: 'acquisition_style',
    transparent: true,
    format: 'image/png',
    zIndex: 2000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
  },
  {
    layerIdentifier: 'pims_management_files',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_MANAGEMENT_VW',
    url: '/ogs-internal/ows?',
    styles: 'management_style',
    transparent: true,
    format: 'image/png',
    zIndex: 4000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
  },
  {
    layerIdentifier: 'pims_disposed_files',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_DISPOSITION_VW',
    url: '/ogs-internal/ows?',
    styles: 'disposition_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
  },
  {
    layerIdentifier: 'pims_lease_receivable',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_LEASE_VW',
    url: '/ogs-internal/ows?',
    styles: 'lease_receivable_style',
    transparent: true,
    format: 'image/png',
    zIndex: 3000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'HAS_RECEIVABLE_LEASE = 1',
  },
  {
    layerIdentifier: 'pims_lease_payable',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_LEASE_VW',
    url: '/ogs-internal/ows?',
    styles: 'lease_payable_style',
    transparent: true,
    format: 'image/png',
    zIndex: 3500,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'HAS_PAYABLE_LEASE = 1',
  },
  {
    layerIdentifier: 'pims_license_to_construct_take',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_INTEREST_VW',
    url: '/ogs-internal/ows?',
    styles: 'license_to_construct_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'IS_NEW_LICENSE_TO_CONSTRUCT = 1',
  },
  {
    layerIdentifier: 'pims_land_act_take',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_INTEREST_VW',
    url: '/ogs-internal/ows?',
    styles: 'land_act_take_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5100,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'IS_NEW_LAND_ACT = 1',
  },
  {
    layerIdentifier: 'pims_srw_take',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_INTEREST_VW',
    url: '/ogs-internal/ows?',
    styles: 'srw_take_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5200,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'IS_NEW_INTEREST_IN_SRW = 1',
  },
  {
    layerIdentifier: 'pims_surplus_take',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_INTEREST_VW',
    url: '/ogs-internal/ows?',
    styles: 'surplus_take_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5300,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'IS_THERE_SURPLUS = 1',
  },
  {
    layerIdentifier: 'pims_inventory_take',
    layers: 'psp:PIMS_PROPERTY_BOUNDARY_INTEREST_VW',
    url: '/ogs-internal/ows?',
    styles: 'inventory_take_style',
    transparent: true,
    format: 'image/png',
    zIndex: 5400,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
    cql_filter: 'IS_ACQUIRED_FOR_INVENTORY = 1',
  },
  {
    layerIdentifier: 'currentEconomicRegions',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW/ows?',
    layers: 'pub:WHSE_HUMAN_CULTURAL_ECONOMIC.CEN_ECONOMIC_REGIONS_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 0,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    // only works on the vpn
    layerIdentifier: 'moti',
    url: 'https://maps.th.gov.bc.ca/geoV05/wms?',
    layers: 'hwy:DSA_REGION_BOUNDARY',
    styles: 'PSP_DSA_REGION_BOUNDARY',
    transparent: true,
    opacity: 0.9,
    format: 'image/png',
    zIndex: 21,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    // only works on the vpn
    layerIdentifier: 'motiHighwayDistricts',
    url: 'https://maps.th.gov.bc.ca/geoV05/wms?',
    layers: 'hwy:DSA_DISTRICT_BOUNDARY',
    styles: 'PSP_DSA_DISTRICT_BOUNDARY',
    transparent: true,
    opacity: 0.9,
    format: 'image/png',
    zIndex: 22,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'municipalityLayer',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 20,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'regionalDistricts',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 19,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    // The actual layers are populated via tenant.json configuration for each live environment
    layerIdentifier: 'plans',
    url: 'ogs-internal/ows?',
    layers: 'psp_dev:plans',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'firstNationsReserves',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP/ows?',
    layers: 'pub:WHSE_ADMIN_BOUNDARIES.ADM_INDIAN_RESERVES_BANDS_SP',
    transparent: true,
    format: 'image/png',
    zIndex: 10,
    opacity: 0.9,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'firstNationTreatyAreas',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP/ows?',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_AREA_SP',
    transparent: true,
    format: 'image/png',
    zIndex: 10,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'firstNationTreatyLands',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP/ows?',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP',
    transparent: true,
    format: 'image/png',
    zIndex: 10,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'firstNationTreatyRelatedLands',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP/ows?',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_RELATED_LAND_SP',
    transparent: true,
    format: 'image/png',
    zIndex: 10,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'firstNationTreatySideAgreement',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP/ows?',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_SIDE_AGREEMENTS_SP',
    transparent: true,
    format: 'image/png',
    zIndex: 10,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownLeases',
    layers: 'pub:WHSE_TANTALIS.TA_CROWN_LEASES_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LEASES_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 7,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownInventory',
    layers: 'pub:WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INVENTORY_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 6,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownInclusions',
    layers: 'pub:WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_INCLUSIONS_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 5,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownLandLicenses',
    layers: 'pub:WHSE_TANTALIS.TA_CROWN_LICENSES_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_LICENSES_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 5,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownTenures',
    layers: 'pub:WHSE_TANTALIS.TA_CROWN_TENURES_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_CROWN_TENURES_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 5,
    styles: '2216',
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'parcelLayer',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
    layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 18,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'srwInterestParcels',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
    layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 20,
    styles: '8984',
    cql_filter: "PARCEL_CLASS = 'Interest'",
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'pmbc_parcel_pid',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
    layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 9999,
    styles: '7834',
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'pmbc_parcel_by_class',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
    layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 21,
    styles: '7943',
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    legendUrl:
      'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=pub%3AWHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW&style=7943',
  },
  {
    layerIdentifier: 'pmbc_parcel_by_owner',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?',
    layers: 'pub:WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW',
    transparent: true,
    format: 'image/png',
    zIndex: 20,
    styles: '6616',
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    legendUrl:
      'https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=pub%3AWHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW&style=6616',
  },
  {
    layerIdentifier: 'bctfa_property',
    layers: 'psp:PMBC_BCTFA_PARCEL_POLYGON_FABRIC',
    url: '/ogs-internal/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 4000,
    zIndexAbsolute: true,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
    authenticated: true,
  },
  {
    layerIdentifier: 'agriculturalLandReserve',
    layers: 'pub:WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_POLYS',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_POLYS/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 4,
    opacity: 1,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'currentElectoralDistricts',
    layers: 'pub:WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.EBC_PROV_ELECTORAL_DIST_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 4,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'federalParks',
    layers: 'pub:WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 4,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'bcParks',
    layers: 'pub:WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 4,
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'crownSurveyParcels',
    layers: 'pub:WHSE_TANTALIS.TA_SURVEY_PARCELS_SVW',
    url: 'https://openmaps.gov.bc.ca/geo/pub/WHSE_TANTALIS.TA_SURVEY_PARCELS_SVW/ows?',
    transparent: true,
    format: 'image/png',
    zIndex: 5,
    id: 'crownSurveyPlans',
    maxNativeZoom: MAP_MAX_NATIVE_ZOOM,
    maxZoom: MAP_MAX_ZOOM,
  },
  {
    layerIdentifier: 'gazettedHighway',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.9,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'closedHighway',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.9,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'parentParcelAcquisition',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'section107Plan',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'motiPlan',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'motiPlanFootprint',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
  {
    layerIdentifier: 'plans',
    url: 'ogs-internal/ows?',
    transparent: true,
    opacity: 0.8,
    format: 'image/png',
    authenticated: true,
    maxNativeZoom: 17,
    maxZoom: 20,
  },
];

export const pimsBoundaryLayers = new Set(
  layerDefinitions.filter(x => x.layers?.includes(PIMS_PROPERTY_BOUNDARY_KEY)),
);
