DELETE
FROM   PIMS_DISPOSITION_FILE
GO

DECLARE @i INT = 0
WHILE @i < 10
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DISPOSITION_FILE (DISPOSITION_STATUS_TYPE_CODE, DISPOSITION_FILE_STATUS_TYPE_CODE, DISPOSITION_TYPE_CODE, DISPOSITION_FUNDING_TYPE_CODE, DISPOSITION_INITIATING_DOC_TYPE_CODE, DSP_PHYS_FILE_STATUS_TYPE_CODE, DSP_INITIATING_BRANCH_TYPE_CODE, REGION_CODE, FILE_NUMBER, FILE_NAME, FILE_REFERENCE, ASSIGNED_DT, COMPLETED_DT, INITIATING_DOCUMENT_DT, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES
      ((SELECT TOP 1 DISPOSITION_STATUS_TYPE_CODE         FROM PIMS_DISPOSITION_STATUS_TYPE ORDER BY NEWID()),          -- DISPOSITION_STATUS_TYPE_CODE
       (SELECT TOP 1 DISPOSITION_FILE_STATUS_TYPE_CODE    FROM PIMS_DISPOSITION_FILE_STATUS_TYPE ORDER BY NEWID()),     -- DISPOSITION_FILE_STATUS_TYPE_CODE
       (SELECT TOP 1 DISPOSITION_TYPE_CODE                FROM PIMS_DISPOSITION_TYPE ORDER BY NEWID()),                 -- DISPOSITION_TYPE_CODE
       (SELECT TOP 1 DISPOSITION_FUNDING_TYPE_CODE        FROM PIMS_DISPOSITION_FUNDING_TYPE ORDER BY NEWID()),         -- DISPOSITION_FUNDING_TYPE_CODE
       (SELECT TOP 1 DISPOSITION_INITIATING_DOC_TYPE_CODE FROM PIMS_DISPOSITION_INITIATING_DOC_TYPE ORDER BY NEWID()),  -- DISPOSITION_INITIATING_DOC_TYPE_CODE
       (SELECT TOP 1 DSP_PHYS_FILE_STATUS_TYPE_CODE       FROM PIMS_DSP_PHYS_FILE_STATUS_TYPE ORDER BY NEWID()),        -- DSP_PHYS_FILE_STATUS_TYPE_CODE
       (SELECT TOP 1 DSP_INITIATING_BRANCH_TYPE_CODE      FROM PIMS_DSP_INITIATING_BRANCH_TYPE ORDER BY NEWID()),       -- DSP_INITIATING_BRANCH_TYPE_CODE
       (SELECT TOP 1 REGION_CODE                          FROM PIMS_REGION ORDER BY NEWID()),                           -- REGION_CODE
       (SELECT N'FILE_NUMBER '      + LEFT(NEWID(),7)),                                                                 -- FILE_NUMBER
       (SELECT N'FILE_NAME '        + LEFT(NEWID(),7) + ' ' + LEFT(NEWID(),7)),                                         -- FILE_NAME
       (SELECT N'FILE_REFERENCE '   + LEFT(NEWID(),7) + ' ' + LEFT(NEWID(),7)),                                         -- FILE_REFERENCE
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                      -- ASSIGNED_DT
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                      -- COMPLETED_DT
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                      -- INITIATING_DOCUMENT_DT
       1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');            -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO
