DELETE
FROM   PIMS_DISPOSITION_FILE_DOCUMENT
GO

DECLARE @i INT = 0
WHILE @i < 1
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DISPOSITION_FILE_DOCUMENT (DOCUMENT_ID, DISPOSITION_FILE_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES
      ((SELECT TOP 1 DOCUMENT_ID         FROM PIMS_DOCUMENT         ORDER BY NEWID()),                        -- DOCUMENT_ID
       (SELECT TOP 1 DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE ORDER BY NEWID()),                        -- DISPOSITION_FILE_ID
       1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');  -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO
