DELETE
FROM   PIMS_DSP_PURCH_SOLICITOR
GO

DECLARE @i INT = 0
WHILE @i < 10
  BEGIN
  SET @i = @i + 1  
  INSERT INTO PIMS_DSP_PURCH_SOLICITOR (DISPOSITION_SALE_ID, PERSON_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
    VALUES (
      (SELECT TOP 1 DISPOSITION_SALE_ID FROM PIMS_DISPOSITION_SALE ORDER BY NEWID()),                        -- DISPOSITION_SALE_ID
      (SELECT TOP 1 PERSON_ID           FROM PIMS_PERSON           ORDER BY NEWID()),                        -- PERSON_ID
      1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');  -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO

DECLARE @i INT = 0
WHILE @i < 10
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DSP_PURCH_SOLICITOR (DISPOSITION_SALE_ID, ORGANIZATION_ID, PRIMARY_CONTACT_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES (
      (SELECT TOP 1 DISPOSITION_SALE_ID FROM PIMS_DISPOSITION_SALE ORDER BY NEWID()),                        -- DISPOSITION_SALE_ID
      (SELECT TOP 1 ORGANIZATION_ID     FROM PIMS_ORGANIZATION     ORDER BY NEWID()),                        -- ORGANIZATION_ID
      (SELECT TOP 1 PERSON_ID           FROM PIMS_PERSON           ORDER BY NEWID()),                        -- PRIMARY_CONTACT_ID
      1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');  -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO
