DELETE
FROM   PIMS_DISPOSITION_CHECKLIST_ITEM
GO

DECLARE @i INT = 0
WHILE @i < 10
  BEGIN
  SET @i = @i + 1  
  INSERT INTO PIMS_DISPOSITION_CHECKLIST_ITEM (DISPOSITION_FILE_ID, DSP_CHKLST_ITEM_TYPE_CODE, DSP_CHKLST_ITEM_STATUS_TYPE_CODE, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
    VALUES (
      (SELECT TOP 1 DISPOSITION_FILE_ID              FROM PIMS_DISPOSITION_FILE            ORDER BY NEWID()), -- DISPOSITION_FILE_ID
      (SELECT TOP 1 DSP_CHKLST_ITEM_TYPE_CODE        FROM PIMS_DSP_CHKLST_ITEM_TYPE        ORDER BY NEWID()), -- DSP_CHKLST_ITEM_TYPE_CODE
      (SELECT TOP 1 DSP_CHKLST_ITEM_STATUS_TYPE_CODE FROM PIMS_DSP_CHKLST_ITEM_STATUS_TYPE ORDER BY NEWID()), -- DSP_CHKLST_ITEM_STATUS_TYPE_CODE
      1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');   -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO