
/* INSERTS */
INSERT INTO [PIMS_TST].[dbo].[PIMS_LEASE_TENANT]
    (LEASE_ID, ORGANIZATION_ID, LESSOR_TYPE_CODE, CONCURRENCY_CONTROL_NUMBER)
VALUES
    (45, 48529, 'ORG', 1)
INSERT INTO PIMS_CONTACT_METHOD
    (CONCURRENCY_CONTROL_NUMBER, CONTACT_METHOD_TYPE_CODE, PERSON_ID, CONTACT_METHOD_VALUE)
VALUES
    (1, 'WORKMOBIL', 12566, '1111111111')
INSERT INTO PIMS_CONTACT_METHOD
    (CONCURRENCY_CONTROL_NUMBER, CONTACT_METHOD_TYPE_CODE, PERSON_ID, CONTACT_METHOD_VALUE)
VALUES
    (1, 'WORKPHONE', 12566, '2222222222')
INSERT INTO PIMS_CONTACT_METHOD
    (CONCURRENCY_CONTROL_NUMBER, CONTACT_METHOD_TYPE_CODE, PERSON_ID, CONTACT_METHOD_VALUE)
VALUES
    (1, 'PERSMOBIL', 12566, '3333333333')
INSERT INTO PIMS_PERSON_ORGANIZATION
    (PERSON_ID, ORGANIZATION_ID, CONCURRENCY_CONTROL_NUMBER)
VALUES
    (50216, 48529, 1)
INSERT INTO PIMS_PERSON_ORGANIZATION
    (PERSON_ID, ORGANIZATION_ID, CONCURRENCY_CONTROL_NUMBER)
VALUES
    (15, 48529, 1)


/*UPDATES*/
UPDATE PIMS_PERSON SET ADDRESS_ID = 450, CONCURRENCY_CONTROL_NUMBER = 2 where PERSON_ID = 12566
UPDATE PIMS_ADDRESS SET POSTAL_CODE = 'V6Z 5G7', CONCURRENCY_CONTROL_NUMBER = 2 where ADDRESS_ID = 450
UPDATE [PIMS_TST].[dbo].[PIMS_LEASE_TENANT] SET [NOTE] = 'This are notes for the organization record', [CONCURRENCY_CONTROL_NUMBER] = 2 where [LEASE_TENANT_ID] = 297

/*DELETES*/
DELETE FROM PIMS_PERSON_ORGANIZATION WHERE PERSON_ORGANIZATION_ID = 138
