DROP SEQUENCE [dbo].[PIMS_INSURANCE_ID_SEQ]

DROP SEQUENCE [dbo].[PIMS_INSURANCE_H_ID_SEQ]

DROP SEQUENCE [dbo].[PIMS_SECURITY_DEPOSIT_ID_SEQ]

DROP SEQUENCE [dbo].[PIMS_SECURITY_DEPOSIT_H_ID_SEQ]

DROP SEQUENCE [dbo].[PIMS_SECURITY_DEPOSIT_RETURN_ID_SEQ]

DROP SEQUENCE [dbo].[PIMS_SECURITY_DEPOSIT_RETURN_H_ID_SEQ]