/* -----------------------------------------------------------------------------
Set the sequence values for the sequences based on the current maximum value of 
the primary key.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-25  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACT_INVOLVED_PARTY_H_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACT_INVOLVED_PARTY_H_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(_MGMT_ACT_INVOLVED_PARTY_HIST_ID) + 1
FROM   dbo.PIMS_MGMT_ACT_INVOLVED_PARTY_HIST;

SET @qry = 'ALTER SEQUENCE PIMS_MGMT_ACT_INVOLVED_PARTY_H_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACT_MIN_CONTACT_H_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACT_MIN_CONTACT_H_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(_MGMT_ACT_MIN_CONTACT_HIST_ID) + 1
FROM   dbo.PIMS_MGMT_ACT_MIN_CONTACT_HIST;

SET @qry = 'ALTER SEQUENCE PIMS_MGMT_ACT_MIN_CONTACT_H_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_H_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_H_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(_MGMT_ACTIVITY_ACTIVITY_SUBTYP_HIST_ID) + 1
FROM   dbo.PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_HIST;

SET @qry = 'ALTER SEQUENCE PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_H_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACTIVITY_DOCUMENT_H_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACTIVITY_DOCUMENT_H_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(_MGMT_ACTIVITY_DOCUMENT_HIST_ID) + 1
FROM   dbo.PIMS_MGMT_ACTIVITY_DOCUMENT_HIST;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MGMT_ACTIVITY_DOCUMENT_H_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MANAGEMENT_ACTIVITY_INVOICE_H_ID_SEQ sequence.
PRINT N'Reset the PIMS_MANAGEMENT_ACTIVITY_INVOICE_H_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(_MANAGEMENT_ACTIVITY_INVOICE_HIST_ID) + 1
FROM   dbo.PIMS_MANAGEMENT_ACTIVITY_INVOICE_HIST;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MANAGEMENT_ACTIVITY_INVOICE_H_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACT_INVOLVED_PARTY_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACT_INVOLVED_PARTY_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(MGMT_ACT_INVOLVED_PARTY_ID) + 1
FROM   dbo.PIMS_MGMT_ACT_INVOLVED_PARTY;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MGMT_ACT_INVOLVED_PARTY_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACT_MIN_CONTACT_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACT_MIN_CONTACT_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(MGMT_ACT_MIN_CONTACT_ID) + 1
FROM   dbo.PIMS_MGMT_ACT_MIN_CONTACT;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MGMT_ACT_MIN_CONTACT_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(MGMT_ACTIVITY_ACTIVITY_SUBTYP_ID) + 1
FROM   dbo.PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MGMT_ACTIVITY_DOCUMENT_ID_SEQ sequence.
PRINT N'Reset the PIMS_MGMT_ACTIVITY_DOCUMENT_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(MGMT_ACTIVITY_DOCUMENT_ID) + 1
FROM   dbo.PIMS_MGMT_ACTIVITY_DOCUMENT;

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MGMT_ACTIVITY_DOCUMENT_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Reset the PIMS_MANAGEMENT_ACTIVITY_INVOICE_ID_SEQ sequence.
PRINT N'Reset the PIMS_MANAGEMENT_ACTIVITY_INVOICE_ID_SEQ sequence.'
GO
DECLARE @CurrVlu BIGINT
      , @qry     NVARCHAR(500);

SELECT @CurrVlu = MAX(MANAGEMENT_ACTIVITY_INVOICE_ID) + 1
FROM   dbo.PIMS_MANAGEMENT_ACTIVITY_INVOICE

SET @qry = 'ALTER SEQUENCE dbo.PIMS_MANAGEMENT_ACTIVITY_INVOICE_ID_SEQ RESTART WITH ' + CONVERT(NVARCHAR, @CurrVlu);
EXEC sp_executesql @qry;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) 
  PRINT 'The database update succeeded'
ELSE 
  BEGIN
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'The database update failed'
  END
GO
