SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop view dbo.PIMS_CONTACT_VW
PRINT N'Drop view dbo.PIMS_CONTACT_VW'
GO
DROP VIEW IF EXISTS [dbo].[PIMS_CONTACT_VW]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

PRINT N'Create view dbo.PIMS_CONTACT_VW'
GO
CREATE VIEW [dbo].[PIMS_CONTACT_VW] AS
SELECT CONCAT('P', PERSON_ID) AS ID, PERSON_ID, NULL AS ORGANIZATION_ID, p.IS_DISABLED, TRIM(CONCAT_WS(' ',FIRST_NAME, MIDDLE_NAMES, SURNAME)) AS SUMMARY, SURNAME, FIRST_NAME, MIDDLE_NAMES, NULL AS ORGANIZATION_NAME, p.ADDRESS_ID, a.STREET_ADDRESS_1 as MAILING_ADDRESS, a.MUNICIPALITY_NAME, ps.DESCRIPTION AS PROVINCE_STATE FROM PIMS_PERSON p
	LEFT JOIN PIMS_ADDRESS a on a.ADDRESS_ID = p.ADDRESS_ID
	LEFT JOIN PIMS_PROVINCE_STATE ps on ps.PROVINCE_STATE_ID = a.PROVINCE_STATE_ID
	UNION
SELECT CONCAT('O',ORGANIZATION_ID) AS ID, NULL AS PERSON_ID, ORGANIZATION_ID, o.IS_DISABLED, ORGANIZATION_NAME AS SUMMARY, NULL AS SURNAME, NULL AS FIRST_NAME, NULL AS MIDDLE_NAMES, ORGANIZATION_NAME, o.ADDRESS_ID, a.STREET_ADDRESS_1 as MAILING_ADDRESS, a.MUNICIPALITY_NAME, ps.DESCRIPTION AS PROVINCE_STATE FROM PIMS_ORGANIZATION o
	LEFT JOIN PIMS_ADDRESS a on a.ADDRESS_ID = o.ADDRESS_ID
	LEFT JOIN PIMS_PROVINCE_STATE ps on ps.PROVINCE_STATE_ID = a.PROVINCE_STATE_ID
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO