//projects
export enum ProjectActions {
  GET_PROJECT_WORKFLOW = 'GET_PROJECT_WORKFLOW',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  UPDATE_WORKFLOW_STATUS = 'UPDATE_WORKFLOW_STATUS',
  ADD_PROJECT = 'ADD_PROJECT',
  GET_PROJECT = 'GET_PROJECT',
  GET_PROJECT_TASKS = 'GET_PROJECT_TASKS',
  GET_PROJECT_STATUSES = 'GET_PROJECT_STATUSES',
}
