ALTER TABLE "dbo"."PIMS_LEASE_TENANT"
	ADD CONSTRAINT "PIM_LSSRTY_PIM_TENANT_FK"
	FOREIGN KEY("LESSOR_TYPE_CODE")
	REFERENCES "dbo"."PIMS_LESSOR_TYPE"("LESSOR_TYPE_CODE")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO