<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>requesterDataDiv</name>
   <tag></tag>
   <elementGuidId>fb5a2f32-c0cf-4d85-ad5f-f461aa227b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/label[contains(text(),'Requester')]/ancestor::div[1]/following-sibling::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
