<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>researchPurposeAcquisitionOption</name>
   <tag></tag>
   <elementGuidId>5618cefb-81cd-408f-8783-4e2951a2cf93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='purpose-selector']/div[2]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a3e2de78-f359-40ea-be2e-ebb95bc8a8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option  highlightOption highlight  </value>
      <webElementGuid>07fbb091-0b06-473e-a728-d1b8bb2aed66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acquisition</value>
      <webElementGuid>ace8a1fa-3f88-49e2-9fb3-a253201a56c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purpose-selector&quot;)/div[@class=&quot;optionListContainer displayBlock&quot;]/ul[@class=&quot;optionContainer&quot;]/li[@class=&quot;option  highlightOption highlight&quot;]</value>
      <webElementGuid>4ff6a0ee-9e99-4005-872e-b5e061a73f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>242e3007-2967-4f4f-832c-e8d64e9925d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option  highlightOption highlight  </value>
      <webElementGuid>6c98758e-a288-45a1-9122-f3ac79a908b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acquisition</value>
      <webElementGuid>7b5ace4c-edf1-48b9-86c7-396721d4f94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purpose-selector&quot;)/div[@class=&quot;optionListContainer displayBlock&quot;]/ul[@class=&quot;optionContainer&quot;]/li[@class=&quot;option  highlightOption highlight&quot;]</value>
      <webElementGuid>11899229-ecdc-4fcd-af03-35b94ff9d0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5d9eeb82-3340-46e0-a08a-3a6612f1bf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option  highlightOption highlight  </value>
      <webElementGuid>4464563f-f87c-4c1d-9cce-7ebc829ae92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acquisition</value>
      <webElementGuid>a897e7ce-0f0e-4770-8ecf-d10d97c744c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purpose-selector&quot;)/div[@class=&quot;optionListContainer displayBlock&quot;]/ul[@class=&quot;optionContainer&quot;]/li[@class=&quot;option  highlightOption highlight&quot;]</value>
      <webElementGuid>0c3a8e0d-e8f0-4039-bf7f-11f23c610231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2b84bfb7-a450-4e43-9baa-746d33524341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option  highlightOption highlight  </value>
      <webElementGuid>38b4ff3c-fa46-47fa-88f6-cd178118cc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acquisition</value>
      <webElementGuid>7e33c9d4-bfd1-45f7-be0e-143499c82905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purpose-selector&quot;)/div[@class=&quot;optionListContainer displayBlock&quot;]/ul[@class=&quot;optionContainer&quot;]/li[@class=&quot;option  highlightOption highlight&quot;]</value>
      <webElementGuid>7eeab33a-d5b5-401b-8f4d-7b4aa838168a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='purpose-selector']/div[2]/ul/li</value>
      <webElementGuid>f3abb346-9c06-4a5c-9831-3bad84128e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research purpose:'])[1]/following::li[1]</value>
      <webElementGuid>53165817-9c59-4f6d-bae0-4b9305b064c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Request'])[1]/following::li[1]</value>
      <webElementGuid>b174d1f0-a037-4ed9-ae00-d3d3ed0567fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposition'])[2]/preceding::li[1]</value>
      <webElementGuid>4854eff8-a7de-455a-bc71-8087b657a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Enquiry'])[1]/preceding::li[2]</value>
      <webElementGuid>5956bd91-f7e8-4746-b9ed-17c5d3499074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>84f25945-5374-4419-b736-bafa7a529b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Acquisition' or . = 'Acquisition')]</value>
      <webElementGuid>12f7545b-b797-45c1-a0b0-75533962797e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
