<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>researchCompletionDateInput</name>
   <tag></tag>
   <elementGuidId>bc6fa0e0-eb0a-4381-9be3-04cd0beb6e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-researchCompletionDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepicker-researchCompletionDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72579b6f-5113-4a58-b1d4-d8e7950ad6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83ac9e7e-bf83-45d1-83ff-49d275741996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-researchCompletionDate</value>
      <webElementGuid>e9d6423a-1f81-4a32-b044-c6bd5a6fe95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchCompletionDate</value>
      <webElementGuid>a4278532-d2c7-44e2-92ca-eed8b64cc985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--/--/----</value>
      <webElementGuid>f83af15b-0de3-4689-9c61-c65a3cf8727b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>312435e9-f4cd-49a2-b876-8aa0b3c7c843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfLBT dqWpFE form-control date-picker react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>9a8f2ac5-09dd-4b78-b221-32647ebd60e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-researchCompletionDate&quot;)</value>
      <webElementGuid>8fde7836-154b-4c9e-acb6-a4c2c4cceb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e532226-e895-4fac-a9af-801ac02fd71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f420ee2-bce5-41d8-a552-6c5b4147fd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-researchCompletionDate</value>
      <webElementGuid>fd4cc202-8774-457a-bc67-54e06f716a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchCompletionDate</value>
      <webElementGuid>d568b01d-e9a5-49c1-84ba-ccfea3833ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--/--/----</value>
      <webElementGuid>ce2b6d23-ca28-4b2b-919f-c6ce38d2536c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d57a42c-d01b-4e4c-9216-70020a904414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfLBT dqWpFE form-control date-picker react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>40c87093-fc19-4121-9f22-6d97c212e920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-researchCompletionDate&quot;)</value>
      <webElementGuid>99a3deec-12f2-4e1a-bf92-d8eb3ea31d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13e4c733-d789-455f-bbe5-71bf86363e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7eb806ed-a653-487f-9634-0a50c32b9c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-researchCompletionDate</value>
      <webElementGuid>fb446777-c336-40c8-870a-ffefaf387006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchCompletionDate</value>
      <webElementGuid>6717df5b-c4b3-4a63-8075-806f45158c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--/--/----</value>
      <webElementGuid>5ae71851-f53f-4c4f-8ce5-0c946fbe3e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61e39ae9-0bef-4558-9cf6-1300d010f20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfLBT dqWpFE form-control date-picker react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>3836a2af-2a70-472e-865e-72bf589fb945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-researchCompletionDate&quot;)</value>
      <webElementGuid>8066a43b-41f0-464f-b1d2-243e75efbeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ec751f8-65e9-4f9f-8e53-071aff946068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab4aee37-0596-442c-b538-356aa4f513f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-researchCompletionDate</value>
      <webElementGuid>2bf7386e-f174-4c02-842f-c3ab1a31d69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchCompletionDate</value>
      <webElementGuid>5fe73ed9-0a39-497b-aed7-049f061fc2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--/--/----</value>
      <webElementGuid>e88cf4ec-b372-46aa-ab9f-077eee1901a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d6bb693-89bb-40b1-801f-be7acd6aecfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfLBT dqWpFE form-control date-picker react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>b9e00da8-8766-4930-a0c2-0957668460cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-researchCompletionDate&quot;)</value>
      <webElementGuid>3cdd8ab6-9884-45f7-be48-713dd846d8ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepicker-researchCompletionDate']</value>
      <webElementGuid>a9ce5665-7d3e-4fd5-a11e-e3a4c007a184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div[3]/div/div/div/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>5ce3775c-1995-4336-899b-7eec80680cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>b6d7e7a5-095d-4e40-8405-583de0d1dcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datepicker-researchCompletionDate' and @name = 'researchCompletionDate' and @placeholder = '--/--/----']</value>
      <webElementGuid>d29c55fd-14d3-489b-b342-50bcc40622cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
