<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultRequestTextarea</name>
   <tag></tag>
   <elementGuidId>ca9ce967-d82d-44d3-822c-89675f9fcf61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-researchResult</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-researchResult']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e337ffc7-6125-4197-a862-7a826b9839b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchResult</value>
      <webElementGuid>b594917f-4930-4df7-83ba-bde387a50b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-researchResult</value>
      <webElementGuid>435c0acc-efb0-4cd3-8568-ca5503d4be42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>882ace91-be94-4ebb-b789-dab3f2890027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>researchResult-error-tooltip}</value>
      <webElementGuid>fa364e16-bbcb-4949-84be-ec9970b86fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>44baf675-e3de-4481-88ce-c5b06b1a4151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>9daac1c5-6aa6-421d-bdba-8770244351ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-researchResult&quot;)</value>
      <webElementGuid>2e571714-aeed-47f4-b6c4-f96f5db94d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03dd99b9-0062-4a3f-bbf3-eceed3120bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchResult</value>
      <webElementGuid>df509c0b-d575-41df-adfa-10c00c583dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-researchResult</value>
      <webElementGuid>5e5f7394-91c3-4cc6-916e-f1a0a4e11556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa6534d1-75ee-4805-9b1e-823d9dcf39f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>researchResult-error-tooltip}</value>
      <webElementGuid>711e892b-ca6d-46b4-81bb-b9dc5253667d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>195bf66f-d8f7-4766-b8ab-c756e9be50cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>4f50e62e-9609-44d0-820b-c81c30e197ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-researchResult&quot;)</value>
      <webElementGuid>973c4d4a-2a61-448e-add1-c5db91ebb8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5868f538-05b1-4c64-806d-7ea68dc9f93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchResult</value>
      <webElementGuid>cfc23078-de50-435f-ad4d-5d5a38302fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-researchResult</value>
      <webElementGuid>aa7ea267-c31a-423a-a4f7-5990644fa3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>79c7c7b6-daeb-4667-8d49-0eb86cf300e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>researchResult-error-tooltip}</value>
      <webElementGuid>2f6ffa97-5f9d-4349-bff3-2c2f2e5ebe56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>fd38e319-75eb-42c7-9d37-4b9754e5eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>c1488927-1f14-4d27-826f-6daceeab470f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-researchResult&quot;)</value>
      <webElementGuid>b6b2968d-c62b-4540-91af-bfe6289c2d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b5114417-f6d0-4cca-a692-ea66e5e5023c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>researchResult</value>
      <webElementGuid>e32e3d78-ab4f-4eff-a4c0-a333ee5437ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-researchResult</value>
      <webElementGuid>a51dbbd7-63e8-4568-a7d5-78d21c40e86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5b55fa8e-440e-424d-ae88-9b7785594afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>researchResult-error-tooltip}</value>
      <webElementGuid>82c5c10d-4147-41e6-b2a4-32d6014ff9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>aab7f6f8-e5fe-451b-8791-8fbb4fff90c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Results</value>
      <webElementGuid>19eac041-07ee-4d40-a788-06ceabf874b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-researchResult&quot;)</value>
      <webElementGuid>9a6fcc1b-c43f-4276-8eff-c8b6b822ab7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-researchResult']</value>
      <webElementGuid>cb8bafef-8494-43e5-bba1-211533128dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div[3]/div/div/div/div[3]/div[3]/textarea</value>
      <webElementGuid>f3b5dd9d-4286-46e4-a807-0b8f341aa720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result of request:'])[1]/following::textarea[1]</value>
      <webElementGuid>bb2fd3e6-d408-496d-a9bb-323acccd5529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research completed on:'])[1]/following::textarea[1]</value>
      <webElementGuid>1a7fc62a-accf-4255-9aa8-04658eba6085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expropriation'])[1]/preceding::textarea[1]</value>
      <webElementGuid>78926ae9-17ff-4f32-8ec3-ec65f22e238a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expropriation?:'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3e0b384a-5e9b-4241-9251-abca14f90e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation Results']/parent::*</value>
      <webElementGuid>58f43f5a-1cda-4e26-88b6-9c9dc5a82495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>2b5a525b-ca1d-4a1a-958d-1d5ef01d9476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'researchResult' and @id = 'input-researchResult' and @title = 'Automation Results' and (text() = 'Automation Results' or . = 'Automation Results')]</value>
      <webElementGuid>bd28fd0e-44b1-4b1d-89f0-b1015d2b4387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
