<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchContactFirstOption</name>
   <tag></tag>
   <elementGuidId>530056ef-4060-49f9-9147-a6d72a249a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.td > div > input[type=&quot;radio&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='radio'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb5e6d9-5c61-44db-a812-c7388b1e3daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>37755298-8b7d-4fed-a5d3-2ed9890a2e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toggle Row Selected</value>
      <webElementGuid>455afaeb-b3e6-43fa-baa0-613bb470fdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>selectrow-P152</value>
      <webElementGuid>826bdf42-8612-444a-bc7f-9519edf1d11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[2]/div[@class=&quot;table&quot;]/div[@class=&quot;tbody&quot;]/div[@class=&quot;tr-wrapper&quot;]/div[@class=&quot;tr&quot;]/div[@class=&quot;td&quot;]/div[1]/input[1]</value>
      <webElementGuid>dec19c86-f79b-478c-a883-44306a112c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e44cd81-1a2f-4cf9-9689-b22d8a30a8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6c0f5497-839b-490a-9ae3-a261b9fd17dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toggle Row Selected</value>
      <webElementGuid>db092e8f-8366-47eb-9b23-45e19c0a5eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>selectrow-P152</value>
      <webElementGuid>5cab7f4a-0574-49e3-a9f7-9df2bca2d769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[2]/div[@class=&quot;table&quot;]/div[@class=&quot;tbody&quot;]/div[@class=&quot;tr-wrapper&quot;]/div[@class=&quot;tr&quot;]/div[@class=&quot;td&quot;]/div[1]/input[1]</value>
      <webElementGuid>b1d41a1c-5d0d-4376-8922-96886b7f48ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>804d53cc-5495-4ce8-9ad8-25ffd151f9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0cd2e8b8-6ba7-473c-8a02-12ad5806381a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toggle Row Selected</value>
      <webElementGuid>aca077d1-b6cf-494a-8ecb-f813cabb8d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>selectrow-P152</value>
      <webElementGuid>4f3e3ef1-3cab-4425-929b-8d2e97cb61e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[2]/div[@class=&quot;table&quot;]/div[@class=&quot;tbody&quot;]/div[@class=&quot;tr-wrapper&quot;]/div[@class=&quot;tr&quot;]/div[@class=&quot;td&quot;]/div[1]/input[1]</value>
      <webElementGuid>2f50c275-64fa-4308-b690-94c0ceee7884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d340e4c9-2a0e-4417-9ae6-a52637223938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>06262a80-343a-42b1-8aa6-e25ec2b5500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toggle Row Selected</value>
      <webElementGuid>74c079b5-7a3d-4605-8884-0c3b0d8ee03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>selectrow-P152</value>
      <webElementGuid>96849ae6-9d5b-4c4d-bd09-f776b65aef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[2]/div[@class=&quot;table&quot;]/div[@class=&quot;tbody&quot;]/div[@class=&quot;tr-wrapper&quot;]/div[@class=&quot;tr&quot;]/div[@class=&quot;td&quot;]/div[1]/input[1]</value>
      <webElementGuid>247252e4-dc66-4532-a6ef-668b74397a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='radio'])[6]</value>
      <webElementGuid>aba3349c-e9a5-4eb7-ae9f-4dcca2004295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d767f631-da74-42e2-82cf-8d055dfd02c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @title = 'Toggle Row Selected']</value>
      <webElementGuid>a2874fc0-2be8-45e2-b47a-185e419ec0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
