PRINT N'Create Sequences for Table Primary Keys'
GO

CREATE SEQUENCE [dbo].[PIMS_LEASE_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_LEASE_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_PROPERTY_LEASE_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_PROPERTY_LEASE_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_LEASE_ACTIVITY_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_LEASE_ACTIVITY_PERIOD_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_LEASE_ACTIVITY_PERIOD_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_LEASE_ACTIVITY_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_EXPECTED_AMOUNT_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50

CREATE SEQUENCE [dbo].[PIMS_EXPECTED_AMOUNT_H_ID_SEQ]
	AS bigint
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50


-- NOT SURE WHAT THIS IS FOR WITHIN THE SCHEMA
CREATE SEQUENCE [dbo].[PIMS_L_FILE_NO_SEQ]
	AS bigint
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 2147483647
	NO CYCLE
	CACHE 50
