INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS)
VALUES
  ('PIMS_LEASE','PIMS_LEASE')
, ('PIMS_PROPERTY_LEASE','PIMS_PROPLS')
, ('PIMS_EXPECTED_AMOUNT','PIMS_EXPAMT')
, ('PIMS_LEASE_ACTIVITY_PERIOD','PIMS_LSACPR')
, ('PIMS_LEASE_ACTIVITY','PIMS_LSACTV')
, ('PIMS_LEASE_TYPE','PIMS_LSTYPE')
, ('PIMS_LEASE_SUBTYPE','PIMS_LSSTYP')
, ('PIMS_LEASE_PURPOSE_TYPE','PIMS_LSPRTY')
, ('PIMS_LEASE_PURPOSE_SUBTYPE','PIMS_LSPRST')
, ('PIMS_LEASE_STATUS_TYPE','PIMS_LSSTSY')
, ('PIMS_LEASE_PMT_FREQ_TYPE','PIMS_LSPMTF')
, ('PIMS_LEASE_PROGRAM_TYPE','PIMS_LSPRGT');
