using System;
using System.Collections.Immutable;
using Mapster;
using Pims.Api.Helpers.Extensions;
using Pims.Core.Extensions;
using Pims.Dal.Entities;
using Pims.Dal.Helpers.Extensions;

namespace Pims.Api.Models.Concepts.Lease
{
    public class LeaseMap : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            config.NewConfig<PimsLease, LeaseModel>()
                .PreserveReference(true)
                .Map(dest => dest.Id, src => src.LeaseId)
                .Map(dest => dest.RowVersion, src => src.ConcurrencyControlNumber)
                .Map(dest => dest.Amount, src => src.LeaseAmount)
                .Map(dest => dest.RenewalCount, src => src.PimsLeaseTerms.Count)
                .Map(dest => dest.FileProperties, src => src.PimsPropertyLeases)
                .Map(dest => dest.LFileNo, src => src.LFileNo)
                .Map(dest => dest.TfaFileNumber, src => src.TfaFileNumber)
                .Map(dest => dest.PsFileNo, src => src.PsFileNo)
                .Map(dest => dest.MotiName, src => src.MotiContact)
                .Map(dest => dest.ExpiryDate, src => src.GetExpiryDate().ToNullableDateOnly())
                .Map(dest => dest.StartDate, src => DateOnly.FromDateTime(src.OrigStartDate))
                .Map(dest => dest.ProgramName, src => src.GetProgramName())
                .Map(dest => dest.OtherCategoryType, src => src.LeaseCategoryOtherDesc)
                .Map(dest => dest.OtherProgramType, src => src.OtherLeaseProgramType)
                .Map(dest => dest.OtherPurposeType, src => src.OtherLeasePurposeType ?? src.LeasePurposeOtherDesc)
                .Map(dest => dest.OtherType, src => src.OtherLeaseLicenseType)
                .Map(dest => dest.Region, src => src.RegionCodeNavigation)
                .Map(dest => dest.ProgramType, src => src.LeaseProgramTypeCodeNavigation)
                .Map(dest => dest.PaymentReceivableType, src => src.LeasePayRvblTypeCodeNavigation)
                .Map(dest => dest.CategoryType, src => src.LeaseCategoryTypeCodeNavigation)
                .Map(dest => dest.Type, src => src.LeaseLicenseTypeCodeNavigation)
                .Map(dest => dest.InitiatorType, src => src.LeaseInitiatorTypeCodeNavigation)
                .Map(dest => dest.PurposeType, src => src.LeasePurposeTypeCodeNavigation)
                .Map(dest => dest.FileStatusTypeCode, src => src.LeaseStatusTypeCodeNavigation)
                .Map(dest => dest.ResponsibilityType, src => src.LeaseResponsibilityTypeCodeNavigation)
                .Map(dest => dest.ResponsibilityEffectiveDate, src => src.ResponsibilityEffectiveDate.ToNullableDateOnly())
                .Map(dest => dest.DocumentationReference, src => src.DocumentationReference)
                .Map(dest => dest.Note, src => src.LeaseNotes)
                .Map(dest => dest.Description, src => src.LeaseDescription)
                .Map(dest => dest.Consultations, src => src.PimsLeaseConsultations)
                .Map(dest => dest.IsResidential, src => src.IsSubjectToRta)
                .Map(dest => dest.IsCommercialBuilding, src => src.IsCommBldg)
                .Map(dest => dest.IsOtherImprovement, src => src.IsOtherImprovement)
                .Map(dest => dest.ReturnNotes, src => src.ReturnNotes)
                .Map(dest => dest.IsExpired, src => src.IsExpired)
                .Map(dest => dest.HasPhysicalFile, src => src.HasPhysicalFile)
                .Map(dest => dest.HasDigitalLicense, src => src.HasDigitalLicense)
                .Map(dest => dest.HasDigitalFile, src => src.HasDigitalFile)
                .Map(dest => dest.HasPhysicalLicense, src => src.HasPhysicialLicense)
                .Map(dest => dest.Project, src => src.Project)
                .Map(dest => dest.Tenants, src => src.PimsLeaseTenants)
                .Map(dest => dest.Terms, src => src.PimsLeaseTerms);

            config.NewConfig<LeaseModel, PimsLease>()
                .PreserveReference(true)
                .Map(dest => dest.LeaseId, src => src.Id)
                .Map(dest => dest.ConcurrencyControlNumber, src => src.RowVersion)
                .Map(dest => dest.LeaseAmount, src => src.Amount)
                .Map(dest => dest.PimsPropertyLeases, src => src.FileProperties.ToImmutableList())
                .Map(dest => dest.LFileNo, src => src.LFileNo)
                .Map(dest => dest.PsFileNo, src => src.PsFileNo)
                .Map(dest => dest.TfaFileNumber, src => src.TfaFileNumber)
                .Map(dest => dest.MotiContact, src => src.MotiName)
                .Map(dest => dest.LeaseCategoryOtherDesc, src => src.OtherCategoryType)
                .Map(dest => dest.OtherLeaseProgramType, src => src.OtherProgramType)
                .Map(dest => dest.OtherLeasePurposeType, src => src.OtherPurposeType)
                .Map(dest => dest.LeasePurposeOtherDesc, src => src.OtherPurposeType)
                .Map(dest => dest.OtherLeaseLicenseType, src => src.OtherType)
                .Map(dest => dest.OrigExpiryDate, src => src.ExpiryDate.ToNullableDateTime())
                .Map(dest => dest.OrigStartDate, src => src.StartDate.ToDateTime(TimeOnly.MinValue))
                .Map(dest => dest.RegionCode, src => src.Region.Id)
                .Map(dest => dest.LeaseProgramTypeCode, src => src.ProgramType.GetTypeId())
                .Map(dest => dest.LeasePayRvblTypeCode, src => src.PaymentReceivableType.GetTypeId())
                .Map(dest => dest.LeaseCategoryTypeCode, src => src.CategoryType.GetTypeId())
                .Map(dest => dest.LeaseLicenseTypeCode, src => src.Type.GetTypeId())
                .Map(dest => dest.LeaseInitiatorTypeCode, src => src.InitiatorType.GetTypeId())
                .Map(dest => dest.LeasePurposeTypeCode, src => src.PurposeType.GetTypeId())
                .Map(dest => dest.LeaseResponsibilityTypeCode, src => src.ResponsibilityType.GetTypeId())
                .Map(dest => dest.LeaseStatusTypeCode, src => src.FileStatusTypeCode.GetTypeId())
                .Map(dest => dest.ResponsibilityEffectiveDate, src => src.ResponsibilityEffectiveDate.ToNullableDateTime())
                .Map(dest => dest.DocumentationReference, src => src.DocumentationReference)
                .Map(dest => dest.LeaseNotes, src => src.Note)
                .Map(dest => dest.LeaseDescription, src => src.Description)
                .Map(dest => dest.PimsLeaseConsultations, src => src.Consultations)
                .Map(dest => dest.IsExpired, src => src.IsExpired)
                .Map(dest => dest.HasPhysicalFile, src => src.HasPhysicalFile)
                .Map(dest => dest.HasPhysicialLicense, src => src.HasPhysicalLicense)
                .Map(dest => dest.HasDigitalFile, src => src.HasDigitalFile)
                .Map(dest => dest.HasDigitalLicense, src => src.HasDigitalLicense)
                .Map(dest => dest.ProjectId, src => src.Project != null ? src.Project.Id : (long?)null)
                .IgnoreNullValues(true);
        }
    }
}
