DECLARE @finance BIGINT;
DECLARE @functional BIGINT;
DECLARE @restricted BIGINT;
DECLARE @readOnly BIGINT;
DECLARE @systemAdministrator BIGINT;
SELECT @finance = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Finance';
SELECT @functional = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Functional';
SELECT @restricted = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Functional (Restricted)';
SELECT @readOnly = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Read Only';
SELECT @systemAdministrator = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'System Administrator';

DECLARE @activityView BIGINT;
DECLARE @activityAdd BIGINT;
DECLARE @activityEdit BIGINT;
DECLARE @activityDelete BIGINT;
SELECT @activityView = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'activity-view';
SELECT @activityAdd = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'activity-add';
SELECT @activityEdit = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'activity-edit';
SELECT @activityDelete = CLAIM_ID FROM PIMS_CLAIM WHERE NAME = 'activity-delete';

/* Functional */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @activityView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @activityEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @activityAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@functional, @activityDelete, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* Functional Restricted */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @activityView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @activityEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@restricted, @activityAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* Read Only */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@readOnly, @activityView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

/* System Administrator */
INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @activityView, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @activityEdit, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @activityAdd, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')

INSERT [dbo].[PIMS_ROLE_CLAIM] ([ROLE_ID], [CLAIM_ID], [IS_DISABLED], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID])
VALUES (@systemAdministrator, @activityDelete, 0, 1, CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', NULL, N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED', CAST(N'2022-07-15T02:17:49.920' AS DateTime), N'SEED')
GO
