/****** DELETE AUTOMATION TESTING DATA  ******/
--CONTACTS
DELETE FROM PIMS_CONTACT_METHOD WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_CONTACT_METHOD  WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_LEASE_TENANT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ADDRESS WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ADDRESS WHERE PERSON_ID IN (SELECT PERSON_ID FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_INTEREST_HOLDER WHERE PERSON_ID IN (SELECT PERSON_ID FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2') AND PIMS_PERSON.PERSON_ID NOT IN (SELECT PERSON_ID FROM PIMS_USER));
DELETE FROM PIMS_ACQUISITION_FILE_TEAM WHERE PERSON_ID IN (SELECT PERSON_ID FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2') AND PIMS_PERSON.PERSON_ID NOT IN (SELECT PERSON_ID FROM PIMS_USER));
DELETE FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2') AND PIMS_PERSON.PERSON_ID NOT IN (SELECT PERSON_ID FROM PIMS_USER);

-- ORGANIZATION
DELETE FROM PIMS_ORGANIZATION_ADDRESS WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_INTEREST_HOLDER SET ORGANIZATION_ID = 1, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_ACQUISITION_FILE_TEAM SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_LEASE_TENANT SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_SECURITY_DEPOSIT_HOLDER SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_CONTACT_METHOD WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');

-- PROJECTS
UPDATE PIMS_ACQUISITION_FILE SET PROJECT_ID = 1091, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_DISPOSITION_FILE SET PROJECT_ID = 1091, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_COMPENSATION_REQUISITION SET ALTERNATE_PROJECT_ID = 1091, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ALTERNATE_PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_LEASE SET PRODUCT_ID = 10674, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PRODUCT_ID IN  (SELECT ID FROM PIMS_PRODUCT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_ACQUISITION_FILE SET PRODUCT_ID = 10674, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PRODUCT_ID IN  (SELECT ID FROM PIMS_PRODUCT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_DISPOSITION_FILE SET PRODUCT_ID = 10674, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PRODUCT_ID IN  (SELECT ID FROM PIMS_PRODUCT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PROJECT_DOCUMENT WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PROJECT_NOTE WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PROJECT_PRODUCT WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PROJECT_PRODUCT WHERE PRODUCT_ID IN (SELECT ID FROM PIMS_PRODUCT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PROJECT_PERSON WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PRODUCT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');


-- LEASES
DELETE FROM PIMS_PROPERTY_LEASE WHERE LEASE_ID IN (SELECT LEASE_ID WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_INSURANCE WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_PAYMENT WHERE LEASE_TERM_ID IN (SELECT LEASE_TERM_ID FROM PIMS_LEASE_TERM WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')));
DELETE FROM PIMS_LEASE_TERM WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROPERTY_IMPROVEMENT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_SECURITY_DEPOSIT_HOLDER WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')));
DELETE FROM PIMS_SECURITY_DEPOSIT_RETURN_HOLDER WHERE SECURITY_DEPOSIT_RETURN_ID IN (SELECT SECURITY_DEPOSIT_RETURN_ID FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'))));
DELETE FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')));
DELETE FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_NOTE WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_CONSULTATION WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_DOCUMENT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_TENANT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');

-- FINANCIAL CODES
UPDATE PIMS_PROJECT SET WORK_ACTIVITY_CODE_ID = 880, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE WORK_ACTIVITY_CODE_ID IN (SELECT WORK_ACTIVITY_CODE_ID FROM PIMS_WORK_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_WORK_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_BUSINESS_FUNCTION_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_CHART_OF_ACCOUNTS_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_FINANCIAL_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_RESPONSIBILITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
UPDATE PIMS_COMPENSATION_REQUISITION SET YEARLY_FINANCIAL_ID = 221, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER +1 WHERE YEARLY_FINANCIAL_ID IN (SELECT YEARLY_FINANCIAL_ID FROM PIMS_YEARLY_FINANCIAL_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_YEARLY_FINANCIAL_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');


-- ACQUISITION FILES
UPDATE PIMS_ACQUISITION_FILE SET FILE_NAME = 'AUTOMATED TEST AF_ARCHIVED', CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE APP_CREATE_USERID IN ('TRANPSP1');

-- ACQUISITION FILES TAKES LOGIC
UPDATE PIMS_PROPERTY_LEASE SET PROPERTY_ID = 9963, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863));
DELETE FROM PIMS_TAKE WHERE PROPERTY_ACQUISITION_FILE_ID IN (SELECT PROPERTY_ACQUISITION_FILE_ID FROM PIMS_PROPERTY_ACQUISITION_FILE WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863)));
DELETE FROM PIMS_INTHLDR_PROP_INTEREST WHERE PROPERTY_ACQUISITION_FILE_ID IN (SELECT PROPERTY_ACQUISITION_FILE_ID FROM PIMS_PROPERTY_ACQUISITION_FILE WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863)));
DELETE from PIMS_PROPERTY_ACQUISITION_FILE WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863));
DELETE FROM PIMS_HISTORICAL_FILE_NUMBER WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863));
DELETE FROM PIMS_PROPERTY WHERE PID IN (006112447,014993805,014983214,015210979,011584360,015197115,014992876,01537673,015339041,015319121,015009513,015197174,015197093,015197140,015184099,012241814,012491284,015372863);

-- RESEARCH FILES
DELETE FROM PIMS_RESEARCH_FILE_PURPOSE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_PROJECT WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_DOCUMENT WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE WHERE PROPERTY_RESEARCH_FILE_ID IN (SELECT PROPERTY_RESEARCH_FILE_ID FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')))
DELETE FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_NOTE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');

-- DISPOSITION FILES
DELETE FROM PIMS_DISPOSITION_PURCHASER WHERE DISPOSITION_SALE_ID IN (SELECT DISPOSITION_SALE_ID FROM PIMS_DISPOSITION_SALE WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_DISPOSITION_SALE WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_APPRAISAL WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_FILE_PROPERTY WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_OFFER WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_FILE_NOTE WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_CHECKLIST_ITEM WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_FILE_TEAM WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_FILE_DOCUMENT WHERE DISPOSITION_FILE_ID IN (SELECT DISPOSITION_FILE_ID FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_DISPOSITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
UPDATE PIMS_PROPERTY SET IS_OWNED = 1, IS_RETIRED = 0, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PID IN (1465350);

-- SUBDIVISIONS
--UPDATE PIMS_PROPERTY_ACQUISITION_FILE SET PROPERTY_ID = 164, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (5091829, 3904181, 18088007));
UPDATE PIMS_PROPERTY SET IS_OWNED = 1, IS_RETIRED = 0, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PID IN (016440790, 016334361);
UPDATE PIMS_PROPERTY_LEASE SET PROPERTY_ID = 9963, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (015192008, 015191877, 015190960, 015492915));
DELETE FROM PIMS_PROPERTY_OPERATION WHERE PROPERTY_OPERATION_TYPE_CODE = 'SUBDIVIDE' AND SOURCE_PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (016440790, 016334361, 015181197));
DELETE FROM PIMS_PROPERTY_OPERATION WHERE PROPERTY_OPERATION_TYPE_CODE = 'SUBDIVIDE' AND DESTINATION_PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (015192008, 015191877, 015190960, 016334361, 015492915));
DELETE FROM PIMS_PROPERTY WHERE PID IN (015192008, 015191877, 015190960, 015492915);

-- CONSOLIDATIONS
--UPDATE PIMS_PROPERTY_ACQUISITION_FILE SET PROPERTY_ID = 164, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (014149478, 014151821, 014412942, 014412951, 028443969, 001282344));
UPDATE PIMS_PROPERTY SET IS_OWNED = 1, IS_RETIRED = 0, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PID IN (016372387, 005602718, 015013430, 015192032, 015181197, 017766036);
DELETE FROM PIMS_PROPERTY_OPERATION WHERE PROPERTY_OPERATION_TYPE_CODE = 'CONSOLIDATE' AND SOURCE_PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (016372387, 005602718, 015013430, 015192032));
DELETE FROM PIMS_PROPERTY_OPERATION WHERE PROPERTY_OPERATION_TYPE_CODE = 'CONSOLIDATE' AND DESTINATION_PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID IN (015801306, 015013430));
DELETE FROM PIMS_PROPERTY WHERE PID IN (015492915, 015801306);

-- GET BACK PROPERTIES TO ACTIVE
SELECT * FROM PIMS_PROPERTY WHERE PID = 004516249
UPDATE PIMS_PROPERTY SET IS_RETIRED = 0, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE PID = 004516249

-- DELETE LEASE - PROPERTY RELATIONSHIP TO CLEAN PROPERTY MANAGEMENT ACTIVE LEASE STATUS
SELECT * FROM PIMS_PROPERTY WHERE PID = 009670301
DELETE FROM PIMS_PROPERTY_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2') AND PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID = 009670301);

-- RESEARCH FILES: CREATE RESEARCH FILE FROM PIN
DELETE FROM PIMS_PROPERTY_RESEARCH_FILE WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PIMS_PROPERTY WHERE PID = 006093914)
DELETE FROM [PIMS_TST].[dbo].[PIMS_PROPERTY] WHERE PID = 006093914

-- MANAGEMENT FILES
DELETE FROM PIMS_MANAGEMENT_FILE_TEAM WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MANAGEMENT_FILE_NOTE WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MANAGEMENT_FILE_PROPERTY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MANAGEMENT_FILE_DOCUMENT WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MGMT_ACTIVITY_ACTIVITY_SUBTYP WHERE MANAGEMENT_ACTIVITY_ID IN (SELECT MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_MGMT_ACT_MIN_CONTACT WHERE MANAGEMENT_ACTIVITY_ID IN (SELECT MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_MGMT_ACT_INVOLVED_PARTY WHERE MANAGEMENT_ACTIVITY_ID IN (SELECT MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_MANAGEMENT_ACTIVITY_INVOICE WHERE MANAGEMENT_ACTIVITY_ID IN (SELECT MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_MANAGEMENT_ACTIVITY_PROPERTY WHERE MANAGEMENT_ACTIVITY_ID IN (SELECT MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2')));
DELETE FROM PIMS_MANAGEMENT_ACTIVITY WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MANAGEMENT_FILE_CONTACT WHERE MANAGEMENT_FILE_ID IN (SELECT MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_MANAGEMENT_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');













