/****** DELETE AUTOMATION TESTING DATA  ******/
--CONTACTS
DELETE FROM PIMS_CONTACT_METHOD WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_CONTACT_METHOD  WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_LEASE_TENANT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ADDRESS WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');
DELETE FROM PIMS_PERSON_ADDRESS WHERE PERSON_ID IN (SELECT PERSON_ID FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_PERSON WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2') AND PIMS_PERSON.PERSON_ID NOT IN (SELECT PERSON_ID FROM PIMS_USER);

-- ORGANIZATION
DELETE FROM PIMS_ORGANIZATION_ADDRESS WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_INTEREST_HOLDER SET ORGANIZATION_ID = 1, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_ACQUISITION_FILE_TEAM SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_LEASE_TENANT SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
UPDATE PIMS_SECURITY_DEPOSIT_HOLDER SET ORGANIZATION_ID = 3, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2'));
DELETE FROM PIMS_ORGANIZATION WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2');

-- PROJECTS
UPDATE PIMS_ACQUISITION_FILE SET PROJECT_ID = 1091, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROJECT_DOCUMENT WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROJECT_NOTE WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROJECT_PRODUCT WHERE PROJECT_ID IN (SELECT ID FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROJECT WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');

-- LEASES
DELETE FROM PIMS_PROPERTY_LEASE WHERE LEASE_ID IN (SELECT LEASE_ID WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_INSURANCE WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_PAYMENT WHERE LEASE_TERM_ID IN (SELECT LEASE_TERM_ID FROM PIMS_LEASE_TERM WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')))
DELETE FROM PIMS_LEASE_TERM WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROPERTY_IMPROVEMENT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_SECURITY_DEPOSIT_HOLDER WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')));
DELETE FROM PIMS_SECURITY_DEPOSIT_RETURN_HOLDER WHERE SECURITY_DEPOSIT_RETURN_ID IN (SELECT SECURITY_DEPOSIT_RETURN_ID FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'))));
DELETE FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID IN (SELECT SECURITY_DEPOSIT_ID FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')));
DELETE FROM PIMS_SECURITY_DEPOSIT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_NOTE WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_CONSULTATION WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_DOCUMENT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE_TENANT WHERE LEASE_ID IN (SELECT LEASE_ID FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_LEASE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');

-- FINANCIAL CODES
UPDATE PIMS_PROJECT SET WORK_ACTIVITY_CODE_ID = 880, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE WORK_ACTIVITY_CODE_ID IN (SELECT WORK_ACTIVITY_CODE_ID FROM PIMS_WORK_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_WORK_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
DELETE FROM PIMS_BUSINESS_FUNCTION_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
DELETE FROM PIMS_CHART_OF_ACCOUNTS_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
DELETE FROM PIMS_FINANCIAL_ACTIVITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
DELETE FROM PIMS_RESPONSIBILITY_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
UPDATE PIMS_COMPENSATION_REQUISITION SET YEARLY_FINANCIAL_ID = 221, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER +1 WHERE YEARLY_FINANCIAL_ID IN (SELECT YEARLY_FINANCIAL_ID FROM PIMS_YEARLY_FINANCIAL_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_YEARLY_FINANCIAL_CODE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');

-- ACQUISITION FILES
DELETE FROM PIMS_EXPROP_PMT_PMT_ITEM WHERE EXPROPRIATION_PAYMENT_ID IN (SELECT EXPROPRIATION_PAYMENT_ID FROM PIMS_EXPROPRIATION_PAYMENT WHERE INTEREST_HOLDER_ID IN (SELECT INTEREST_HOLDER_ID FROM PIMS_INTEREST_HOLDER WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'))));
DELETE FROM PIMS_EXPROPRIATION_PAYMENT WHERE INTEREST_HOLDER_ID IN (SELECT INTEREST_HOLDER_ID FROM PIMS_INTEREST_HOLDER WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1')));
DELETE FROM PIMS_INTEREST_HOLDER WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_AGREEMENT WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_ACQUISITION_FILE_DOCUMENT WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_ACQUISITION_CHECKLIST_ITEM WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_TAKE WHERE PROPERTY_ACQUISITION_FILE_ID IN (SELECT PROPERTY_ACQUISITION_FILE_ID FROM PIMS_PROPERTY_ACQUISITION_FILE WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1')));
DELETE FROM PIMS_INTHLDR_PROP_INTEREST WHERE PROPERTY_ACQUISITION_FILE_ID IN (SELECT PROPERTY_ACQUISITION_FILE_ID FROM PIMS_PROPERTY_ACQUISITION_FILE WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1')));
DELETE FROM PIMS_EXPROP_PMT_PMT_ITEM WHERE EXPROPRIATION_PAYMENT_ID IN (SELECT EXPROPRIATION_PAYMENT_ID FROM PIMS_EXPROPRIATION_PAYMENT WHERE ACQUISITION_OWNER_ID IN (SELECT ACQUISITION_OWNER_ID FROM PIMS_ACQUISITION_OWNER WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'))));
DELETE FROM PIMS_EXPROPRIATION_PAYMENT WHERE ACQUISITION_OWNER_ID IN (SELECT ACQUISITION_OWNER_ID FROM PIMS_ACQUISITION_OWNER WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1')));
DELETE FROM PIMS_COMP_REQ_FINANCIAL WHERE COMPENSATION_REQUISITION_ID IN (SELECT COMPENSATION_REQUISITION_ID FROM PIMS_COMPENSATION_REQUISITION WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1')))
DELETE FROM PIMS_COMPENSATION_REQUISITION WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_ACQUISITION_CHECKLIST_ITEM WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_ACQUISITION_FILE_NOTE WHERE ACQUISITION_FILE_ID IN (SELECT ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1'));
DELETE FROM PIMS_ACQUISITION_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1');

-- RESEARCH FILES
DELETE FROM PIMS_RESEARCH_FILE_PURPOSE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_PROJECT WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_DOCUMENT WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE WHERE PROPERTY_RESEARCH_FILE_ID IN (SELECT PROPERTY_RESEARCH_FILE_ID FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA')))
DELETE FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_PROPERTY_RESEARCH_FILE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE_NOTE WHERE RESEARCH_FILE_ID IN (SELECT RESEARCH_FILE_ID FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA'));
DELETE FROM PIMS_RESEARCH_FILE WHERE APP_CREATE_USERID IN ('TRANPSP1', 'TRANPSP2', 'SUTAIRAK','PRAVKUMA');
