/****** FUNTIONAL/ REGRESSION TESTING SCRIPTS ******/

-- Contacts - Organization relationship - Get Organizations with n contacts associated
  SELECT PO.ORGANIZATION_ID, ORG.ORGANIZATION_NAME
  FROM PIMS_PERSON_ORGANIZATION PO
  INNER JOIN PIMS_ORGANIZATION ORG ON PO.ORGANIZATION_ID = ORG.ORGANIZATION_ID
  GROUP BY PO.ORGANIZATION_ID, ORG.ORGANIZATION_NAME
  HAVING COUNT(PO.ORGANIZATION_ID) = 0

-- Properties - Get nbr of Files associated to it
-- Acquisition Files
SELECT AF.ACQUISITION_FILE_ID, AF.FILE_NUMBER, PR.PID, PR.PIN
  FROM PIMS_PROPERTY_ACQUISITION_FILE PRAF
  INNER JOIN PIMS_ACQUISITION_FILE AF ON PRAF.ACQUISITION_FILE_ID = AF.ACQUISITION_FILE_ID
  INNER JOIN PIMS_PROPERTY PR ON PRAF.PROPERTY_ID = PR.PROPERTY_ID
  WHERE PR.PID = 10087346
  --WHERE AF.FILE_NUMBER = '01-100018-01'
  GROUP BY AF.ACQUISITION_FILE_ID, AF.FILE_NUMBER, PR.PID, PR.PIN

  -- Research Files
SELECT RF.RESEARCH_FILE_ID, RF.RFILE_NUMBER
  FROM PIMS_PROPERTY_RESEARCH_FILE PRRF
  INNER JOIN PIMS_RESEARCH_FILE RF ON PRRF.RESEARCH_FILE_ID = RF.RESEARCH_FILE_ID
  INNER JOIN PIMS_PROPERTY PR ON PRRF.PROPERTY_ID = PR.PROPERTY_ID
  WHERE PR.PID = 10087346
  GROUP BY RF.RESEARCH_FILE_ID, RF.RFILE_NUMBER



SELECT P.PID, P.PIN FROM PIMS_PROPERTY P
  INNER JOIN PIMS_PROPERTY_RESEARCH_FILE PRF ON P.PROPERTY_ID = PRF.PROPERTY_ID
  INNER JOIN PIMS_PROPERTY_LEASE PL ON P.PROPERTY_ID = PL.PROPERTY_ID
  INNER JOIN PIMS_PROPERTY_ACQUISITION_FILE PAF ON P.PROPERTY_ID = PAF.PROPERTY_ID
  INNER JOIN PIMS_DISPOSITION_FILE_PROPERTY PDF ON P.PROPERTY_ID = PDF.PROPERTY_ID
  WHERE P.BOUNDARY IS NOT NULL
  AND P.LOCATION IS NOT NULL
  AND P.PID IS NOT NULL
  
