/****** FUNTIONAL/ REGRESSION TESTING SCRIPTS ******/

-- Contacts - Organization relationship - Get Organizations with n contacts associated
  SELECT PO.ORGANIZATION_ID, ORG.ORGANIZATION_NAME
  FROM PIMS_PERSON_ORGANIZATION PO
  INNER JOIN PIMS_ORGANIZATION ORG ON PO.ORGANIZATION_ID = ORG.ORGANIZATION_ID
  GROUP BY PO.ORGANIZATION_ID, ORG.ORGANIZATION_NAME
  HAVING COUNT(PO.ORGANIZATION_ID) = 0

-- Properties - Get nbr of Files associated to it
-- Acquisition Files
SELECT AF.ACQUISITION_FILE_ID, AF.FILE_NUMBER
  FROM PIMS_PROPERTY_ACQUISITION_FILE PRAF
  INNER JOIN PIMS_ACQUISITION_FILE AF ON PRAF.ACQUISITION_FILE_ID = AF.ACQUISITION_FILE_ID
  INNER JOIN PIMS_PROPERTY PR ON PRAF.PROPERTY_ID = PR.PROPERTY_ID
  WHERE PR.PID = 007095333
  GROUP BY AF.ACQUISITION_FILE_ID, AF.FILE_NUMBER

  -- Acquisition Files
SELECT RF.RESEARCH_FILE_ID, RF.RFILE_NUMBER
  FROM PIMS_PROPERTY_RESEARCH_FILE PRRF
  INNER JOIN PIMS_RESEARCH_FILE RF ON PRRF.RESEARCH_FILE_ID = RF.RESEARCH_FILE_ID
  INNER JOIN PIMS_PROPERTY PR ON PRRF.PROPERTY_ID = PR.PROPERTY_ID
  WHERE PR.PID = 007095333
  GROUP BY RF.RESEARCH_FILE_ID, RF.RFILE_NUMBER
  
