DELETE 
FROM   PIMS_PROPERTY_ACQUISITION_FILE;
GO

INSERT INTO [dbo].[PIMS_PROPERTY_ACQUISITION_FILE] ([ACQUISITION_FILE_ID], [PROPERTY_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES((SELECT MAX(ACQUISITION_FILE_ID) FROM PIMS_ACQUISITION_FILE), (SELECT MAX(PROPERTY_ID) FROM PIMS_PROPERTY), 1)
GO
