kind: Template
apiVersion: v1
metadata:
  name: jenkins-deploy
  annotations:
    description: Jenkins deployment.
    tags: jenkins
parameters:
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "3cd915"

  - name: CPU_REQUEST
    displayName: "Requested Minimum Resources CPU Limit"
    description: "The requested minimum resources CPU limit (in cores) for this build."
    required: true
    value: "2000m"
  - name: CPU_LIMIT
    displayName: "Resources CPU Limit"
    description: "The resources CPU limit (in cores) for this build."
    required: true
    value: "2500m"
  - name: MEMORY_REQUEST
    displayName: "Requested Minimum Memory Limit"
    description: "Minimum requested amount of memory the container can use."
    required: true
    value: "4Gi"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    required: true
    value: "6Gi"
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      annotations:
        description: Defines how to deploy jenkins
      name: jenkins
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        app: jenkins
        app.kubernetes.io/part-of: pims-cicd
        env: ${ENV_NAME}
        name: jenkins
        role: jenkins
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - jenkins
            from:
              kind: ImageStreamTag
              namespace: openshift
              name: "jenkins:2"
            lastTriggeredImage: >-
              image-registry.openshift-image-registry.svc:5000/openshift/jenkins@sha256:814895e84a11e25716361def4a868da6eeb79fcfc3a11cba3dc9e85b44f09dfe
        - type: ConfigChange
      replicas: 1
      revisionHistoryLimit: 10
      test: false
      selector:
        app: jenkins
      template:
        metadata:
          name: jenkins
          creationTimestamp: null
          labels:
            app: jenkins
            name: jenkins
            role: jenkins
        spec:
          restartPolicy: Always
          serviceAccountName: jenkins
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              volumeMounts:
                - name: jenkins-data
                  mountPath: /var/lib/jenkins
                - name: mssql-data
                  mountPath: /var/opt/mssql
                - name: backup
                  mountPath: /backups
              terminationMessagePath: /dev/termination-log
              name: jenkins
              env:
                - name: OPENSHIFT_ENABLE_OAUTH
                  value: "true"
                - name: OPENSHIFT_JENKINS_JVM_ARCH
                  value: x86_64
                - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
                  value: "true"
                - name: KUBERNETES_MASTER
                  value: "https://kubernetes.default:443"
                - name: KUBERNETES_TRUST_CERTIFICATES
                  value: "true"
                - name: JNLP_SERVICE_NAME
                  value: jenkins-jnlp
                - name: JAVA_OPTS
                  value: >-
                    -XX:MaxMetaspaceSize=512m -Duser.timezone=America/Vancouver
                    -Dhudson.model.DirectoryBrowserSupport.CSP=
              ports:
                - containerPort: 8080
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              image: >-
                image-registry.openshift-image-registry.svc:5000/openshift/jenkins@sha256:814895e84a11e25716361def4a868da6eeb79fcfc3a11cba3dc9e85b44f09dfe
          serviceAccount: jenkins
          volumes:
            - name: jenkins-data
              persistentVolumeClaim:
                claimName: jenkins-data
          dnsPolicy: ClusterFirst
