ALTER TABLE [PIMS_ACCESS_REQUEST_ORGANIZATION] ADD CONSTRAINT ACRQOR_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

IF EXISTS(select con.[name] from sys.default_constraints con where con.[name] = 'TSKTAM_IS_MANDATORY_DEF')
BEGIN
	ALTER TABLE [PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] DROP CONSTRAINT TSKTAM_IS_MANDATORY_DEF;
END
ALTER TABLE [PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] ADD CONSTRAINT TSKTAM_IS_MANDATORY_DEF DEFAULT (CONVERT([bit],(1))) FOR [IS_MANDATORY];
ALTER TABLE [PIMS_TASK_TEMPLATE_ACTIVITY_MODEL] ADD CONSTRAINT TSKTAM_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_CLAIM] ADD CONSTRAINT CLMTYP_IS_DISABLED_DEFrop DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_LEASE_ACTIVITY_PERIOD] ADD CONSTRAINT LSACPR_IS_CLOSED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_CLOSED];

ALTER TABLE [PIMS_LEASE] ADD CONSTRAINT LEASE_EXPIRED_DEF DEFAULT (CONVERT([bit],(0))) FOR [EXPIRED];
ALTER TABLE [PIMS_LEASE] ADD CONSTRAINT LEASE_HAS_DIGITAL_FILE_DEF DEFAULT (CONVERT([bit],(0))) FOR [HAS_DIGITAL_FILE];
ALTER TABLE [PIMS_LEASE] ADD CONSTRAINT LEASE_HAS_PHYSICAL_FILE_DEF DEFAULT (CONVERT([bit],(0))) FOR [HAS_PHYSICAL_FILE];
ALTER TABLE [PIMS_LEASE] ADD CONSTRAINT LEASE_HAS_PHYSICAL_LICENSE_DEF DEFAULT (CONVERT([bit],(0))) FOR [HAS_PHYSICAL_LICENSE];
ALTER TABLE [PIMS_LEASE] ADD CONSTRAINT LEASE_HAS_DIGITAL_LICENSE_DEF DEFAULT (CONVERT([bit],(0))) FOR [HAS_DIGITAL_LICENSE];

ALTER TABLE [PIMS_ORGANIZATION] ADD CONSTRAINT ORG_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_PERSON] ADD CONSTRAINT PERSON_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_PERSON_ORGANIZATION] ADD CONSTRAINT PERORG_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_PROJECT_PROPERTY] ADD CONSTRAINT PRJPRP_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_PROJECT_WORKFLOW_MODEL] ADD CONSTRAINT PRWKMD_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

IF EXISTS(select con.[name] from sys.default_constraints con where con.[name] = 'PRPRTY_IS_OWNED_DEF')
BEGIN
	ALTER TABLE [PIMS_PROPERTY] DROP CONSTRAINT PRPRTY_IS_OWNED_DEF;
END
ALTER TABLE [PIMS_PROPERTY] ADD CONSTRAINT PRPRTY_IS_OWNED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_OWNED];

ALTER TABLE [PIMS_PROPERTY_ACTIVITY] ADD CONSTRAINT PRPACT_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_ROLE] ADD CONSTRAINT ROLE_IS_PUBLIC_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_PUBLIC];

ALTER TABLE [PIMS_USER_ORGANIZATION] ADD CONSTRAINT USRORG_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];

ALTER TABLE [PIMS_USER_ROLE] ADD CONSTRAINT USERRL_IS_DISABLED_DEF DEFAULT (CONVERT([bit],(0))) FOR [IS_DISABLED];
