DECLARE @PIMS_PROPERTY_ID VARCHAR(MAX);
DECLARE @sql VARCHAR(MAX);
SET @PIMS_PROPERTY_ID = (SELECT max(PROPERTY_ID) from PIMS_PROPERTY) + 1;
SET @sql = 'ALTER SEQUENCE PIMS_PROPERTY_ID_SEQ RESTART WITH ' + @PIMS_PROPERTY_ID
EXEC (@sql)
GO