PRINT N'Create history tables'
GO

CREATE TABLE [dbo].[PIMS_LEASE_TENANT_HIST]  ( 
	[_LEASE_TENANT_HIST_ID]         	bigint NOT NULL DEFAULT (NEXT VALUE FOR [PIMS_LEASE_TENANT_H_ID_SEQ]),
	[APP_CREATE_TIMESTAMP]          	datetime NOT NULL,
	[APP_CREATE_USER_DIRECTORY]     	nvarchar(30) NOT NULL,
	[APP_CREATE_USER_GUID]          	uniqueidentifier NULL,
	[APP_CREATE_USERID]             	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_TIMESTAMP]     	datetime NOT NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY]	nvarchar(30) NOT NULL,
	[APP_LAST_UPDATE_USER_GUID]     	uniqueidentifier NULL,
	[APP_LAST_UPDATE_USERID]        	nvarchar(30) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER]    	bigint NOT NULL,
	[DB_CREATE_TIMESTAMP]           	datetime NOT NULL,
	[DB_CREATE_USERID]              	nvarchar(30) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP]      	datetime NOT NULL,
	[DB_LAST_UPDATE_USERID]         	nvarchar(30) NOT NULL,
	[EFFECTIVE_DATE_HIST]           	datetime NOT NULL DEFAULT (getutcdate()),
	[END_DATE_HIST]                 	datetime NULL,
	[LEASE_ID]                      	bigint NOT NULL,
	[LEASE_TENANT_ID]               	bigint NOT NULL,
	[LESSOR_TYPE_CODE]              	nvarchar(20) NOT NULL,
	[ORGANIZATION_ID]               	bigint NULL,
	[PERSON_ID]                     	bigint NULL,
	PRIMARY KEY CLUSTERED([_LEASE_TENANT_HIST_ID])
 ON [PRIMARY])
GO
ALTER TABLE [dbo].[PIMS_LEASE_TENANT_HIST]
	ADD UNIQUE ([_LEASE_TENANT_HIST_ID], [END_DATE_HIST])  
	WITH (
		DATA_COMPRESSION = NONE
	) ON [PRIMARY]

ALTER TABLE [dbo].[PIMS_PROPERTY_HIST]
	ADD [PROP_MGMT_ORG_ID] bigint NULL, 
	[PROPERTY_MANAGER_ID] bigint NULL, 
	[SURPLUS_DECLARATION_COMMENT] nvarchar(2000) NULL, 
	[SURPLUS_DECLARATION_DATE] datetime NULL, 
	[SURPLUS_DECLARATION_TYPE_CODE] nvarchar(20) NULL

DROP TABLE [dbo].[PIMS_EXPECTED_AMOUNT_HIST]

DROP TABLE [dbo].[PIMS_LEASE_ACTIVITY_HIST]

DROP TABLE [dbo].[PIMS_LEASE_ACTIVITY_PERIOD_HIST]