-- Drop foreign key constraint dbo.PIM_TSKTMP_PIM_TASK_FK
PRINT N'Drop foreign key constraint dbo.PIM_TSKTMP_PIM_TASK_FK'
GO
ALTER TABLE [dbo].[PIMS_TASK]
	DROP CONSTRAINT [PIM_TSKTMP_PIM_TASK_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_TSKTMP_PIM_TSKTAM_FK
PRINT N'Drop foreign key constraint dbo.PIM_TSKTMP_PIM_TSKTAM_FK'
GO
ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL]
	DROP CONSTRAINT [PIM_TSKTMP_PIM_TSKTAM_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop primary key constraint dbo.TSKTMP_PK
PRINT N'Drop primary key constraint dbo.TSKTMP_PK'
GO
ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE]
	DROP CONSTRAINT [TSKTMP_PK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_TSKTMT_PIM_TSKTMP_FK
PRINT N'Drop foreign key constraint dbo.PIM_TSKTMT_PIM_TSKTMP_FK'
GO
ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE]
	DROP CONSTRAINT [PIM_TSKTMT_PIM_TSKTMP_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

ALTER TABLE [dbo].[PIMS_TASK_TEMPLATE]
DROP CONSTRAINT [TSKTMP_TASK_TEMPLATE_ID_DEF]
GO