INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS)
VALUES
  ('PIMS_LEASE_LICENSE_TYPE','PIMS_LSLITYPE')
, ('PIMS_LEASE_TENANT','PIMS_LEATEN')
, ('PIMS_LEASE_PAY_RVBL_TYPE','PIMS_LSRVBL')
, ('PIMS_SURPLUS_DECLARATION_TYPE','PIMS_SPDCLT')
, ('PIMS_LEASE_CATEGORY_TYPE','PIMS_LSCATYPE');
