-- File generated on 10/21/2025 02:34:02 PM.
-- Autogenerated file. Do not manually modify.

:On Error Exit
SET XACT_ABORT ON
GO

PRINT '     == DB SCRIPT START ========'
GO

BEGIN TRANSACTION
PRINT '     == DB TRANSACTION START ========'
   GO

   --Script section

   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/010_PSP_PIMS_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/010_PSP_PIMS_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/020_PIMS_STATIC_VARIABLE_VERSION_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/078_DML_PIMS_PROPERTY_ANOMALY_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/078_DML_PIMS_PROPERTY_ANOMALY_TYPE_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/109_DML_PIMS_LEASE_STAKEHOLDER_TYPE_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/109_DML_PIMS_LEASE_STAKEHOLDER_TYPE_Alter_Down.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/160_DML_PIMS_ACQ_FILE_APPRAISAL_TYPE.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/160_DML_PIMS_ACQ_FILE_APPRAISAL_TYPE.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/161_DML_PIMS_ACQ_FILE_LGL_SRVY_TYPE.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/161_DML_PIMS_ACQ_FILE_LGL_SRVY_TYPE.sql"
   :r $(filepath)
   PRINT '- Executing PSP_PIMS_S112_00/Alter Down/999_Build_Foreign_Keys_Alter_Down.sql '
   :setvar filepath "PSP_PIMS_S112_00/Alter Down/999_Build_Foreign_Keys_Alter_Down.sql"
   :r $(filepath)

   --End script section

PRINT '     == DB TRANSACTION FINISH ========'
GO

If XACT_STATE()=1
  BEGIN
  PRINT '- Success: Committing Transaction...'
  COMMIT TRANSACTION;
  END
ELSE IF XACT_STATE()=-1
  BEGIN
  PRINT '- Error: Rolling Back Transaction...'
  ROLLBACK TRANSACTION;
  END;
ELSE IF XACT_STATE()=0
  BEGIN
  PRINT '- Error: No pending transactions...'
  ROLLBACK TRANSACTION;
  END;
GO
