PRINT N'Create Sequences for Table Primary Keys'
GO

CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_AGENCY_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ROLE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ADDRESS_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ADMINISTRATIVE_AREA_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_AGENCY_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_CONSTRUCTION_TYPE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_EVALUATION_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_FISCAL_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_OCCUPANT_TYPE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_BUILDING_PREDOMINATE_USE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_CLAIM_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_NOTIFICATION_QUEUE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_NOTIFICATION_TEMPLATE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PARCEL_BUILDING_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PARCEL_FISCAL_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PARCEL_EVALUATION_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PARCEL_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PARCEL_PARCEL_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO

CREATE SEQUENCE [dbo].[PIMS_PROJECT_NUMBER_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_CLASSIFICATION_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_TYPE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROVINCE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ROLE_CLAIM_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ROLE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_TENANT_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_AGENCY_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_ROLE_ID_SEQ]
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE  1
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO
