PRINT N'Create Sequences for Table Primary Keys'
GO

CREATE SEQUENCE [dbo].[PIMS_TENANT_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO

CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_MODEL_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_MODEL_TASK_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_SERVICE_FILE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_TASK_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ADDRESS_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_CLAIM_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_CONTACT_METHOD_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PERSON_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PERSON_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_NOTE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_NUMBER_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_PROPERTY_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_EVALUATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_ACTIVITY_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROPERTY_SERVICE_FILE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ROLE_CLAIM_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_ROLE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_TASK_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_ROLE_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_USER_TASK_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_WORKFLOW_MODEL_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO


CREATE SEQUENCE [dbo].[PIMS_PROJECT_ORGANIZATION_ID_SEQ]
  AS BIGINT
  START WITH 0
  INCREMENT BY 1
  MINVALUE  0
  MAXVALUE  2147483647
  NO CYCLE
  CACHE 50
GO
