PRINT N'Create history tables'
GO

-- PIMS_ACCESS_REQUEST_HIST
CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ACCESS_REQUEST_HIST] (
    [_ACCESS_REQUEST_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ACCE___ACCE__7993056A] DEFAULT NEXT VALUE FOR [PIMS_ACCESS_REQUEST_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ACCE__EFFEC__7A8729A3] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ACCESS_REQUEST_ID] BIGINT NOT NULL,
    [USER_ID] BIGINT NOT NULL,
    [ROLE_ID] BIGINT,
    [ACCESS_REQUEST_STATUS_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [NOTE] NVARCHAR(1000),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ACRQST_H_PK] PRIMARY KEY CLUSTERED ([_ACCESS_REQUEST_HIST_ID]),
    CONSTRAINT [PIMS_ACRQST_H_UK] UNIQUE ([_ACCESS_REQUEST_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ACCESS_REQUEST_ORGANIZATION_HIST
CREATE SEQUENCE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ACCESS_REQUEST_ORGANIZATION_HIST] (
    [_ACCESS_REQUEST_ORGANIZATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ACCE___ACCE__7F4BDEC0] DEFAULT NEXT VALUE FOR [PIMS_ACCESS_REQUEST_ORGANIZATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ACCE__EFFEC__004002F9] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ACCESS_REQUEST_ORGANIZATION_ID] BIGINT NOT NULL,
    [ORGANIZATION_ID] BIGINT,
    [ACCESS_REQUEST_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ACRQOR_H_PK] PRIMARY KEY CLUSTERED ([_ACCESS_REQUEST_ORGANIZATION_HIST_ID]),
    CONSTRAINT [PIMS_ACRQOR_H_UK] UNIQUE ([_ACCESS_REQUEST_ORGANIZATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ACTIVITY_HIST
CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ACTIVITY_HIST] (
    [_ACTIVITY_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ACTI___ACTI__0504B816] DEFAULT NEXT VALUE FOR [PIMS_ACTIVITY_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ACTI__EFFEC__05F8DC4F] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ACTIVITY_ID] BIGINT NOT NULL,
    [PROJECT_ID] BIGINT,
    [WORKFLOW_ID] BIGINT,
    [ACTIVITY_MODEL_ID] BIGINT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ACTVTY_H_PK] PRIMARY KEY CLUSTERED ([_ACTIVITY_HIST_ID]),
    CONSTRAINT [PIMS_ACTVTY_H_UK] UNIQUE ([_ACTIVITY_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ACTIVITY_MODEL_HIST
CREATE SEQUENCE [dbo].[PIMS_ACTIVITY_MODEL_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ACTIVITY_MODEL_HIST] (
    [_ACTIVITY_MODEL_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ACTI___ACTI__0ABD916C] DEFAULT NEXT VALUE FOR [PIMS_ACTIVITY_MODEL_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ACTI__EFFEC__0BB1B5A5] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ACTIVITY_MODEL_ID] BIGINT NOT NULL,
    [DESCRIPTION] NVARCHAR(200) NOT NULL,
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ACTMDL_H_PK] PRIMARY KEY CLUSTERED ([_ACTIVITY_MODEL_HIST_ID]),
    CONSTRAINT [PIMS_ACTMDL_H_UK] UNIQUE ([_ACTIVITY_MODEL_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ADDRESS_HIST
CREATE SEQUENCE [dbo].[PIMS_ADDRESS_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ADDRESS_HIST] (
    [_ADDRESS_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ADDR___ADDR__10766AC2] DEFAULT NEXT VALUE FOR [PIMS_ADDRESS_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ADDR__EFFEC__116A8EFB] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ADDRESS_ID] BIGINT NOT NULL,
    [ADDRESS_USAGE_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [REGION_CODE] SMALLINT,
    [DISTRICT_CODE] SMALLINT,
    [PROVINCE_STATE_ID] SMALLINT NOT NULL,
    [COUNTRY_ID] SMALLINT,
    [STREET_ADDRESS_1] NVARCHAR(200),
    [STREET_ADDRESS_2] NVARCHAR(200),
    [STREET_ADDRESS_3] NVARCHAR(200),
    [MUNICIPALITY_NAME] NVARCHAR(200),
    [POSTAL_CODE] NVARCHAR(20),
    [LATITUDE] NUMERIC(18),
    [LONGITUDE] NUMERIC(18),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ADDRSS_H_PK] PRIMARY KEY CLUSTERED ([_ADDRESS_HIST_ID]),
    CONSTRAINT [PIMS_ADDRSS_H_UK] UNIQUE ([_ADDRESS_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_CLAIM_HIST
CREATE SEQUENCE [dbo].[PIMS_CLAIM_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_CLAIM_HIST] (
    [_CLAIM_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_CLAI___CLAI__162F4418] DEFAULT NEXT VALUE FOR [PIMS_CLAIM_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_CLAI__EFFEC__17236851] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [CLAIM_ID] BIGINT NOT NULL,
    [CLAIM_UID] UNIQUEIDENTIFIER NOT NULL,
    [KEYCLOAK_ROLE_ID] UNIQUEIDENTIFIER,
    [NAME] NVARCHAR(100) NOT NULL,
    [DESCRIPTION] NVARCHAR(500) NOT NULL,
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_CLMTYP_H_PK] PRIMARY KEY CLUSTERED ([_CLAIM_HIST_ID]),
    CONSTRAINT [PIMS_CLMTYP_H_UK] UNIQUE ([_CLAIM_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_CONTACT_METHOD_HIST
CREATE SEQUENCE [dbo].[PIMS_CONTACT_METHOD_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_CONTACT_METHOD_HIST] (
    [_CONTACT_METHOD_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_CONT___CONT__1BE81D6E] DEFAULT NEXT VALUE FOR [PIMS_CONTACT_METHOD_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_CONT__EFFEC__1CDC41A7] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [CONTACT_METHOD_ID] BIGINT NOT NULL,
    [CONTACT_METHOD_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PERSON_ID] BIGINT,
    [ORGANIZATION_ID] BIGINT,
    [CONTACT_METHOD_VALUE] NVARCHAR(200) NOT NULL,
    [IS_PREFERRED_METHOD] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_CNTMTH_H_PK] PRIMARY KEY CLUSTERED ([_CONTACT_METHOD_HIST_ID]),
    CONSTRAINT [PIMS_CNTMTH_H_UK] UNIQUE ([_CONTACT_METHOD_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ORGANIZATION_HIST
CREATE SEQUENCE [dbo].[PIMS_ORGANIZATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ORGANIZATION_HIST] (
    [_ORGANIZATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ORGA___ORGA__21A0F6C4] DEFAULT NEXT VALUE FOR [PIMS_ORGANIZATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ORGA__EFFEC__22951AFD] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ORGANIZATION_ID] BIGINT NOT NULL,
    [PRNT_ORGANIZATION_ID] BIGINT,
    [ADDRESS_ID] BIGINT NOT NULL,
    [REGION_CODE] SMALLINT,
    [DISTRICT_CODE] SMALLINT,
    [ORGANIZATION_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [ORG_IDENTIFIER_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [ORGANIZATION_IDENTIFIER] NVARCHAR(100),
    [ORGANIZATION_NAME] NVARCHAR(200) NOT NULL,
    [WEBSITE] NVARCHAR(200),
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ORG_H_PK] PRIMARY KEY CLUSTERED ([_ORGANIZATION_HIST_ID]),
    CONSTRAINT [PIMS_ORG_H_UK] UNIQUE ([_ORGANIZATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PERSON_HIST
CREATE SEQUENCE [dbo].[PIMS_PERSON_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PERSON_HIST] (
    [_PERSON_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PERS___PERS__2759D01A] DEFAULT NEXT VALUE FOR [PIMS_PERSON_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PERS__EFFEC__284DF453] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PERSON_ID] BIGINT NOT NULL,
    [ADDRESS_ID] BIGINT,
    [SURNAME] NVARCHAR(50) NOT NULL,
    [FIRST_NAME] NVARCHAR(50) NOT NULL,
    [MIDDLE_NAMES] NVARCHAR(200),
    [NAME_SUFFIX] NVARCHAR(50),
    [BIRTH_DATE] DATE,
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PERSON_H_PK] PRIMARY KEY CLUSTERED ([_PERSON_HIST_ID]),
    CONSTRAINT [PIMS_PERSON_H_UK] UNIQUE ([_PERSON_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PERSON_ORGANIZATION_HIST
CREATE SEQUENCE [dbo].[PIMS_PERSON_ORGANIZATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PERSON_ORGANIZATION_HIST] (
    [_PERSON_ORGANIZATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PERS___PERS__2D12A970] DEFAULT NEXT VALUE FOR [PIMS_PERSON_ORGANIZATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PERS__EFFEC__2E06CDA9] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PERSON_ORGANIZATION_ID] BIGINT NOT NULL,
    [PERSON_ID] BIGINT,
    [ORGANIZATION_ID] BIGINT,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PERORG_H_PK] PRIMARY KEY CLUSTERED ([_PERSON_ORGANIZATION_HIST_ID]),
    CONSTRAINT [PIMS_PERORG_H_UK] UNIQUE ([_PERSON_ORGANIZATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROJECT_HIST
CREATE SEQUENCE [dbo].[PIMS_PROJECT_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROJECT_HIST] (
    [_PROJECT_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROJ___PROJ__32CB82C6] DEFAULT NEXT VALUE FOR [PIMS_PROJECT_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROJ__EFFEC__33BFA6FF] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROJECT_ID] BIGINT NOT NULL,
    [PROJECT_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROJECT_STATUS_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROJECT_RISK_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROJECT_TIER_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PROJCT_H_PK] PRIMARY KEY CLUSTERED ([_PROJECT_HIST_ID]),
    CONSTRAINT [PIMS_PROJCT_H_UK] UNIQUE ([_PROJECT_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROJECT_NOTE_HIST
CREATE SEQUENCE [dbo].[PIMS_PROJECT_NOTE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROJECT_NOTE_HIST] (
    [_PROJECT_NOTE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROJ___PROJ__38845C1C] DEFAULT NEXT VALUE FOR [PIMS_PROJECT_NOTE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROJ__EFFEC__39788055] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROJECT_NOTE_ID] BIGINT NOT NULL,
    [PROJECT_ID] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PROJNT_H_PK] PRIMARY KEY CLUSTERED ([_PROJECT_NOTE_HIST_ID]),
    CONSTRAINT [PIMS_PROJNT_H_UK] UNIQUE ([_PROJECT_NOTE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROJECT_PROPERTY_HIST
CREATE SEQUENCE [dbo].[PIMS_PROJECT_PROPERTY_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROJECT_PROPERTY_HIST] (
    [_PROJECT_PROPERTY_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROJ___PROJ__3E3D3572] DEFAULT NEXT VALUE FOR [PIMS_PROJECT_PROPERTY_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROJ__EFFEC__3F3159AB] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROJECT_PROPERTY_ID] BIGINT NOT NULL,
    [PROJECT_ID] BIGINT NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRJPRP_H_PK] PRIMARY KEY CLUSTERED ([_PROJECT_PROPERTY_HIST_ID]),
    CONSTRAINT [PIMS_PRJPRP_H_UK] UNIQUE ([_PROJECT_PROPERTY_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROJECT_WORKFLOW_MODEL_HIST
CREATE SEQUENCE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROJECT_WORKFLOW_MODEL_HIST] (
    [_PROJECT_WORKFLOW_MODEL_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROJ___PROJ__43F60EC8] DEFAULT NEXT VALUE FOR [PIMS_PROJECT_WORKFLOW_MODEL_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROJ__EFFEC__44EA3301] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROJECT_WORKFLOW_MODEL_ID] BIGINT NOT NULL,
    [PROJECT_ID] BIGINT NOT NULL,
    [WORKFLOW_MODEL_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRWKMD_H_PK] PRIMARY KEY CLUSTERED ([_PROJECT_WORKFLOW_MODEL_HIST_ID]),
    CONSTRAINT [PIMS_PRWKMD_H_UK] UNIQUE ([_PROJECT_WORKFLOW_MODEL_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_ACTIVITY_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_ACTIVITY_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_ACTIVITY_HIST] (
    [_PROPERTY_ACTIVITY_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__49AEE81E] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_ACTIVITY_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__4AA30C57] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_ACTIVITY_ID] BIGINT NOT NULL,
    [ACTIVITY_ID] BIGINT,
    [PROPERTY_ID] BIGINT,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRPACT_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_ACTIVITY_HIST_ID]),
    CONSTRAINT [PIMS_PRPACT_H_UK] UNIQUE ([_PROPERTY_ACTIVITY_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_EVALUATION_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_EVALUATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_EVALUATION_HIST] (
    [_PROPERTY_EVALUATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__4F67C174] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_EVALUATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__505BE5AD] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_EVALUATION_ID] BIGINT NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [EVALUATION_DATE] DATE NOT NULL,
    [KEY] INTEGER NOT NULL,
    [VALUE] MONEY NOT NULL,
    [NOTE] NVARCHAR(1000),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRPEVL_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_EVALUATION_HIST_ID]),
    CONSTRAINT [PIMS_PRPEVL_H_UK] UNIQUE ([_PROPERTY_EVALUATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_HIST] (
    [_PROPERTY_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__55209ACA] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__5614BF03] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_ID] BIGINT NOT NULL,
    [PROPERTY_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROPERTY_CLASSIFICATION_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [ADDRESS_ID] BIGINT NOT NULL,
    [REGION_CODE] SMALLINT NOT NULL,
    [DISTRICT_CODE] SMALLINT NOT NULL,
    [PROPERTY_TENURE_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROPERTY_AREA_UNIT_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROPERTY_STATUS_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROPERTY_DATA_SOURCE_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [PROPERTY_DATA_SOURCE_EFFECTIVE_DATE] DATE NOT NULL,
    [NAME] NVARCHAR(250),
    [DESCRIPTION] NVARCHAR(2000),
    [PID] INTEGER NOT NULL,
    [PIN] INTEGER,
    [LAND_AREA] REAL NOT NULL,
    [ENCUMBRANCE_REASON] NVARCHAR(500),
    [IS_OWNED] BIT NOT NULL,
    [IS_PROPERTY_OF_INTEREST] BIT NOT NULL,
    [IS_VISIBLE_TO_OTHER_AGENCIES] BIT NOT NULL,
    [IS_SENSITIVE] BIT NOT NULL,
    [ZONING] NVARCHAR(50),
    [ZONING_POTENTIAL] NVARCHAR(50),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRPRTY_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_HIST_ID]),
    CONSTRAINT [PIMS_PRPRTY_H_UK] UNIQUE ([_PROPERTY_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_ORGANIZATION_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_ORGANIZATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_ORGANIZATION_HIST] (
    [_PROPERTY_ORGANIZATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__5AD97420] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_ORGANIZATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__5BCD9859] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_ORGANIZATION_ID] BIGINT NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [ORGANIZATION_ID] BIGINT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [IS_DISABLED] BIT,
    CONSTRAINT [PIMS_PRPORG_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_ORGANIZATION_HIST_ID]),
    CONSTRAINT [PIMS_PRPORG_H_UK] UNIQUE ([_PROPERTY_ORGANIZATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_PROPERTY_SERVICE_FILE_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_PROPERTY_SERVICE_FILE_HIST] (
    [_PROPERTY_PROPERTY_SERVICE_FILE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__60924D76] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_PROPERTY_SERVICE_FILE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__618671AF] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_PROPERTY_SERVICE_FILE_ID] BIGINT NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [PROPERTY_SERVICE_FILE_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRPRSF_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_PROPERTY_SERVICE_FILE_HIST_ID]),
    CONSTRAINT [PIMS_PRPRSF_H_UK] UNIQUE ([_PROPERTY_PROPERTY_SERVICE_FILE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_PROPERTY_SERVICE_FILE_HIST
CREATE SEQUENCE [dbo].[PIMS_PROPERTY_SERVICE_FILE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_PROPERTY_SERVICE_FILE_HIST] (
    [_PROPERTY_SERVICE_FILE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_PROP___PROP__664B26CC] DEFAULT NEXT VALUE FOR [PIMS_PROPERTY_SERVICE_FILE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_PROP__EFFEC__673F4B05] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [PROPERTY_SERVICE_FILE_ID] BIGINT NOT NULL,
    [PROPERTY_SERVICE_FILE_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_PRPSVC_H_PK] PRIMARY KEY CLUSTERED ([_PROPERTY_SERVICE_FILE_HIST_ID]),
    CONSTRAINT [PIMS_PRPSVC_H_UK] UNIQUE ([_PROPERTY_SERVICE_FILE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ROLE_CLAIM_HIST
CREATE SEQUENCE [dbo].[PIMS_ROLE_CLAIM_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ROLE_CLAIM_HIST] (
    [_ROLE_CLAIM_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ROLE___ROLE__6C040022] DEFAULT NEXT VALUE FOR [PIMS_ROLE_CLAIM_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ROLE__EFFEC__6CF8245B] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ROLE_CLAIM_ID] BIGINT NOT NULL,
    [ROLE_ID] BIGINT NOT NULL,
    [CLAIM_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ROLCLM_H_PK] PRIMARY KEY CLUSTERED ([_ROLE_CLAIM_HIST_ID]),
    CONSTRAINT [PIMS_ROLCLM_H_UK] UNIQUE ([_ROLE_CLAIM_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_ROLE_HIST
CREATE SEQUENCE [dbo].[PIMS_ROLE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_ROLE_HIST] (
    [_ROLE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_ROLE___ROLE__71BCD978] DEFAULT NEXT VALUE FOR [PIMS_ROLE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_ROLE__EFFEC__72B0FDB1] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [ROLE_ID] BIGINT NOT NULL,
    [ROLE_UID] UNIQUEIDENTIFIER NOT NULL,
    [KEYCLOAK_GROUP_ID] UNIQUEIDENTIFIER,
    [NAME] NVARCHAR(100) NOT NULL,
    [DESCRIPTION] NVARCHAR(500),
    [IS_PUBLIC] BIT NOT NULL,
    [IS_DISABLED] BIT NOT NULL,
    [SORT_ORDER] INTEGER NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_ROLE_H_PK] PRIMARY KEY CLUSTERED ([_ROLE_HIST_ID]),
    CONSTRAINT [PIMS_ROLE_H_UK] UNIQUE ([_ROLE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_TASK_HIST
CREATE SEQUENCE [dbo].[PIMS_TASK_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_TASK_HIST] (
    [_TASK_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_TASK___TASK__7775B2CE] DEFAULT NEXT VALUE FOR [PIMS_TASK_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_TASK__EFFEC__7869D707] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [TASK_ID] BIGINT NOT NULL,
    [TASK_TEMPLATE_ID] BIGINT NOT NULL,
    [ACTIVITY_ID] BIGINT,
    [USER_ID] BIGINT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_TASK_H_PK] PRIMARY KEY CLUSTERED ([_TASK_HIST_ID]),
    CONSTRAINT [PIMS_TASK_H_UK] UNIQUE ([_TASK_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_HIST
CREATE SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_HIST] (
    [_TASK_TEMPLATE_ACTIVITY_MODEL_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_TASK___TASK__7D2E8C24] DEFAULT NEXT VALUE FOR [PIMS_TASK_TEMPLATE_ACTIVITY_MODEL_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_TASK__EFFEC__7E22B05D] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [TASK_TEMPLATE_ACTIVITY_MODEL_ID] BIGINT NOT NULL,
    [TASK_TEMPLATE_ID] BIGINT NOT NULL,
    [ACTIVITY_MODEL_ID] BIGINT NOT NULL,
    [IS_MANDATORY] BIT NOT NULL,
    [IMPLEMENTATION_ORDER] SMALLINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_TSKTAM_H_PK] PRIMARY KEY CLUSTERED ([_TASK_TEMPLATE_ACTIVITY_MODEL_HIST_ID]),
    CONSTRAINT [PIMS_TSKTAM_H_UK] UNIQUE ([_TASK_TEMPLATE_ACTIVITY_MODEL_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_TASK_TEMPLATE_HIST
CREATE SEQUENCE [dbo].[PIMS_TASK_TEMPLATE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_TASK_TEMPLATE_HIST] (
    [_TASK_TEMPLATE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_TASK___TASK__02E7657A] DEFAULT NEXT VALUE FOR [PIMS_TASK_TEMPLATE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_TASK__EFFEC__03DB89B3] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [TASK_TEMPLATE_ID] BIGINT NOT NULL,
    [TASK_TEMPLATE_TYPE_CODE] NVARCHAR(40) NOT NULL,
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_TSKTMP_H_PK] PRIMARY KEY CLUSTERED ([_TASK_TEMPLATE_HIST_ID]),
    CONSTRAINT [PIMS_TSKTMP_H_UK] UNIQUE ([_TASK_TEMPLATE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_USER_HIST
CREATE SEQUENCE [dbo].[PIMS_USER_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_USER_HIST] (
    [_USER_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_USER___USER__08A03ED0] DEFAULT NEXT VALUE FOR [PIMS_USER_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_USER__EFFEC__09946309] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [USER_ID] BIGINT NOT NULL,
    [PERSON_ID] BIGINT NOT NULL,
    [BUSINESS_IDENTIFIER_VALUE] NVARCHAR(30) NOT NULL,
    [GUID_IDENTIFIER_VALUE] UNIQUEIDENTIFIER,
    [POSITION] NVARCHAR(100),
    [NOTE] NVARCHAR(1000),
    [LAST_LOGIN] DATETIME,
    [APPROVED_BY_ID] NVARCHAR(30),
    [ISSUE_DATE] DATETIME NOT NULL,
    [EXPIRY_DATE] DATETIME,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_USER_H_PK] PRIMARY KEY CLUSTERED ([_USER_HIST_ID]),
    CONSTRAINT [PIMS_USER_H_UK] UNIQUE ([_USER_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_USER_ORGANIZATION_HIST
CREATE SEQUENCE [dbo].[PIMS_USER_ORGANIZATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_USER_ORGANIZATION_HIST] (
    [_USER_ORGANIZATION_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_USER___USER__0E591826] DEFAULT NEXT VALUE FOR [PIMS_USER_ORGANIZATION_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_USER__EFFEC__0F4D3C5F] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [USER_ORGANIZATION_ID] BIGINT NOT NULL,
    [ORGANIZATION_ID] BIGINT NOT NULL,
    [USER_ID] BIGINT NOT NULL,
    [ROLE_ID] BIGINT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_USRORG_H_PK] PRIMARY KEY CLUSTERED ([_USER_ORGANIZATION_HIST_ID]),
    CONSTRAINT [PIMS_USRORG_H_UK] UNIQUE ([_USER_ORGANIZATION_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_USER_ROLE_HIST
CREATE SEQUENCE [dbo].[PIMS_USER_ROLE_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_USER_ROLE_HIST] (
    [_USER_ROLE_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_USER___USER__1411F17C] DEFAULT NEXT VALUE FOR [PIMS_USER_ROLE_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_USER__EFFEC__150615B5] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [USER_ROLE_ID] BIGINT NOT NULL,
    [USER_ID] BIGINT NOT NULL,
    [ROLE_ID] BIGINT NOT NULL,
    [IS_DISABLED] BIT,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_USERRL_H_PK] PRIMARY KEY CLUSTERED ([_USER_ROLE_HIST_ID]),
    CONSTRAINT [PIMS_USERRL_H_UK] UNIQUE ([_USER_ROLE_HIST_ID], [END_DATE_HIST])
)
GO

-- PIMS_WORKFLOW_MODEL_HIST
CREATE SEQUENCE [dbo].[PIMS_WORKFLOW_MODEL_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[PIMS_WORKFLOW_MODEL_HIST] (
    [_WORKFLOW_MODEL_HIST_ID] BIGINT CONSTRAINT [DF__PIMS_WORK___WORK__19CACAD2] DEFAULT NEXT VALUE FOR [PIMS_WORKFLOW_MODEL_H_ID_SEQ] NOT NULL,
    [EFFECTIVE_DATE_HIST] DATETIME CONSTRAINT [DF__PIMS_WORK__EFFEC__1ABEEF0B] DEFAULT getutcdate() NOT NULL,
    [END_DATE_HIST] DATETIME,
    [WORKFLOW_MODEL_ID] BIGINT NOT NULL,
    [WORKFLOW_MODEL_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [IS_DISABLED] BIT NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PIMS_WFLMDL_H_PK] PRIMARY KEY CLUSTERED ([_WORKFLOW_MODEL_HIST_ID]),
    CONSTRAINT [PIMS_WFLMDL_H_UK] UNIQUE ([_WORKFLOW_MODEL_HIST_ID], [END_DATE_HIST])
)
GO
