SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PIMSX_TableDefinitions](
	[TABLE_NAME] [nvarchar](255) NULL,
	[TABLE_ALIAS] [nvarchar](255) NULL,
	[DESCRIPTION] [nvarchar](max) NULL
)
GO

/* Insert table metadata Entries */

INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) 
VALUES 
  ('PIMS_ACTIVITY_MODEL','PIMS_ACTMDL')
, ('PIMS_WORKFLOW_MODEL_TYPE','PIMS_WFLMDT')
, ('PIMS_PROPERTY_TYPE','PIMS_PRPTYP')
, ('PIMS_REGION','PIMS_REGION')
, ('PIMS_COUNTRY','PIMS_CNTRY')
, ('PIMS_ADDRESS_USAGE_TYPE','PIMS_ADUSGT')
, ('PIMS_CLAIM','PIMS_CLMTYP')
, ('PIMS_PROJECT_TYPE','PIMS_PRJTYP')
, ('PIMS_TASK_TEMPLATE_TYPE','PIMS_TSKTMT')
, ('PIMS_ORGANIZATION_TYPE','PIMS_ORGTYP')
, ('PIMS_ACCESS_REQUEST_STATUS_TYPE','PIMS_ARQSTT')
, ('PIMS_PROJECT_STATUS_TYPE','PIMS_PRJSTY')
, ('PIMS_PROPERTY_SERVICE_FILE_TYPE','PIMS_PRSVFT')
, ('PIMS_PROJECT_RISK_TYPE','PIMS_PRJRSK')
, ('PIMS_PROJECT_TIER_TYPE','PIMS_PROJTR')
, ('PIMS_ROLE','PIMS_ROLE')
, ('PIMS_PROPERTY_CLASSIFICATION_TYPE','PIMS_PRPCLT')
, ('PIMS_CONTACT_METHOD_TYPE','PIMS_CNTMTT')
, ('PIMS_PROPERTY_TENURE_TYPE','PIMS_PRPTNR')
, ('PIMS_AREA_UNIT_TYPE','PIMS_ARUNIT')
, ('PIMS_PROPERTY_DATA_SOURCE_TYPE','PIMS_PIDSRT')
, ('PIMS_PROPERTY_STATUS_TYPE','PIMS_PRPSTS')
, ('PIMS_ORG_IDENTIFIER_TYPE','PIMS_ORGIDT')
, ('PIMS_PROJECT','PIMS_PROJCT')
, ('PIMS_PROPERTY_SERVICE_FILE','PIMS_PRPSVC')
, ('PIMS_TASK_TEMPLATE','PIMS_TSKTMP')
, ('PIMS_WORKFLOW_MODEL','PIMS_WFLMDL')
, ('PIMS_DISTRICT','PIMS_DSTRCT')
, ('PIMS_PROVINCE_STATE','PIMS_PROVNC')
, ('PIMS_ROLE_CLAIM','PIMS_ROLCLM')
, ('PIMS_PROJECT_NOTE','PIMS_PROJNT')
, ('PIMS_TASK_TEMPLATE_ACTIVITY_MODEL','PIMS_TSKTAM')
, ('PIMS_PROJECT_WORKFLOW_MODEL','PIMS_PRWKMD')
, ('PIMS_ADDRESS','PIMS_ADDRSS')
, ('PIMS_ORGANIZATION','PIMS_ORG')
, ('PIMS_PERSON','PIMS_PERSON')
, ('PIMS_PERSON_ORGANIZATION','PIMS_PERORG')
, ('PIMS_CONTACT_METHOD','PIMS_CNTMTH')
, ('PIMS_PROPERTY','PIMS_PRPRTY')
, ('PIMS_ACTIVITY','PIMS_ACTVTY')
, ('PIMS_USER','PIMS_USER')
, ('PIMS_PROJECT_PROPERTY','PIMS_PRJPRP')
, ('PIMS_PROPERTY_ACTIVITY','PIMS_PRPACT')
, ('PIMS_USER_ORGANIZATION','PIMS_USRORG')
, ('PIMS_ACCESS_REQUEST','PIMS_ACRQST')
, ('PIMS_ACCESS_REQUEST_ORGANIZATION','PIMS_ACRQOR')
, ('PIMS_USER_ROLE','PIMS_USERRL')
, ('PIMS_PROPERTY_PROPERTY_SERVICE_FILE','PIMS_PRPRSF')
, ('PIMS_PROPERTY_ORGANIZATION','PIMS_PRPORG')
, ('PIMS_PROPERTY_EVALUATION','PIMS_PRPEVL')
, ('PIMS_TASK','PIMS_TASK');
