-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-01-02
-- Updates:
--	2020-01-02:  column changes supporting sprint 4
--	2019-12-12:  tables supporting sprints 4 & 5
-- 	2019-11-27:  tables supporting SPrint 3 & 4
--  2020-02-29:  added HIST attribute to differentiate
--  2021-05-10:  Modified for PIMS (Doug Filteau)
-- Description:	Temporary table metadata table for use in generation of triggers & hist tables
-- =============================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PIMSX_TableDefinitions](
	[TABLE_NAME] [nvarchar](255) NULL,
	[TABLE_ALIAS] [nvarchar](255) NULL,
	[DESCRIPTION] [nvarchar](max) NULL
)
GO

/* Insert table metadata Entries */

INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ACCESS_REQUEST','PIMS_ACCRQT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ACCESS_REQUEST_AGENCY','PIMS_ACRQAG');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ACCESS_REQUEST_ROLE','PIMS_ACCRQR');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ADDRESS','PIMS_ADDR');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ADMINISTRATIVE_AREA','PIMS_ADMINA');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_AGENCY','PIMS_AGNCY');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING','PIMS_BUILDG');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING_CONSTRUCTION_TYPE','PIMS_BLCNTY');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING_EVALUATION','PIMS_BLDEVL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING_FISCAL','PIMS_BLDFSC');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING_OCCUPANT_TYPE','PIMS_BLOCCT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_BUILDING_PREDOMINATE_USE','PIMS_BLPRDU');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_CLAIM','PIMS_CLAIM');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_MIGRATION_HISTORY','PIMS_MIGHST');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_NOTIFICATION_QUEUE','PIMS_NOTIFQ');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_NOTIFICATION_TEMPLATE','PIMS_NTTMPL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PARCEL','PIMS_PARCEL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PARCEL_BUILDING','PIMS_PRCLBL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PARCEL_EVALUATION','PIMS_PREVAL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PARCEL_FISCAL','PIMS_PRFSCL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PARCEL_PARCEL','PIMS_PRCPRC');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_STATUS_NOTIFICATION','PIMS_PRSTNT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_STATUS_TRANSITION','PIMS_PRSTTX');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT','PIMS_PROJCT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_AGENCY_RESPONSE','PIMS_PRAGRP');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_NOTE','PIMS_PROJNT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_NUMBER','PIMS_PRJNUM');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_PROPERTIES','PIMS_PRJPRP');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_REPORT','PIMS_PRJRPT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_RISK','PIMS_PRJRSK');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_SNAPSHOT','PIMS_PRJSNP');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_STATUS','PIMS_PRJSTS');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROJECT_TASK','PIMS_PRJTSK');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROPERTY_CLASSIFICATION','PIMS_PRPCLS');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROPERTY_TYPE','PIMS_PRPTYP');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_PROVINCE','PIMS_PROV');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ROLE','PIMS_ROLE');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_ROLE_CLAIM','PIMS_ROLCLM');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_TASK','PIMS_TASK');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_TENANT','PIMS_TENANT');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_TIER_LEVEL','PIMS_TRLEVL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_USER','PIMS_USER');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_USER_AGENCY','PIMS_USRAGC');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_USER_ROLE','PIMS_USRROL');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_WORKFLOW','PIMS_WRKFLW');
INSERT INTO PIMSX_TableDefinitions (TABLE_NAME, TABLE_ALIAS) VALUES ('PIMS_WORKFLOW_PROJECT_STATUS','PIMS_WRPRST');
