export enum ProjectStatusTypes {
  Draft = 'DR',
  DraftProperties = 'DR-P',
  DraftInformation = 'DR-I',
  DraftDocuments = 'DR-D',
  DraftApproval = 'DR-A',
  DraftReview = 'DR-RE',
  Submitted = 'AS-I',
  SubmittedExemption = 'AS-EXE',
  AssessDocuments = 'AS-D',
  AssessAppraisal = 'AS-AP',
  AssessFirstNationConsultation = 'AS-FNC',
  AssessExemption = 'AS-EXP',
  ApprovedForERP = 'AP-ERP',
  ApprovedForExemption = 'AP-EXE',
  Denied = 'DE',
  TransferredWithinGRE = 'T-GRE',
  ApprovedForSPL = 'AP-SPL',
  ApprovedNotInSPL = 'AP-!SPL',
  Cancelled = 'CA',
  InERP = 'ERP-ON',
  OnHold = 'ERP-OH',
  Disposed = 'DIS',
  SPLPreMarketing = 'SPL-PM',
  SPLMarketing = 'SPL-M',
  SPLContractInPlaceConditional = 'SPL-CIP-C',
  SPLContractInPlaceUnconditional = 'SPL-CIP-U',
}
