DELETE
FROM  PIMS_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_INSTANCE] ([FILE_ID], [ACTIVITY_TEMPLATE_ID], [ACTIVITY_INSTANCE_STATUS_TYPE_CODE], [DESCRIPTION], [ACTIVITY_DATA_JSON], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES(1, 1, N'NOSTART', N'DeeDee Billy', N'<Empty>', 1)
GO
