ALTER TABLE PIMS_LEASE_HIST ALTER COLUMN LEASE_PAY_RVBL_TYPE_CODE NVARCHAR(20) NULL
  ALTER TABLE PIMS_LEASE_HIST ALTER COLUMN LEASE_INITIATOR_TYPE_CODE NVARCHAR(20) NULL
  ALTER TABLE PIMS_LEASE_HIST ALTER COLUMN LEASE_RESPONSIBILITY_TYPE_CODE NVARCHAR(20) NULL