kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: mayan-sync
  annotations:
    description: "This template creates a task to deploy mayan configuration."
    tags: "mayan,upgrade,document"
objects:
  - kind: TaskRun
    apiVersion: tekton.dev/v1beta1
    metadata:
        generateName: mayan-sync-
        namespace: ${NAMESPACE}
    spec:
      params:
        - name: TOKEN_URL
          value: ${TOKEN_URL}
        - name: CLIENT_ID
          value: ${CLIENT_ID}
        - name: MAYAN_SYNC_URL
          value: ${MAYAN_SYNC_URL}
        - name: KEYCLOAK_SECRET_NAME
          value: ${KEYCLOAK_SECRET_NAME}
      serviceAccountName: pipeline
      taskRef:
        kind: Task
        name: mayan-sync
parameters:
  - name: TOKEN_URL
    description: The keycloak token endpoint
    required: true
  - name: CLIENT_ID
    description: The id of the keycloak client
    required: true
  - name: MAYAN_SYNC_URL
    description: The endpoint that will be used to sync the documents
    required: true
  - name: KEYCLOAK_SECRET_NAME
    description: The name of the Openshift secret that contains the keycloak credentials
    required: true
  - name: NAMESPACE
    description: The namespace to deploy this template
    required: true
