UPDATE PIMS_ROLE SET IS_DISABLED = 0, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE NAME IN ('Organization Administrator', 'Undetermined', 'Real Estate Manager', 'Real Estate Analyst')
GO

DECLARE @functional BIGINT;
DECLARE @readOnly BIGINT;
DECLARE @rem BIGINT;
DECLARE @rea BIGINT;
SELECT @functional = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Functional';
SELECT @readOnly = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Read Only';
SELECT @rem = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Real Estate Manager';
SELECT @rea = ROLE_ID FROM PIMS_ROLE WHERE NAME = 'Real Estate Analyst';

UPDATE PIMS_USER_ROLE SET ROLE_ID = @rea, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ROLE_ID = @functional;
UPDATE PIMS_USER_ROLE SET ROLE_ID = @rem, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1 WHERE ROLE_ID = @readOnly;

DELETE FROM PIMS_USER_ROLE WHERE ROLE_ID IN (SELECT ROLE_ID FROM PIMS_ROLE WHERE NAME IN ('Finance', 'Functional', 'Functional (Restricted)', 'Read Only'));
DELETE FROM PIMS_ROLE WHERE NAME IN ('Finance', 'Functional', 'Functional (Restricted)', 'Read Only');
GO