PRINT N'Adding DB Audit Columns'

ALTER TABLE dbo.[PIMS_PROPERTY_IMPROVEMENT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_LEASE_RESPONSIBILITY_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

    ALTER TABLE dbo.[PIMS_LEASE_INITIATOR_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_PROPERTY_IMPROVEMENT_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()