DELETE
FROM   PIMS_PROPERTY_OPERATION
GO

DECLARE @SeqVlu BIGINT -- VARCHAR(1000)
SELECT NEXT VALUE FOR PIMS_PROPERTY_OPERATION_NO_SEQ
SET @SeqVlu = CONVERT(bigint, (SELECT current_value FROM sys.sequences WHERE name = 'PIMS_PROPERTY_OPERATION_NO_SEQ'))

INSERT INTO dbo.PIMS_PROPERTY_OPERATION (DESTINATION_PROPERTY_ID, SOURCE_PROPERTY_ID, PROPERTY_OPERATION_TYPE_CODE, PROPERTY_OPERATION_NO, OPERATION_DT, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
  VALUES
    ( 1,  2, N'CONSOLIDATE', @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'), 
    ( 1,  3, N'CONSOLIDATE', @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    ( 1,  4, N'CONSOLIDATE', @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    ( 1,  5, N'CONSOLIDATE', @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    ( 1,  6, N'CONSOLIDATE', @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');

SELECT NEXT VALUE FOR PIMS_PROPERTY_OPERATION_NO_SEQ
SET @SeqVlu = CONVERT(bigint, (SELECT current_value FROM sys.sequences WHERE name = 'PIMS_PROPERTY_OPERATION_NO_SEQ'))

INSERT INTO dbo.PIMS_PROPERTY_OPERATION (DESTINATION_PROPERTY_ID, SOURCE_PROPERTY_ID, PROPERTY_OPERATION_TYPE_CODE, PROPERTY_OPERATION_NO, OPERATION_DT, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
  VALUES
    ( 7, 13, N'SUBDIVIDE',   @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    ( 8, 13, N'SUBDIVIDE',   @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    ( 9, 13, N'SUBDIVIDE',   @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    (10, 14, N'SUBDIVIDE',   @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER'),
    (11, 14, N'SUBDIVIDE',   @SeqVlu, getutcdate(), 0, 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');

SELECT NEXT VALUE FOR PIMS_PROPERTY_OPERATION_NO_SEQ
SET @SeqVlu = CONVERT(bigint, (SELECT current_value FROM sys.sequences WHERE name = 'PIMS_PROPERTY_OPERATION_NO_SEQ'))

INSERT INTO dbo.PIMS_PROPERTY_OPERATION (DESTINATION_PROPERTY_ID, SOURCE_PROPERTY_ID, PROPERTY_OPERATION_TYPE_CODE, PROPERTY_OPERATION_NO, OPERATION_DT, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
  VALUES
    (16, 15, N'SUBDIVIDE',   @SeqVlu, getutcdate()+1, 0, 1, getutcdate()+1, N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate()+1, N'FOUGSTER', NEWID(), N'FOUGSTER'),
    (17, 15, N'SUBDIVIDE',   @SeqVlu, getutcdate()+1, 0, 1, getutcdate()+1, N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate()+1, N'FOUGSTER', NEWID(), N'FOUGSTER');

SELECT NEXT VALUE FOR PIMS_PROPERTY_OPERATION_NO_SEQ
SET @SeqVlu = CONVERT(bigint, (SELECT current_value FROM sys.sequences WHERE name = 'PIMS_PROPERTY_OPERATION_NO_SEQ'))

INSERT INTO dbo.PIMS_PROPERTY_OPERATION (DESTINATION_PROPERTY_ID, SOURCE_PROPERTY_ID, PROPERTY_OPERATION_TYPE_CODE, PROPERTY_OPERATION_NO, OPERATION_DT, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
  VALUES
    (1, 16, N'CONSOLIDATE',  @SeqVlu, getutcdate()+2, 0, 1, getutcdate()+2, N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate()+2, N'FOUGSTER', NEWID(), N'FOUGSTER'),
    (1, 17, N'CONSOLIDATE',  @SeqVlu, getutcdate()+2, 0, 1, getutcdate()+2, N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate()+2, N'FOUGSTER', NEWID(), N'FOUGSTER');
GO