INSERT INTO [dbo].[PIMS_SECURITY_DEPOSIT_RETURN_HOLDER]
	(
	 [SECURITY_DEPOSIT_RETURN_ID]
	,[PERSON_ID]
	,[CONCURRENCY_CONTROL_NUMBER]
	)
VALUES
	(
	  (SELECT TOP 1 SECURITY_DEPOSIT_RETURN_ID FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID = 1)
	, (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Wilson')
	, 1
  ),
	(
	  (SELECT TOP 1 SECURITY_DEPOSIT_RETURN_ID FROM PIMS_SECURITY_DEPOSIT_RETURN WHERE SECURITY_DEPOSIT_ID = 2)
	, (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Mouse')
	, 1
  )
