DELETE
FROM   PIMS_DOCUMENT_QUEUE
GO

DECLARE @i   INT = 0
DECLARE @max INT = 25

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DOCUMENT_QUEUE (DOCUMENT_ID, DOCUMENT_QUEUE_STATUS_TYPE_CODE, DATA_SOURCE_TYPE_CODE, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
	  VALUES((SELECT TOP 1 DOCUMENT_ID FROM PIMS_DOCUMENT ORDER BY NEWID()), (SELECT TOP 1 DOCUMENT_QUEUE_STATUS_TYPE_CODE FROM PIMS_DOCUMENT_QUEUE_STATUS_TYPE ORDER BY NEWID()), (SELECT TOP 1 DATA_SOURCE_TYPE_CODE FROM PIMS_DATA_SOURCE_TYPE ORDER BY NEWID()), 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER')
  END
GO
