DELETE
FROM   PIMS_PROPERTY_NOTE
GO

DECLARE @i   INT = 0
DECLARE @max INT = 500

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_PROPERTY_NOTE (PROPERTY_ID, NOTE_ID)
    VALUES
      ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()), (SELECT TOP 1 NOTE_ID FROM PIMS_NOTE ORDER BY NEWID()))
  END
GO
