DELETE
FROM   PIMS_MANAGEMENT_FILE_CONTACT
GO

-- Load random person
DECLARE @i   INT = 0
DECLARE @max INT = 30

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_MANAGEMENT_FILE_CONTACT (MANAGEMENT_FILE_ID, PERSON_ID, PURPOSE)
    VALUES
      ((SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 SUBSTRING(NOTE_TXT, 1, 50) FROM PIMS_NOTE ORDER BY NEWID()))
  END
GO

-- Load random person
DECLARE @i   INT = 0
DECLARE @max INT = 30

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_MANAGEMENT_FILE_CONTACT (MANAGEMENT_FILE_ID, ORGANIZATION_ID, PRIMARY_CONTACT_ID, PURPOSE)
    VALUES
      ((SELECT TOP 1 MANAGEMENT_FILE_ID FROM PIMS_MANAGEMENT_FILE ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_PERSON_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 SUBSTRING(NOTE_TXT, 1, 50) FROM PIMS_NOTE ORDER BY NEWID()))
  END
GO
