/* -----------------------------------------------------------------------------
Create and populate the temporary TMP_COMP_REQ_LEASE_PAYEE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Feb-12  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Create the tempoarary table
PRINT N'Create the tempoarary table'
GO
CREATE TABLE dbo.TMP_COMP_REQ_LEASE_PAYEE (
    COMP_REQ_LEASE_PAYEE_ID BIGINT NOT NULL,
    COMPENSATION_REQUISITION_ID BIGINT NOT NULL,
    LEASE_STAKEHOLDER_ID BIGINT,
    LEASE_LICENSE_TEAM_ID BIGINT,
    CONCURRENCY_CONTROL_NUMBER BIGINT NOT NULL,
    APP_CREATE_TIMESTAMP DATETIME NOT NULL,
    APP_CREATE_USERID NVARCHAR(30) NOT NULL,
    APP_CREATE_USER_GUID UNIQUEIDENTIFIER,
    APP_CREATE_USER_DIRECTORY NVARCHAR(30) NOT NULL,
    APP_LAST_UPDATE_TIMESTAMP DATETIME NOT NULL,
    APP_LAST_UPDATE_USERID NVARCHAR(30) NOT NULL,
    APP_LAST_UPDATE_USER_GUID UNIQUEIDENTIFIER,
    APP_LAST_UPDATE_USER_DIRECTORY NVARCHAR(30) NOT NULL,
    DB_CREATE_TIMESTAMP DATETIME NOT NULL,
    DB_CREATE_USERID NVARCHAR(30) NOT NULL,
    DB_LAST_UPDATE_TIMESTAMP DATETIME NOT NULL,
    DB_LAST_UPDATE_USERID NVARCHAR(30) NOT NULL)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_LEASE_STAKEHOLDER_COMP_REQ data to the TMP_LEASE_STAKEHOLDER_COMP_REQ table
PRINT N'Migrate the PIMS_COMP_REQ_PAYEE data to the TMP_COMP_REQ_PAYEE table'
GO
INSERT INTO dbo.TMP_COMP_REQ_LEASE_PAYEE (COMP_REQ_LEASE_PAYEE_ID, COMPENSATION_REQUISITION_ID, LEASE_STAKEHOLDER_ID, LEASE_LICENSE_TEAM_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT COMP_REQ_LEASE_PAYEE_ID
       , COMPENSATION_REQUISITION_ID
       , LEASE_STAKEHOLDER_ID
       , LEASE_LICENSE_TEAM_ID
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.PIMS_COMP_REQ_LEASE_PAYEE
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
