/* -----------------------------------------------------------------------------
Migrate the data from the affected_TYPE tables to the renamed/recreated _TYP 
equivalent tables.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Mar-24  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

CREATE TABLE [dbo].[TMP_PROP_PROP_ROAD_TYP] (
    [PROP_PROP_ROAD_TYPE_ID] BIGINT CONSTRAINT [PRPRRT2_PROP_PROP_ROAD_TYPE_ID_DEF] DEFAULT NEXT VALUE FOR [PIMS_PROP_PROP_ROAD_TYPE_ID_SEQ] NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [PROPERTY_ROAD_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT CONSTRAINT [PRPRRT2_CONCURRENCY_CONTROL_NUMBER_DEF] DEFAULT 1 NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRRT2_APP_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRRT2_APP_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRRT2_APP_CREATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRRT2_APP_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRRT2_APP_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRRT2_APP_LAST_UPDATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRRT2_DB_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRRT2_DB_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRRT2_DB_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRRT2_DB_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    CONSTRAINT [PRPRRT2_PK] PRIMARY KEY CLUSTERED ([PROP_PROP_ROAD_TYPE_ID]),
    CONSTRAINT [PRPRRT2_PROP_ROAD_TYPE_TUC] UNIQUE ([PROPERTY_ROAD_TYPE_CODE], [PROPERTY_ID])
)
GO

CREATE TABLE [dbo].[TMP_PROP_PROP_ANOMALY_TYP] (
    [PROP_PROP_ANOMALY_TYPE_ID] BIGINT CONSTRAINT [PRPRAT2_PROP_PROP_ANOMALY_TYPE_ID_DEF] DEFAULT NEXT VALUE FOR [PIMS_PROP_PROP_ANOMALY_TYPE_ID_SEQ] NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [PROPERTY_ANOMALY_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT CONSTRAINT [PRPRAT2_CONCURRENCY_CONTROL_NUMBER_DEF] DEFAULT 1 NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRAT2_APP_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRAT2_APP_CREATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRAT2_APP_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRAT2_APP_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRAT2_APP_LAST_UPDATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRAT2_APP_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRAT2_DB_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRAT2_DB_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRAT2_DB_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRAT2_DB_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    CONSTRAINT [PRPRAT2_PK] PRIMARY KEY CLUSTERED ([PROP_PROP_ANOMALY_TYPE_ID]),
    CONSTRAINT [PRPRAT2_PROP_ANOMALY_TYPE_TUC] UNIQUE ([PROPERTY_ANOMALY_TYPE_CODE], [PROPERTY_ID])
)
GO

CREATE TABLE [dbo].[TMP_PROP_PROP_TENURE_TYP] (
    [PROP_PROP_TENURE_TYPE_ID] BIGINT CONSTRAINT [PRPRTT2_PROP_PROP_TENURE_TYPE_ID_DEF] DEFAULT NEXT VALUE FOR [PIMS_PROP_PROP_TENURE_TYPE_ID_SEQ] NOT NULL,
    [PROPERTY_ID] BIGINT NOT NULL,
    [PROPERTY_TENURE_TYPE_CODE] NVARCHAR(20) CONSTRAINT [PRPRTT2_PROPERTY_TENURE_TYPE_CODE_DEF] DEFAULT 'UNKNOWN' NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT CONSTRAINT [PRPRTT2_CONCURRENCY_CONTROL_NUMBER_DEF] DEFAULT 1 NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRTT2_APP_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRTT2_APP_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRTT2_APP_CREATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRTT2_APP_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRTT2_APP_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRPRTT2_APP_LAST_UPDATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRTT2_DB_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRTT2_DB_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRPRTT2_DB_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRPRTT2_DB_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    CONSTRAINT [PRPRTT2_PK] PRIMARY KEY CLUSTERED ([PROP_PROP_TENURE_TYPE_ID]),
    CONSTRAINT [PRPRTT2_PROP_PROP_TENURE_TUC] UNIQUE ([PROPERTY_TENURE_TYPE_CODE], [PROPERTY_ID])
)
GO

CREATE TABLE [dbo].[TMP_PRF_PROP_RESEARCH_PURPOSE_TYP] (
    [PRF_PROP_RESEARCH_PURPOSE_ID] BIGINT CONSTRAINT [PRSPRP2_PRF_PROP_RESEARCH_PURPOSE_ID_DEF] DEFAULT NEXT VALUE FOR [PIMS_PRF_PROP_RESEARCH_PURPOSE_ID_SEQ] NOT NULL,
    [PROPERTY_RESEARCH_FILE_ID] BIGINT,
    [PROP_RESEARCH_PURPOSE_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT CONSTRAINT [PRSPRP2_CONCURRENCY_CONTROL_NUMBER_DEF] DEFAULT 1 NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRSPRP2_APP_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRSPRP2_APP_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRSPRP2_APP_CREATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRSPRP2_APP_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRSPRP2_APP_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PRSPRP2_APP_LAST_UPDATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PRSPRP2_DB_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PRSPRP2_DB_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PRSPRP2_DB_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PRSPRP2_DB_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    CONSTRAINT [PRSPRP2_PK] PRIMARY KEY CLUSTERED ([PRF_PROP_RESEARCH_PURPOSE_ID]),
    CONSTRAINT [PRSPRP2_PROP_PURPOSE_TUC] UNIQUE ([PROP_RESEARCH_PURPOSE_TYPE_CODE], [PROPERTY_RESEARCH_FILE_ID])
)
GO

CREATE TABLE [dbo].[TMP_PROP_INTHLDR_INTEREST_TYP] (
    [PROP_INTHLDR_INTEREST_TYPE_ID] BIGINT CONSTRAINT [PIHITY2_PROP_INTHLDR_INTEREST_TYPE_ID_DEF] DEFAULT NEXT VALUE FOR [PIMS_PROP_INTHLDR_INTEREST_TYPE_ID_SEQ] NOT NULL,
    [PIMS_INTHLDR_PROP_INTEREST_ID] BIGINT NOT NULL,
    [INTEREST_HOLDER_INTEREST_TYPE_CODE] NVARCHAR(20) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT CONSTRAINT [PIHITY2_CONCURRENCY_CONTROL_NUMBER_DEF] DEFAULT 1 NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PIHITY2_APP_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PIHITY2_APP_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_CREATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PIHITY2_APP_CREATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PIHITY2_APP_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [APP_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PIHITY2_APP_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER,
    [APP_LAST_UPDATE_USER_DIRECTORY] NVARCHAR(30) CONSTRAINT [PIHITY2_APP_LAST_UPDATE_USER_DIRECTORY_DEF] DEFAULT user_name() NOT NULL,
    [DB_CREATE_TIMESTAMP] DATETIME CONSTRAINT [PIHITY2_DB_CREATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_CREATE_USERID] NVARCHAR(30) CONSTRAINT [PIHITY2_DB_CREATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    [DB_LAST_UPDATE_TIMESTAMP] DATETIME CONSTRAINT [PIHITY2_DB_LAST_UPDATE_TIMESTAMP_DEF] DEFAULT getutcdate() NOT NULL,
    [DB_LAST_UPDATE_USERID] NVARCHAR(30) CONSTRAINT [PIHITY2_DB_LAST_UPDATE_USERID_DEF] DEFAULT user_name() NOT NULL,
    CONSTRAINT [PIHITY2_PK] PRIMARY KEY CLUSTERED ([PROP_INTHLDR_INTEREST_TYPE_ID])
)
GO

-- Migrate the PIMS_PROP_PROP_ROAD_TYPE table data.
PRINT N'Migrate the PIMS_PROP_PROP_ROAD_TYPE table data.'
GO
INSERT INTO [dbo].[TMP_PROP_PROP_ROAD_TYP]([PROP_PROP_ROAD_TYPE_ID], [PROPERTY_ID], [PROPERTY_ROAD_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_ROAD_TYPE_ID], [PROPERTY_ID], [PROPERTY_ROAD_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[PIMS_PROP_PROP_ROAD_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_PROP_ANOMALY_TYPE table data.
PRINT N'Migrate the PIMS_PROP_PROP_ANOMALY_TYPE table data.'
GO
INSERT INTO [dbo].[TMP_PROP_PROP_ANOMALY_TYP]([PROP_PROP_ANOMALY_TYPE_ID], [PROPERTY_ID], [PROPERTY_ANOMALY_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_ANOMALY_TYPE_ID], [PROPERTY_ID], [PROPERTY_ANOMALY_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[PIMS_PROP_PROP_ANOMALY_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_PROP_TENURE_TYPE table data.
PRINT N'Migrate the PIMS_PROP_PROP_TENURE_TYPE table data.'
GO
INSERT INTO [dbo].[TMP_PROP_PROP_TENURE_TYP]([PROP_PROP_TENURE_TYPE_ID], [PROPERTY_ID], [PROPERTY_TENURE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_TENURE_TYPE_ID], [PROPERTY_ID], [PROPERTY_TENURE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[PIMS_PROP_PROP_TENURE_TYP]
GO

-- Migrate the PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE table data.
PRINT N'Migrate the PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE table data.'
GO
INSERT INTO [dbo].[TMP_PRF_PROP_RESEARCH_PURPOSE_TYP]([PRF_PROP_RESEARCH_PURPOSE_ID], [PROPERTY_RESEARCH_FILE_ID], [PROP_RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PRF_PROP_RESEARCH_PURPOSE_ID], [PROPERTY_RESEARCH_FILE_ID], [PROP_RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[PIMS_PRF_PROP_RESEARCH_PURPOSE_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_INTHLDR_INTEREST_TYPE table data.
PRINT N'Migrate the PIMS_PROP_INTHLDR_INTEREST_TYPE table data.'
GO
INSERT INTO [dbo].[TMP_PROP_INTHLDR_INTEREST_TYP]([PROP_INTHLDR_INTEREST_TYPE_ID], [PIMS_INTHLDR_PROP_INTEREST_ID], [INTEREST_HOLDER_INTEREST_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_INTHLDR_INTEREST_TYPE_ID], [PIMS_INTHLDR_PROP_INTEREST_ID], [INTEREST_HOLDER_INTEREST_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[PIMS_PROP_INTHLDR_INTEREST_TYP]
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
