SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF EXISTS(SELECT * 
          FROM   SYS.INDEXES 
          WHERE  NAME = 'PLYFAB_PID_NUMBER_IDX' 
             AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    DROP INDEX IF EXISTS [PLYFAB_PID_NUMBER_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC]
    END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF EXISTS(SELECT * 
          FROM   SYS.INDEXES 
          WHERE  NAME = 'PLYFAB_PLAN_NUMBER_IDX' 
             AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    DROP INDEX IF EXISTS [PLYFAB_PLAN_NUMBER_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC]
    END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF EXISTS(SELECT * 
          FROM   SYS.INDEXES 
          WHERE  NAME = 'PLYFAB_SHAPE_IDX' 
             AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    DROP INDEX [PLYFAB_SHAPE_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC]
    END                   
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
