/* -----------------------------------------------------------------------------
Drop PIMS_EXPROPRIATION_NOTICE
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jan-29  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPNOT_I_S_U_TR
PRINT N'Drop trigger dbo.PIMS_EXPNOT_I_S_U_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPNOT_I_S_U_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPNOT_I_S_I_TR
PRINT N'Drop trigger dbo.PIMS_EXPNOT_I_S_I_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPNOT_I_S_I_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPNOT_A_S_IUD_TR
PRINT N'Drop trigger dbo.PIMS_EXPNOT_A_S_IUD_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPNOT_A_S_IUD_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_ACQOWN_PIM_EXPNOT_FK
PRINT N'Drop foreign key constraint dbo.PIM_ACQOWN_PIM_EXPNOT_FK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE]
	DROP CONSTRAINT IF EXISTS [PIM_ACQOWN_PIM_EXPNOT_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_ACQNFL_PIM_EXPNOT_FK
PRINT N'Drop foreign key constraint dbo.PIM_ACQNFL_PIM_EXPNOT_FK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE]
	DROP CONSTRAINT IF EXISTS [PIM_ACQNFL_PIM_EXPNOT_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_INTHLD_PIM_EXPNOT_FK
PRINT N'Drop foreign key constraint dbo.PIM_INTHLD_PIM_EXPNOT_FK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE]
	DROP CONSTRAINT IF EXISTS [PIM_INTHLD_PIM_EXPNOT_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPNOT_INTEREST_HOLDER_ID_IDX
PRINT N'Drop index dbo.EXPNOT_INTEREST_HOLDER_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE].[EXPNOT_INTEREST_HOLDER_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPNOT_COMPENSATION_REQUISITION_ID_IDX
PRINT N'Drop index dbo.EXPNOT_COMPENSATION_REQUISITION_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE].[EXPNOT_COMPENSATION_REQUISITION_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPNOT_ACQUISITION_OWNER_ID_IDX
PRINT N'Drop index dbo.EXPNOT_ACQUISITION_OWNER_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE].[EXPNOT_ACQUISITION_OWNER_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPNOT_ACQUISITION_FILE_ID_IDX
PRINT N'Drop index dbo.EXPNOT_ACQUISITION_FILE_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE].[EXPNOT_ACQUISITION_FILE_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop unique constraint dbo.PIMS_EXPNOT_H_UK
PRINT N'Drop unique constraint dbo.PIMS_EXPNOT_H_UK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE_HIST]
	DROP CONSTRAINT IF EXISTS [PIMS_EXPNOT_H_UK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop primary key constraint dbo.PIMS_EXPNOT_H_PK
PRINT N'Drop primary key constraint dbo.PIMS_EXPNOT_H_PK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE_HIST]
	DROP CONSTRAINT IF EXISTS [PIMS_EXPNOT_H_PK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop primary key constraint dbo.EXPNOT_PK
PRINT N'Drop primary key constraint dbo.EXPNOT_PK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_NOTICE]
	DROP CONSTRAINT IF EXISTS [EXPNOT_PK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.PIMS_EXPROPRIATION_NOTICE
PRINT N'Drop table dbo.PIMS_EXPROPRIATION_NOTICE'
GO
DROP TABLE IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.PIMS_EXPROPRIATION_NOTICE_HIST
PRINT N'Drop table dbo.PIMS_EXPROPRIATION_NOTICE_HIST'
GO
DROP TABLE IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE_HIST]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop sequence dbo.PIMS_EXPROPRIATION_NOTICE_H_ID_SEQ
PRINT N'Drop sequence dbo.PIMS_EXPROPRIATION_NOTICE_H_ID_SEQ'
GO
DROP SEQUENCE IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE_H_ID_SEQ]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop sequence dbo.PIMS_EXPROPRIATION_NOTICE_ID_SEQ
PRINT N'Drop sequence dbo.PIMS_EXPROPRIATION_NOTICE_ID_SEQ'
GO
DROP SEQUENCE IF EXISTS [dbo].[PIMS_EXPROPRIATION_NOTICE_ID_SEQ]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
