/* -----------------------------------------------------------------------------
Drop PIMS_EXPROPRIATION_VESTING
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jan-29  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPVST_I_S_U_TR
PRINT N'Drop trigger dbo.PIMS_EXPVST_I_S_U_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPVST_I_S_U_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPVST_I_S_I_TR
PRINT N'Drop trigger dbo.PIMS_EXPVST_I_S_I_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPVST_I_S_I_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop foreign key constraint dbo.PIM_ACQNFL_PIM_EXPVST_FK
PRINT N'Drop foreign key constraint dbo.PIM_ACQNFL_PIM_EXPVST_FK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_VESTING]
	DROP CONSTRAINT IF EXISTS [PIM_ACQNFL_PIM_EXPVST_FK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop trigger dbo.PIMS_EXPVST_A_S_IUD_TR
PRINT N'Drop trigger dbo.PIMS_EXPVST_A_S_IUD_TR'
GO
DROP TRIGGER IF EXISTS [dbo].[PIMS_EXPVST_A_S_IUD_TR]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPVST_COMPENSATION_REQUISITION_ID_IDX
PRINT N'Drop index dbo.EXPVST_COMPENSATION_REQUISITION_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING].[EXPVST_COMPENSATION_REQUISITION_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop index dbo.EXPVST_ACQUISITION_FILE_ID_IDX
PRINT N'Drop index dbo.EXPVST_ACQUISITION_FILE_ID_IDX'
GO
DROP INDEX IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING].[EXPVST_ACQUISITION_FILE_ID_IDX]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop primary key constraint dbo.EXPVST_PK
PRINT N'Drop primary key constraint dbo.EXPVST_PK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_VESTING]
	DROP CONSTRAINT IF EXISTS [EXPVST_PK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.PIMS_EXPROPRIATION_VESTING
PRINT N'Drop table dbo.PIMS_EXPROPRIATION_VESTING'
GO
DROP TABLE IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop unique constraint dbo.PIMS_EXPVST_H_UK
PRINT N'Drop unique constraint dbo.PIMS_EXPVST_H_UK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_VESTING_HIST]
	DROP CONSTRAINT IF EXISTS [PIMS_EXPVST_H_UK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop primary key constraint dbo.PIMS_EXPVST_H_PK
PRINT N'Drop primary key constraint dbo.PIMS_EXPVST_H_PK'
GO
ALTER TABLE [dbo].[PIMS_EXPROPRIATION_VESTING_HIST]
	DROP CONSTRAINT IF EXISTS [PIMS_EXPVST_H_PK]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop sequence dbo.PIMS_EXPROPRIATION_VESTING_ID_SEQ
PRINT N'Drop sequence dbo.PIMS_EXPROPRIATION_VESTING_ID_SEQ'
GO
DROP SEQUENCE IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING_ID_SEQ]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.PIMS_EXPROPRIATION_VESTING_HIST
PRINT N'Drop table dbo.PIMS_EXPROPRIATION_VESTING_HIST'
GO
DROP TABLE IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING_HIST]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop sequence dbo.PIMS_EXPROPRIATION_VESTING_H_ID_SEQ
PRINT N'Drop sequence dbo.PIMS_EXPROPRIATION_VESTING_H_ID_SEQ'
GO
DROP SEQUENCE IF EXISTS [dbo].[PIMS_EXPROPRIATION_VESTING_H_ID_SEQ]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
