-- Create foreign key constraint dbo.PIM_MGTPGM_PIM_MGMTFL_FK
PRINT N'Create foreign key constraint dbo.PIM_MGTPGM_PIM_MGMTFL_FK'
GO
ALTER TABLE [dbo].[PIMS_MANAGEMENT_FILE]
	ADD CONSTRAINT [PIM_MGTPGM_PIM_MGMTFL_FK]
	FOREIGN KEY([MANAGEMENT_FILE_PROGRAM_TYPE_CODE])
	REFERENCES [dbo].[PIMS_MANAGEMENT_FILE_PROGRAM_TYPE]([MANAGEMENT_FILE_PROGRAM_TYPE_CODE])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO