SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF NOT EXISTS(SELECT * 
              FROM   SYS.INDEXES 
              WHERE  NAME = 'PLYFAB_PID_NUMBER_IDX' 
                 AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    CREATE NONCLUSTERED INDEX [PLYFAB_PID_NUMBER_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC] ([PID_NUMBER] ASC)
    END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF NOT EXISTS(SELECT * 
              FROM   SYS.INDEXES 
              WHERE  NAME = 'PLYFAB_PLAN_NUMBER_IDX' 
                 AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    CREATE NONCLUSTERED INDEX [PLYFAB_PLAN_NUMBER_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC] ([PLAN_NUMBER] ASC)
    END
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

IF NOT EXISTS(SELECT * 
              FROM   SYS.INDEXES 
              WHERE  NAME = 'PLYFAB_SHAPE_IDX' 
                 AND OBJECT_ID = OBJECT_ID('[pmbc].[PMBC_PARCEL_POLYGON_FABRIC]'))
    BEGIN
    CREATE SPATIAL INDEX [PLYFAB_SHAPE_IDX] ON [pmbc].[PMBC_PARCEL_POLYGON_FABRIC] (SHAPE)
      USING GEOMETRY_AUTO_GRID 
      WITH (BOUNDING_BOX =( XMIN =200000, YMIN =300000, XMAX =1900000, YMAX =1800000 ))
    END                   
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
