PRINT N'Drop history tables'
GO

DROP TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT_HIST]
GO

-- Alter table dbo.PIMS_LEASE_TENANT_HIST
PRINT N'Alter table dbo.PIMS_LEASE_TENANT_HIST'
GO
ALTER TABLE [dbo].[PIMS_LEASE_TENANT_HIST]
	DROP COLUMN [NOTE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Alter table dbo.PIMS_LEASE_HIST
PRINT N'Alter table dbo.PIMS_LEASE_HIST'
GO
ALTER TABLE [dbo].[PIMS_LEASE_HIST] ALTER COLUMN [RENEWAL_COUNT] smallint NOT NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
EXEC sp_dropextendedproperty 
	@name = N'MS_Description' , 
	@level0type = N'Schema', @level0name = N'dbo', 
	@level1type = N'Table', @level1name = N'PIMS_LEASE_HIST', 
	@level2type = N'Column', @level2name = N'RENEWAL_TERM_MONTHS'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[PIMS_LEASE_HIST]
	ADD [TERM_EXPIRY_DATE] datetime NULL, 
	[TERM_RENEWAL_DATE] datetime NULL, 
	[TERM_START_DATE] datetime NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE [dbo].[PIMS_LEASE_HIST]
	DROP COLUMN [IS_COMM_BLDG], [IS_OTHER_IMPROVEMENT], [IS_SUBJECT_TO_RTA], [LEASE_INITIATOR_TYPE_CODE], [LEASE_RESPONSIBILITY_TYPE_CODE], [RESPONSIBILITY_EFFECTIVE_DATE]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO