export enum TeamProfileTypeCode {
  KEY_CONTACT = 'KEYCNTCT',
  LISTING_AGENT = 'LISTAGENT',
  MOTT_LEAD = 'MOTILEAD',
  MOTT_SOLICITOR = 'MOTILAWYER',
  NEGOTIATION_AGENT = 'NEGOTAGENT',
  PROPERTY_COORDINATOR = 'PROPCOORD',
  PROPERTY_AGENT = 'PROPAGENT',
  PROPERTY_ANALYST = 'PROPANLYS',
}
