/* -----------------------------------------------------------------------------
Delete the missing code values in the PIMS_BUSINESS_FUNCTION_CODE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2023-Jan-30  Initial version
----------------------------------------------------------------------------- */

BEGIN TRANSACTION;

DECLARE @CurrCd NVARCHAR(20)
SET @CurrCd = N'MANAGE'

SELECT CODE
FROM   PIMS_BUSINESS_FUNCTION_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_BUSINESS_FUNCTION_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'MANAGE', N'MANAGE', 110, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'ORIO ACQ'

SELECT CODE
FROM   PIMS_BUSINESS_FUNCTION_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_BUSINESS_FUNCTION_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'ORIO ACQ', N'ORIO ACQ', 111, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'PROP AQU'

SELECT CODE
FROM   PIMS_BUSINESS_FUNCTION_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_BUSINESS_FUNCTION_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'PROP AQU', N'PROP AQU', 112, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'PROP MAN'

SELECT CODE
FROM   PIMS_BUSINESS_FUNCTION_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_BUSINESS_FUNCTION_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'PROP MAN', N'PROP MAN', 113, CONVERT(DATETIME, '1990.01.01', 102));
  END

COMMIT TRANSACTION;
