/* -----------------------------------------------------------------------------
Populate the missing code values in the PIMS_WORK_ACTIVITY_CODE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2023-Jan-30  Initial version
----------------------------------------------------------------------------- */

BEGIN TRANSACTION;

DECLARE @CurrCd NVARCHAR(20)
SET @CurrCd = N'PROP MAN'

SELECT CODE
FROM   PIMS_WORK_ACTIVITY_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_WORK_ACTIVITY_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'PROP MAN', N'PROP MAN', 2000, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'SURVEY'

SELECT CODE
FROM   PIMS_WORK_ACTIVITY_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_WORK_ACTIVITY_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'SURVEY', N'SURVEY', 2001, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'ELEC MAIN'

SELECT CODE
FROM   PIMS_WORK_ACTIVITY_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_WORK_ACTIVITY_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'ELEC MAIN', N'ELEC MAIN', 2002, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'ACQ PROP'

SELECT CODE
FROM   PIMS_WORK_ACTIVITY_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_WORK_ACTIVITY_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'ACQ PROP', N'ACQ PROP', 2003, CONVERT(DATETIME, '1990.01.01', 102));
  END

SET @CurrCd = N'PA GENERAL'

SELECT CODE
FROM   PIMS_WORK_ACTIVITY_CODE
WHERE  CODE = @CurrCd;

IF @@ROWCOUNT = 0
  BEGIN
  INSERT INTO PIMS_WORK_ACTIVITY_CODE (CODE, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE)
  VALUES 
    (N'PA GENERAL', N'PA GENERALP', 2004, CONVERT(DATETIME, '1990.01.01', 102));
  END

COMMIT TRANSACTION;
