DELETE FROM PIMS_ACQ_FILE_ACQ_FL_TAKE_TYP
GO

DECLARE @i   INT = 0
DECLARE @max INT = 20

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_ACQ_FILE_ACQ_FL_TAKE_TYP (ACQUISITION_FILE_ID, ACQ_FILE_TAKE_TYPE_CODE, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES((SELECT TOP 1 ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE ORDER BY NEWID()), (SELECT TOP 1 ACQ_FILE_TAKE_TYPE_CODE FROM PIMS_ACQ_FILE_TAKE_TYPE ORDER BY NEWID()), 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER')
  END
GO
