DELETE 
FROM   PIMS_PROPERTY_ACQUISITION_FILE;
GO

DECLARE @i   INT = 0
DECLARE @max INT = 50

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO [dbo].[PIMS_PROPERTY_ACQUISITION_FILE] ([ACQUISITION_FILE_ID], [PROPERTY_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	  VALUES
	    ((SELECT TOP 1 ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE ORDER BY NEWID()),
	     (SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY                 ORDER BY NEWID()),
	     1)
  END
GO
