DELETE
FROM   PIMS_PROPERTY_CONTACT
GO

DECLARE @i   INT = 0
DECLARE @max INT = 25

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_PROPERTY_CONTACT (PROPERTY_ID, PERSON_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
    VALUES
      ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER')
  END
GO

DECLARE @i   INT = 0
DECLARE @max INT = 25

WHILE @i < @max
  BEGIN
  SET @i = @i + 1
  INSERT INTO dbo.PIMS_PROPERTY_CONTACT (PROPERTY_ID, ORGANIZATION_ID, PRIMARY_CONTACT_ID, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY)
    VALUES
      ((SELECT TOP 1 PROPERTY_ID FROM PIMS_PROPERTY ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), 1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER')
  END
GO
