UPDATE PIMS_DOCUMENT_TYP
SET DOCUMENT_TYPE 
= CASE DOCUMENT_TYPE
WHEN 'Affidavit of service' THEN 'AFFISERV'
WHEN 'Miscellaneous notes ' THEN 'MISCNOTE'
WHEN 'MoTI plan' THEN 'MOTIPLAN'
WHEN 'Notice of advanced p' THEN 'NOTIADVA'
WHEN 'Notice of claims/Lit' THEN 'NOTICLAI'
WHEN 'Notice of expropriat' THEN 'NOTIEXPR'
WHEN 'Notice of possible e' THEN 'NOTIPOSS'
WHEN 'OIC' THEN 'OIC'
WHEN 'Other' THEN 'OTHER'
WHEN 'Owner agreement/offe' THEN 'OWNEAGRE'
WHEN 'Ministerial order' THEN 'MINIORDE'
WHEN 'PA plans / Design dr' THEN 'PAPLAN'
WHEN 'Privy council' THEN 'PRIVCOUN'
WHEN 'Professional reports' THEN 'PROFREPO'
WHEN 'Record of negotiatio' THEN 'RECONEGO'
WHEN 'Release of claims' THEN 'RELECLAI'
WHEN 'Spending authority a' THEN 'SPENAUTH'
WHEN 'Surplus property dec' THEN 'SURPPROP'
WHEN 'Tax notices and asse' THEN 'TAXNOTI'
WHEN 'Temporary license fo' THEN 'TEMPLICE'
WHEN 'Title search / Histo' THEN 'TITLSEAR'
WHEN 'Photos / Images / Vi' THEN 'PHOTIMAG'
WHEN 'Licensing approval/s' THEN 'LICEAPPR'
WHEN 'Legal survey plan' THEN 'LEGASURV'
WHEN 'Legal correspondence' THEN 'LEGACORR'
WHEN 'Appraisal/Review' THEN 'APPRREVI'
WHEN 'Approval of expropri' THEN 'APPREXPR'
WHEN 'BC assessment search' THEN 'BCASSE'
WHEN 'Briefing notes' THEN 'BRIENOTE'
WHEN 'CDOGS template' THEN 'CDOGTEMP'
WHEN 'Canada lands survey' THEN 'CANALAND'
WHEN 'Certificate of Insur' THEN 'CERTINSU'
WHEN 'Company search' THEN 'COMPSEAR'
WHEN 'Compensation cheque' THEN 'COMPCHEQ'
WHEN 'Compensation requisi' THEN 'COMPREQU'
WHEN 'Condition of entry (' THEN 'CONDENTR'
WHEN 'Conveyance closing d' THEN 'CONVCLOS'
WHEN 'Correspondence' THEN 'CORR'
WHEN 'Crown grant' THEN 'CROWGRAN'
WHEN 'District road regist' THEN 'DISTREGI'
WHEN 'Field notes' THEN 'FIELNOTE'
WHEN 'First nations consul' THEN 'FIRSNTAI'
WHEN 'Gazette' THEN 'GAZE'
WHEN 'Historical file' THEN 'HISTFILE'
WHEN 'LTSA documents and p' THEN 'LTSADOCU'
WHEN 'Lease / License (H10' THEN 'LEASLICE'
WHEN 'Transfer of administ' THEN 'TRANADMI'
WHEN 'Vesting notice (Form' THEN 'VESTNOTI'
ELSE DOCUMENT_TYPE
END, CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE DISPLAY_ORDER >= 0;