INSERT INTO [dbo].[PIMS_FORM_8] ([ACQUISITION_FILE_ID], [ACQUISITION_OWNER_ID], [PAYMENT_ITEM_TYPE_CODE], [DESCRIPTION], [IS_GST_REQUIRED], [PRETAX_AMT], [TAX_AMT], [TOTAL_AMT])
VALUES
  ( 1, 1, N'MARKETVALUE', N'Description 1', CONVERT([bit],(1)), 100, 5, 105),
  ( 1, 2, N'PERMSRW',     N'Description 2', CONVERT([bit],(0)), 101, 0, 101);
GO
