DELETE FROM  PIMS_ACQUISITION_FILE_TEAM;
GO

INSERT INTO [dbo].[PIMS_ACQUISITION_FILE_TEAM] ([ACQUISITION_FILE_ID], [PERSON_ID], [ORGANIZATION_ID], [PRIMARY_CONTACT_ID], [ACQ_FL_TEAM_PROFILE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES
	  ((SELECT TOP 1 ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ACQ_FL_TEAM_PROFILE_TYPE_CODE FROM PIMS_ACQ_FL_TEAM_PROFILE_TYPE ORDER BY NEWID()), 1),
	  ((SELECT TOP 1 ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ACQ_FL_TEAM_PROFILE_TYPE_CODE FROM PIMS_ACQ_FL_TEAM_PROFILE_TYPE ORDER BY NEWID()), 1),
	  ((SELECT TOP 1 ACQUISITION_FILE_ID FROM PIMS_ACQUISITION_FILE ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM ORGANIZATION ORDER BY NEWID()), (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ACQ_FL_TEAM_PROFILE_TYPE_CODE FROM PIMS_ACQ_FL_TEAM_PROFILE_TYPE ORDER BY NEWID()), 1);
GO
