DELETE
FROM  PIMS_LEASE_ACTIVITY_INSTANCE;
GO

DECLARE @sql   VARCHAR(1000)
DECLARE @minLS VARCHAR(1000)
DECLARE @maxLS VARCHAR(1000)
DECLARE @minAI VARCHAR(1000)
DECLARE @maxAI VARCHAR(1000)

SET @minLS = (SELECT CAST(MIN(LEASE_ID) AS VARCHAR) FROM PIMS_LEASE)
SET @maxLS = (SELECT CAST(MAX(LEASE_ID) AS VARCHAR) FROM PIMS_LEASE)
SET @minAI = (SELECT CAST(MIN(ACTIVITY_INSTANCE_ID) AS VARCHAR) FROM PIMS_ACTIVITY_INSTANCE) 
SET @maxAI = (SELECT CAST(MAX(ACTIVITY_INSTANCE_ID) AS VARCHAR) FROM PIMS_ACTIVITY_INSTANCE)

SET @sql = 'INSERT INTO PIMS_LEASE_ACTIVITY_INSTANCE (ACTIVITY_INSTANCE_ID, LEASE_ID) VALUES (' + @minAI + ', ' + @minLS + ');'
EXECUTE (@sql)
SET @sql = 'INSERT INTO PIMS_LEASE_ACTIVITY_INSTANCE (ACTIVITY_INSTANCE_ID, LEASE_ID) VALUES (' + @minAI + ', ' + @maxLS + ');'
EXECUTE (@sql)
SET @sql = 'INSERT INTO PIMS_LEASE_ACTIVITY_INSTANCE (ACTIVITY_INSTANCE_ID, LEASE_ID) VALUES (' + @maxAI + ', ' + @minLS + ');'
EXECUTE (@sql)
SET @sql = 'INSERT INTO PIMS_LEASE_ACTIVITY_INSTANCE (ACTIVITY_INSTANCE_ID, LEASE_ID) VALUES (' + @maxAI + ', ' + @maxLS + ');'
EXECUTE (@sql)

GO