/* -----------------------------------------------------------------------------
Insert lease data for testing
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2021-Aug-19  Initial version
----------------------------------------------------------------------------- */

-- Insert addresses
INSERT INTO PIMS_ADDRESS (STREET_ADDRESS_1, STREET_ADDRESS_2, STREET_ADDRESS_3, MUNICIPALITY_NAME, POSTAL_CODE, PROVINCE_STATE_ID, COUNTRY_ID, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  (N'45 - 904 Hollywood Crescent', N'Living in a van', N'Down by the River',                N'Hollywood North', N'M4T F0L', 1, 1, CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data', CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data'),
  (N'PO Box 2',                    N'Stealth Camping', N'Walmart Parking Lot',              N'South Podunk',    N'H1I B0B', 1, 1, CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data', CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data'),
  (N'123 Main Street',             N'PO Box 123',      N'Next to the Dairy Queen',          N'East Podunk',     N'I4M B0B', 1, 1, CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data', CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data'),
  (N'456 Souris Street',           N'PO Box 250',      N'A Hoot and a holler from the A&W', N'North Podunk',    N'IH8 B0B', 1, 1, CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data', CURRENT_TIMESTAMP, N'Seed Data', N'Seed Data');

-- Insert organizations
INSERT INTO PIMS_ORGANIZATION (ORGANIZATION_IDENTIFIER, ORGANIZATION_NAME, ORGANIZATION_TYPE_CODE, ORG_IDENTIFIER_TYPE_CODE, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  (N'LILMOUSE', N'French Mouse Property Management',         N'REALTOR', N'OTHINCORPNO', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'DQ4EVA',   N'Dairy Queen Forever! Property Management', N'REALTOR', N'OTHINCORPNO', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'DAKATZ',   N'Pussycat Property Management',             N'REALTOR', N'OTHINCORPNO', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'BOB123',   N'Bob''s Property Management',               N'REALTOR', N'OTHINCORPNO', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');

-- Insert organization addresses
INSERT INTO PIMS_ORGANIZATION_ADDRESS(ADDRESS_ID, ORGANIZATION_ID, ADDRESS_USAGE_TYPE_CODE, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '%Hollywood%'), (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER LIKE '%LILMOUSE%'), 'MAILADDR',  CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE 'PO Box%'),     (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER LIKE 'DQ4EVA%'),'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '123 Main%'),   (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER LIKE 'DAKATZ%'),'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '%Souris%'),    (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER LIKE 'BOB123%'),'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');

-- Insert people
INSERT INTO PIMS_PERSON (SURNAME, FIRST_NAME, MIDDLE_NAMES, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  (N'Smith',  N'Bob',    N'Billy',        CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'Wilson', N'Volley', N'Ball',         CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'Cheese', N'Stinky', N'',             CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  (N'Mouse',  N'Minnie', N'Nacho Cheese', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');

--Insert person addresses
INSERT INTO PIMS_PERSON_ADDRESS(ADDRESS_ID, PERSON_ID, ADDRESS_USAGE_TYPE_CODE, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '%Hollywood%'), (SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME LIKE '%Smith%'), 'MAILADDR',  CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE 'PO Box%'),     (SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME LIKE 'Wilson%'), 'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '123 Main%'),   (SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME LIKE 'Cheese%'), 'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ADDRESS_ID FROM PIMS_ADDRESS WHERE STREET_ADDRESS_1 LIKE '%Souris%'),    (SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME LIKE 'Mouse%'), 'MAILADDR', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');


-- Insert contact information for people
INSERT INTO PIMS_CONTACT_METHOD (PERSON_ID, CONTACT_METHOD_TYPE_CODE, CONTACT_METHOD_VALUE, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Smith'),  N'PERSPHONE', N'6049934251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Wilson'), N'PERSPHONE', N'2509977251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Cheese'), N'PERSPHONE', N'6049983251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Mouse'),  N'PERSPHONE', N'7785761234', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');

-- Insert contact information for organizations
INSERT INTO PIMS_CONTACT_METHOD (ORGANIZATION_ID, CONTACT_METHOD_TYPE_CODE, CONTACT_METHOD_VALUE, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  ((SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'BOB123'),   N'WORKPHONE', N'6049934251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'DAKATZ'),   N'WORKPHONE', N'2509977251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'DQ4EVA'),   N'WORKPHONE', N'6049983251', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'LILMOUSE'), N'WORKPHONE', N'7785761234', CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');

-- Associate person with organization
INSERT INTO PIMS_PERSON_ORGANIZATION (PERSON_ID, ORGANIZATION_ID, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_DIRECTORY)
VALUES
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Smith'),  (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'BOB123'),   CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Wilson'), (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'DAKATZ'),   CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Cheese'), (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'DQ4EVA'),   CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data'),
  ((SELECT PERSON_ID FROM PIMS_PERSON WHERE SURNAME = 'Mouse'),  (SELECT ORGANIZATION_ID FROM PIMS_ORGANIZATION WHERE ORGANIZATION_IDENTIFIER = 'LILMOUSE'), CURRENT_TIMESTAMP, N'Lease Seed Data', N'Leasse Seed Data', CURRENT_TIMESTAMP, N'Leasse Seed Data', N'Leasse Seed Data');
