DELETE FROM PIMS_MGMT_ACT_MIN_CONTACT;
GO

INSERT INTO PIMS_MGMT_ACT_MIN_CONTACT (MANAGEMENT_ACTIVITY_ID, PERSON_ID)
VALUES
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID())),
  ((SELECT TOP 1 MANAGEMENT_ACTIVITY_ID FROM PIMS_MANAGEMENT_ACTIVITY ORDER BY NEWID()),(SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()));
GO
