INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (1, 'AC', '00048', 'CLAIMS');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (2, 'AC', '00053', 'DIRECTOR, C&M & CLAIMS OVERHEAD');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (3, 'AC', '00055', 'AVALANCHE &  PROGRAM REVIEW - OH');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (4, 'AC', '00064', 'AUTOPLAN');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (1, 'AC', '00065', 'RADIO & ELECTRONICS OVERHEAD');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (2, 'AC', '00067', 'TRAFFIC, ELEC, SAFETY, & GEOMETRIC O/H');
INSERT INTO PIMS_PROJECT (REGION_CODE, PROJECT_STATUS_TYPE_CODE, CODE, DESCRIPTION) VALUES (3, 'AC', '00070', 'GUIDE SIGN REHAB');