DELETE
FROM   PIMS_DISPOSITION_OFFER
GO

DECLARE @i INT = 0
WHILE @i < 25
  BEGIN
  SET @i = @i + 1
  INSERT INTO PIMS_DISPOSITION_OFFER (DISPOSITION_FILE_ID, DISPOSITION_OFFER_STATUS_TYPE_CODE, OFFER_NAME, OFFER_DT, OFFER_EXPIRY_DT, OFFER_AMT, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) 
    VALUES
      ((SELECT TOP 1 DISPOSITION_FILE_ID                FROM PIMS_DISPOSITION_FILE              ORDER BY NEWID()), -- DISPOSITION_FILE_ID
       (SELECT TOP 1 DISPOSITION_OFFER_STATUS_TYPE_CODE FROM PIMS_DISPOSITION_OFFER_STATUS_TYPE ORDER BY NEWID()), -- DISPOSITION_OFFER_STATUS_TYPE_CODE
       (SELECT N'OFFER_NAME ' + LEFT(NEWID(),7)),                                                                  -- FILE_NUMBER
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                 -- OFFER_NAME
       (SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % 65530), 0)),                                                 -- OFFER_EXPIRY_DT
       (SELECT CONVERT(MONEY, RAND()*15000)),                                                                      -- OFFER_AMT
       1, getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER', getutcdate(), N'FOUGSTER', NEWID(), N'FOUGSTER');       -- CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORYCONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY
  END       
GO
