export enum UserOverrideCode {
  ADD_PROPERTY_TO_INVENTORY = 'ADD_PROPERTY_TO_INVENTORY',
  ADD_LOCATION_TO_PROPERTY = 'ADD_LOCATION_TO_PROPERTY',
  UPDATE_REGION = 'UPDATE_REGION',
  PROPERTY_OF_INTEREST_TO_INVENTORY = 'PROPERTY_OF_INTEREST_TO_INVENTORY',
  CONTRACTOR_SELFREMOVED = 'CONTRACTOR_SELFREMOVED',
}
