kind: Template
apiVersion: v1
metadata:
  name: pods-reader
  annotations:
    openshift.io/display-name: Pod reader rolebinding
    description: Allow default user to read pod's log.
    tags: pims-logging
parameters:
  - name: NAMESPACE
    description: Target namespace
    displayName: Target Namespace
    required: true
    value: "3cd915-dev"
objects:
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: pod-reader
      namespace: ${NAMESPACE}
    rules:
      - apiGroups: [""]
        resources: ["pods", "services", "pods/log"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["extensions"]
        resources: ["deployments"]
        verbs: ["get", "list", "watch"]

  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: default-pod-reader
      namespace: ${NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: pod-reader
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: ${NAMESPACE}
