/* -----------------------------------------------------------------------------
Alter the PIMS_DSP_CHKLST_ITEM_TYPE table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Dec-09  Added 'UTILCOAPP', 'ADJLOREF', and 'ADCOMPLT' 
                           checklist items.
Doug Filteau  2025-Dec-09  Disabled 'STRNTHCLM' checklist item.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable UTILCOAPP code.
PRINT N'Add/enable UTILCOAPP code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'UTILCOAPP';

IF @@ROWCOUNT = 0
  INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
    VALUES (N'DIRCTSAL',  N'UTILCOAPP',  N'Utility company referral', 16, NULL);
ELSE
  UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
  SET    EXPIRY_DATE                = NULL
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
     AND DSP_CHKLST_ITEM_TYPE_CODE    = N'UTILCOAPP';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable ADJLOREF code.
PRINT N'Add/enable ADJLOREF code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADJLOREF';

IF @@ROWCOUNT = 0
  INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
	  VALUES (N'DIRCTSAL',  N'ADJLOREF',  N'Adjacent landowner referral', 17, NULL);
ELSE
  UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
  SET    EXPIRY_DATE                = NULL
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
     AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADJLOREF';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add/enable ADCOMPLT code.
PRINT N'Add/enable ADCOMPLT code.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADCOMPLT';

IF @@ROWCOUNT = 0
  INSERT INTO PIMS_DSP_CHKLST_ITEM_TYPE (DSP_CHKLST_SECTION_TYPE_CODE, DSP_CHKLST_ITEM_TYPE_CODE, DESCRIPTION, DISPLAY_ORDER, HINT)
	  VALUES (N'DIRCTSAL',  N'ADCOMPLT',  N'Advertising completed', 18, NULL);
ELSE
  UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
  SET    EXPIRY_DATE                = NULL
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'DIRCTSAL'
     AND DSP_CHKLST_ITEM_TYPE_CODE    = N'ADCOMPLT';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Disable the "STRNTHCLM" type.
PRINT N'Disable the "STRNTHCLM" type.'
GO
SELECT DSP_CHKLST_ITEM_TYPE_CODE
FROM   PIMS_DSP_CHKLST_ITEM_TYPE
WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'REFRCONS'
   AND DSP_CHKLST_ITEM_TYPE_CODE    = N'STRNTHCLM';

IF @@ROWCOUNT = 1
  UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
  SET    EXPIRY_DATE                = CAST('2026-01-01' AS DATE)
       , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
  WHERE  DSP_CHKLST_SECTION_TYPE_CODE = N'REFRCONS'
     AND DSP_CHKLST_ITEM_TYPE_CODE    = N'STRNTHCLM';
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update the display order for the existng Direct Sale and Sale Information checklist items.
PRINT N'Update the display order for the existng Direct Sale and Sale Information checklist items.'
GO
UPDATE PIMS_DSP_CHKLST_ITEM_TYPE
SET    DISPLAY_ORDER              = DISPLAY_ORDER + 3
     , CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE  DSP_CHKLST_SECTION_TYPE_CODE  IN (N'DIRCTSAL', N'SALEINFO')
   AND DSP_CHKLST_ITEM_TYPE_CODE NOT IN (N'UTILCOAPP', N'ADJLOREF', N'ADCOMPLT');
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) 
  PRINT 'The database update succeeded'
ELSE 
  BEGIN
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'The database update failed'
  END
GO
