<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>createResearchFileLink</name>
   <tag></tag>
   <elementGuidId>f5e9b01c-6db9-452c-a567-e42ff48762f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>397b4614-18cf-47cb-b168-a838b77a9346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mapview/research/new</value>
      <webElementGuid>4c419e4d-0ead-40c8-81e8-a4bee3569aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Research File</value>
      <webElementGuid>2b4d1698-d9e9-4e55-9b5c-73d7c1492896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[2]</value>
      <webElementGuid>f1450a86-0109-4301-ac9a-13ee9357251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67166374-6750-4947-b659-3b27d833bc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mapview/research/new</value>
      <webElementGuid>273c3d1c-ee41-4d29-80dd-82f1ff4fb26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Research File</value>
      <webElementGuid>e3576b77-5fd1-4599-80df-e9ce39abc50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[2]</value>
      <webElementGuid>0cfb60dd-4e6d-421d-9eb6-4ceeaf1ed9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91d9cd79-a5e2-4ca7-95c3-b95a8781efab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mapview/research/new</value>
      <webElementGuid>b26831ac-e543-49fe-b55c-f4abaca9f0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Research File</value>
      <webElementGuid>80f4ce35-712d-4120-9e58-690be6aaf849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[2]</value>
      <webElementGuid>a5fee578-9548-4bc9-88fe-862f679bb218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63a225a0-f028-4d33-bb29-e1c1875836b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mapview/research/new</value>
      <webElementGuid>f56f4090-5233-46b2-9ee7-a64646614850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Research File</value>
      <webElementGuid>4b9a9956-ed5e-4160-935f-bc2b0d05732c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[2]</value>
      <webElementGuid>632636f5-efaf-4ae1-87c8-ace4c6266e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/a[2]</value>
      <webElementGuid>ce894cc3-349b-45c9-96f8-eb7b37a3884c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create a Research File')]</value>
      <webElementGuid>b12c3ca3-3acc-4f02-aad9-11006945c8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for a Research File'])[1]/following::a[1]</value>
      <webElementGuid>0d7a700a-b7a1-463b-baa4-1257d6ba1123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Files'])[1]/following::a[2]</value>
      <webElementGuid>e049d4da-aa4c-4ad2-b4f8-f0bf7f6b88ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[1]</value>
      <webElementGuid>d100b783-bd7a-4ce6-82bd-d0d30fed8b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satellite'])[1]/preceding::a[1]</value>
      <webElementGuid>b0d51dfc-957c-408d-8062-5f7c8bda1e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create a Research File']/parent::*</value>
      <webElementGuid>2e7080bb-d544-47a9-b5db-79422ebd885d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mapview/research/new')]</value>
      <webElementGuid>640fa7be-623d-439a-9ef8-f187345d8b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>0824d7d8-ec4d-4f80-bf01-f8d826c0aefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mapview/research/new' and (text() = 'Create a Research File' or . = 'Create a Research File')]</value>
      <webElementGuid>e38b3662-4071-4c98-9da2-c0bab0635385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
