<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResearchFileLink</name>
   <tag></tag>
   <elementGuidId>1cbf7493-8111-4c5d-a31c-b2aaeb3ef0cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-dtDOJZ.epBZUF > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f52086b2-3a3e-4c01-bf58-713ce117d1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/research/list</value>
      <webElementGuid>50bd76ac-6a69-4c84-8c0f-9ee2aa752ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search for a Research File</value>
      <webElementGuid>e039e67b-de84-4ea4-85a0-30424db7f966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[1]</value>
      <webElementGuid>e152c105-634f-480f-96e6-e9c15d6359ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebbb0b2b-7656-4703-821e-55b32beed115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/research/list</value>
      <webElementGuid>5ed94cb9-6c5d-46ca-8d01-4296d558dea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search for a Research File</value>
      <webElementGuid>7412b34c-dfa8-45c7-840a-7cc12738b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ilftOa bmhitc authenticated&quot;]/div[@class=&quot;sc-jgrIVw DBTfN&quot;]/div[@class=&quot;sc-iNGGwv hsrLVo show&quot;]/div[@class=&quot;sc-gSQGeZ iOAir&quot;]/div[@class=&quot;sc-dtDOJZ epBZUF&quot;]/a[1]</value>
      <webElementGuid>d1848b41-4469-47e7-9ce2-20be4fc2479b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>6dc122e8-ede3-4fb9-9952-3e49ba4313c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search for a Research File')]</value>
      <webElementGuid>b6577d8c-8ed4-4652-9741-900b9a8b5f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Files'])[1]/following::a[1]</value>
      <webElementGuid>09a7daf3-44c0-4c0c-b27c-7bad15cbff03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Tools'])[1]/following::a[1]</value>
      <webElementGuid>77444f42-326a-45a3-9c91-6a05a123d2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Research File'])[1]/preceding::a[1]</value>
      <webElementGuid>464f6656-e68d-4645-81b5-a5898d1df72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[2]</value>
      <webElementGuid>1f56c9bb-b2e5-4205-8052-3379e9eb0778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search for a Research File']/parent::*</value>
      <webElementGuid>1b805915-5982-4b24-b039-807d192b6d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/research/list')]</value>
      <webElementGuid>457a9f57-9af0-4d9c-9182-a12e65e29f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>911812f2-fff3-454e-a03c-71cd15c7af1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/research/list' and (text() = 'Search for a Research File' or . = 'Search for a Research File')]</value>
      <webElementGuid>c3d3be99-8530-49e6-9c05-2fc56b69f102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
