-- Create foreign key constraint dbo.PIM_PIMPRS_PIM_PIMPRV_FK
PRINT N'Create foreign key constraint dbo.PIM_PIMPRS_PIM_PIMPRV_FK'
GO
ALTER TABLE [dbo].[PIMS_PROPERTY_IMPROVEMENT]
	ADD CONSTRAINT [PIM_PIMPRS_PIM_PIMPRV_FK]
	FOREIGN KEY([PROP_IMPRVMNT_STATUS_TYPE_CODE])
	REFERENCES [dbo].[PIMS_PROP_IMPRVMNT_STATUS_TYPE]([PROP_IMPRVMNT_STATUS_TYPE_CODE])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO