DELETE FROM PIMS_PROPERTY_ACTIVITY;
GO

INSERT INTO PIMS_PROPERTY_ACTIVITY (PROP_MGMT_ACTIVITY_TYPE_CODE, PROP_MGMT_ACTIVITY_SUBTYPE_CODE, PROP_MGMT_ACTIVITY_STATUS_TYPE_CODE, SERVICE_PROVIDER_PERSON_ID, SERVICE_PROVIDER_ORG_ID, REQUEST_ADDED_DT, COMPLETION_DT, DESCRIPTION, REQUEST_SOURCE, PRETAX_AMT, GST_AMT, PST_AMT, TOTAL_AMT)
VALUES
  (N'PROPERTYMTC',   N'SNOWREMOVAL',   N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 100, 5, 7, 112),
  (N'LANDLORDIMPRV', N'LL_PREMISES',   N'INPROGRESS', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 110, 2, 0, 112),
  (N'TENANTIMPROV',  N'TN_BUILDGLAND', N'COMPLETED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 101, 3, 5, 109),
  (N'INCDNTISSUE',   N'ENCAMPMENT',    N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 102, 6, 4, 112),
  (N'INQUIRY',       N'GENINQUIRY',    N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 103, 4, 4, 111),
  (N'INVESTRPT',     N'GEOTECH',       N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 104, 8, 5, 117),
  (N'1STNTNCONSULT', N'ACCOMMAGREE',   N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 105, 7, 7, 119),
  (N'APPLICPERMIT',  N'DEVELOPMENT',   N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source', 106, 9, 8, 123);
GO
