DELETE 
FROM   PIMS_ACQUISITION_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_ACQUISITION_ACTIVITY_INSTANCE] ([ACQUISITION_FILE_ID], [ACTIVITY_INSTANCE_ID], [CONCURRENCY_CONTROL_NUMBER]) 
	VALUES((SELECT MAX(ACQUISITION_FILE_ID) FROM PIMS_ACQUISITION_FILE), (SELECT MAX(ACTIVITY_INSTANCE_ID) FROM PIMS_ACTIVITY_INSTANCE), 1)
GO
