kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dotnet-60
  namespace: 3cd915-tools
  annotations:
    openshift.io/display-name: .NET 6 base images
    description: ImageStream definitions for .NET 6 on RHEL8
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '6.0'
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/dotnet-60:6.0'
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source
