PRINT N'Adding DB Audit Columns'

ALTER TABLE dbo.[PIMS_INSURANCE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_INSURANCE_PAYEE_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_INSURANCE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_SECURITY_DEPOSIT]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_SECURITY_DEPOSIT_RETURN]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

ALTER TABLE dbo.[PIMS_SECURITY_DEPOSIT_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()

    ALTER TABLE dbo.[PIMS_SEC_DEP_HOLDER_TYPE]
  ADD [DB_CREATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_CREATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()
    , [DB_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL DEFAULT GETUTCDATE()
    , [DB_LAST_UPDATE_USERID] NVARCHAR(30) NOT NULL DEFAULT user_name()