DELETE FROM "dbo"."PIMSX_TableDefinitions"
GO

ALTER TABLE "dbo"."PIMSX_TableDefinitions" ADD HIST_REQUIRED nvarchar(1) NULL
GO

INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ACCESS_REQUEST', N'PIMS_ACRQST', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ACCESS_REQUEST_ORGANIZATION', N'PIMS_ACRQOR', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ACCESS_REQUEST_STATUS_TYPE', N'PIMS_ARQSTT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ACTIVITY', N'PIMS_ACTVTY', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ACTIVITY_MODEL', N'PIMS_ACTMDL', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ADDRESS', N'PIMS_ADDRSS', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ADDRESS_USAGE_TYPE', N'PIMS_ADUSGT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_AREA_UNIT_TYPE', N'PIMS_ARUNIT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_CLAIM', N'PIMS_CLMTYP', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_CONTACT_METHOD', N'PIMS_CNTMTH', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_CONTACT_METHOD_TYPE', N'PIMS_CNTMTT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_COUNTRY', N'PIMS_CNTRY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_DISTRICT', N'PIMS_DSTRCT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_DISTRICT', N'PIMS_DSTRCT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_INSURANCE', N'PIMS_INSRNC', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_INSURANCE_PAYEE_TYPE', N'PIMS_INSPAY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_INSURANCE_TYPE', N'PIMS_INSPYT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE', N'PIMS_LEASE', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_CATEGORY_TYPE', N'PIMS_LSCATT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_LICENSE_TYPE', N'PIMS_LELIST', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_PAY_RVBL_TYPE', N'PIMS_LSPRTY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_PMT_FREQ_TYPE', N'PIMS_LSPMTF', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_PROGRAM_TYPE', N'PIMS_LSPRGT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_PURPOSE_TYPE', N'PIMS_LPRPTY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LEASE_TENANT', N'PIMS_TENANT', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_LESSOR_TYPE', N'PIMS_LSSRTY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ORG_IDENTIFIER_TYPE', N'PIMS_ORGIDT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ORGANIZATION', N'PIMS_ORG', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ORGANIZATION_TYPE', N'PIMS_ORGTYP', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PERSON', N'PIMS_PERSON', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PERSON_ORGANIZATION', N'PIMS_PERORG', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT', N'PIMS_PROJCT', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_NOTE', N'PIMS_PROJNT', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_PROPERTY', N'PIMS_PRJPRP', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_RISK_TYPE', N'PIMS_PRJRSK', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_STATUS_TYPE', N'PIMS_PRJSTY', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_TIER_TYPE', N'PIMS_PROJTR', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_TYPE', N'PIMS_PRJTYP', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROJECT_WORKFLOW_MODEL', N'PIMS_PRWKMD', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY', N'PIMS_PRPRTY', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_ACTIVITY', N'PIMS_PRPACT', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_CLASSIFICATION_TYPE', N'PIMS_PRPCLT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_DATA_SOURCE_TYPE', N'PIMS_PIDSRT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_EVALUATION', N'PIMS_PRPEVL', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_IMPROVEMENT', N'PIMS_PIMPRV', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_IMPROVEMENT_TYPE', N'PIMS_PIMPRT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_IMPROVEMENT_UOM_TYPE', N'PIMS_PIMPRU', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_LEASE', N'PIMS_PROPLS', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_ORGANIZATION', N'PIMS_PRPORG', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_PROPERTY_SERVICE_FILE', N'PIMS_PRPRSF', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_SERVICE_FILE', N'PIMS_PRPSVC', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_SERVICE_FILE_TYPE', N'PIMS_PRSVFT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_STATUS_TYPE', N'PIMS_PRPSTS', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_TAX', N'PIMS_PRPTAX', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_TAX_REMIT_TYPE', N'PIMS_PTRMTT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_TENURE_TYPE', N'PIMS_PRPTNR', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROPERTY_TYPE', N'PIMS_PRPTYP', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_PROVINCE_STATE', N'PIMS_PROVNC', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_REGION', N'PIMS_REGION', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ROLE', N'PIMS_ROLE', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_ROLE_CLAIM', N'PIMS_ROLCLM', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_SEC_DEP_HOLDER_TYPE', N'PIMS_SCHLDT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_SECURITY_DEPOSIT', N'PIMS_SECDEP', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_SECURITY_DEPOSIT_RETURN', N'PIMS_SDRTRN', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_SECURITY_DEPOSIT_TYPE', N'PIMS_SECDPT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_SURPLUS_DECLARATION_TYPE', N'PIMS_SPDCLT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_TASK', N'PIMS_TASK', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_TASK_TEMPLATE', N'PIMS_TSKTMP', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_TASK_TEMPLATE_ACTIVITY_MODEL', N'PIMS_TSKTAM', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_TASK_TEMPLATE_TYPE', N'PIMS_TSKTMT', N'N', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_USER', N'PIMS_USER', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_USER_ORGANIZATION', N'PIMS_USRORG', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_USER_ROLE', N'PIMS_USERRL', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_WORKFLOW_MODEL', N'PIMS_WFLMDL', N'Y', NULL)
GO
INSERT INTO "dbo"."PIMSX_TableDefinitions"("TABLE_NAME", "TABLE_ALIAS", "HIST_REQUIRED", "DESCRIPTION")
  VALUES(N'PIMS_WORKFLOW_MODEL_TYPE', N'PIMS_WFLMDT', N'N', NULL)
GO