/* -----------------------------------------------------------------------------
Migrate the data from the affected_TYPE tables to the renamed/recreated _TYP 
equivalent tables.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Mar-24  Initial version.
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_PROP_ROAD_TYP table data.
PRINT N'Migrate the PIMS_PROP_PROP_ROAD_TYP table data.'
GO
INSERT INTO [dbo].[PIMS_PROP_PROP_ROAD_TYPE]([PROP_PROP_ROAD_TYPE_ID], [PROPERTY_ID], [PROPERTY_ROAD_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_ROAD_TYPE_ID], [PROPERTY_ID], [PROPERTY_ROAD_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[TMP_PROP_PROP_ROAD_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_PROP_ANOMALY_TYP table data.
PRINT N'Migrate the PIMS_PROP_PROP_ANOMALY_TYP table data.'
GO
INSERT INTO [dbo].[PIMS_PROP_PROP_ANOMALY_TYPE]([PROP_PROP_ANOMALY_TYPE_ID], [PROPERTY_ID], [PROPERTY_ANOMALY_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_ANOMALY_TYPE_ID], [PROPERTY_ID], [PROPERTY_ANOMALY_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_DIRECTORY], [APP_CREATE_USER_GUID], [APP_CREATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_DIRECTORY], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USERID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[TMP_PROP_PROP_ANOMALY_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_PROP_TENURE_TYPE table data.
PRINT N'Migrate the PIMS_PROP_PROP_TENURE_TYPE table data.'
GO
INSERT INTO [dbo].[PIMS_PROP_PROP_TENURE_TYPE]([PROP_PROP_TENURE_TYPE_ID], [PROPERTY_ID], [PROPERTY_TENURE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_PROP_TENURE_TYPE_ID], [PROPERTY_ID], [PROPERTY_TENURE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[TMP_PROP_PROP_TENURE_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE table data.
PRINT N'Migrate the PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE table data.'
GO
INSERT INTO [dbo].[PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE]([PRF_PROP_RESEARCH_PURPOSE_ID], [PROPERTY_RESEARCH_FILE_ID], [PROP_RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PRF_PROP_RESEARCH_PURPOSE_ID], [PROPERTY_RESEARCH_FILE_ID], [PROP_RESEARCH_PURPOSE_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[TMP_PRF_PROP_RESEARCH_PURPOSE_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the PIMS_PROP_INTHLDR_INTEREST_TYPE table data.
PRINT N'Migrate the PIMS_PROP_INTHLDR_INTEREST_TYPE table data.'
GO
INSERT INTO [dbo].[PIMS_PROP_INTHLDR_INTEREST_TYPE]([PROP_INTHLDR_INTEREST_TYPE_ID], [PIMS_INTHLDR_PROP_INTEREST_ID], [INTEREST_HOLDER_INTEREST_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) 
  SELECT [PROP_INTHLDR_INTEREST_TYPE_ID], [PIMS_INTHLDR_PROP_INTEREST_ID], [INTEREST_HOLDER_INTEREST_TYPE_CODE], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID] 
  FROM   [dbo].[TMP_PROP_INTHLDR_INTEREST_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- -----------------------------------------------------------------------------
-- Drop the temporary tables.
-- -----------------------------------------------------------------------------

-- Drop table dbo.TMP_PROP_PROP_ROAD_TYP
PRINT N'Drop table dbo.TMP_PROP_PROP_ROAD_TYP'
GO
DROP TABLE IF EXISTS [dbo].[TMP_PROP_PROP_ROAD_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.TMP_PROP_PROP_ANOMALY_TYP
PRINT N'Drop table dbo.TMP_PROP_PROP_ANOMALY_TYP'
GO
DROP TABLE IF EXISTS [dbo].[TMP_PROP_PROP_ANOMALY_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.TMP_PROP_PROP_TENURE_TYP
PRINT N'Drop table dbo.TMP_PROP_PROP_TENURE_TYP'
GO
DROP TABLE IF EXISTS [dbo].[TMP_PROP_PROP_TENURE_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.TMP_PRF_PROP_RESEARCH_PURPOSE_TYP
PRINT N'Drop table dbo.TMP_PRF_PROP_RESEARCH_PURPOSE_TYP'
GO
DROP TABLE IF EXISTS [dbo].[TMP_PRF_PROP_RESEARCH_PURPOSE_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop table dbo.TMP_PROP_INTHLDR_INTEREST_TYP
PRINT N'Drop table dbo.TMP_PROP_INTHLDR_INTEREST_TYP'
GO
DROP TABLE IF EXISTS [dbo].[TMP_PROP_INTHLDR_INTEREST_TYP]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
