<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectMotiRegion</name>
   <tag></tag>
   <elementGuidId>cae7dbc0-2622-479a-8ed6-655af04f478c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-region']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-motiRegion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56451bca-477f-47bb-a2dd-b3a1502f1744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>motiRegion</value>
      <webElementGuid>d51eb10d-5dee-4251-b05d-570ba35b0110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-motiRegion</value>
      <webElementGuid>8adb8b7c-99ad-4445-9ac5-8635e840c249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b7cacf4b-04a7-4844-9573-8e4f87e50958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>motiRegion-error-tooltip}</value>
      <webElementGuid>a6e49162-6309-48fe-bc2d-3600dfcbc57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-motiRegion&quot;)</value>
      <webElementGuid>c56e2321-29e1-4fcd-af86-f6f48c3e39ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
