<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPurpose</name>
   <tag></tag>
   <elementGuidId>8aabbaea-6578-43da-8f54-081e8d380807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-purposeType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-purposeType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purposeType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-purposeType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select purposeAccess (Industrial/Commercial)Access (Residential)AgriculturalBC FerriesCampingCommercial BuildingEmergency ServicesEncroachmentFencing/GateGardeningGravelGrazingLogging/Timber HarvestMarine FacilityMobile Home PadMaintenance YardOther*ParkParkingPark and RidePipelinePreloadPrivate transportationRailwayRest Area/PulloutSidewalks/LandscapingSignageSpecial EventStaging AreaStockpilingStorageTourist InfoTrailUtilities-infrastructureUtilities-overhead xingUtilities-underground xingWater ReservoirWeigh ScaleCrossing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-purposeType&quot;)</value>
   </webElementProperties>
</WebElementEntity>
