DELETE FROM PIMS_PROJECT_PRODUCT;
GO

INSERT INTO PIMS_PROJECT_PRODUCT (PROJECT_ID, PRODUCT_ID)
VALUES 
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID())),
  ((SELECT TOP 1 ID FROM PIMS_PROJECT ORDER BY NEWID()), (SELECT TOP 1 ID FROM PIMS_PRODUCT ORDER BY NEWID()));
GO
