DELETE FROM PIMS_PROPERTY_ACTIVITY;
GO

INSERT INTO PIMS_PROPERTY_ACTIVITY (PROP_MGMT_ACTIVITY_TYPE_CODE, PROP_MGMT_ACTIVITY_SUBTYPE_CODE, PROP_MGMT_ACTIVITY_STATUS_TYPE_CODE, SERVICE_PROVIDER_PERSON_ID, SERVICE_PROVIDER_ORG_ID, REQUEST_ADDED_DT, COMPLETION_DT, DESCRIPTION, REQUEST_SOURCE)
VALUES
  (N'PROPERTYMTC',   N'SNOWREMOVAL',   N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'LANDLORDIMPRV', N'LL_PREMISES',   N'INPROGRESS', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'TENANTIMPROV',  N'TN_BUILDGLAND', N'COMPLETED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'INCDNTISSUE',   N'ENCAMPMENT',    N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'INQUIRY',       N'GENINQUIRY',    N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'INVESTRPT',     N'GEOTECH',       N'ONHOLD',     (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'1STNTNCONSULT', N'ACCOMMAGREE',   N'CANCELLED',  (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source'),
  (N'APPLICPERMIT',  N'DEVELOPMENT',   N'NOTSTARTED', (SELECT TOP 1 PERSON_ID FROM PIMS_PERSON ORDER BY NEWID()), (SELECT TOP 1 ORGANIZATION_ID FROM PIMS_ORGANIZATION ORDER BY NEWID()), getutcdate(), getutcdate(), N'This is a description', N'This is a request source');
GO
