IF NOT EXISTS (
    SELECT
        1
    FROM
        PIMS_LEASE_STAKEHOLDER_TYPE
    WHERE
        LEASE_STAKEHOLDER_TYPE_CODE = 'OWNER'
)
INSERT INTO
    PIMS_LEASE_STAKEHOLDER_TYPE (
        LEASE_STAKEHOLDER_TYPE_CODE,
        DESCRIPTION,
        IS_PAYABLE_RELATED
    )
VALUES
    ('OWNER', N'Owner', 1);

ELSE
UPDATE
    PIMS_LEASE_STAKEHOLDER_TYPE
SET
    IS_DISABLED = 0,
    CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE
    LEASE_STAKEHOLDER_TYPE_CODE = 'OWNER';

IF NOT EXISTS (
    SELECT
        1
    FROM
        PIMS_LEASE_STAKEHOLDER_TYPE
    WHERE
        LEASE_STAKEHOLDER_TYPE_CODE = 'OWNREP'
)
INSERT INTO
    PIMS_LEASE_STAKEHOLDER_TYPE (
        LEASE_STAKEHOLDER_TYPE_CODE,
        DESCRIPTION,
        IS_PAYABLE_RELATED
    )
VALUES
    ('OWNREP', N'Owner Representative', 1);

ELSE
UPDATE
    PIMS_LEASE_STAKEHOLDER_TYPE
SET
    IS_DISABLED = 0,
    CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1
WHERE
    LEASE_STAKEHOLDER_TYPE_CODE = 'OWNREP';

GO