DELETE 
FROM   PIMS_ACTIVITY_INSTANCE;
GO

INSERT INTO [dbo].[PIMS_ACTIVITY_INSTANCE] ([ACTIVITY_TEMPLATE_ID], ACTIVITY_INSTANCE_STATUS_TYPE_CODE, [CONCURRENCY_CONTROL_NUMBER])
VALUES
  ((SELECT ACTIVITY_TEMPLATE_ID FROM PIMS_ACTIVITY_TEMPLATE WHERE ACTIVITY_TEMPLATE_TYPE_CODE = N'FILEDOC'), N'NOSTART', 1),
  ((SELECT ACTIVITY_TEMPLATE_ID FROM PIMS_ACTIVITY_TEMPLATE WHERE ACTIVITY_TEMPLATE_TYPE_CODE = N'GENERAL'), N'NOSTART', 1),
  ((SELECT ACTIVITY_TEMPLATE_ID FROM PIMS_ACTIVITY_TEMPLATE WHERE ACTIVITY_TEMPLATE_TYPE_CODE = N'SITEVIS'), N'NOSTART', 1),
  ((SELECT ACTIVITY_TEMPLATE_ID FROM PIMS_ACTIVITY_TEMPLATE WHERE ACTIVITY_TEMPLATE_TYPE_CODE = N'SURVEY'),  N'NOSTART', 1);
GO
