INSERT INTO [dbo].[PIMS_INTEREST_HOLDER]([ACQUISITION_FILE_ID], [PERSON_ID], [ORGANIZATION_ID], [INTEREST_HOLDER_TYPE_CODE])
VALUES
  (1,    1, NULL, N'AOREP'),
  (1, NULL,    1, N'AOREP'),
  (2,    1, NULL, N'AOSLCTR'),
  (2,    2, NULL, N'AOSLCTR'),
  (3, NULL,    2, N'INTHLDR');
GO
