name: Hide prod maintenance page after deployment.
env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  # service account: gitaction
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  MS_TEAMS_WEBHOOK_BUILD_CHANNEL: ${{ secrets.MS_TEAMS_WEBHOOK_URI_BUILD_CHANNEL }}

on:
  workflow_dispatch:

jobs:
  maintenance-page:
    name: Hide the maintenance page
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #6.0.3
        with:
          ref: master
          fetch-depth: 0
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@f19c5f4f98c725396a5eeb265b1338333634828a # v2.0
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: 3cd915-tools
      - name: Hide the maintenance page and display the app
        run: |
          APPLICATION_NAME=pims-app-prod ./tools/cicd/maintenance/maintenance.sh prod off

  ci-cd-end-notification:
    name: CI-CD End Notification to Teams Channel
    runs-on: ubuntu-22.04
    needs: maintenance-page
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #6.0.3
      - name: check workflow status
        uses: martialonline/workflow-status@326830cacf79872efe767e15031f58d1ea0508c4 # v4.2
        id: check
      - name: End notification to Teams Channel
        uses: ./.github/actions/teams-notification
        with:
          webhook-uri: ${{ env.MS_TEAMS_WEBHOOK_BUILD_CHANNEL }}
          summary: PIMS Deployment COMPLETED in PRODUCTION environment with status ${{ steps.check.outputs.status }}
          title: PIMS Deployment PROD
          color: 17a2b8
          timezone: America/Los_Angeles
