name: Keycloak Sync
env:
  OPENSHIFT_TOOLS_NAMESPACE: "3cd915-tools"
  MS_TEAMS_WEBHOOK_BUILD_CHANNEL: ${{ secrets.MS_TEAMS_WEBHOOK_URI_BUILD_CHANNEL }}
  AUTH__KEYCLOAK__SECRET: ${{ secrets.KEYCLOAK_SECRET }}
  AUTH__KEYCLOAK__SERVICEACCOUNT__SECRET: ${{ secrets.KEYCLOAK_SERVICEACCOUNT_SECRET }}
  sync-directory: ./tools/keycloak/sync
  ASPNETCORE_ENVIRONMENT: "Development"

on:
  workflow_dispatch:

jobs:
  sync-keycloak:
    name: Sync Keycloak
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies for keycloak sync
        run: dotnet restore
        working-directory: ${{env.sync-directory}}

      - name: Build keycloak sync
        run: dotnet build
        working-directory: ${{env.sync-directory}}

      - name: Start keycloak sync
        run: dotnet run
        working-directory: ${{env.sync-directory}}
