name: Keycloak Sync
env:
  AUTH__KEYCLOAK__SECRET: ${{ secrets.KEYCLOAK_SECRET }}
  AUTH__KEYCLOAK__SERVICEACCOUNT__SECRET: ${{ secrets.KEYCLOAK_SERVICEACCOUNT_SECRET }}
  sync-directory: ./tools/keycloak/sync
  ASPNETCORE_ENVIRONMENT: ${{ inputs.TARGET_BRANCH }}

on:
  workflow_dispatch:
    inputs:
      TARGET_BRANCH:
        description: "Enter the target branch (dev/test)"
        required: true

jobs:
  sync-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TARGET_BRANCH }}

      - name: Set ASPNETCORE_ENVIRONMENT (dev)
        if: ${{ inputs.TARGET_BRANCH == 'dev' }}
        run: echo "ASPNETCORE_ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dependencies for keycloak sync
        run: dotnet restore
        working-directory: ${{env.sync-directory}}

      - name: Build keycloak sync
        run: dotnet build
        working-directory: ${{env.sync-directory}}

      - name: Start keycloak sync
        run: dotnet run
        working-directory: ${{env.sync-directory}}
