name: Bump version

on:
  push:
    branches: [dev]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Bump version number
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # this just prints the new version number - will not update any files
          NEW_VERSION=$(node ./build/bump-version.js --print-version)

          # bump version
          node ./build/bump-version.js --apply

          # create commit
          git add -A
          git commit -m "build(release): Bump version to v${NEW_VERSION}"
          git push
