name: Bump version

on:
  pull_request_target:
    types: [closed]
    branches: [dev, test]

jobs:
  bump-version:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }} # with this we can bypass branch protection rules here (no-push)

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup git
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version number
        run: |
          # this just prints the new version number - will not update any files
          NEW_VERSION=$(tools/cicd/build/version-next.sh)

          # auto-increment version number upon merging pull requests
          tools/cicd/build/bump.sh --apply

          # create commit
          git add source/frontend/package.json source/backend/api/Pims.Api.csproj
          git commit -m "CI: Bump version to v${NEW_VERSION}"
          git push
