/* -----------------------------------------------------------------------------
Create and populate the PIMS_PROPERTY_ACTIVITY table from the temporary 
TMP_PROPERTY_ACTIVITY table.
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Author        Date         Comment
------------  -----------  -----------------------------------------------------
Doug Filteau  2025-Jul-07  Initial version
----------------------------------------------------------------------------- */

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY DISABLE TRIGGER PIMS_PRPACT_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY DISABLE TRIGGER PIMS_PRPACT_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY DISABLE TRIGGER PIMS_PRPACT_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Migrate the TMP_PROPERTY_ACTIVITY data to the PIMS_PROPERTY_ACTIVITY table
PRINT N'Migrate the TMP_PROPERTY_ACTIVITY data to the PIMS_PROPERTY_ACTIVITY table'
GO
INSERT INTO dbo.PIMS_PROPERTY_ACTIVITY (PIMS_PROPERTY_ACTIVITY_ID, PROP_MGMT_ACTIVITY_STATUS_TYPE_CODE, SERVICE_PROVIDER_PERSON_ID, SERVICE_PROVIDER_ORG_ID, MANAGEMENT_FILE_ID, PROP_MGMT_ACTIVITY_TYPE_CODE, REQUEST_ADDED_DT, COMPLETION_DT, DESCRIPTION, REQUEST_SOURCE, IS_DISABLED, CONCURRENCY_CONTROL_NUMBER, APP_CREATE_TIMESTAMP, APP_CREATE_USERID, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY, DB_CREATE_TIMESTAMP, DB_CREATE_USERID, DB_LAST_UPDATE_TIMESTAMP, DB_LAST_UPDATE_USERID)
  SELECT PIMS_PROPERTY_ACTIVITY_ID
       , PROP_MGMT_ACTIVITY_STATUS_TYPE_CODE
       , SERVICE_PROVIDER_PERSON_ID
       , SERVICE_PROVIDER_ORG_ID
       , MANAGEMENT_FILE_ID
       , PROP_MGMT_ACTIVITY_TYPE_CODE
       , REQUEST_ADDED_DT
       , COMPLETION_DT
       , DESCRIPTION
       , REQUEST_SOURCE
       , IS_DISABLED
       , CONCURRENCY_CONTROL_NUMBER
       , APP_CREATE_TIMESTAMP
       , APP_CREATE_USERID
       , APP_CREATE_USER_GUID
       , APP_CREATE_USER_DIRECTORY
       , APP_LAST_UPDATE_TIMESTAMP
       , APP_LAST_UPDATE_USERID
       , APP_LAST_UPDATE_USER_GUID
       , APP_LAST_UPDATE_USER_DIRECTORY
       , DB_CREATE_TIMESTAMP
       , DB_CREATE_USERID
       , DB_LAST_UPDATE_TIMESTAMP
       , DB_LAST_UPDATE_USERID
  FROM   dbo.TMP_PROPERTY_ACTIVITY
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Temporarily disable the triggers on the table
PRINT N'Temporarily disable the triggers on the table'
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY ENABLE TRIGGER PIMS_PRPACT_A_S_IUD_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY ENABLE TRIGGER PIMS_PRPACT_I_S_I_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
ALTER TABLE PIMS_PROPERTY_ACTIVITY ENABLE TRIGGER PIMS_PRPACT_I_S_U_TR
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop the temporary table
PRINT N'Drop the temporary table'
GO
DROP TABLE IF EXISTS dbo.TMP_PROPERTY_ACTIVITY
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
